"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Plus, Trash2, TriangleAlert } from "lucide-react";
import { loadEntries } from "@/lib/storage/accounting";
import { loadTasks, saveTasks, taskMetrics } from "@/lib/storage/tasks";
import type { AccountingTask, Locale, TaskCategory, TaskPriority, TaskRecurrence, TaskStatus } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
const empty = (): AccountingTask => ({ id: crypto.randomUUID(), title: "", description: "", dueDate: today(), status: "new", priority: "medium", category: "entries", recurrence: "none", createdAt: new Date().toISOString() });
const statuses: TaskStatus[] = ["new", "in-progress", "review", "completed"];
const priorities: TaskPriority[] = ["low", "medium", "high", "urgent"];
const categories: TaskCategory[] = ["entries", "taxes", "banks", "customers", "suppliers", "payroll", "closing", "other"];

export function TaskDashboard({ locale }: { locale: Locale }) {
  const ar = locale === "ar"; const [tasks, setTasks] = useState<AccountingTask[]>([]); const [draft, setDraft] = useState(empty); const [status, setStatus] = useState("all"); const [category, setCategory] = useState("all"); const [query, setQuery] = useState(""); const [entries, setEntries] = useState<ReturnType<typeof loadEntries>>([]);
  useEffect(() => { setTasks(loadTasks()); setEntries(loadEntries()); }, []);
  const commit = (next: AccountingTask[]) => { setTasks(next); saveTasks(next); };
  const metrics = taskMetrics(tasks, today());
  const visible = useMemo(() => tasks.filter((task) => (status === "all" || task.status === status) && (category === "all" || task.category === category) && `${task.title} ${task.description}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.dueDate.localeCompare(b.dueDate)), [tasks, status, category, query]);
  const add = () => { if (!draft.title.trim()) return; commit([{ ...draft, title: draft.title.trim() }, ...tasks]); setDraft(empty()); };
  const update = (id: string, nextStatus: TaskStatus) => commit(tasks.map((task) => task.id === id ? { ...task, status: nextStatus, completedAt: nextStatus === "completed" ? new Date().toISOString() : undefined } : task));
  const labels: Record<string, string> = ar ? { new: "جديدة", "in-progress": "قيد التنفيذ", review: "بانتظار المراجعة", completed: "مكتملة", low: "منخفضة", medium: "متوسطة", high: "عالية", urgent: "عاجلة", entries: "قيود", taxes: "ضرائب", banks: "بنوك", customers: "عملاء", suppliers: "موردون", payroll: "رواتب", closing: "إقفالات", other: "أخرى", none: "بدون تكرار", daily: "يوميًا", weekly: "أسبوعيًا", monthly: "شهريًا" } : {};
  const label = (value: string) => labels[value] || value;
  return <div className="grid">
    <section className="grid four">{[[Clock3, ar ? "مهام اليوم" : "Due today", metrics.dueToday], [TriangleAlert, ar ? "متأخرة" : "Overdue", metrics.overdue], [Plus, ar ? "مفتوحة" : "Open", metrics.open], [CheckCircle2, ar ? "مكتملة" : "Completed", metrics.completed]].map(([Icon, title, value]) => { const I = Icon as typeof Clock3; return <div className="card" key={String(title)}><I /><p className="muted">{String(title)}</p><div className="impact">{String(value)}</div></div>; })}</section>
    <section className="card"><h2>{ar ? "إضافة مهمة محاسبية" : "Add accounting task"}</h2><div className="grid three"><label>{ar ? "عنوان المهمة" : "Task title"}<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder={ar ? "مثال: مراجعة كشف البنك" : "Example: Review bank statement"} /></label><label>{ar ? "موعد الاستحقاق" : "Due date"}<input type="date" value={draft.dueDate} onChange={(event) => setDraft({ ...draft, dueDate: event.target.value })} /></label><label>{ar ? "الأولوية" : "Priority"}<select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value as TaskPriority })}>{priorities.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>{ar ? "التصنيف" : "Category"}<select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as TaskCategory })}>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>{ar ? "التكرار" : "Recurrence"}<select value={draft.recurrence} onChange={(event) => setDraft({ ...draft, recurrence: event.target.value as TaskRecurrence })}>{["none", "daily", "weekly", "monthly"].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>{ar ? "ربط بقيد محفوظ" : "Link saved entry"}<select value={draft.linkedEntryId || ""} onChange={(event) => setDraft({ ...draft, linkedEntryId: event.target.value || undefined })}><option value="">{ar ? "بدون قيد" : "No entry"}</option>{entries.map((entry) => <option key={entry.id} value={entry.id}>{entry.entryNumber} — {ar ? entry.titleAr : entry.titleEn}</option>)}</select></label></div><label>{ar ? "التفاصيل" : "Details"}<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><button className="btn btn-primary" onClick={add}><Plus size={17} />{ar ? "إضافة المهمة" : "Add task"}</button></section>
    <section className="card"><div className="grid three"><label>{ar ? "بحث" : "Search"}<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>{ar ? "الحالة" : "Status"}<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">{ar ? "كل الحالات" : "All statuses"}</option>{statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>{ar ? "التصنيف" : "Category"}<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">{ar ? "كل التصنيفات" : "All categories"}</option>{categories.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label></div>
      <div className="grid section">{visible.map((task) => { const overdue = task.dueDate < today() && task.status !== "completed"; return <article className="card" key={task.id}><div className="actions" style={{ justifyContent: "space-between" }}><div><span className={overdue ? "badge error" : "badge"}>{label(task.priority)}</span> <span className="badge">{label(task.category)}</span><h3>{task.title}</h3><p className="muted">{task.description || (ar ? "بدون تفاصيل" : "No details")} · {task.dueDate} · {label(task.recurrence)}</p>{task.linkedEntryId && <small>{ar ? "مرتبطة بقيد محفوظ" : "Linked to a saved entry"}</small>}</div><button className="btn btn-danger" onClick={() => commit(tasks.filter((item) => item.id !== task.id))}><Trash2 size={16} /></button></div><div className="actions">{statuses.map((item) => <button key={item} className={`btn ${task.status === item ? "tab-active" : ""}`} onClick={() => update(task.id, item)}>{label(item)}</button>)}</div></article>; })}{!visible.length && <p className="muted">{ar ? "لا توجد مهام مطابقة." : "No matching tasks."}</p>}</div>
    </section>
  </div>;
}
