"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Move, Play, Sparkles, Target, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { moneyFlowScenarios } from "@/data/money-flow/scenarios";
import { loadMoneyFlowProgress, setMoneyFlowLearningStage, subscribeToMoneyFlowProgress } from "@/lib/storage/money-flow";
import type { Locale, MoneyFlowDifficulty, MoneyFlowProgress } from "@/types";

const empty:MoneyFlowProgress={schemaVersion:1,records:{},skills:{},currentLearningStage:"beginner"};
export function MoneyFlowHome({locale}:{locale:Locale}){
 const ar=locale==="ar",[progress,setProgress]=useState(empty); useEffect(()=>{setProgress(loadMoneyFlowProgress());return subscribeToMoneyFlowProgress(setProgress);},[]);
 const completed=Object.values(progress.records).filter((item)=>item.completed).length,first=moneyFlowScenarios.find((item)=>!progress.records[item.id]?.completed)||moneyFlowScenarios[0];
 const choose=(stage:MoneyFlowDifficulty)=>{setProgress(setMoneyFlowLearningStage(stage));};
 return <div className="money-flow-page"><section className="flow-hero"><div className="flow-container flow-hero-grid"><div><span className="flow-kicker"><Sparkles/> FINORA MONEY FLOW LAB</span><h1>{ar?"افهم القيد وهو بيتكوّن.":"Understand the entry as it forms."}</h1><p>{ar?"حرّك القيمة، شوف إيه زاد وإيه نقص، وبعدها اكتشف بنفسك ليه الحساب مدين أو دائن.":"Move value, see what increased or decreased, then discover why each account becomes debit or credit."}</p><div className="flow-actions"><Link className="flow-primary" href={`/${locale}/money-flow/${first.slug}`}><Play/>{ar?"ابدأ أول حركة":"Start first flow"}{ar?<ArrowLeft/>:<ArrowRight/>}</Link><Link className="flow-secondary" href={`/${locale}/missions`}><Target/>{ar?"FINORA Missions":"FINORA Missions"}</Link></div></div><div className="flow-hero-demo"><div className="demo-token">10,000 EGP</div><div className="demo-line"><span>رأس المال</span><i>→</i><span>البنك</span></div><div className="demo-result"><b>{ar?"القيمة اتحركت":"Value moved"}</b><small>{ar?"دلوقتي نكتشف القيد":"Now discover the journal"}</small></div></div></div></section>
 <section className="flow-container flow-summary"><div><Move/><span><b>{completed}/{moneyFlowScenarios.length}</b><small>{ar?"حركات مكتملة":"flows complete"}</small></span></div><div><Trophy/><span><b>{Math.max(0,...Object.values(progress.records).map((item)=>item.bestScore))}</b><small>{ar?"أفضل نتيجة":"best score"}</small></span></div><div><CheckCircle2/><span><b>{Object.values(progress.skills).filter((value)=>(value||0)>=60).length}</b><small>{ar?"مهارات متقنة":"skills mastered"}</small></span></div></section>
 <section className="flow-container flow-stage-picker"><div><span>{ar?"اختار مستوى المساعدة":"Choose guidance level"}</span><h2>{ar?"نفس المنطق، بدرجات مساعدة مختلفة":"The same logic, with different guidance"}</h2></div><div>{(["beginner","intermediate","advanced"] as MoneyFlowDifficulty[]).map((stage)=><button className={progress.currentLearningStage===stage?"active":""} onClick={()=>choose(stage)} key={stage}><b>{stage==="beginner"?(ar?"مبتدئ":"Beginner"):stage==="intermediate"?(ar?"متوسط":"Intermediate"):(ar?"متقدم":"Advanced")}</b><small>{stage==="beginner"?(ar?"زاد ونقص الأول":"Increase/decrease first"):stage==="intermediate"?(ar?"نوع الحساب والاتجاه":"Account type and side"):(ar?"كوّن الحل بأقل مساعدة":"Solve with minimal guidance")}</small></button>)}</div></section>
 <section className="flow-container flow-catalog"><div className="flow-section-title"><span>{ar?"سبع عمليات مترابطة":"Seven connected operations"}</span><h2>{ar?"شوف القيمة بتتحرك في شغل حقيقي":"Watch value move through real work"}</h2></div><div className="flow-card-grid">{moneyFlowScenarios.map((scenario)=>{const record=progress.records[scenario.id];return <article className="flow-card" key={scenario.id}><div><span>FLOW {scenario.number}</span>{record?.completed?<b><CheckCircle2/>{ar?"مكتملة":"Complete"}</b>:<b>{ar?"جديدة":"New"}</b>}</div><h3>{ar?scenario.titleAr:scenario.titleEn}</h3><p>{ar?scenario.summaryAr:scenario.summaryEn}</p><small>{scenario.estimatedMinutes} {ar?"دقائق":"min"} · {scenario.difficulty}</small><Link href={`/${locale}/money-flow/${scenario.slug}`}>{ar?"افتح الحركة":"Open flow"}{ar?<ArrowLeft/>:<ArrowRight/>}</Link></article>})}</div></section></div>;
}
