"use client";

import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, CheckCircle2, CircleHelp, Eye, Lightbulb, RotateCcw, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { AccountContainer } from "./account-container";
import { MoneyToken } from "./money-token";
import { accountById, applyMoneyMovement, calculateMoneyFlowScore, getWrongMovementConsequence, isCorrectMoneyMovement, isQuestionAnswerCorrect, isReverseAnswerCorrect, validateMoneyFlowJournal } from "@/lib/money-flow/engine";
import { loadMoneyFlowProgress, recordMoneyFlowResult } from "@/lib/storage/money-flow";
import type { Locale, MoneyFlowConsequence, MoneyFlowDifficulty, MoneyFlowScenario } from "@/types";

type Phase="movement"|"questions"|"journal"|"impact"|"variation"|"reverse"|"result";
const phaseOrder:Phase[]=["movement","questions","journal","impact","variation","reverse","result"];
const money=(value:number)=>value.toLocaleString("en-US");
export function MoneyFlowLab({scenario,locale}:{scenario:MoneyFlowScenario;locale:Locale}){
 const ar=locale==="ar",[phase,setPhase]=useState<Phase>("movement"),[mode,setMode]=useState<MoneyFlowDifficulty>("beginner"),[placed,setPlaced]=useState(false),[selectedTarget,setSelectedTarget]=useState(""),[draggingToken,setDraggingToken]=useState(""),[wrong,setWrong]=useState<MoneyFlowConsequence>(),[questionIndex,setQuestionIndex]=useState(0),[questionChoice,setQuestionChoice]=useState(""),[questionFeedback,setQuestionFeedback]=useState(""),[hintsUsed,setHintsUsed]=useState(0),[mistakes,setMistakes]=useState(0),[whyLine,setWhyLine]=useState<number>(),[reverseChoice,setReverseChoice]=useState(""),[reverseFeedback,setReverseFeedback]=useState(""),[score,setScore]=useState(0),[elapsedMinutes,setElapsedMinutes]=useState(1); const started=useRef(0);
 useEffect(()=>{setMode(loadMoneyFlowProgress().currentLearningStage);started.current=Date.now();},[]);
 useEffect(()=>{if(!draggingToken)return;const stop=()=>setDraggingToken("");window.addEventListener("pointerup",stop);window.addEventListener("pointercancel",stop);return()=>{window.removeEventListener("pointerup",stop);window.removeEventListener("pointercancel",stop);};},[draggingToken]);
 const token=scenario.tokens[0],accountStates=useMemo(()=>applyMoneyMovement(scenario),[scenario]),journalValidation=validateMoneyFlowJournal(scenario),step=phaseOrder.indexOf(phase)+1;
 const attemptMove=(targetId:string,tokenId=token.id)=>{setSelectedTarget(targetId);if(isCorrectMoneyMovement(scenario,tokenId,targetId,token.sourceAccountId)){setPlaced(true);setWrong(undefined);}else{setMistakes((n)=>n+1);setWrong(getWrongMovementConsequence(scenario,targetId)||{targetAccountId:targetId,titleAr:"لو حركنا القيمة هنا",titleEn:"If value moves here",explanationAr:"الحساب ده لا يعكس حقيقة العملية.",explanationEn:"This account does not reflect the transaction substance.",reflectionAr:"ارجع لكلمات العملية: استلمنا؟ دفعنا؟ لينا ولا علينا؟",reflectionEn:"Return to the facts: received, paid, owed to us, or owed by us?",impacts:[]});}};
 const answerQuestion=()=>{const question=scenario.questions[questionIndex];if(!questionChoice)return;if(!isQuestionAnswerCorrect(scenario,question.id,questionChoice)){setMistakes((n)=>n+1);setQuestionFeedback(ar?question.feedbackAr:question.feedbackEn);return;}setQuestionFeedback("");setQuestionChoice("");if(questionIndex<scenario.questions.length-1)setQuestionIndex((n)=>n+1);else setPhase("journal");};
 const finishReverse=()=>{if(!reverseChoice)return;if(!isReverseAnswerCorrect(scenario,reverseChoice)){setMistakes((n)=>n+1);setReverseFeedback(ar?"القيد لا يحكي العملية دي. ركز في الحساب الذي زاد والذي نقص.":"This entry does not tell that story. Focus on what increased and decreased.");return;}const finalScore=calculateMoneyFlowScore(mistakes,hintsUsed);setScore(finalScore);setElapsedMinutes(Math.max(1,Math.round((Date.now()-started.current)/60000)));recordMoneyFlowResult({scenarioId:scenario.id,completedAt:new Date().toISOString(),mode,attempts:mistakes+1,mistakes,hintsUsed,score:finalScore,masteredSkills:scenario.skills});setPhase("result");};
 const reset=()=>{setPhase("movement");setPlaced(false);setSelectedTarget("");setWrong(undefined);setQuestionIndex(0);setQuestionChoice("");setQuestionFeedback("");setHintsUsed(0);setMistakes(0);setWhyLine(undefined);setReverseChoice("");setReverseFeedback("");started.current=Date.now();};
 const hint=Math.min(hintsUsed,(ar?scenario.hintsAr:scenario.hintsEn).length-1),source=token.sourceAccountId?accountById(scenario,token.sourceAccountId):undefined;
 return <div className="flow-lab-page"><div className="flow-lab-shell"><header className="flow-lab-head"><Link href={`/${locale}/money-flow`}>{ar?<ArrowRight/>:<ArrowLeft/>}<span>{ar?"كل الحركات":"All flows"}</span></Link><div><span>FLOW {scenario.number}</span><b>{ar?scenario.titleAr:scenario.titleEn}</b></div><label><span>{ar?"المستوى":"Mode"}</span><select value={mode} onChange={(event)=>setMode(event.target.value as MoneyFlowDifficulty)}><option value="beginner">{ar?"مبتدئ":"Beginner"}</option><option value="intermediate">{ar?"متوسط":"Intermediate"}</option><option value="advanced">{ar?"متقدم":"Advanced"}</option></select></label></header><div className="flow-lab-progress"><i style={{width:`${step/phaseOrder.length*100}%`}}/></div>

 {phase==="movement"&&<section className="flow-lab-stage"><div className="flow-stage-intro"><span><Target/> {ar?"عملية واقعية":"REAL TRANSACTION"}</span><h1>{ar?scenario.titleAr:scenario.titleEn}</h1><p>{ar?scenario.scenarioAr:scenario.scenarioEn}</p></div><div className="flow-instruction"><b>{ar?scenario.movementPromptAr:scenario.movementPromptEn}</b><small>{ar?"اسحب القيمة أو اضغط الحساب المناسب — الطريقتان تعملان.":"Drag the value or tap the right account — both work."}</small></div>
 <div className="flow-table"><div className="flow-source-zone">{source&&<span>{ar?"من":"From"}: <b>{ar?source.nameAr:source.nameEn}</b></span>}<MoneyToken token={token} locale={locale} active={!placed} dragging={draggingToken===token.id} onPointerStart={setDraggingToken}/></div><div className="flow-accounts-grid">{scenario.accounts.map((account)=>{const state=accountStates.find((item)=>item.id===account.id)!;return <AccountContainer key={account.id} account={account} locale={locale} selected={selectedTarget===account.id} change={placed?state.change:0} revealType={placed||mode!=="beginner"} onSelect={()=>!placed&&attemptMove(account.id)} onDropToken={(tokenId)=>!placed&&attemptMove(account.id,tokenId)} onPointerDrop={()=>{if(!placed&&draggingToken)attemptMove(account.id,draggingToken);}}/>})}</div></div>
 {!placed&&<div className="flow-tap-help"><Eye/>{ar?"بديل السحب: اضغط على الحساب الذي تريد نقل القيمة إليه.":"Drag alternative: tap the account where value should move."}</div>}
 {wrong&&<aside className="flow-consequence"><div><X/><span><small>{ar?"لو سجلناها كده، هيحصل إيه؟":"What happens if we record it this way?"}</small><h2>{ar?wrong.titleAr:wrong.titleEn}</h2></span></div><p>{ar?wrong.explanationAr:wrong.explanationEn}</p>{wrong.impacts.length>0&&<div className="flow-mini-impact">{wrong.impacts.map((item)=><span key={item.key}><i>{item.direction==="increase"?"↑":item.direction==="decrease"?"↓":"—"}</i><b>{ar?item.labelAr:item.labelEn}</b><small>{item.amount?money(item.amount):ar?item.noteAr:item.noteEn}</small></span>)}</div>}<strong>{ar?wrong.reflectionAr:wrong.reflectionEn}</strong><button onClick={()=>{setWrong(undefined);setSelectedTarget("");}}><RotateCcw/>{ar?"جرّب حركة تانية":"Try another move"}</button></aside>}
 {placed&&<aside className="flow-success"><CheckCircle2/><div><small>{ar?"الحركة صحيحة":"Correct movement"}</small><h2>{ar?"شوف الرصيد قبل وبعد":"See the balance before and after"}</h2><p>{ar?"دلوقتي عرفت إيه زاد وإيه نقص. نبدأ نستنتج المعالجة.":"Now you know what increased and decreased. Let's derive the treatment."}</p></div><button className="flow-primary" onClick={()=>setPhase("questions")}>{ar?"كمّل الاستنتاج":"Continue reasoning"}{ar?<ArrowLeft/>:<ArrowRight/>}</button></aside>}
 {!placed&&<div className="flow-hint-row"><button onClick={()=>setHintsUsed((n)=>Math.min(scenario.hintsAr.length,n+1))}><Lightbulb/>{ar?"مساعدة":"Hint"}</button>{hintsUsed>0&&<p>{(ar?scenario.hintsAr:scenario.hintsEn)[hint]}</p>}</div>}</section>}

 {phase==="questions"&&(()=>{const question=scenario.questions[questionIndex];return <section className="flow-lab-stage flow-question-stage"><span>{ar?`نفهم الحركة ${questionIndex+1}/${scenario.questions.length}`:`Understand the flow ${questionIndex+1}/${scenario.questions.length}`}</span><h2>{ar?question.promptAr:question.promptEn}</h2><div className="flow-choice-grid">{question.choices.map((item)=><button className={questionChoice===item.id?"selected":""} onClick={()=>{setQuestionChoice(item.id);setQuestionFeedback("");}} key={item.id}><i>{questionChoice===item.id?<Check/>:null}</i><b>{ar?item.labelAr:item.labelEn}</b></button>)}</div>{questionFeedback&&<div className="flow-answer-feedback"><CircleHelp/><p>{questionFeedback}</p></div>}<button className="flow-primary" disabled={!questionChoice} onClick={answerQuestion}>{ar?"ثبّت الإجابة":"Confirm answer"}</button></section>})()}

 {phase==="journal"&&<section className="flow-lab-stage"><div className="flow-stage-intro"><span><Sparkles/>{ar?"المصطلح المحاسبي بيظهر دلوقتي":"Accounting terms appear now"}</span><h2>{ar?"القيد اتكوّن من الحركة":"The entry came from the movement"}</h2><p>{ar?"ما حفظناش قاعدة. عرفنا نوع الحساب والتغير، فاستنتجنا الجانب.":"We did not memorize a rule. Account type plus change gave us the side."}</p></div><div className="flow-journal"><header><span>{ar?scenario.journalEntry.narrationAr:scenario.journalEntry.narrationEn}</span><b className={journalValidation.valid?"balanced":""}>{journalValidation.valid?(ar?"متوازن ✓":"Balanced ✓"):(ar?"غير متوازن":"Unbalanced")}</b></header>{scenario.journalEntry.lines.map((line,index)=><div key={line.accountId}><span className={line.debit?"debit":"credit"}>{line.debit?(ar?"مدين":"Debit"):(ar?"دائن":"Credit")}</span><p><b>{ar?line.accountNameAr:line.accountNameEn}</b><small dir="ltr">{line.accountCode}</small></p><strong dir="ltr">{money(line.debit||line.credit)} EGP</strong><button onClick={()=>setWhyLine(whyLine===index?undefined:index)}>{ar?"ليه؟":"Why?"}</button>{whyLine===index&&<em>{ar?line.whyAr:line.whyEn}</em>}</div>)}<footer><span>{ar?"إجمالي المدين":"Total debit"}<b dir="ltr">{money(scenario.journalEntry.lines.reduce((s,l)=>s+l.debit,0))}</b></span><span>{ar?"إجمالي الدائن":"Total credit"}<b dir="ltr">{money(scenario.journalEntry.lines.reduce((s,l)=>s+l.credit,0))}</b></span></footer></div>{scenario.noteAr&&<p className="flow-note"><CircleHelp/>{ar?scenario.noteAr:scenario.noteEn}</p>}<button className="flow-primary" onClick={()=>setPhase("impact")}>{ar?"شوف التأثير المالي":"See financial impact"}</button></section>}

 {phase==="impact"&&<section className="flow-lab-stage"><div className="flow-stage-intro"><span>{ar?"FINANCIAL IMPACT":"FINANCIAL IMPACT"}</span><h2>{ar?"القيد غيّر إيه في الشركة؟":"What did the entry change?"}</h2></div><div className="flow-impact-grid">{scenario.financialImpact.map((item)=><article key={item.key}><i className={item.direction}>{item.direction==="increase"?<ArrowUp/>:item.direction==="decrease"?<ArrowDown/>:"—"}</i><b>{ar?item.labelAr:item.labelEn}</b><strong dir={item.amount!==undefined?"ltr":undefined}>{item.amount!==undefined?money(item.amount):ar?item.noteAr:item.noteEn}</strong><small>{item.direction==="increase"?(ar?"زاد":"Increased"):item.direction==="decrease"?(ar?"نقص":"Decreased"):(ar?"لا تغيير":"No change")}</small></article>)}</div><button className="flow-primary" onClick={()=>setPhase("variation")}>{ar?"لو غيرنا كلمة واحدة؟":"What if one word changed?"}</button></section>}

 {phase==="variation"&&<section className="flow-lab-stage flow-variation"><span>{ar?"ثبّت الفرق":"LOCK THE DIFFERENCE"}</span><h2>{ar?"لو غيرنا كلمة واحدة؟":"What if one word changed?"}</h2>{scenario.variations.map((item,index)=><article key={index}><small>{ar?item.changedWordAr:item.changedWordEn}</small><h3>{ar?item.promptAr:item.promptEn}</h3><div><span>{ar?item.fromAccountAr:item.fromAccountEn}</span><i>{ar?<ArrowLeft/>:<ArrowRight/>}</i><span>{ar?item.toAccountAr:item.toAccountEn}</span></div><p>{ar?item.explanationAr:item.explanationEn}</p></article>)}<button className="flow-primary" onClick={()=>setPhase("reverse")}>{ar?"احكيلي القيد":"Tell me the entry"}</button></section>}

 {phase==="reverse"&&<section className="flow-lab-stage flow-reverse"><span>{ar?"من القيد للعملية":"ENTRY → TRANSACTION"}</span><h2>{ar?scenario.reverseQuestion.promptAr:scenario.reverseQuestion.promptEn}</h2><div className="flow-choice-grid">{scenario.reverseQuestion.choices.map((item)=><button className={reverseChoice===item.id?"selected":""} onClick={()=>{setReverseChoice(item.id);setReverseFeedback("");}} key={item.id}><i>{reverseChoice===item.id?<Check/>:null}</i><b>{ar?item.labelAr:item.labelEn}</b></button>)}</div>{reverseFeedback&&<div className="flow-answer-feedback"><CircleHelp/><p>{reverseFeedback}</p></div>}<button className="flow-primary" onClick={finishReverse} disabled={!reverseChoice}>{ar?"أنهِ الحركة":"Finish flow"}</button></section>}

 {phase==="result"&&<section className="flow-lab-stage flow-result"><span className="flow-result-icon"><ShieldCheck/></span><small>FLOW COMPLETE</small><h1>{ar?"فهمت الحركة قبل القاعدة ✅":"You understood the flow before the rule ✅"}</h1><div><span><b>{score}</b><small>{ar?"النتيجة":"Score"}</small></span><span><b>{mistakes}</b><small>{ar?"أخطاء راجعتها":"mistakes reviewed"}</small></span><span><b>{hintsUsed}</b><small>{ar?"مساعدات":"hints"}</small></span><span><b>{elapsedMinutes}m</b><small>{ar?"الوقت":"time"}</small></span></div><div className="flow-skills">{scenario.skills.map((skill)=><b key={skill}>{skill.replaceAll("-"," ")}</b>)}</div><div className="flow-result-actions"><button className="flow-secondary" onClick={reset}><RotateCcw/>{ar?"إعادة الحركة":"Replay"}</button><Link className="flow-primary" href={`/${locale}/money-flow`}>{ar?"كل الحركات":"All flows"}</Link></div></section>}
 </div></div>;
}
