"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowUpRight, BarChart3, BriefcaseBusiness, Building2, CheckCircle2, Copy, Eye, EyeOff, FileDown, Gauge, Home, Info, Layers3, ListFilter, LockKeyhole, PlusCircle, Printer, RefreshCw, ShieldAlert, Sparkles, Store, Users, WalletCards } from "lucide-react";
import { posProviders } from "@/data/pos";
import { calculatePosCommandCenter } from "@/lib/pos/analytics";
import { calculatePosShiftSnapshot } from "@/lib/pos/engine";
import { buildOwnerCommandCenter, compareStores, planCanAccess } from "@/lib/pos/recommendations";
import { loadLocalSubscription, loadServicePointSettings, seedSalesDemo } from "@/lib/storage/service-point-demo";
import { effectiveSubscriptionStatus, trialDaysRemaining } from "@/lib/pos/demo";
import { loadActivePosStoreId, loadPosOperations, loadPosShifts, loadPosStores } from "@/lib/storage/pos";
import type { Locale, PosProviderId, PosShiftSnapshot } from "@/types";
import type { OwnerCommandCenterInput } from "@/lib/pos/recommendations";
import type { OwnerRecommendation } from "@/types/pos-owner";

const privacyKey = "finora-owner-dashboard-hide-values";
const modeKey = "finora-owner-dashboard-mode";
const money = (value: number, hidden = false) => hidden ? "•••••" : `${value.toLocaleString("ar-EG", { maximumFractionDigits: 2 })} ج.م`;

function storeInput(storeId: string, now: Date): OwnerCommandCenterInput | undefined {
  const store = loadPosStores().find((item) => item.id === storeId);
  if (!store) return undefined;
  const shifts = loadPosShifts(storeId), operations = loadPosOperations(storeId), activeShift = shifts.find((item) => item.status === "open"), last = shifts[0];
  const snapshot: PosShiftSnapshot = activeShift ? calculatePosShiftSnapshot(activeShift, operations) : {
    expectedCash: last?.actualClosingCash || 0,
    expectedProviders: Object.fromEntries(posProviders.map((provider) => [provider.id, last?.providers.find((item) => item.providerId === provider.id)?.actualClosingBalance || 0])) as Record<PosProviderId, number>,
    revenue: 0, expenses: 0, profit: 0, operationCount: 0,
  };
  return { storeId, storeName: store.name, shifts, operations, snapshot, settings: loadServicePointSettings(), subscription: loadLocalSubscription(), now };
}

async function copyWithFallback(text: string) {
  try { await navigator.clipboard.writeText(text); return true; } catch {
    const area = document.createElement("textarea"); area.value = text; area.style.position = "fixed"; area.style.opacity = "0"; document.body.appendChild(area); area.select();
    const copied = document.execCommand("copy"); area.remove(); return copied;
  }
}

export function OwnerDashboard({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  const [storeId, setStoreId] = useState("");
  const [hidden, setHidden] = useState(false);
  const [mode, setMode] = useState<"quick" | "detailed">("quick");
  const [rankBy, setRankBy] = useState<"profit" | "margin">("profit");
  const [notice, setNotice] = useState("");
  const [tick, setTick] = useState(0);
  useEffect(() => {
    setStoreId(loadActivePosStoreId() || loadPosStores()[0]?.id || "");
    setHidden(localStorage.getItem(privacyKey) === "1");
    setMode(localStorage.getItem(modeKey) === "detailed" ? "detailed" : "quick");
  }, []);
  const data = useMemo(() => {
    void tick;
    const now = new Date(), input = storeInput(storeId, now);
    if (!input) return undefined;
    const store = loadPosStores().find((item) => item.id === storeId), activeShift = input.shifts.find((item) => item.status === "open");
    const command = buildOwnerCommandCenter(input);
    const pos = calculatePosCommandCenter(input.snapshot, input.operations.filter((item) => item.businessDate === now.toISOString().slice(0, 10)));
    const allStoreInputs = loadPosStores().map((item) => storeInput(item.id, now)).filter(Boolean) as OwnerCommandCenterInput[];
    return { input, store, activeShift, command, pos, stores: compareStores(allStoreInputs) };
  }, [storeId, tick]);
  const subscription = data?.input.subscription;
  const togglePrivacy = () => { const next = !hidden; setHidden(next); localStorage.setItem(privacyKey, next ? "1" : "0"); };
  const changeMode = (next: "quick" | "detailed") => { setMode(next); localStorage.setItem(modeKey, next); };
  const showNotice = (value: string) => { setNotice(value); window.setTimeout(() => setNotice(""), 2200); };
  if (!data || !subscription) return <main className="grid min-h-screen place-items-center bg-[#eef3f8] p-5 text-center" dir={ar ? "rtl" : "ltr"}><div className="max-w-md rounded-[2rem] border border-slate-200 bg-white p-8 shadow-xl"><Store className="mx-auto text-blue-700" size={42}/><h1 className="mt-5 text-2xl">{ar ? "ابدأ تجربة مركز المالك" : "Start the Owner Command Center"}</h1><p className="mt-3 leading-7 text-slate-600">{ar ? "سننشئ سيناريو مبيعات متوازن داخل هذا المتصفح فقط، بدون أي بيانات سحابية." : "A balanced sales scenario will be created only in this browser, with no cloud data."}</p><button className="btn btn-primary mt-6" onClick={() => { const store = seedSalesDemo(); setStoreId(store.id); setTick((value) => value + 1); }}>{ar ? "إنشاء Demo احترافي" : "Create professional demo"}</button></div></main>;

  const { command, pos } = data, plan = subscription.currentPlan, days = trialDaysRemaining(subscription), status = effectiveSubscriptionStatus(subscription);
  const canDecide = planCanAccess(plan, "recommendations"), canCompare = planCanAccess(plan, "storeComparison");
  const rankedProviders = [...command.providerPerformance].sort((a, b) => rankBy === "profit" ? b.profit - a.profit : b.margin - a.margin);
  const priority = command.recommendations.slice(0, 5);
  const visiblePriority = canDecide ? priority : [];
  const briefAttention = canDecide ? (ar ? command.brief.attentionAr : command.brief.attentionEn) : (ar ? `لديك ${command.today.pending} معلقة و${command.today.failed} فاشلة اليوم.` : `You have ${command.today.pending} pending and ${command.today.failed} failed today.`);
  const briefActions = canDecide ? (ar ? command.brief.actionsAr : command.brief.actionsEn) : [];
  const summaryText = ar
    ? `${data.store?.name} — ملخص المالك\n${command.brief.happenedAr}\n${briefAttention}\nالإجراءات: ${briefActions.join("، ") || "لا يوجد إجراء عاجل"}`
    : `${data.store?.name} — Owner summary\n${command.brief.happenedEn}\n${briefAttention}\nActions: ${briefActions.join(", ") || "No urgent action"}`;
  const copySummary = async () => showNotice(await copyWithFallback(summaryText) ? (ar ? "تم نسخ ملخص المالك" : "Owner summary copied") : (ar ? "تعذر النسخ" : "Copy failed"));

  return <div className="owner-command-center min-h-screen overflow-x-hidden bg-[#eef3f8] pb-24 text-slate-950" dir={ar ? "rtl" : "ltr"}>
    <header className="owner-screen-only sticky top-0 z-30 border-b border-slate-200 bg-white/95 px-3 py-3 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3">
      <div className="min-w-0"><small className="block truncate font-bold text-blue-700">FINORA · {ar ? "مركز قيادة المالك" : "Owner Command Center"}</small><h1 className="truncate text-lg font-black">{data.store?.name}</h1></div>
      <div className="flex items-center gap-2"><ModeSwitch ar={ar} mode={mode} onChange={changeMode}/><button title={ar ? "تحديث البيانات" : "Refresh data"} className="grid h-11 w-11 place-items-center rounded-2xl border bg-white" onClick={() => setTick((value) => value + 1)}><RefreshCw size={18}/></button><button title={ar ? "إخفاء القيم عند مشاركة الشاشة" : "Hide values while screen sharing"} className="grid h-11 w-11 place-items-center rounded-2xl border bg-white" onClick={togglePrivacy}>{hidden ? <Eye size={19}/> : <EyeOff size={19}/>}</button></div>
    </div></header>

    <main className="mx-auto grid max-w-6xl gap-5 p-3 sm:p-5">
      <div className="owner-screen-only flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-950"><span><Info className="me-1 inline" size={14}/>{ar ? "التحليل مبني على بيانات هذا الجهاز فقط. لا توجد مزامنة سحابية في Demo Edition." : "Insights use this device's data only. Demo Edition has no cloud sync."}</span><Link className="font-bold underline" href={`/${locale}/service-point/plans`}>{status === "trial" ? (ar ? `${days} يومًا متبقيًا · ${plan.toUpperCase()}` : `${days} days left · ${plan.toUpperCase()}`) : (ar ? `الباقة: ${plan.toUpperCase()}` : `Plan: ${plan.toUpperCase()}`)}</Link></div>

      <section className="overflow-hidden rounded-[2rem] bg-[#082c52] text-white shadow-xl"><div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[1.2fr_.8fr]">
        <div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-200"><Sparkles size={14}/>{ar ? "ملخص اليوم" : "Today summary"}</span><h2 className="mt-4 text-3xl font-black text-white sm:text-4xl">{money(command.today.profit, hidden)}</h2><p className="mt-2 text-sm text-white/65">{ar ? "صافي الربح الحقيقي: عمولات العملاء - تكلفة مقدم الخدمة - مصروفات المحل" : "True profit: customer commissions − provider cost − store expenses"}<Info className="ms-1 inline" size={13}/></p><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-xl bg-white/10 px-3 py-2">{data.activeShift ? (ar ? `وردية مفتوحة · ${data.activeShift.cashierName}` : `Open shift · ${data.activeShift.cashierName}`) : (ar ? "لا توجد وردية مفتوحة" : "No open shift")}</span><Trend ar={ar} value={command.comparisons.todayProfit}/></div></div>
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-2"><HeroKpi title={ar ? "حجم العمليات" : "Volume"} value={money(command.today.volume, hidden)} hint={ar ? "قيمة العمليات الناجحة اليوم" : "Successful operation value today"}/><HeroKpi title={ar ? "عدد العمليات" : "Operations"} value={String(command.today.operations)} hint={ar ? "العمليات الناجحة فقط" : "Successful only"}/><HeroKpi title={ar ? "الخزنة" : "Cash"} value={money(pos.cash, hidden)} hint={ar ? "الرصيد المتوقع للوردية الحالية" : "Expected current-shift balance"}/><HeroKpi title={ar ? "أرصدة الخدمات" : "Service balances"} value={money(pos.wallets, hidden)} hint={ar ? "مجموع أرصدة مقدمي الخدمة" : "Total provider balances"}/><HeroKpi title={ar ? "المعلقة" : "Pending"} value={String(pos.pending)} hint={ar ? "لا تدخل في الربح حتى الحسم" : "Excluded from profit until resolved"}/><HeroKpi title={ar ? "الفروق" : "Differences"} value={money(pos.unresolvedVariance, hidden)} hint={ar ? "الفروق غير المحسومة" : "Unresolved variance"}/></div>
      </div></section>

      <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="flex items-center gap-2 text-xs font-black text-emerald-700"><BriefcaseBusiness size={17}/>SMART DAILY BRIEF</span><h2 className="mt-2 text-2xl">{ar ? "ملخص FINORA لليوم" : "FINORA summary for today"}</h2></div><div className="owner-screen-only flex gap-2"><button className="btn" onClick={copySummary}><Copy size={17}/>{ar ? "نسخ الملخص" : "Copy"}</button><button className="btn" onClick={() => window.print()}><Printer size={17}/>{ar ? "طباعة / PDF" : "Print / PDF"}</button></div></div>
        <div className="mt-5 grid gap-3 md:grid-cols-3"><BriefItem step="01" title={ar ? "ماذا حدث؟" : "What happened?"} text={ar ? command.brief.happenedAr : command.brief.happenedEn}/><BriefItem step="02" title={ar ? "ما الذي يحتاج الانتباه؟" : "What needs attention?"} text={briefAttention}/><BriefItem step="03" title={ar ? "أهم الإجراءات الآن" : "Top actions now"} text={briefActions.slice(0, 3).join(" · ") || (ar ? "استمر في المتابعة" : "Keep monitoring")}/></div>
      </section>

      <Section title={ar ? "أهم ما يحتاج انتباهك الآن" : "What needs your attention now"} subtitle={ar ? "كل بطاقة تشرح السبب والخطوة التالية، بلا اتهامات أو تخمينات." : "Every card explains why it matters and what to do next—without blame."} icon={Gauge}>
        {canDecide ? <div className="grid gap-3 lg:grid-cols-2">{priority.map((item) => <DecisionCard key={item.id} item={item} ar={ar} locale={locale}/>)}{!priority.length && <EmptyGood ar={ar}/>}</div> : <LockedFeature ar={ar} locale={locale} title={ar ? "التوصيات التنفيذية متاحة في Pro" : "Action recommendations are available in Pro"}/>}
      </Section>

      <Section title={ar ? "خريطة السيولة" : "Liquidity map"} subtitle={ar ? "أين تعمل الأموال، وأين تقترب من النفاد، وأين بقيت راكدة؟" : "See where money is working, running low, or sitting idle."} icon={WalletCards}>
        {planCanAccess(plan, "liquidity") ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{command.providerPerformance.map((provider) => { const insight = provider.health === "low" ? (ar ? "غذِّ الرصيد" : "Top up") : provider.health === "dormant" || provider.turnover < .2 ? (ar ? "أعد توزيع السيولة" : "Redistribute") : (ar ? "الرصيد مناسب" : "Well balanced"); return <article key={provider.providerId} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 font-bold"><i className="h-3 w-3 rounded-full" style={{ background: posProviders.find((item) => item.id === provider.providerId)?.color }}/>{providerName(provider.providerId, ar)}</span><StatusPill status={provider.health === "low" ? "danger" : provider.health === "dormant" || provider.turnover < .2 ? "idle" : "good"} ar={ar}/></div><strong className="mt-4 block text-xl">{money(provider.balance, hidden)}</strong><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, Math.max(4, provider.turnover * 35))}%` }}/></div><p className="mt-3 text-xs font-bold text-slate-600">{insight} · {ar ? "دوران" : "turnover"} {provider.turnover}</p></article>; })}</div> : <LockedFeature ar={ar} locale={locale} title={ar ? "خريطة السيولة متاحة في Pro" : "Liquidity map is available in Pro"}/>}
      </Section>

      {mode === "detailed" && <>
        <section className="grid gap-4 lg:grid-cols-3"><ComparisonCard title={ar ? "اليوم مقابل أمس" : "Today vs yesterday"} current={command.today.profit} previous={command.yesterday.profit} change={command.comparisons.todayProfit} operationsChange={command.comparisons.todayOperations} averageChange={command.comparisons.todayAverageProfit} ar={ar} hidden={hidden}/><ComparisonCard title={ar ? "آخر 7 أيام مقابل السابقة" : "Last 7 days vs prior"} current={command.week.profit} previous={command.priorWeek.profit} change={command.comparisons.weekProfit} operationsChange={command.comparisons.weekOperations} averageChange={command.comparisons.weekAverageProfit} ar={ar} hidden={hidden}/><article className="rounded-3xl bg-[#0f6b61] p-5 text-white shadow-sm"><small className="text-white/65">{ar ? "لقطة الشهر" : "Monthly snapshot"}</small><strong className="mt-3 block text-2xl">{money(command.month.profit, hidden)}</strong><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><MiniStat label={ar ? "الحجم" : "Volume"} value={money(command.month.volume, hidden)}/><MiniStat label={ar ? "العمليات" : "Operations"} value={String(command.month.operations)}/><MiniStat label={ar ? "متوسط الربح اليومي" : "Avg daily profit"} value={money(command.monthlyInsights.averageDailyProfit, hidden)}/><MiniStat label={ar ? "أكبر فرق" : "Largest variance"} value={money(command.monthlyInsights.largestShiftDifference, hidden)}/><MiniStat label={ar ? "أفضل خدمة" : "Best provider"} value={command.monthlyInsights.bestProviderId ? String(providerName(command.monthlyInsights.bestProviderId, ar)) : "—"}/><MiniStat label={ar ? "أعلى هامش" : "Highest margin"} value={command.monthlyInsights.highestMarginProviderId ? String(providerName(command.monthlyInsights.highestMarginProviderId, ar)) : "—"}/><MiniStat label={ar ? "معلقة" : "Pending"} value={String(command.month.pending)}/></div></article></section>

        <Section title={ar ? "ترتيب ربحية الخدمات" : "Provider profitability ranking"} subtitle={ar ? "بدّل بين صافي الربح والهامش لتفهم أين يأتي العائد." : "Switch between net profit and margin to see where returns come from."} icon={BarChart3} action={<div className="flex rounded-xl bg-slate-100 p-1"><button className={`rounded-lg px-3 py-2 text-xs font-bold ${rankBy === "profit" ? "bg-white shadow" : ""}`} onClick={() => setRankBy("profit")}>{ar ? "الربح" : "Profit"}</button><button className={`rounded-lg px-3 py-2 text-xs font-bold ${rankBy === "margin" ? "bg-white shadow" : ""}`} onClick={() => setRankBy("margin")}>{ar ? "الهامش" : "Margin"}</button></div>}>
          {rankedProviders[0]?.operations > 0 && <p className="mb-3 rounded-2xl bg-emerald-50 p-3 text-sm font-bold text-emerald-900">{ar ? `${providerName(rankedProviders[0].providerId, true)} هي أعلى خدمة حسب ${rankBy === "profit" ? "صافي الربح" : "الهامش"} الآن.` : `${providerName(rankedProviders[0].providerId, false)} currently ranks highest by ${rankBy}.`}</p>}
          <div className="grid gap-2">{rankedProviders.map((provider, index) => <article key={provider.providerId} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 rounded-2xl border border-slate-200 p-3"><b className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-800">{index + 1}</b><span className="min-w-0"><strong className="block truncate">{providerName(provider.providerId, ar)}</strong><small className="block text-slate-500">{provider.operations} {ar ? "عملية" : "ops"} · {ar ? "حجم" : "volume"} {money(provider.volume, hidden)}</small><small className="block text-slate-500">{ar ? "إيراد" : "Revenue"} {money(provider.revenue, hidden)} · {ar ? "تكلفة" : "Cost"} {money(provider.cost, hidden)}</small></span><span className="text-end"><b className="block">{rankBy === "profit" ? money(provider.profit, hidden) : `${provider.margin}%`}</b><small className="text-slate-500">{rankBy === "profit" ? `${provider.margin}% ${ar ? "هامش" : "margin"}` : money(provider.profit, hidden)}</small></span></article>)}</div>
        </Section>

        <Section title={ar ? "أداء الكاشير" : "Cashier performance"} subtitle={ar ? "تصنيف تشغيلي للمراجعة والدعم، وليس حكمًا على الأشخاص." : "An operational signal for support and review—not a judgment of people."} icon={Users}>
          {planCanAccess(plan, "cashiers") ? <><p className="mb-3 rounded-2xl bg-blue-50 p-3 text-sm font-bold text-blue-900">{command.cashierInsight ? (ar ? command.cashierInsight.titleAr : command.cashierInsight.titleEn) : (ar ? "لا توجد ورديات كافية للمقارنة." : "Not enough shifts to compare.")}</p><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{command.cashierPerformance.map((cashier) => <article key={cashier.shiftId} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><b className="truncate">{cashier.cashierName}</b><CashierStatus status={cashier.status} ar={ar}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs sm:grid-cols-3"><Stat label={ar ? "العمليات" : "Ops"} value={String(cashier.operations)}/><Stat label={ar ? "الحجم" : "Volume"} value={money(cashier.volume, hidden)}/><Stat label={ar ? "صافي الربح" : "Net profit"} value={money(cashier.profit, hidden)}/><Stat label={ar ? "ربح/ساعة" : "Profit/hour"} value={money(cashier.profitPerHour, hidden)}/><Stat label={ar ? "متوسط/عملية" : "Avg/transaction"} value={money(cashier.averageProfit, hidden)}/><Stat label={ar ? "فرق الوردية" : "Shift variance"} value={money(Math.abs(cashier.variance), hidden)}/></div><p className="mt-3 text-xs leading-6 text-slate-500">{cashier.failed + cashier.pending > 0 ? `${ar ? "تنبيهات" : "Warnings"}: ${cashier.failed} ${ar ? "فاشلة" : "failed"} · ${cashier.pending} ${ar ? "معلقة" : "pending"}. ` : ""}{cashier.status === "needs-review" ? (ar ? "تحتاج الوردية مراجعة هادئة للمستندات والأرصدة." : "Review the shift records and balances constructively.") : cashier.status === "stable" ? (ar ? "الأداء مستقر مع نقاط بسيطة للمتابعة." : "Stable performance with minor follow-up.") : (ar ? "تسوية جيدة واستقرار تشغيلي." : "Good reconciliation and operational stability.")}</p></article>)}</div></> : <LockedFeature ar={ar} locale={locale} title={ar ? "تحليل الكاشير متاح في Pro" : "Cashier insights are available in Pro"}/>}
        </Section>

        {data.stores.length > 1 && <Section title={ar ? "مقارنة المحلات" : "Store comparison"} subtitle={ar ? "نفس قواعد القياس على كل محل؛ البيانات تظل على هذا الجهاز." : "The same rules across every store; data stays on this device."} icon={Building2}>
          {canCompare ? <div className="grid gap-3 md:grid-cols-2">{data.stores.map((store, index) => <article key={store.storeId} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><b>{index + 1}. {store.storeName}</b><span className="text-xs text-slate-500">{store.operations} {ar ? "عملية" : "ops"}</span></div><strong className="mt-3 block text-xl">{money(store.profit, hidden)}</strong><p className="mt-2 text-xs text-slate-500">{ar ? "حجم" : "Volume"} {money(store.volume, hidden)} · {ar ? "أكبر فرق" : "Largest variance"} {money(store.difference, hidden)} · {ar ? "أفضل كاشير" : "Top cashier"} {store.topCashier || "—"} · {store.prioritySignals} {ar ? "إشارات أولوية" : "priority signals"}</p></article>)}</div> : <LockedFeature ar={ar} locale={locale} title={ar ? "مقارنة المحلات متاحة في Business" : "Store comparison is available in Business"}/>}
        </Section>}
      </>}

      <section className="owner-screen-only grid grid-cols-2 gap-3 sm:grid-cols-4"><Link className="btn btn-primary" href={`/${locale}/service-point#new-operation`}><PlusCircle/>{ar ? "عملية جديدة" : "New operation"}</Link><Link className="btn" href={`/${locale}/service-point#shift-actions`}><Store/>{data.activeShift ? (ar ? "إقفال وردية" : "Close shift") : (ar ? "فتح وردية" : "Open shift")}</Link><button className="btn" onClick={() => window.print()}><FileDown/>{ar ? "تقرير اليوم" : "Today report"}</button><Link className="btn" href={`/${locale}/service-point/plans`}><Layers3/>{ar ? "الباقات" : "Plans"}</Link></section>
    </main>

    <article className="owner-daily-print" dir={ar ? "rtl" : "ltr"}><header><span>FINORA Service Point</span><h1>{ar ? "تقرير صاحب المحل اليومي" : "Daily Owner Report"}</h1><p>{data.store?.name} · {new Date().toLocaleDateString(ar ? "ar-EG" : "en-GB")} · {ar ? "الورديات" : "Shifts"}: {data.input.shifts.filter((item) => item.businessDate === new Date().toISOString().slice(0, 10)).map((item) => item.cashierName).join("، ") || "—"}</p></header><div className="print-kpis"><span>{ar ? "صافي الربح" : "Net profit"}<b>{money(command.today.profit)}</b></span><span>{ar ? "الحجم" : "Volume"}<b>{money(command.today.volume)}</b></span><span>{ar ? "العمليات" : "Operations"}<b>{command.today.operations}</b></span><span>{ar ? "الخزنة" : "Cash"}<b>{money(pos.cash)}</b></span></div><h2>{ar ? "تفاصيل الأداء" : "Performance details"}</h2><p>{ar ? "عمولات العملاء" : "Customer commissions"}: {money(command.today.revenue)} · {ar ? "تكاليف مقدمي الخدمة" : "Provider costs"}: {money(command.today.providerCosts)} · {ar ? "مصروفات التشغيل" : "Operating expenses"}: {money(command.today.operatingExpenses)} · {ar ? "معلقة / فاشلة / مستردة" : "Pending / failed / reversed"}: {pos.pending} / {pos.failed} / {pos.reversed} · {ar ? "فروق الوردية" : "Shift differences"}: {money(pos.unresolvedVariance)}</p><p>{ar ? "أفضل خدمة" : "Top provider"}: {command.providerPerformance[0] ? providerName(command.providerPerformance[0].providerId, ar) : "—"} · {ar ? "أفضل كاشير بالربح لكل ساعة" : "Top cashier by profit/hour"}: {[...command.cashierPerformance].sort((a, b) => b.profitPerHour - a.profitPerHour)[0]?.cashierName || "—"}</p><h2>{ar ? "أرصدة الخدمات" : "Service balances"}</h2><p>{command.providerPerformance.map((item) => `${providerName(item.providerId, ar)}: ${money(item.balance)}`).join(" · ")}</p><h2>{ar ? "الملخص التنفيذي والتنبيهات" : "Executive summary and alerts"}</h2><p>{ar ? command.brief.happenedAr : command.brief.happenedEn}</p><p>{briefAttention}</p><h2>{ar ? "القرارات المقترحة" : "Recommended decisions"}</h2><ol>{visiblePriority.map((item) => <li key={item.id}><b>{ar ? item.titleAr : item.titleEn}:</b> {ar ? item.actionAr : item.actionEn}</li>)}</ol>{!visiblePriority.length && <p>{ar ? "لا توجد توصيات متاحة ضمن الباقة الحالية." : "No recommendations are available in the current plan."}</p>}<footer>{ar ? "تم إنشاء التقرير محليًا من بيانات هذا الجهاز." : "Generated locally from this device's data."}</footer></article>

    {notice && <div className="owner-screen-only fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-xl">{notice}</div>}
    <nav className="owner-screen-only fixed inset-x-0 bottom-0 z-30 border-t border-slate-200 bg-white p-2 md:hidden"><div className="mx-auto grid max-w-lg grid-cols-4 gap-1 text-center text-xs"><Link className="rounded-xl bg-blue-50 p-2 text-blue-800" href={`/${locale}/service-point/owner-dashboard`}><Home className="mx-auto mb-1" size={18}/>{ar ? "المالك" : "Owner"}</Link><Link className="rounded-xl p-2" href={`/${locale}/service-point#new-operation`}><PlusCircle className="mx-auto mb-1" size={18}/>{ar ? "عملية" : "Operation"}</Link><Link className="rounded-xl p-2" href={`/${locale}/service-point`}><WalletCards className="mx-auto mb-1" size={18}/>{ar ? "التشغيل" : "Operate"}</Link><button className="rounded-xl p-2" onClick={() => changeMode(mode === "quick" ? "detailed" : "quick")}><ListFilter className="mx-auto mb-1" size={18}/>{mode === "quick" ? (ar ? "تفصيلي" : "Details") : (ar ? "سريع" : "Quick")}</button></div></nav>
  </div>;
}

function providerName(id: PosProviderId, ar: boolean) { const provider = posProviders.find((item) => item.id === id); return ar ? provider?.nameAr : provider?.nameEn; }
function ModeSwitch({ ar, mode, onChange }: { ar: boolean; mode: "quick" | "detailed"; onChange: (value: "quick" | "detailed") => void }) { return <div className="hidden rounded-xl bg-slate-100 p-1 sm:flex"><button className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === "quick" ? "bg-white shadow" : ""}`} onClick={() => onChange("quick")}>{ar ? "سريع" : "Quick"}</button><button className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === "detailed" ? "bg-white shadow" : ""}`} onClick={() => onChange("detailed")}>{ar ? "تفصيلي" : "Detailed"}</button></div>; }
function HeroKpi({ title, value, hint }: { title: string; value: string; hint: string }) { return <article className="min-w-0 rounded-2xl bg-white/10 p-3"><small className="flex items-center gap-1 truncate text-white/60">{title}<Info size={12}/></small><b className="mt-2 block truncate text-sm sm:text-lg" title={hint}>{value}</b></article>; }
function Trend({ ar, value }: { ar: boolean; value: number | null }) { if (value === null) return <span className="rounded-xl bg-white/10 px-3 py-2">{ar ? "لا توجد قاعدة مقارنة" : "No comparison baseline"}</span>; const good = value >= 0; return <span className={`rounded-xl px-3 py-2 ${good ? "bg-emerald-400/15 text-emerald-200" : "bg-rose-400/15 text-rose-200"}`}>{good ? "+" : ""}{value}% {ar ? "عن أمس" : "vs yesterday"}</span>; }
function BriefItem({ step, title, text }: { step: string; title: string; text: string }) { return <article className="rounded-2xl bg-slate-50 p-4"><span className="text-xs font-black text-blue-700">{step}</span><b className="mt-2 block">{title}</b><p className="mt-2 text-sm leading-7 text-slate-600">{text}</p></article>; }
function Section({ title, subtitle, icon: Icon, action, children }: { title: string; subtitle: string; icon: typeof Store; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><header className="mb-5 flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-blue-50 text-blue-700"><Icon size={21}/></span><div><h2 className="text-xl">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{subtitle}</p></div></div>{action}</header>{children}</section>; }
function DecisionCard({ item, ar, locale }: { item: OwnerRecommendation; ar: boolean; locale: Locale }) { const urgent = item.severity === "critical" || item.severity === "high", positive = item.severity === "positive"; const href = item.actionTarget === "plans" ? `/${locale}/service-point/plans` : item.actionTarget === "shift" ? `/${locale}/service-point#shift-actions` : `/${locale}/service-point${item.actionTarget === "operation" ? "#new-operation" : ""}`; return <article className={`rounded-2xl border p-4 ${positive ? "border-emerald-200 bg-emerald-50/50" : urgent ? "border-rose-200 bg-rose-50/45" : "border-amber-200 bg-amber-50/45"}`}><div className="flex items-start gap-3"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${positive ? "bg-emerald-100 text-emerald-700" : urgent ? "bg-rose-100 text-rose-700" : "bg-amber-100 text-amber-700"}`}>{positive ? <CheckCircle2 size={20}/> : urgent ? <ShieldAlert size={20}/> : <AlertTriangle size={20}/>}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b>{ar ? item.titleAr : item.titleEn}</b><small className="font-black text-slate-400">P{item.priority}</small></div><p className="mt-2 text-sm leading-6 text-slate-600">{ar ? item.detailAr : item.detailEn}</p><Link className="mt-3 inline-flex items-center gap-1 text-sm font-black text-blue-700" href={href}>{ar ? item.actionAr : item.actionEn}<ArrowUpRight size={15}/></Link></div></div></article>; }
function EmptyGood({ ar }: { ar: boolean }) { return <div className="col-span-full rounded-2xl bg-emerald-50 p-5 text-emerald-900"><CheckCircle2 className="mb-2"/><b>{ar ? "لا توجد قرارات عاجلة الآن" : "No urgent decisions right now"}</b><p className="mt-1 text-sm">{ar ? "تابع الأرصدة والعمليات كالمعتاد." : "Keep monitoring balances and operations."}</p></div>; }
function LockedFeature({ ar, locale, title }: { ar: boolean; locale: Locale; title: string }) { return <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-dashed border-blue-300 bg-blue-50 p-5"><span className="flex items-center gap-3"><LockKeyhole className="text-blue-700"/><span><b className="block">{title}</b><small className="text-slate-600">{ar ? "شاهد قيمة الميزة قبل التفعيل؛ بياناتك لن تُحذف." : "Preview the value before activation; your data remains safe."}</small></span></span><Link className="btn" href={`/${locale}/service-point/plans`}>{ar ? "مقارنة الباقات" : "Compare plans"}</Link></div>; }
function StatusPill({ status, ar }: { status: "good" | "danger" | "idle"; ar: boolean }) { const label = status === "good" ? (ar ? "مناسب" : "Good") : status === "danger" ? (ar ? "منخفض" : "Low") : (ar ? "راكد" : "Idle"); return <span className={`rounded-full px-2 py-1 text-[10px] font-black ${status === "good" ? "bg-emerald-100 text-emerald-800" : status === "danger" ? "bg-rose-100 text-rose-800" : "bg-amber-100 text-amber-800"}`}>{label}</span>; }
function CashierStatus({ status, ar }: { status: "excellent" | "stable" | "needs-review"; ar: boolean }) { const label = status === "excellent" ? (ar ? "ممتاز" : "Excellent") : status === "stable" ? (ar ? "مستقر" : "Stable") : (ar ? "يحتاج مراجعة" : "Needs review"); return <span className={`rounded-full px-2 py-1 text-[10px] font-black ${status === "excellent" ? "bg-emerald-100 text-emerald-800" : status === "stable" ? "bg-blue-100 text-blue-800" : "bg-amber-100 text-amber-800"}`}>{label}</span>; }
function Stat({ label, value }: { label: string; value: string }) { return <span className="rounded-xl bg-slate-50 p-2">{label}<b className="mt-1 block">{value}</b></span>; }
function MiniStat({ label, value }: { label: string; value: string }) { return <span className="rounded-xl bg-white/10 p-3">{label}<b className="mt-1 block">{value}</b></span>; }
function changeLabel(value: number | null, ar: boolean) { return value === null ? (ar ? "بلا قاعدة" : "No baseline") : `${value >= 0 ? "+" : ""}${value}%`; }
function ComparisonCard({ title, current, previous, change, operationsChange, averageChange, ar, hidden }: { title: string; current: number; previous: number; change: number | null; operationsChange: number | null; averageChange: number | null; ar: boolean; hidden: boolean }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><small className="text-slate-500">{title}</small><strong className="mt-3 block text-2xl">{money(current, hidden)}</strong><div className="mt-4 grid gap-2 text-xs"><span className="flex justify-between rounded-xl bg-slate-50 p-3"><i className="not-italic">{ar ? "الربح" : "Profit"}</i><b>{changeLabel(change, ar)}</b></span><span className="flex justify-between rounded-xl bg-slate-50 p-3"><i className="not-italic">{ar ? "العمليات" : "Operations"}</i><b>{changeLabel(operationsChange, ar)}</b></span><span className="flex justify-between rounded-xl bg-slate-50 p-3"><i className="not-italic">{ar ? "متوسط ربح العملية" : "Avg profit/transaction"}</i><b>{changeLabel(averageChange, ar)}</b></span><span className="text-slate-500">{ar ? "ربح الفترة السابقة" : "Previous profit"}: {money(previous, hidden)}</span></div></article>; }
