"use client";
/* eslint-disable react-hooks/exhaustive-deps -- tick intentionally refreshes localStorage-derived view data */
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { AlertTriangle,BarChart3,Eye,EyeOff,FileText,Home,PlusCircle,RefreshCw,ShieldAlert,Store,WalletCards } from "lucide-react";
import { posProviders } from "@/data/pos";
import { calculatePosCommandCenter } from "@/lib/pos/analytics";
import { calculatePosShiftSnapshot } from "@/lib/pos/engine";
import { backupOverdue,loadLocalSubscription,loadServicePointSettings,seedSalesDemo } from "@/lib/storage/service-point-demo";
import { effectiveSubscriptionStatus,trialDaysRemaining } from "@/lib/pos/demo";
import { loadActivePosStoreId,loadPosOperations,loadPosShifts,loadPosStores } from "@/lib/storage/pos";
import type { Locale,PosProviderId } from "@/types";

const privacyKey="finora-owner-dashboard-hide-values";
const money=(value:number,hidden:boolean)=>hidden?"•••••":`${value.toLocaleString("ar-EG",{maximumFractionDigits:2})} ج.م`;

export function OwnerDashboard({locale}:{locale:Locale}){
 const ar=locale==="ar",[storeId,setStoreId]=useState(""),[hidden,setHidden]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{setStoreId(loadActivePosStoreId()||loadPosStores()[0]?.id||"");setHidden(localStorage.getItem(privacyKey)==="1");},[]);
 const model=useMemo(()=>{if(!storeId)return undefined;const store=loadPosStores().find(x=>x.id===storeId),shifts=loadPosShifts(storeId),operations=loadPosOperations(storeId),activeShift=shifts.find(x=>x.status==="open"),last=shifts[0],snapshot=activeShift?calculatePosShiftSnapshot(activeShift,operations):{expectedCash:last?.actualClosingCash||0,expectedProviders:Object.fromEntries(posProviders.map(p=>[p.id,last?.providers.find(x=>x.providerId===p.id)?.actualClosingBalance||0])) as Record<PosProviderId,number>,revenue:0,expenses:0,profit:0,operationCount:0},today=new Date().toISOString().slice(0,10),todayOps=operations.filter(x=>x.businessDate===today),pos=calculatePosCommandCenter(snapshot,todayOps),settings=loadServicePointSettings(),subscription=loadLocalSubscription();return{store,activeShift,pos,todayOps,snapshot,settings,subscription};},[storeId,tick]);
 const toggle=()=>{const next=!hidden;setHidden(next);localStorage.setItem(privacyKey,next?"1":"0");};
 if(!model)return <main className="grid min-h-screen place-items-center bg-[#f4f7fb] p-5 text-center" dir={ar?"rtl":"ltr"}><div className="max-w-md rounded-3xl bg-white p-8 shadow-xl"><Store className="mx-auto text-blue-700" size={40}/><h1 className="mt-5 text-2xl">{ar?"ابدأ تجربة الموبايل":"Start the mobile demo"}</h1><p className="mt-3 leading-7 text-slate-600">{ar?"سيتم إنشاء بيانات عرض مستقلة داخل هذا المتصفح فقط.":"Demo data will be created only in this browser."}</p><button className="btn btn-primary mt-6" onClick={()=>{const store=seedSalesDemo();setStoreId(store.id);setTick(x=>x+1);}}>{ar?"ابدأ التجربة":"Start demo"}</button></div></main>;
 const days=trialDaysRemaining(model.subscription),status=effectiveSubscriptionStatus(model.subscription),alerts=[model.pos.pending&&(ar?`${model.pos.pending} عملية معلقة`:`${model.pos.pending} pending operations`),model.pos.failed&&(ar?`${model.pos.failed} عملية فاشلة`:`${model.pos.failed} failed operations`),model.snapshot.expectedProviders.fawry<500&&(ar?"رصيد فوري منخفض":"Fawry balance is low"),backupOverdue(model.settings)&&(ar?"حان وقت إنشاء Backup":"Backup is due")].filter(Boolean) as string[];
 return <div className="min-h-screen overflow-x-hidden bg-[#f4f7fb] pb-24 text-slate-950" dir={ar?"rtl":"ltr"}>
  <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 px-3 py-3 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between gap-3"><div className="min-w-0"><small className="block truncate text-slate-500">{ar?"لوحة صاحب المحل — بيانات هذا الجهاز":"Owner dashboard — this device's data"}</small><h1 className="truncate text-lg font-black">{model.store?.name}</h1></div><div className="flex gap-2"><button title={ar?"تحديث":"Refresh"} className="grid h-11 w-11 place-items-center rounded-2xl border" onClick={()=>setTick(x=>x+1)}><RefreshCw size={18}/></button><button title={ar?"إخفاء القيم":"Hide values"} className="grid h-11 w-11 place-items-center rounded-2xl border" onClick={toggle}>{hidden?<Eye/>:<EyeOff/>}</button></div></div></header>
  <main className="mx-auto grid max-w-5xl gap-4 p-3 sm:p-5">
   <div className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-950"><span>{ar?"كل جهاز يحفظ نسخة محلية مستقلة. المزامنة بين الأجهزة ضمن Cloud Edition.":"Each device keeps separate local data. Sync is a Cloud Edition feature."}</span><Link className="font-bold underline" href={`/${locale}/service-point/plans`}>{status==="trial"?(ar?`${days} يومًا في التجربة`:`${days} trial days`):(ar?"شاهد الباقات":"View plans")}</Link></div>
   <section className="rounded-3xl bg-gradient-to-l from-[#0b315d] to-[#2166a5] p-5 text-white shadow-lg"><div className="flex justify-between gap-3"><div><small className="text-white/70">{ar?"ربح اليوم":"Today's profit"}</small><h2 className="mt-1 text-3xl text-white">{money(model.pos.trueProfit,hidden)}</h2><p className="mt-2 text-sm text-white/70">{model.activeShift?(ar?`وردية مفتوحة · ${model.activeShift.cashierName}`:`Open shift · ${model.activeShift.cashierName}`):(ar?"لا توجد وردية مفتوحة":"No open shift")}</p></div><Store size={34}/></div><div className="mt-5 grid grid-cols-3 gap-2"><MobileKpi title={ar?"الخزنة":"Cash"} value={money(model.pos.cash,hidden)}/><MobileKpi title={ar?"الخدمات":"Providers"} value={money(model.pos.wallets,hidden)}/><MobileKpi title={ar?"العمليات":"Operations"} value={String(model.todayOps.length)}/></div></section>
   <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card icon={ShieldAlert} title={ar?"معلقة":"Pending"} value={String(model.pos.pending)}/><Card icon={AlertTriangle} title={ar?"فاشلة":"Failed"} value={String(model.pos.failed)}/><Card icon={RefreshCw} title={ar?"مستردة":"Reversed"} value={String(model.pos.reversed)}/><Card icon={BarChart3} title={ar?"حجم اليوم":"Today volume"} value={money(model.todayOps.reduce((n,x)=>n+x.amount,0),hidden)}/></section>
   <section className="rounded-3xl bg-white p-4 shadow-sm sm:p-6"><div className="flex items-center justify-between"><h2 className="text-lg">{ar?"أرصدة الخدمات":"Provider balances"}</h2><WalletCards className="text-blue-700"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{posProviders.map(p=><article key={p.id} className="flex min-w-0 items-center justify-between gap-2 rounded-2xl border p-3"><span className="flex min-w-0 items-center gap-2"><i className="h-3 w-3 shrink-0 rounded-full" style={{background:p.color}}/><b className="truncate text-sm">{ar?p.nameAr:p.nameEn}</b></span><strong className="text-sm">{money(model.snapshot.expectedProviders[p.id],hidden)}</strong></article>)}</div></section>
   <section className="rounded-3xl bg-white p-4 shadow-sm sm:p-6"><h2 className="flex items-center gap-2 text-lg"><AlertTriangle size={20}/>{ar?"تنبيهات اليوم":"Today's alerts"}</h2><div className="mt-4 grid gap-2">{alerts.map(alert=><div key={alert} className="rounded-2xl bg-amber-50 p-3 text-sm text-amber-950">{alert}</div>)}{!alerts.length&&<p className="rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-900">{ar?"لا توجد تنبيهات عاجلة.":"No urgent alerts."}</p>}</div></section>
   <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Link className="btn btn-primary" href={`/${locale}/service-point#new-operation`}><PlusCircle/>{ar?"عملية جديدة":"New operation"}</Link><Link className="btn" href={`/${locale}/service-point#shift-actions`}><Store/>{model.activeShift?(ar?"إقفال وردية":"Close shift"):(ar?"فتح وردية":"Open shift")}</Link><Link className="btn" href={`/${locale}/service-point`}><FileText/>{ar?"تقرير اليوم":"Today report"}</Link><Link className="btn" href={`/${locale}/service-point/plans`}>{ar?"الباقات":"Plans"}</Link></section>
  </main>
  <nav className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200 bg-white p-2 md:hidden"><div className="mx-auto grid max-w-lg grid-cols-4 gap-1 text-center text-xs"><Link className="rounded-xl bg-blue-50 p-2 text-blue-800" href={`/${locale}/service-point/owner-dashboard`}><Home className="mx-auto mb-1" size={18}/>{ar?"اليوم":"Today"}</Link><Link className="rounded-xl p-2" href={`/${locale}/service-point#new-operation`}><PlusCircle className="mx-auto mb-1" size={18}/>{ar?"عملية":"Operation"}</Link><Link className="rounded-xl p-2" href={`/${locale}/service-point`}><WalletCards className="mx-auto mb-1" size={18}/>{ar?"المحافظ":"Wallets"}</Link><Link className="rounded-xl p-2" href={`/${locale}/service-point/plans`}><FileText className="mx-auto mb-1" size={18}/>{ar?"الباقات":"Plans"}</Link></div></nav>
 </div>;
}
function MobileKpi({title,value}:{title:string;value:string}){return <div className="min-w-0 rounded-2xl bg-white/10 p-3"><small className="block truncate text-white/70">{title}</small><b className="mt-1 block truncate text-sm sm:text-lg">{value}</b></div>}
function Card({icon:Icon,title,value}:{icon:typeof Store;title:string;value:string}){return <article className="min-w-0 rounded-2xl bg-white p-4 shadow-sm"><Icon className="text-blue-700" size={20}/><small className="mt-3 block truncate text-slate-500">{title}</small><b className="mt-1 block truncate text-lg">{value}</b></article>}
