"use client";

import { useEffect, useMemo, useState } from "react";
import { posOperationTypes, posProviders } from "@/data/pos";
import { calculateLiquidity, calculateProfitLeakage, calculateProfitability, feeRuleKey, type LocalRuleSettings } from "@/lib/pos/local-intelligence";
import { emptyInnovationData, loadInnovationData, saveInnovationData, type InnovationStoreData } from "@/lib/storage/service-point-innovation";
import type { Locale, PosOperation, PosShift, PosShiftSnapshot } from "@/types";

const money = (value: number) => `${value.toLocaleString("ar-EG", { maximumFractionDigits: 2 })} ج.م`;
const statusAr = { healthy: "جيد", watch: "مراقبة", low: "منخفض", critical: "حرج" };
const statusColor = { healthy: "bg-emerald-50 text-emerald-800", watch: "bg-amber-50 text-amber-900", low: "bg-orange-50 text-orange-900", critical: "bg-red-50 text-red-900" };

export function ServicePointInnovation({ locale, storeId, operations, shifts, snapshot, onDataChange }: { locale: Locale; storeId: string; operations: PosOperation[]; shifts: PosShift[]; snapshot: PosShiftSnapshot; onDataChange?: (data: InnovationStoreData) => void }) {
  const ar = locale === "ar";
  const [data, setData] = useState<InnovationStoreData>(emptyInnovationData);
  const [tab, setTab] = useState<"liquidity" | "leakage" | "alerts" | "profitability" | "rules">("liquidity");
  useEffect(() => { setData(loadInnovationData(storeId)); }, [storeId]);
  const change = (next: InnovationStoreData) => { setData(next); saveInnovationData(storeId, next); onDataChange?.(next); };
  const updateRules = (rules: LocalRuleSettings) => change({ ...data, rules });
  const liquidity = useMemo(() => calculateLiquidity(snapshot, operations, data.rules), [snapshot, operations, data.rules]);
  const leakage = useMemo(() => calculateProfitLeakage(operations, shifts, data.rules), [operations, shifts, data.rules]);
  const profitability = useMemo(() => calculateProfitability(operations), [operations]);
  const alerts = [
    ...leakage.map((signal) => ({ id: signal.id, title: ar ? signal.titleAr : signal.titleEn, priority: signal.kind === "potential-leakage" ? "important" : "watch" })),
    ...liquidity.filter((row) => row.status !== "healthy").map((row) => ({ id: `balance-${row.id}`, title: `${row.id === "cash" ? (ar ? "الخزنة" : "Cash") : ar ? posProviders.find((item) => item.id === row.id)?.nameAr : posProviders.find((item) => item.id === row.id)?.nameEn}: ${ar ? statusAr[row.status] : row.status}`, priority: row.status === "critical" ? "critical" : row.status === "low" ? "important" : "watch" })),
  ];
  return <section className="card no-print" data-no-bilingual id="service-point-intelligence">
    <h2>{ar ? "مركز حماية الأرباح والسيولة" : "Profit and liquidity center"}</h2>
    <p className="muted mt-1 text-sm">{ar ? "حسابات محلية تقديرية من عمليات هذا المحل فقط. الإشارات للمراجعة ولا تعني اتهامًا." : "Local estimates from this store only. Signals invite review and do not imply misconduct."}</p>
    <div className="mt-5 flex flex-wrap gap-2">{(["liquidity", "leakage", "alerts", "profitability", "rules"] as const).map((item) => <button key={item} className={`btn ${tab === item ? "btn-primary" : ""}`} onClick={() => setTab(item)}>{ar ? ({ liquidity: "السيولة وصحة الخدمات", leakage: "تسريب الأرباح", alerts: "التنبيهات", profitability: "ربحية الرسوم", rules: "القواعد والأهداف" }[item]) : ({ liquidity: "Liquidity & providers", leakage: "Profit leakage", alerts: "Alerts", profitability: "Fee profitability", rules: "Rules & targets" }[item])}</button>)}</div>
    {tab === "liquidity" && <><p className="muted mt-5 text-sm">{ar ? "التقدير مبني على أيام التشغيل المحلية خلال آخر 14 يومًا؛ يحتاج يومي تشغيل على الأقل." : "Estimate based on local operating days in the last 14 days; at least two days are required."}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{liquidity.map((row) => { const name = row.id === "cash" ? ar ? "الخزنة" : "Cash" : ar ? posProviders.find((item) => item.id === row.id)?.nameAr : posProviders.find((item) => item.id === row.id)?.nameEn; return <article key={row.id} className="rounded-2xl border border-daftar-line p-4"><div className="flex items-center justify-between gap-2"><b>{name}</b><span className={`rounded-full px-2 py-1 text-xs ${statusColor[row.status]}`}>{ar ? statusAr[row.status] : row.status}</span></div><strong className="mt-3 block text-xl">{money(row.balance)}</strong><p className="muted mt-2 text-sm">{ar ? "الحد الأدنى" : "Minimum"}: {money(row.minimum)}</p><p className="muted text-sm">{ar ? "الطلب الخارج يوميًا" : "Daily outgoing demand"}: {row.averageDailyOutflow === null ? ar ? "بيانات غير كافية" : "Not enough data" : money(row.averageDailyOutflow)}</p><p className="muted text-sm">{ar ? "مدة كفاية الرصيد" : "Estimated runway"}: {row.runwayDays === null ? ar ? "بيانات غير كافية" : "Not enough data" : `${row.runwayDays} ${ar ? "يوم تشغيل" : "operating days"}`}</p><div className="mt-3 border-t border-daftar-line pt-3 text-sm"><p>{ar ? "عمليات" : "Transactions"}: {row.transactionCount} · {ar ? "صافي التدفق" : "Net flow"}: {money(row.netFlow)}</p><p>{ar ? "عمولات" : "Fees"}: {money(row.fees)} · {ar ? "تكلفة" : "Cost"}: {money(row.costs)}</p><p>{ar ? "ربح" : "Profit"}: {money(row.profit)} · {ar ? "معلقة/فاشلة" : "Pending/failed"}: {row.pending}/{row.failed}</p></div></article>; })}</div></>}
    {tab === "leakage" && <div className="mt-5 grid gap-3 md:grid-cols-2">{leakage.length ? leakage.map((signal) => <article className="rounded-2xl border border-amber-200 bg-amber-50 p-4" key={signal.id}><b>{ar ? signal.titleAr : signal.titleEn}</b><p className="mt-1 text-sm">{ar ? "عدد الحالات" : "Cases"}: {signal.count}</p><p className="text-sm">{signal.impact !== undefined ? `${ar ? "الأثر التقديري" : "Estimated impact"}: ${money(signal.impact)}` : ar ? "يحتاج مراجعة؛ لا يمكن تقدير أثر مالي موثوق." : "Needs review; financial impact cannot be reliably estimated."}</p></article>) : <p className="muted">{ar ? "لا توجد إشارات وفق البيانات والقواعد الحالية." : "No signals under current data and rules."}</p>}</div>}
    {tab === "alerts" && <div className="mt-5 space-y-2">{alerts.length ? alerts.map((alert) => <div key={alert.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-daftar-line p-3"><div><b>{alert.title}</b><small className="muted ms-3">{alert.priority}</small>{data.reviewedAlerts.includes(alert.id) && <small className="ms-2 text-emerald-700">{ar ? "تمت المراجعة" : "Reviewed"}</small>}</div><button className="btn" onClick={() => change({ ...data, reviewedAlerts: data.reviewedAlerts.includes(alert.id) ? data.reviewedAlerts : [...data.reviewedAlerts, alert.id] })}>{ar ? "تحديد كمراجع" : "Mark reviewed"}</button></div>) : <p className="muted">{ar ? "لا توجد تنبيهات حاليًا." : "No current alerts."}</p>}</div>}
    {tab === "profitability" && <div className="table-wrap mt-5"><table><thead><tr>{(ar ? ["الخدمة", "النوع", "العدد", "متوسط القيمة", "متوسط العمولة", "متوسط التكلفة", "ربح العملية", "إجمالي الربح", "هامش العمولة", "التصنيف"] : ["Provider", "Type", "Count", "Avg amount", "Avg fee", "Avg cost", "Profit / txn", "Total profit", "Fee margin", "Category"]).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{profitability.map((row) => <tr key={`${row.providerId}-${row.type}`}><td>{ar ? posProviders.find((item) => item.id === row.providerId)?.nameAr : posProviders.find((item) => item.id === row.providerId)?.nameEn}</td><td>{ar ? posOperationTypes.find((item) => item.id === row.type)?.nameAr : posOperationTypes.find((item) => item.id === row.type)?.nameEn}</td><td>{row.count}</td><td>{money(row.averageAmount)}</td><td>{money(row.averageFee)}</td><td>{money(row.averageCost)}</td><td>{money(row.averageProfit)}</td><td>{money(row.totalProfit)}</td><td>{row.margin === null ? "—" : `${row.margin}%`}</td><td>{row.label === "insufficient" ? ar ? "بيانات غير كافية" : "Insufficient data" : row.label}</td></tr>)}</tbody></table>{!profitability.length && <p className="muted p-4">{ar ? "لا توجد عمليات كافية." : "No operations yet."}</p>}</div>}
    {tab === "rules" && <div className="mt-5 space-y-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{([ ["minimumCash", "الحد الأدنى للخزنة", "Minimum cash"], ["dailyProfitTarget", "هدف الربح اليومي", "Daily profit target"], ["dailyTransactionTarget", "هدف العمليات اليومي", "Daily transaction target"], ["maxPending", "أقصى عدد معلق", "Maximum pending"], ["maxVariance", "أقصى فرق مقبول", "Maximum variance"] ] as const).map(([key, labelAr, labelEn]) => <label key={key}>{ar ? labelAr : labelEn}<input type="number" min="0" value={data.rules[key]} onChange={(event) => updateRules({ ...data.rules, [key]: Math.max(0, Number(event.target.value) || 0) })}/></label>)}</div><h3>{ar ? "حدود الخدمات وقواعد الرسوم" : "Provider minimums and fee rules"}</h3><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{posProviders.map((provider) => <div key={provider.id} className="rounded-xl border border-daftar-line p-3"><b>{ar ? provider.nameAr : provider.nameEn}</b><label className="mt-2 block">{ar ? "الحد الأدنى" : "Minimum balance"}<input type="number" min="0" value={data.rules.minimumProviders[provider.id] ?? 0} onChange={(event) => updateRules({ ...data.rules, minimumProviders: { ...data.rules.minimumProviders, [provider.id]: Math.max(0, Number(event.target.value) || 0) } })}/></label><details className="mt-3"><summary>{ar ? "قواعد العمولة والتكلفة" : "Fee and cost rules"}</summary>{posOperationTypes.filter((type) => ["send-transfer", "cash-withdrawal", "bill-payment", "recharge"].includes(type.id)).map((type) => { const key = feeRuleKey(provider.id, type.id); return <div key={key} className="mt-2"><small>{ar ? type.nameAr : type.nameEn}</small><div className="grid grid-cols-2 gap-2"><label>{ar ? "عمولة عادية" : "Normal fee"}<input type="number" min="0" placeholder="—" value={data.rules.normalFees[key] ?? ""} onChange={(event) => { const next = { ...data.rules.normalFees }; if (event.target.value === "") delete next[key]; else next[key] = Math.max(0, Number(event.target.value) || 0); updateRules({ ...data.rules, normalFees: next }); }}/></label><label>{ar ? "تكلفة عادية" : "Normal cost"}<input type="number" min="0" placeholder="—" value={data.rules.normalCosts[key] ?? ""} onChange={(event) => { const next = { ...data.rules.normalCosts }; if (event.target.value === "") delete next[key]; else next[key] = Math.max(0, Number(event.target.value) || 0); updateRules({ ...data.rules, normalCosts: next }); }}/></label></div></div>; })}</details></div>)}</div></div>}
  </section>;
}
