"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, BarChart3, FileSpreadsheet, Gauge, ShieldCheck, WalletCards } from "lucide-react";
import { posProviders } from "@/data/pos";
import { calculatePosCommandCenter, calculateProviderPerformance, liquidityRecommendation, posReportCatalog } from "@/lib/pos/analytics";
import type { Locale, PosOperation, PosShiftSnapshot } from "@/types";

const money=(value:number)=>`${value.toLocaleString("ar-EG",{maximumFractionDigits:2})} ج.م`;
export function ServicePointIntelligence({locale,snapshot,operations}:{locale:Locale;snapshot:PosShiftSnapshot;operations:PosOperation[]}){
 const ar=locale==="ar",[tab,setTab]=useState("overview");
 const summary=useMemo(()=>calculatePosCommandCenter(snapshot,operations),[snapshot,operations]);
 const providers=useMemo(()=>calculateProviderPerformance(operations,snapshot.expectedProviders),[operations,snapshot.expectedProviders]);
 const max=Math.max(1,...providers.map((item)=>item.volume));
 const tabs=[['overview',ar?'لوحة التشغيل':'Operations'],['profit',ar?'الربحية':'Profitability'],['liquidity',ar?'السيولة':'Liquidity'],['controls',ar?'الرقابة':'Controls'],['reports',ar?'التقارير':'Reports']];
 return <section className="overflow-hidden rounded-3xl border border-daftar-line bg-daftar-card shadow-sm" data-no-bilingual><header className="bg-[#0f315d] p-6 text-white"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-sm"><Gauge size={16}/>{ar?'مركز قيادة نقطة الخدمات':'Service point command center'}</span><h2 className="mt-3 text-white">{ar?'الرصيد والحركة والربح والرقابة من العمليات الفعلية':'Live balances, activity, profit and controls'}</h2><nav className="mt-5 flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-2 text-sm font-bold ${tab===id?'bg-white text-[#0f315d]':'bg-white/10 text-white'}`}>{label}</button>)}</nav></header>
 {tab==='overview'&&<div className="p-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={WalletCards} label={ar?'السيولة الكلية':'Total liquidity'} value={money(summary.totalLiquidity)}/><Kpi icon={ArrowUpRight} label={ar?'إجمالي الداخل':'Money in'} value={money(summary.moneyIn)} good/><Kpi icon={ArrowDownLeft} label={ar?'إجمالي الخارج':'Money out'} value={money(summary.moneyOut)}/><Kpi icon={BarChart3} label={ar?'الربح الحقيقي':'True profit'} value={money(summary.trueProfit)} good={summary.trueProfit>=0}/></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Mini label={ar?'الخزنة':'Cash'} value={summary.cash}/><Mini label={ar?'المحافظ':'Wallets'} value={summary.wallets}/><Mini label={ar?'عمولات العملاء':'Customer fees'} value={summary.fees}/></div><p className="mt-4 rounded-2xl bg-blue-50 p-4 text-sm leading-7 text-blue-900">{ar?'الربح الحقيقي = عمولات العملاء − تكلفة مقدمي الخدمة − مصروفات التشغيل. التحويل الداخلي بين محافظ المحل لا يُحسب إيرادًا أو ربحًا.':'True profit excludes internal wallet transfers and deducts provider costs and operating expenses.'}</p></div>}
 {tab==='profit'&&<div className="grid gap-4 p-6 lg:grid-cols-2">{providers.map((item)=>{const p=posProviders.find((x)=>x.id===item.providerId)!;return <article className="rounded-2xl border border-daftar-line p-5" key={item.providerId}><div className="flex justify-between gap-3"><b>{ar?p.nameAr:p.nameEn}</b><strong className={item.profit>=0?'text-emerald-700':'text-red-700'}>{money(item.profit)}</strong></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full" style={{width:`${Math.max(2,item.volume/max*100)}%`,background:p.color}}/></div><div className="mt-4 flex justify-between text-sm"><span>{ar?'الحجم':'Volume'}: {money(item.volume)}</span><span>{ar?'الهامش':'Margin'}: {item.margin}%</span><span>{item.operations} {ar?'عملية':'ops'}</span></div></article>})}</div>}
 {tab==='liquidity'&&<div className="grid gap-3 p-6">{providers.map((item)=>{const p=posProviders.find((x)=>x.id===item.providerId)!;return <article className="grid gap-3 rounded-2xl border border-daftar-line p-4 md:grid-cols-[1fr_auto_1.5fr] md:items-center" key={item.providerId}><b>{ar?p.nameAr:p.nameEn}</b><strong>{money(item.balance)}</strong><p className={`text-sm ${item.health==='low'?'text-red-700':item.health==='dormant'?'text-amber-700':'text-emerald-700'}`}>{liquidityRecommendation(item.health,ar)}</p></article>})}<p className="rounded-2xl bg-daftar-bg p-4 text-sm">{ar?'التوصيات إرشادية فقط؛ النظام لا ينفذ تحويلات تلقائية.':'Recommendations are advisory; no automatic transfers are made.'}</p></div>}
 {tab==='controls'&&<div className="p-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Alert label={ar?'معلقة':'Pending'} value={summary.pending}/><Alert label={ar?'فاشلة':'Failed'} value={summary.failed}/><Alert label={ar?'مستردة':'Reversed'} value={summary.reversed}/><Alert label={ar?'اشتباه تكرار':'Duplicate risk'} value={summary.duplicateRisks}/></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Control icon={ShieldCheck} title={ar?'ضوابط التسجيل':'Posting controls'} body={ar?'منع الرصيد السالب، منع التسجيل دون وردية، تنبيه التكرار، وعدم تحريك الرصيد للعمليات المعلقة أو الفاشلة.':'Blocks negative balances and closed shifts; pending or failed activity does not move balances.'}/><Control icon={AlertTriangle} title={ar?'فرق الجرد':'Count variance'} body={`${money(summary.unresolvedVariance)} — ${ar?'راجعه واكتب سبب الفرق قبل الإقفال.':'Review and explain before close.'}`}/></div></div>}
 {tab==='reports'&&<div className="p-6"><h3 className="flex items-center gap-2"><FileSpreadsheet/>{ar?'مكتبة التقارير':'Report library'}</h3><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{posReportCatalog.map((name,index)=><div className="flex items-center gap-3 rounded-2xl border border-daftar-line p-4" key={name}><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 font-black text-daftar-primary">{index+1}</span><b>{ar?name:`Report ${index+1}`}</b></div>)}</div></div>}
 </section>;
}
function Kpi({icon:Icon,label,value,good=false}:{icon:typeof WalletCards;label:string;value:string;good?:boolean}){return <article className={`rounded-2xl border p-5 ${good?'border-emerald-200 bg-emerald-50':'border-blue-200 bg-blue-50'}`}><Icon/><small className="mt-4 block text-daftar-muted">{label}</small><strong className="mt-1 block text-2xl">{value}</strong></article>}
function Mini({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-daftar-bg p-4"><small>{label}</small><b className="mt-1 block text-xl">{money(value)}</b></div>}
function Alert({label,value}:{label:string;value:number}){return <div className={`rounded-2xl border p-5 ${value?'border-amber-200 bg-amber-50':'border-emerald-200 bg-emerald-50'}`}><small>{label}</small><strong className="mt-2 block text-3xl">{value}</strong></div>}
function Control({icon:Icon,title,body}:{icon:typeof ShieldCheck;title:string;body:string}){return <div className="rounded-2xl border border-daftar-line p-5"><Icon className="text-daftar-primary"/><b className="mt-3 block">{title}</b><p className="mt-2 text-sm leading-7 text-daftar-muted">{body}</p></div>}
