"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Check, CheckCircle2, CircleDollarSign, Clock3, Eye, Landmark, Play, RefreshCw, Rocket, ShieldAlert, Smartphone, Store, WalletCards, X } from "lucide-react";
import { posProviders } from "@/data/pos";
import { servicePointSalesDemoConfig as config } from "@/data/service-point-sales-demo";
import { calculatePosShiftSnapshot } from "@/lib/pos/engine";
import { buildOwnerCommandCenter } from "@/lib/pos/recommendations";
import { recommendedDemoPlan } from "@/lib/pos/sales-demo";
import { loadLocalSubscription, loadServicePointSettings, seedSalesDemo } from "@/lib/storage/service-point-demo";
import { demoAcknowledgeAlert, demoAcknowledgeOwner, demoCloseShift, demoRecordFawry, demoRecordPending, demoRecordVodafone, demoStartShift, initializeInteractiveSalesDemo, loadSalesDemoProgress, resetInteractiveSalesDemo } from "@/lib/storage/service-point-sales-demo";
import { loadPosOperations, loadPosShifts } from "@/lib/storage/pos";
import { PwaInstallCard } from "@/components/pwa/pwa-install-card";
import type { Locale, PosProviderId, PosShiftSnapshot } from "@/types";
import type { SalesDemoProgress } from "@/types/sales-demo";

const money = (value: number) => `${value.toLocaleString("ar-EG", { maximumFractionDigits: 2 })} ج.م`;

export function ServicePointSalesDemo({ locale }: { locale: Locale }) {
  const ar = locale === "ar", router = useRouter();
  const [ready, setReady] = useState(false), [progress, setProgress] = useState<SalesDemoProgress>(), [resume, setResume] = useState(false), [message, setMessage] = useState(""), [toast, setToast] = useState(""), [showInstall, setShowInstall] = useState(false);
  useEffect(() => { const saved = loadSalesDemoProgress(); setProgress(saved); setResume(Boolean(saved?.status === "active" && saved.demoStep > 1)); setReady(true); }, []);
  useEffect(() => { if (progress?.demoStep === 5 && !localStorage.getItem("finora-demo-install-cta-seen")) { localStorage.setItem("finora-demo-install-cta-seen", "1"); setShowInstall(true); } }, [progress?.demoStep]);
  const model = useMemo(() => {
    if (!progress) return undefined;
    const shifts = loadPosShifts(progress.storeId), operations = loadPosOperations(progress.storeId), shift = shifts[0];
    const snapshot: PosShiftSnapshot = shift ? calculatePosShiftSnapshot(shift, operations, shift.status === "closed" ? shift.actualClosingCash : undefined, shift.status === "closed" ? Object.fromEntries(shift.providers.map((provider) => [provider.providerId, provider.actualClosingBalance])) as Partial<Record<PosProviderId, number>> : undefined) : { expectedCash: config.openingCash, expectedProviders: config.providerBalances, revenue: 0, expenses: 0, profit: 0, operationCount: 0 };
    const command = buildOwnerCommandCenter({ storeId: progress.storeId, storeName: progress.locale === "ar" ? config.businessNameAr : config.businessNameEn, shifts, operations, snapshot, settings: loadServicePointSettings(), subscription: loadLocalSubscription() });
    return { shifts, operations, shift, snapshot, command };
  }, [progress]);
  const run = (action: (value: SalesDemoProgress) => SalesDemoProgress) => { if (!progress) return; try { const finishedStep = progress.demoStep; setProgress(action(progress)); setMessage(""); const success = ar ? ["تم فتح الوردية بنجاح.", "تم تنفيذ عملية فوري وحساب ربحها.", "تم تحديث رصيد Vodafone Cash مستقلًا.", "تم حفظ العملية كمعلقة دون تحريك الأرصدة.", "تمت مراجعة التنبيه.", "تمت مراجعة لوحة المالك.", "تم إقفال الوردية وكشف الفرق."][finishedStep - 1] : ["Shift opened successfully.", "Fawry operation posted and profit calculated.", "Vodafone Cash balance updated separately.", "Pending operation saved without moving balances.", "Alert reviewed.", "Owner dashboard reviewed.", "Shift closed and variance detected."][finishedStep - 1]; setToast(success); window.setTimeout(() => setToast(""), 1800); } catch { setMessage(ar ? "الخطوة الحالية لم تكتمل. ارجع للمهمة وحاول مرة أخرى." : "The current step is not complete. Return to the task and try again."); } };
  const start = () => { const next = initializeInteractiveSalesDemo(new Date(), locale); setProgress(next); setResume(false); };
  const restart = () => { resetInteractiveSalesDemo(); start(); };
  const skip = () => { if (confirm(ar ? "هل تريد الخروج من التجربة السريعة؟" : "Exit the quick demo?")) router.push(`/${locale}/service-point`); };
  if (!ready) return <main className="grid min-h-[70vh] place-items-center"><div className="pwa-startup"><Image src="/finora-icon-192.png" alt="FINORA" width={72} height={72}/><b>FINORA</b></div></main>;
  if (!progress) return <DemoLanding locale={locale} onStart={start} onFull={() => { seedSalesDemo(); router.push(`/${locale}/service-point/owner-dashboard`); }}/>
  if (resume) return <main className="demo-page grid min-h-screen place-items-center p-4" dir={ar ? "rtl" : "ltr"}><section className="w-full max-w-md rounded-[2rem] bg-white p-7 shadow-2xl"><Clock3 className="text-blue-700" size={35}/><h1 className="mt-4 text-2xl">{ar ? "تكمل التجربة من حيث توقفت؟" : "Continue where you left off?"}</h1><p className="mt-2 text-slate-600">{ar ? `توقفت عند الخطوة ${progress.demoStep} من 7.` : `You stopped at step ${progress.demoStep} of 7.`}</p><div className="mt-6 grid gap-3"><button className="btn btn-primary" onClick={() => setResume(false)}>{ar ? "متابعة" : "Continue"}</button><button className="btn" onClick={restart}><RefreshCw size={17}/>{ar ? "ابدأ من جديد" : "Start again"}</button></div></section></main>;
  if (progress.status === "completed" && model) return <DemoFinale locale={locale} model={model} restart={restart}/>;
  const step = progress.demoStep;
  return <main className="demo-page min-h-screen pb-[calc(7rem+env(safe-area-inset-bottom))]" dir={ar ? "rtl" : "ltr"}>
    <header className="demo-header"><Link href={`/${locale}/service-point`} className="demo-logo"><Image src="/finora-icon-192.png" alt="FINORA" width={40} height={40}/><span><b>FINORA</b><small>{ar ? "تجربة 5 دقائق" : "5-minute demo"}</small></span></Link><button onClick={skip} aria-label={ar ? "تخطي الجولة" : "Skip tour"}><X size={18}/>{ar ? "تخطي" : "Skip"}</button></header>
    <div className="demo-progress"><i style={{ width: `${step / 7 * 100}%` }}/></div>
    <div className="mx-auto grid max-w-6xl gap-5 p-3 sm:p-6 lg:grid-cols-[330px_1fr]">
      <aside className="demo-task-card"><span>{ar ? `الخطوة ${step} من 7` : `Step ${step} of 7`}</span><h1>{stepTitle(step, ar)}</h1><p>{stepTask(step, ar)}</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Smartphone size={15}/>{ar ? "مصممة للاستخدام بإبهام واحد" : "Designed for one-thumb use"}</div></aside>
      <section className="demo-workspace demo-spotlight">
        {step === 1 && <StartShiftStep ar={ar} onRun={() => run((value) => demoStartShift(value))}/>} 
        {step === 2 && <FawryStep ar={ar} onRun={() => run(demoRecordFawry)}/>} 
        {step === 3 && <VodafoneStep ar={ar} model={model} onRun={() => run(demoRecordVodafone)}/>} 
        {step === 4 && <PendingStep ar={ar} onRun={() => run((value) => demoRecordPending(value))}/>} 
        {step === 5 && <AlertStep ar={ar} model={model} onRun={() => run(demoAcknowledgeAlert)}/>} 
        {step === 6 && <OwnerStep ar={ar} model={model} locale={locale} onRun={() => run(demoAcknowledgeOwner)}/>} 
        {step === 7 && <CloseStep ar={ar} model={model} onRun={() => run((value) => demoCloseShift(value))}/>} 
      </section>
    </div>
    {message && <div className="demo-error"><AlertTriangle size={17}/>{message}<button onClick={() => setMessage("")}>{ar ? "العودة للمهمة" : "Return to task"}</button></div>}
    {toast && <div className="demo-toast"><CheckCircle2 size={18}/>{toast}</div>}
    {showInstall && <div className="demo-install"><button className="demo-install-close" onClick={() => setShowInstall(false)} aria-label={ar ? "إغلاق" : "Close"}><X/></button><PwaInstallCard locale={locale}/></div>}
  </main>;
}

function DemoLanding({ locale, onStart, onFull }: { locale: Locale; onStart: () => void; onFull: () => void }) { const ar = locale === "ar"; return <main className="demo-landing min-h-screen" dir={ar ? "rtl" : "ltr"}><div className="mx-auto grid max-w-6xl gap-8 px-4 py-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><section><span className="inline-flex items-center gap-2 rounded-full bg-emerald-400/15 px-4 py-2 text-sm font-bold text-emerald-200"><Play size={16}/>{ar ? "تجربة تفاعلية — بدون تسجيل" : "Interactive demo — no sign-up"}</span><h1 className="mt-6 text-4xl font-black text-white sm:text-6xl">{ar ? "جرّب FINORA بنفسك" : "Try FINORA yourself"}</h1><p className="mt-5 max-w-2xl text-lg leading-9 text-white/70">{ar ? "عِش يوم عمل كامل في محل خدمات: افتح الوردية، نفّذ عملية، راقب الربح، واكتشف الفرق بنفسك." : "Run a real service-point day: open a shift, post an operation, see true profit, and catch the difference yourself."}</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><button className="demo-primary" onClick={onStart}><Play/>{ar ? "تجربة 5 دقائق" : "5-minute demo"}</button><button className="demo-secondary" onClick={onFull}><BarChart3/>{ar ? "بيانات جاهزة كاملة" : "Full ready data"}</button><Link className="demo-secondary" href={`/${locale}/service-point`}><Rocket/>{ar ? "ابدأ نشاطك" : "Start your business"}</Link></div><p className="mt-6 text-sm text-white/60">{ar ? "نسخة العرض تحفظ بيانات التجربة على الجهاز الحالي. لا توجد مزامنة سحابية مفعلة." : "Demo data is saved on this device. Cloud sync is not enabled."}</p><div className="mt-5 max-w-xl"><PwaInstallCard locale={locale}/></div></section><aside className="demo-qr-card"><Image src="/finora-mobile-demo-qr.svg" alt={ar ? "QR لتجربة FINORA على الهاتف" : "QR code for the FINORA mobile demo"} width={220} height={220}/><div><Smartphone className="text-emerald-600"/><h2>{ar ? "جرّب FINORA على موبايلك" : "Try FINORA on your phone"}</h2><p>{ar ? "امسح الكود وافتح التجربة على جهازك. سيحفظ الهاتف Dataset مستقلة." : "Scan to open the demo. Your phone will keep a separate local dataset."}</p></div></aside></div></main>; }

function StartShiftStep({ ar, onRun }: { ar: boolean; onRun: () => void }) { return <><StepHead icon={Store} title={ar ? "ابدأ يوم العمل" : "Start the workday"} text={ar ? "راجع النقدية والأرصدة ثم افتح الوردية." : "Review cash and balances, then open the shift."}/><div className="demo-balance-grid"><Kpi label={ar ? "الكاشير" : "Cashier"} value={ar ? config.cashierNameAr : config.cashierNameEn}/><Kpi label={ar ? "الخزنة الافتتاحية" : "Opening cash"} value={money(config.openingCash)}/>{(["fawry", "vodafone-cash", "orange-cash", "instapay"] as PosProviderId[]).map((id) => <Kpi key={id} label={providerName(id, ar)} value={money(config.providerBalances[id])}/>)}</div><button className="demo-action" onClick={onRun}><Check/>{ar ? "فتح الوردية" : "Open shift"}</button></>; }
function FawryStep({ ar, onRun }: { ar: boolean; onRun: () => void }) { const profit = config.fawry.customerFee - config.fawry.providerCost; return <><StepHead icon={CircleDollarSign} title={ar ? "فاتورة فوري بقيمة 1,000 جنيه" : "Pay a 1,000 EGP Fawry bill"} text={ar ? "راجع أثر العملية الحقيقي قبل التنفيذ." : "Review the real financial impact before posting."}/><div className="demo-preview"><Kpi label={ar ? "قيمة العملية" : "Transaction value"} value={money(config.fawry.amount)}/><Kpi label={ar ? "حركة الخزنة" : "Cash impact"} value={`+${money(config.fawry.amount + config.fawry.customerFee)}`}/><Kpi label={ar ? "حركة رصيد فوري" : "Fawry balance impact"} value={`-${money(config.fawry.amount + config.fawry.providerCost)}`}/><Kpi label={ar ? "عمولة العميل" : "Customer commission"} value={money(config.fawry.customerFee)}/><Kpi label={ar ? "تكلفة مقدم الخدمة" : "Provider cost"} value={money(config.fawry.providerCost)}/><Kpi label={ar ? "صافي الربح" : "Net profit"} value={money(profit)}/></div><p className="demo-insight">{ar ? `FINORA فصل قيمة العملية عن ربح المحل: 1,000 ج.م حركة، لكن الربح الحقيقي ${profit} ج.م.` : `FINORA separates transaction value from store profit: 1,000 EGP moved, but true profit is ${profit} EGP.`}</p><button className="demo-action" onClick={onRun}><Check/>{ar ? "تنفيذ العملية" : "Post operation"}</button></>; }
function VodafoneStep({ ar, model, onRun }: { ar: boolean; model?: ReturnTypeModel; onRun: () => void }) { return <><StepHead icon={WalletCards} title={ar ? "عملية سريعة على Vodafone Cash" : "Quick Vodafone Cash operation"} text={ar ? "اضغط مرة واحدة؛ البيانات جاهزة حتى ترى استقلال الأرصدة." : "One tap—details are ready so you can see separate balances."}/><div className="demo-preview"><Kpi label="Fawry" value={money(model?.snapshot.expectedProviders.fawry || 0)}/><Kpi label="Vodafone Cash" value={money(model?.snapshot.expectedProviders["vodafone-cash"] || 0)}/><Kpi label={ar ? "العملية التالية" : "Next operation"} value={money(config.vodafone.amount)}/><Kpi label={ar ? "ربحها الحقيقي" : "True profit"} value={money(config.vodafone.customerFee - config.vodafone.providerCost)}/></div><p className="demo-insight">{ar ? "رصيد فوري وVodafone Cash منفصلان؛ لا تختلط أموال الخدمات." : "Fawry and Vodafone Cash stay separate; provider funds are never mixed."}</p><button className="demo-action" onClick={onRun}><Check/>{ar ? "تنفيذ العملية السريعة" : "Post quick operation"}</button></>; }
function PendingStep({ ar, onRun }: { ar: boolean; onRun: () => void }) { return <><StepHead icon={Clock3} title={ar ? "عملية تحتاج تأكيدًا" : "An operation awaiting confirmation"} text={ar ? "سجّلها كمعلقة حتى لا تحرك الأرصدة قبل التأكد." : "Keep it pending so balances do not move before confirmation."}/><div className="demo-preview"><Kpi label={ar ? "القيمة" : "Amount"} value={money(config.pending.amount)}/><Kpi label={ar ? "الحالة" : "Status"} value={ar ? "معلقة" : "Pending"}/><Kpi label={ar ? "أثر الخزنة الآن" : "Cash impact now"} value={money(0)}/><Kpi label={ar ? "أثر الرصيد الآن" : "Balance impact now"} value={money(0)}/></div><p className="demo-insight">{ar ? "العملية المعلقة لا تحرك الخزنة أو رصيد الخدمة حتى يتم اعتمادها." : "A pending operation does not move cash or provider balance until approved."}</p><button className="demo-action" onClick={onRun}><Clock3/>{ar ? "حفظ كعملية معلقة" : "Save as pending"}</button></>; }
function AlertStep({ ar, model, onRun }: { ar: boolean; model?: ReturnTypeModel; onRun: () => void }) { const alert = model?.command.recommendations.find((item) => item.type === "LOW_SERVICE_BALANCE"); return <><StepHead icon={ShieldAlert} title={ar ? "راجع المشكلة قبل ما تكبر" : "Catch the issue before it grows"} text={ar ? "التنبيه خرج من قواعد FINORA المحلية، وليس رقمًا مكتوبًا يدويًا." : "This alert comes from FINORA's local rules, not a hardcoded KPI."}/><article className="demo-alert"><ShieldAlert/><div><b>{alert ? (ar ? alert.titleAr : alert.titleEn) : (ar ? "رصيد فوري يحتاج متابعة" : "Fawry balance needs attention")}</b><p>{alert ? (ar ? alert.descriptionAr : alert.descriptionEn) : "—"}</p><strong>{money(model?.snapshot.expectedProviders.fawry || 0)}</strong></div></article><button className="demo-action" onClick={onRun}><Eye/>{ar ? "راجعت الرصيد" : "Balance reviewed"}</button></>; }
function OwnerStep({ ar, model, locale, onRun }: { ar: boolean; model?: ReturnTypeModel; locale: Locale; onRun: () => void }) { return <><StepHead icon={BarChart3} title={ar ? "دي الشاشة اللي صاحب المحل بيراجع منها شغله" : "This is where the owner reviews the business"} text={ar ? "في Cloud Edition مستقبلًا يمكن مزامنة اللوحة بين الأجهزة؛ المزامنة غير مفعلة الآن." : "A future Cloud Edition can sync this view across devices; sync is not enabled now."}/><div className="demo-owner"><Kpi label={ar ? "ربح اليوم" : "Today's profit"} value={money(model?.command.today.profit || 0)}/><Kpi label={ar ? "الخزنة" : "Cash"} value={money(model?.snapshot.expectedCash || 0)}/><Kpi label={ar ? "أرصدة الخدمات" : "Service balances"} value={money(Object.values(model?.snapshot.expectedProviders || {}).reduce((sum, value) => sum + value, 0))}/><Kpi label={ar ? "العمليات" : "Operations"} value={String(model?.command.today.operations || 0)}/><Kpi label={ar ? "أفضل خدمة" : "Top provider"} value={model?.command.providerPerformance[0] ? providerName(model.command.providerPerformance[0].providerId, ar) : "—"}/><Kpi label={ar ? "الكاشير" : "Cashier"} value={ar ? config.cashierNameAr : config.cashierNameEn}/></div><div className="mt-5 flex flex-wrap gap-3"><button className="demo-action" onClick={onRun}>{ar ? "متابعة إلى الإقفال" : "Continue to close"}</button><Link className="btn" href={`/${locale}/service-point/owner-dashboard`}>{ar ? "فتح اللوحة الكاملة" : "Open full dashboard"}</Link></div></>; }
function CloseStep({ ar, model, onRun }: { ar: boolean; model?: ReturnTypeModel; onRun: () => void }) { const expected = model?.snapshot.expectedCash || 0, actual = expected + config.closingDifference; return <><StepHead icon={Landmark} title={ar ? "أقفل الوردية واكتشف الفرق" : "Close the shift and catch the difference"} text={ar ? "الفارق إشارة تحتاج مراجعة، وليس اتهامًا للكاشير." : "The variance is a review signal, not an accusation."}/><div className="demo-close"><Kpi label={ar ? "الخزنة المتوقعة" : "Expected cash"} value={money(expected)}/><Kpi label={ar ? "الخزنة الفعلية" : "Actual cash"} value={money(actual)}/><Kpi label={ar ? "الفرق" : "Difference"} value={money(config.closingDifference)}/><Kpi label={ar ? "المعلقة" : "Pending"} value={String(model?.command.today.pending || 0)}/></div><p className="demo-insight">{ar ? `FINORA سيكشف فرق ${money(config.closingDifference)} فورًا ويضعه للمراجعة.` : `FINORA will flag the ${money(config.closingDifference)} variance immediately for review.`}</p><button className="demo-action" onClick={onRun}><CheckCircle2/>{ar ? "إقفال الوردية" : "Close shift"}</button></>; }

type ReturnTypeModel = { shifts: ReturnType<typeof loadPosShifts>; operations: ReturnType<typeof loadPosOperations>; shift: ReturnType<typeof loadPosShifts>[number] | undefined; snapshot: PosShiftSnapshot; command: ReturnType<typeof buildOwnerCommandCenter> };
function DemoFinale({ locale, model, restart }: { locale: Locale; model: ReturnTypeModel; restart: () => void }) {
  const ar = locale === "ar", plan = recommendedDemoPlan(["owner-command-center", "smart-brief", "cashier-performance", "advanced-alerts", "profitability"]);
  const items = ar ? ["فتح وردية", "تتبع أرصدة الخدمات", "حساب الربح الحقيقي", "متابعة المعلقات", "تنبيهات ذكية", "مراقبة الكاشير", "إقفال الوردية", "كشف الفرق", "تقرير صاحب المحل"] : ["Open a shift", "Track provider balances", "Calculate true profit", "Monitor pending operations", "Use smart alerts", "Review cashier performance", "Close the shift", "Detect variance", "Read the owner report"];
  return <main className="demo-finale min-h-screen p-4 sm:p-8" dir={ar ? "rtl" : "ltr"}><div className="mx-auto max-w-5xl">
    <section className="rounded-[2rem] bg-[#082c52] p-6 text-white shadow-2xl sm:p-10"><span className="inline-flex rounded-full bg-emerald-400/15 px-3 py-1 text-sm font-bold text-emerald-200">FINORA · Demo complete</span><h1 className="mt-5 text-3xl font-black text-white sm:text-5xl">{ar ? "شفت FINORA بيعمل إيه في يوم شغل؟" : "See what FINORA does in one workday?"}</h1><div className="mt-7 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <span className="flex items-center gap-2 rounded-xl bg-white/10 p-3 text-sm" key={item}><Check className="text-emerald-300" size={17}/>{item}</span>)}</div></section>
    <section className="mt-5 rounded-[2rem] bg-white p-6 shadow-sm sm:p-8"><h2>{ar ? "نتيجة إقفال الوردية" : "Shift close result"}</h2><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4"><Kpi label={ar ? "العمليات" : "Operations"} value={String(model.command.today.operations)}/><Kpi label={ar ? "حجم العمليات" : "Transaction volume"} value={money(model.command.today.volume)}/><Kpi label={ar ? "إيراد العمولات" : "Commission revenue"} value={money(model.command.today.revenue)}/><Kpi label={ar ? "تكلفة مقدم الخدمة" : "Provider cost"} value={money(model.command.today.providerCosts)}/><Kpi label={ar ? "صافي الربح" : "Net profit"} value={money(model.command.today.profit)}/><Kpi label={ar ? "فرق الخزنة" : "Cash difference"} value={money(model.snapshot.totalVariance || 0)}/><Kpi label={ar ? "المعلقة" : "Pending"} value={String(model.command.today.pending)}/><Kpi label={ar ? "الفاشلة" : "Failed"} value={String(model.command.today.failed)}/></div>
      <h2 className="mt-8">{ar ? "ملخص FINORA لليوم" : "FINORA summary for today"}</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><FinalBrief label={ar ? "ما حدث" : "What happened"} value={ar ? model.command.brief.happenedAr : model.command.brief.happenedEn}/><FinalBrief label={ar ? "ما يحتاج الانتباه" : "What needs attention"} value={ar ? model.command.brief.attentionAr : model.command.brief.attentionEn}/><FinalBrief label={ar ? "الإجراء الأول" : "First action"} value={(ar ? model.command.brief.actionsAr : model.command.brief.actionsEn)[0] || "—"}/></div><div className="mt-6 rounded-2xl bg-blue-50 p-4 text-blue-950"><b>{ar ? `الباقة الأنسب للتجربة التي شاهدتها: ${plan.toUpperCase()}` : `Recommended plan for what you explored: ${plan.toUpperCase()}`}</b><p className="mt-1 text-sm">{ar ? "توصية مبنية على المزايا التي ظهرت في الجولة، وليست قرار ذكاء اصطناعي." : "A rule-based suggestion from the features shown—not an AI decision."}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Link className="btn btn-primary" href={`/${locale}/service-point/plans`}>{ar ? "شاهد الباقات" : "View plans"}</Link><Link className="btn" href={`/${locale}/service-point`}>{ar ? "ابدأ نشاطك" : "Start your business"}</Link><button className="btn" onClick={restart}><RefreshCw/>{ar ? "أعد التجربة" : "Replay demo"}</button></div></section>
  </div></main>;
}
function StepHead({ icon: Icon, title, text }: { icon: typeof Store; title: string; text: string }) { return <header className="demo-step-head"><span><Icon/></span><div><h2>{title}</h2><p>{text}</p></div></header>; }
function Kpi({ label, value }: { label: string; value: string }) { return <article className="demo-kpi"><small>{label}</small><b>{value}</b></article>; }
function FinalBrief({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl bg-slate-50 p-4"><small className="font-bold text-blue-700">{label}</small><p className="mt-2 text-sm leading-7 text-slate-600">{value}</p></article>; }
function providerName(id: PosProviderId, ar: boolean) { const provider = posProviders.find((item) => item.id === id); return (ar ? provider?.nameAr : provider?.nameEn) || id; }
function stepTitle(step: number, ar: boolean) { const values = ar ? ["ابدأ يوم العمل", "سجّل فاتورة فوري", "افصل أرصدة الخدمات", "تابع عملية معلقة", "راجع التنبيه الذكي", "افتح لحظة المالك", "أقفل الوردية"] : ["Start the workday", "Post a Fawry bill", "Keep balances separate", "Track a pending operation", "Review the smart alert", "See the owner moment", "Close the shift"]; return values[step - 1]; }
function stepTask(step: number, ar: boolean) { const values = ar ? ["راجع الأرصدة واضغط فتح الوردية.", "راجع المعاينة ثم نفّذ العملية.", "نفّذ عملية Vodafone الجاهزة.", "احفظ العملية بالحالة المعلقة.", "اقرأ السبب وراجع الرصيد.", "راجع مؤشرات صاحب المحل.", "قارن المتوقع بالفعلي ثم أقفل."] : ["Review balances and open the shift.", "Review the preview and post.", "Post the ready Vodafone operation.", "Save the operation as pending.", "Read the reason and review balance.", "Review the owner's indicators.", "Compare expected and actual, then close."]; return values[step - 1]; }
