"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArchiveRestore, BarChart3, Bell, Building2, Check, ChevronLeft, ChevronRight, Cloud, Crown, Download, FileBarChart, HardDriveDownload, Home, KeyRound, Languages, Menu, Moon, Play, Plus, ReceiptText, Rocket, Search, Settings, ShieldCheck, Sparkles, Store, Upload, UserRound, UsersRound, WalletCards, X } from "lucide-react";
import { useTheme } from "next-themes";
import { posProviders } from "@/data/pos";
import { getServicePointPlan, servicePointCommercialConfig } from "@/data/service-point-plans";
import { canLocalRole, effectiveSubscriptionStatus, trialDaysRemaining } from "@/lib/pos/demo";
import { appendLocalAudit, createLocalUser, currentLocalUser, ensureLocalSubscription, exportServicePointBackup, loadLocalAudit, loadLocalSubscription, loadLocalUsers, loadServicePointSettings, parseServicePointBackup, resetSalesDemo, restoreServicePointBackup, saveLocalSubscription, saveServicePointSettings, seedSalesDemo, setCurrentLocalUser, verifyLocalPin } from "@/lib/storage/service-point-demo";
import { createPosStore, openPosShift } from "@/lib/storage/pos";
import type { Locale, PosProviderId, PosShift } from "@/types";
import type { LocalRole, PlanId, ServicePointBackup } from "@/types/service-point-demo";
import { PwaInstallCard } from "@/components/pwa/pwa-install-card";
import { HawallyBrand } from "@/components/brand/hawally-brand";

const roleNames:Record<LocalRole,{ar:string;en:string}>={owner:{ar:"المالك",en:"Owner"},manager:{ar:"مدير",en:"Manager"},cashier:{ar:"كاشير",en:"Cashier"},accountant:{ar:"محاسب",en:"Accountant"},viewer:{ar:"مشاهدة فقط",en:"Viewer"}};

export function ServicePointDemoShell({locale,children}:{locale:Locale;children:React.ReactNode}){
  const ar=locale==="ar",[ready,setReady]=useState(false),[refresh,setRefresh]=useState(0),[panel,setPanel]=useState<"none"|"settings"|"users"|"audit"|"backup"|"login">("none"),[tour,setTour]=useState(0);
  const [activeHash,setActiveHash]=useState("#pos-app-root");
  const {setTheme,resolvedTheme}=useTheme();
  void refresh;
  const settings=ready?loadServicePointSettings():undefined,subscription=ready?ensureLocalSubscription():undefined,user=ready?currentLocalUser():undefined;
  useEffect(()=>setReady(true),[]);
  useEffect(()=>{if(settings?.onboardingComplete&&!settings.tourComplete)setTour(1);},[settings]);
  useEffect(()=>{const sync=()=>setActiveHash(window.location.hash||"#pos-app-root");sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync);},[]);
  if(!ready)return <div className="min-h-[60vh]"/>;
  if(!settings?.onboardingComplete)return <div className="sp-demo-shell"><Onboarding locale={locale} onDone={()=>setRefresh(x=>x+1)}/></div>;
  const days=subscription?trialDaysRemaining(subscription):0,status=subscription?effectiveSubscriptionStatus(subscription):"trial";
  const other=ar?"en":"ar";
  return <div className="sp-demo-shell hawally-app-shell" data-no-bilingual>
    <aside className="hawally-sidebar no-print">
      <HawallyBrand locale={locale} href={`/${locale}/service-point`}/>
      <nav>
        <a className={activeHash==="#pos-app-root"?"active":""} href="#pos-app-root"><Home/>{ar?"الرئيسية":"Home"}</a>
        <a className={activeHash==="#new-operation"?"active":""} href="#new-operation"><ReceiptText/>{ar?"العمليات":"Operations"}</a>
        <a className={activeHash==="#service-point-intelligence"?"active":""} href="#service-point-intelligence"><WalletCards/>{ar?"الخدمات والأرصدة":"Services & balances"}</a>
        <a className={activeHash==="#shift-actions"?"active":""} href="#shift-actions"><Store/>{ar?"الورديات والتسوية":"Shifts & reconcile"}</a>
        <a className={activeHash==="#service-point-reports"?"active":""} href="#service-point-reports"><FileBarChart/>{ar?"التقارير":"Reports"}</a>
        <a className={activeHash==="#store-accounts"?"active":""} href="#store-accounts"><Building2/>{ar?"المحلات":"Stores"}</a>
        <a className={activeHash==="#service-point-control"?"active":""} href="#service-point-control"><UsersRound/>{ar?"الفريق والرقابة":"Team & control"}</a>
        <Link href={`/${locale}/service-point/owner-dashboard`}><BarChart3/>{ar?"لوحة المالك":"Owner dashboard"}</Link>
        <button className={panel==="audit"?"active":""} onClick={()=>setPanel("audit")}><Bell/>{ar?"التنبيهات والسجل":"Alerts & audit"}</button>
        <button onClick={()=>setPanel("backup")}><HardDriveDownload/>{ar?"النسخ والتقارير":"Backup & reports"}</button>
        <button className={panel==="settings"?"active":""} onClick={()=>setPanel("settings")}><Settings/>{ar?"الإعدادات":"Settings"}</button>
      </nav>
      <Link className="hawally-sidebar-plan" href={`/${locale}/service-point/plans`}><Crown/>{status==="expired-demo"?(ar?"انتهت التجربة":"Trial expired"):(ar?`${days} يوم متبقٍ`:`${days} days left`)}</Link>
    </aside>
    <div className="hawally-main">
      <header className="hawally-topbar no-print">
        <div className="hawally-mobile-brand"><HawallyBrand locale={locale} href={`/${locale}/service-point`} compact/></div>
        <a className={`hawally-search ${activeHash==="#operation-search"?"active":""}`} href="#operation-search"><Search/><span>{ar?"ابحث عن عملية أو مرجع...":"Search operations or references..."}</span><kbd>Ctrl K</kbd></a>
        <div className="hawally-top-actions">
          <Link href={`/${other}/service-point`} className="hawally-icon-button" aria-label={ar?"English":"العربية"}><Languages/></Link>
          <button className="hawally-icon-button" onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")} aria-label={ar?"تغيير المظهر":"Toggle theme"}><Moon/></button>
          <button className="hawally-user" onClick={()=>setPanel("login")}><span><b>{user?.name|| (ar?"مستخدم محلي":"Local user")}</b><small>{user?roleNames[user.role][ar?"ar":"en"]:(ar?"بيانات هذا الجهاز":"This device")}</small></span><UserRound/></button>
          <button className="hawally-icon-button md:hidden" onClick={()=>setPanel(panel==="none"?"settings":"none")}><Menu/></button>
        </div>
      </header>
      <div className="hawally-content">
        {panel!=="none"&&<DemoPanel locale={locale} panel={panel} close={()=>setPanel("none")} changed={()=>setRefresh(x=>x+1)}/>}
        {status==="expired-demo"&&<div className="hawally-info-card"><b>{ar?"انتهت التجربة المجانية — بياناتك ما زالت محفوظة.":"Your free trial ended — your data is still safe."}</b><p>{ar?"يمكنك الاستعراض والطباعة والنسخ الاحتياطي واختيار باقة في أي وقت.":"You can still view, print, back up, and choose a plan."}</p></div>}
        {children}
      </div>
    </div>
    <nav className="hawally-mobile-nav no-print"><a className={activeHash==="#pos-app-root"?"active":""} href="#pos-app-root"><Home/>{ar?"الرئيسية":"Home"}</a><a className={activeHash==="#new-operation"?"active":""} href="#new-operation"><Plus/>{ar?"عملية":"New"}</a><a className={activeHash==="#service-point-intelligence"?"active":""} href="#service-point-intelligence"><WalletCards/>{ar?"الخدمات":"Services"}</a><a className={activeHash==="#shift-actions"?"active":""} href="#shift-actions"><Store/>{ar?"الوردية":"Shift"}</a><button className={panel==="settings"?"active":""} onClick={()=>setPanel("settings")}><Settings/>{ar?"المزيد":"More"}</button></nav>
    {tour>0&&<ProductTour locale={locale} step={tour} next={()=>{if(tour===5){saveServicePointSettings({...settings,tourComplete:true});setTour(0);}else setTour(x=>x+1);}} skip={()=>{saveServicePointSettings({...settings,tourComplete:true});setTour(0);}}/>}
  </div>;
}

function Onboarding({locale,onDone}:{locale:Locale;onDone:()=>void}){
  const ar=locale==="ar",[mode,setMode]=useState<"choice"|"empty">("choice"),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[business,setBusiness]=useState(""),[storeName,setStoreName]=useState(""),[providers,setProviders]=useState<PosProviderId[]>(posProviders.map(x=>x.id)),[cash,setCash]=useState("5000"),[balances,setBalances]=useState<Record<string,string>>(Object.fromEntries(posProviders.map(x=>[x.id,x.id==="fawry"?"5000":"2000"]))),[cashier,setCashier]=useState(""),[pin,setPin]=useState("1234"),[plan,setPlan]=useState<PlanId>("pro");
  const startDemo=async()=>{setBusy(true);const owner=await createLocalUser(ar?"مالك التجربة":"Demo Owner","owner","5678");await createLocalUser(ar?"أحمد الكاشير":"Ahmed Cashier","cashier","1234");setCurrentLocalUser(owner.id);ensureLocalSubscription("pro");saveServicePointSettings({...loadServicePointSettings(),onboardingComplete:true,profileMode:"demo",businessName:"Hawally Demo Business",enabledProviders:posProviders.map(x=>x.id),salesDemoMode:true});seedSalesDemo();appendLocalAudit("onboarding","system","Ready-made demo selected",owner);setBusy(false);onDone();};
  const finish=async()=>{setBusy(true);const store=createPosStore(storeName.trim()||business.trim()),now=new Date(),shift:PosShift={id:crypto.randomUUID(),storeName:store.name,cashierName:cashier.trim(),businessDate:now.toISOString().slice(0,10),openedAt:now.toISOString(),status:"open",openingCash:Number(cash)||0,providers:posProviders.map(p=>({providerId:p.id,openingBalance:providers.includes(p.id)?Number(balances[p.id])||0:0}))};openPosShift(store.id,shift);const owner=await createLocalUser(ar?`مالك ${business}`:`${business} Owner`,"owner","5678");await createLocalUser(cashier.trim(),"cashier",pin);setCurrentLocalUser(owner.id);saveLocalSubscription({...ensureLocalSubscription(plan),currentPlan:plan});saveServicePointSettings({...loadServicePointSettings(),onboardingComplete:true,profileMode:"empty",businessName:business.trim(),enabledProviders:providers,salesDemoMode:false});appendLocalAudit("open-shift","shift",`${store.name} — ${cashier}`,owner);setBusy(false);onDone();};
  if(mode==="choice")return <main className="sp-onboarding-choice min-h-screen px-4 py-10"><div className="mx-auto max-w-5xl"><div className="mx-auto max-w-2xl text-center"><span className="rounded-full bg-white/10 px-4 py-2 text-sm">Hawally Service Point</span><h1 className="mt-6 text-3xl font-black sm:text-5xl">{ar?"جرّب إدارة نقطة خدمات كاملة خلال دقائق":"Run a complete service point in minutes"}</h1><p className="mt-4 leading-8">{ar?"نسخة عرض احترافية تعمل محليًا بلا تكاليف شهرية أو خدمات خارجية.":"A professional local-first demo with no paid infrastructure."}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><button disabled={busy} onClick={startDemo} className="rounded-3xl border p-7 text-start shadow-sm"><Sparkles className="text-amber-500"/><h2 className="mt-5 text-2xl">{ar?"جرّب بنموذج جاهز":"Try a ready-made demo"}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{ar?"محل ووردية وأرصدة وعمليات وربح وتنبيه جاهزون للعرض فورًا.":"Instant store, shift, balances, operations, profit, and alerts."}</p><b className="mt-6 block text-blue-700">{busy?(ar?"جارٍ التجهيز…":"Preparing…"):(ar?"ابدأ العرض الآن ←":"Start demo now →")}</b></button><button onClick={()=>setMode("empty")} className="rounded-3xl border p-7 text-start shadow-sm"><Rocket/><h2 className="mt-5 text-2xl">{ar?"ابدأ نشاطك من الصفر":"Start from scratch"}</h2><p className="mt-3 text-sm leading-7">{ar?"إعداد بسيط من 7 خطوات ينقلك مباشرة إلى أول وردية.":"A simple 7-step setup takes you straight to your first shift."}</p><b className="mt-6 block">{ar?"إعداد نشاط جديد ←":"Set up a business →"}</b></button></div><p className="mt-8 text-center text-xs">{ar?"كل متصفح يحتفظ ببياناته محليًا. المزامنة بين الأجهزة متاحة مستقبلًا في Cloud Edition.":"Each browser keeps separate local data. Multi-device sync is a future Cloud Edition feature."}</p></div></main>;
  const next=()=>setStep(x=>Math.min(7,x+1)),back=()=>setStep(x=>Math.max(1,x-1));
  return <main className="sp-onboarding-setup min-h-screen px-3 py-8"><div className="mx-auto max-w-3xl rounded-3xl p-5 sm:p-9"><div className="flex items-center justify-between"><div><small className="font-bold text-blue-700">Hawally SETUP</small><h1 className="mt-1 text-2xl">{ar?"جهّز نقطة الخدمات":"Set up your service point"}</h1></div><b className="rounded-full bg-blue-50 px-4 py-2 text-blue-800">{step} / 7</b></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100"><i className="block h-full bg-blue-600 transition-all" style={{width:`${step/7*100}%`}}/></div><div className="min-h-[330px] py-8">
    {step===1&&<Field title={ar?"ما اسم النشاط؟":"Business name"} hint={ar?"سيظهر في مساحة العمل والتقارير.":"Shown in the workspace and reports."}><input autoFocus value={business} onChange={e=>setBusiness(e.target.value)} placeholder={ar?"مثال: خدمات النور":"e.g. Al Noor Services"}/></Field>}
    {step===2&&<Field title={ar?"ما اسم أول محل؟":"First store name"} hint={ar?"يمكن إضافة محلات أخرى لاحقًا.":"You can add more later."}><input autoFocus value={storeName} onChange={e=>setStoreName(e.target.value)} placeholder={ar?"المحل الرئيسي":"Main store"}/></Field>}
    {step===3&&<Field title={ar?"اختر الخدمات المستخدمة":"Choose your providers"} hint={ar?"يمكن تعديلها لاحقًا من الإعدادات.":"You can change these later."}><div className="grid gap-3 sm:grid-cols-2">{posProviders.map(p=><label key={p.id} className="flex items-center gap-3 rounded-2xl border p-4"><input type="checkbox" checked={providers.includes(p.id)} onChange={()=>setProviders(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/><b>{ar?p.nameAr:p.nameEn}</b></label>)}</div></Field>}
    {step===4&&<Field title={ar?"الأرصدة الافتتاحية":"Opening balances"} hint={ar?"اكتب الموجود فعليًا الآن.":"Enter what is physically available now."}><div className="grid gap-3 sm:grid-cols-2"><label>{ar?"الخزنة":"Cash"}<input type="number" min="0" value={cash} onChange={e=>setCash(e.target.value)}/></label>{posProviders.filter(p=>providers.includes(p.id)).map(p=><label key={p.id}>{ar?p.nameAr:p.nameEn}<input type="number" min="0" value={balances[p.id]} onChange={e=>setBalances({...balances,[p.id]:e.target.value})}/></label>)}</div></Field>}
    {step===5&&<Field title={ar?"أضف أول كاشير":"Add your first cashier"} hint={ar?"PIN محلي على هذا الجهاز فقط. PIN المالك المبدئي: 5678":"Local PIN on this device only. Initial owner PIN: 5678"}><div className="grid gap-4 sm:grid-cols-2"><label>{ar?"اسم الكاشير":"Cashier name"}<input value={cashier} onChange={e=>setCashier(e.target.value)}/></label><label>PIN<input inputMode="numeric" maxLength={8} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label></div></Field>}
    {step===6&&<Field title={ar?"اختر باقة التجربة":"Choose a trial plan"} hint={ar?`${servicePointCommercialConfig.trialDays} يومًا مجانًا — بدون دفع أو بطاقة.`:`${servicePointCommercialConfig.trialDays} days free — no card or payment.`}><div className="grid gap-3 sm:grid-cols-3">{servicePointCommercialConfig.plans.map(p=><button onClick={()=>setPlan(p.id)} className={`rounded-2xl border p-4 text-start ${plan===p.id?"border-blue-600 bg-blue-50":""}`} key={p.id}><b>{ar?p.nameAr:p.nameEn}</b><span className="mt-2 block text-xl">{p.monthlyPrice} {ar?"ج.م":"EGP"}</span></button>)}</div></Field>}
    {step===7&&<Field title={ar?"جاهز لأول وردية":"Ready for your first shift"} hint={ar?"سنفتح الوردية بالأرصدة والكاشير اللذين أدخلتهما.":"We will open the shift with your balances and cashier."}><div className="rounded-3xl bg-blue-50 p-6"><Check className="text-emerald-600"/><h3 className="mt-3">{business||"—"} · {storeName||"—"}</h3><p className="mt-2 text-sm text-slate-600">{cashier||"—"} · {getServicePointPlan(plan).nameEn} · {providers.length} providers</p></div></Field>}
  </div><div className="flex justify-between gap-3"><button className="btn" onClick={step===1?()=>setMode("choice"):back}>{ar?"السابق":"Back"}</button>{step<7?<button disabled={(step===1&&!business.trim())||(step===2&&!storeName.trim())||(step===3&&!providers.length)||(step===5&&(!cashier.trim()||pin.length<4))} className="btn btn-primary" onClick={next}>{ar?"التالي":"Next"}</button>:<button disabled={busy} className="btn btn-primary" onClick={finish}><Play size={17}/>{busy?(ar?"جارٍ البدء…":"Starting…"):(ar?"ابدأ أول وردية":"Start first shift")}</button>}</div></div></main>;
}

function Field({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){return <section><h2 className="text-2xl">{title}</h2><p className="mt-2 mb-6 text-sm text-slate-500">{hint}</p>{children}</section>}

function DemoPanel({locale,panel,close,changed}:{locale:Locale;panel:string;close:()=>void;changed:()=>void}){
  const ar=locale==="ar",[users,setUsers]=useState(loadLocalUsers()),[audit]=useState(loadLocalAudit()),[name,setName]=useState(""),[role,setRole]=useState<LocalRole>("cashier"),[pin,setPin]=useState("1234"),[loginPin,setLoginPin]=useState(""),[selected,setSelected]=useState(users[0]?.id||""),[message,setMessage]=useState(""),[backup,setBackup]=useState<ServicePointBackup>(),file=useRef<HTMLInputElement>(null),current=currentLocalUser(),allowed=current?canLocalRole(current.role,"manage-users"):false;
  const add=async()=>{if(!allowed)return setMessage(ar?"هذه الصلاحية متاحة للمالك فقط.":"Owner permission required.");const user=await createLocalUser(name,role,pin);setUsers(loadLocalUsers());setName("");setMessage(`${user.name} ✓`);};
  const login=async()=>{const user=users.find(x=>x.id===selected);if(!user||!await verifyLocalPin(user,loginPin))return setMessage(ar?"PIN غير صحيح.":"Incorrect PIN.");setCurrentLocalUser(user.id);changed();close();};
  const download=()=>{const value=exportServicePointBackup(),blob=new Blob([JSON.stringify(value,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`finora-service-point-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);changed();};
  const readFile=async(fileValue?:File)=>{if(!fileValue)return;try{const value=parseServicePointBackup(await fileValue.text());setBackup(value);setMessage("");}catch{setMessage(ar?"ملف النسخة غير صالح.":"Invalid backup file.");}};
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/55 p-3 sm:p-8"><section className="mx-auto max-w-3xl rounded-3xl bg-white p-5 text-slate-950 shadow-2xl sm:p-8" dir={ar?"rtl":"ltr"}><div className="flex items-center justify-between"><h2>{panel==="users"?(ar?"المستخدمون المحليون":"Local users"):panel==="audit"?(ar?"سجل النشاط المحلي":"Local audit log"):panel==="backup"?(ar?"النسخ الاحتياطي والاستعادة":"Backup & restore"):panel==="login"?(ar?"تبديل المستخدم":"Switch user"):(ar?"الإعدادات":"Settings")}</h2><button onClick={close} className="rounded-xl border p-2"><X/></button></div>
    {panel==="login"&&<div className="mt-6 grid gap-4"><label>{ar?"المستخدم":"User"}<select value={selected} onChange={e=>setSelected(e.target.value)}>{users.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name} — {roleNames[x.role][ar?"ar":"en"]}</option>)}</select></label><label>PIN<input inputMode="numeric" value={loginPin} onChange={e=>setLoginPin(e.target.value)}/></label><button className="btn btn-primary" onClick={login}><KeyRound size={17}/>{ar?"دخول محلي":"Local sign in"}</button></div>}
    {panel==="users"&&<><div className="mt-6 grid gap-3">{users.map(x=><div className="flex items-center justify-between rounded-2xl border p-4" key={x.id}><span><b>{x.name}</b><small className="block text-slate-500">{roleNames[x.role][ar?"ar":"en"]}</small></span><ShieldCheck className={x.active?"text-emerald-600":"text-slate-300"}/></div>)}</div><div className="mt-6 grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-3"><input placeholder={ar?"الاسم":"Name"} value={name} onChange={e=>setName(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as LocalRole)}>{Object.entries(roleNames).map(([id,label])=><option key={id} value={id}>{label[ar?"ar":"en"]}</option>)}</select><input placeholder="PIN" value={pin} onChange={e=>setPin(e.target.value)}/><button disabled={!name.trim()||pin.length<4} className="btn btn-primary" onClick={add}><Plus/>{ar?"إضافة مستخدم":"Add user"}</button></div><p className="mt-4 text-xs text-amber-800">{ar?"الأدوار وPIN محلية للتجربة وليست بديلًا لتسجيل دخول آمن عبر الخادم.":"Local roles and PINs are a demo, not production authentication."}</p></>}
    {panel==="audit"&&<><p className="mt-3 text-sm text-slate-500">{ar?"سجل محلي قابل للتعديل للاستخدام التجريبي على جهاز واحد.":"A mutable local log for demo/single-device use."}</p><div className="mt-5 max-h-[60vh] overflow-auto"><table><thead><tr><th>{ar?"الوقت":"Time"}</th><th>{ar?"المستخدم":"User"}</th><th>{ar?"الإجراء":"Action"}</th><th>{ar?"التفاصيل":"Details"}</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.at).toLocaleString(ar?"ar-EG":"en")}</td><td>{x.userName}</td><td>{x.action}</td><td>{x.details}</td></tr>)}</tbody></table></div></>}
    {panel==="backup"&&<div className="mt-6 grid gap-4 sm:grid-cols-2"><button className="rounded-2xl border p-6 text-start" onClick={download}><Download className="text-blue-700"/><b className="mt-3 block">{ar?"تنزيل نسخة JSON":"Download JSON backup"}</b><small className="mt-2 block text-slate-500">{ar?"المحلات والعمليات والمستخدمون والإعدادات والسجل.":"Stores, operations, users, settings, and audit."}</small></button><button className="rounded-2xl border p-6 text-start" onClick={()=>file.current?.click()}><Upload className="text-emerald-700"/><b className="mt-3 block">{ar?"اختيار نسخة للاستعادة":"Choose backup to restore"}</b><input ref={file} hidden type="file" accept="application/json" onChange={e=>readFile(e.target.files?.[0])}/></button>{backup&&<div className="sm:col-span-2 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3>{ar?"معاينة قبل الاستعادة":"Restore preview"}</h3><p className="mt-2 text-sm">{backup.businessName||"—"} · {backup.stores.length} {ar?"محل":"stores"} · {Object.values(backup.storeData).reduce((n,x)=>n+x.operations.length,0)} {ar?"عملية":"operations"}</p><p className="text-sm">{new Date(backup.exportedAt).toLocaleString(ar?"ar-EG":"en")}</p><button className="btn btn-primary mt-4" onClick={()=>{if(confirm(ar?"سيتم استبدال بيانات Service Point المحلية الحالية. متابعة؟":"Replace current local Service Point data?")){restoreServicePointBackup(backup);changed();close();}}}><ArchiveRestore/>{ar?"تأكيد الاستعادة":"Confirm restore"}</button></div>}</div>}
    {panel==="settings"&&<SettingsPanel locale={locale} changed={changed}/>} {message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">{message}</p>}
  </section></div>;
}

function SettingsPanel({locale,changed}:{locale:Locale;changed:()=>void}){const ar=locale==="ar",settings=loadServicePointSettings(),sub=loadLocalSubscription(),plan=getServicePointPlan(sub.currentPlan);return <div className="mt-6 grid gap-4"><PwaInstallCard locale={locale} statusOnly/><div className="rounded-2xl bg-blue-50 p-5"><small>{ar?"الباقة الحالية":"Current plan"}</small><h3 className="mt-1">{ar?plan.nameAr:plan.nameEn} · {effectiveSubscriptionStatus(sub)}</h3><p className="mt-2 text-sm">{new Date(sub.trialStartedAt).toLocaleDateString(ar?"ar-EG":"en")} → {new Date(sub.trialEndsAt).toLocaleDateString(ar?"ar-EG":"en")}</p></div><div className="rounded-2xl border p-5"><Cloud className="text-blue-700"/><b className="mt-3 block">Cloud Edition · {ar?"يتطلب تفعيلًا سحابيًا":"Requires Cloud Activation"}</b><p className="mt-2 text-sm leading-7 text-slate-600">{ar?"نسخة العرض تحفظ البيانات على الجهاز المستخدم. المزامنة وتسجيل الدخول الآمن والنسخ التلقائي ولوحة المالك عن بُعد تتطلب التفعيل السحابي.":"This demo stores data on this device. Sync, secure login, automatic backup, and remote owner access require Cloud activation."}</p></div><Link className="btn btn-primary" href={`/${locale}/service-point/demo`}><Play/>{ar?"إعادة الجولة السريعة":"Replay quick tour"}</Link><button className="btn" onClick={()=>{seedSalesDemo();changed();location.reload();}}><Sparkles/>{ar?"تفعيل Sales Demo Mode":"Enable Sales Demo Mode"}</button>{settings.demoStoreIds?.length?<button className="btn btn-danger" onClick={()=>{if(confirm(ar?"مسح بيانات العرض المعزولة فقط؟":"Remove isolated demo data only?")){resetSalesDemo();changed();location.reload();}}}>{ar?"مسح بيانات Demo المحلية":"Clear local demo data"}</button>:null}</div>}

function ProductTour({locale,step,next,skip}:{locale:Locale;step:number;next:()=>void;skip:()=>void}){const ar=locale==="ar",items=ar?[["الخزنة","تابع النقدية المتوقعة لحظة بلحظة."],["أرصدة الخدمات","كل شركة لها رصيد مستقل وواضح."],["الوردية","ابدأ بالأرصدة الحقيقية وأغلق بالمطابقة."],["عملية جديدة","شاهد تأثير العملية وربحها قبل الحفظ."],["لوحة المالك","راجع الربح والتنبيهات من واجهة هاتف سريعة."]]:[["Cash","Track expected cash in real time."],["Provider balances","Every provider has a separate balance."],["Shifts","Open with real balances and close by reconciliation."],["New operation","Preview impact and profit before posting."],["Owner dashboard","Review profit and alerts in a mobile view."]];return <div className="fixed inset-0 z-[70] grid place-items-end bg-slate-950/40 p-4 sm:place-items-center"><div className="sp-product-tour w-full max-w-md rounded-3xl p-6 shadow-2xl" dir={ar?"rtl":"ltr"}><span className="text-sm font-bold text-blue-700">{step} / 5</span><h2 className="mt-3">{items[step-1][0]}</h2><p className="mt-2 text-slate-600">{items[step-1][1]}</p><div className="mt-6 flex justify-between"><button onClick={skip} className="text-sm text-slate-500">{ar?"تخطي":"Skip"}</button><button onClick={next} className="btn btn-primary">{step===5?(ar?"ابدأ":"Start"):(ar?"التالي":"Next")}{ar?<ChevronLeft/>:<ChevronRight/>}</button></div></div></div>}
