"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Banknote, CalendarDays, CheckCircle2, Landmark, MessageCircle, TrendingDown, TrendingUp } from "lucide-react";
import { buildCashflowPlan } from "@/lib/parties/cashflow";
import { itemOutstanding } from "@/lib/parties/aging";
import { whatsappChatUrl } from "@/lib/parties/profile";
import { loadAccounts, loadEntries, saveEntry } from "@/lib/storage/accounting";
import { treasuryAccounts, treasuryBalances } from "@/lib/accounting/treasury";
import { loadOpenItems, loadParties, saveOpenItems } from "@/lib/storage/parties";
import { generateJournalEntry } from "@/rules";
import type { ChartAccount, GeneratedJournalEntry, Locale, OpenItem, Party } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
const plusDays = (date: string, days: number) => { const value = new Date(date); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); };
const money = (value: number, locale: Locale) => value.toLocaleString(locale === "ar" ? "ar-EG" : "en-US", { maximumFractionDigits: 2 });

export function CashflowCenter({ locale }: { locale: Locale }) {
  const ar = locale === "ar", asOf = today(), [parties, setParties] = useState<Party[]>([]), [items, setItems] = useState<OpenItem[]>([]), [entries, setEntries] = useState<GeneratedJournalEntry[]>([]), [accounts, setAccounts] = useState<ChartAccount[]>([]), [paymentAccountCode, setPaymentAccountCode] = useState("1110"), [horizon, setHorizon] = useState<"today" | "7" | "30" | "all">("today"), [kind, setKind] = useState<"all" | OpenItem["kind"]>("all"), [notice, setNotice] = useState("");
  useEffect(() => { const loadedAccounts = loadAccounts(); setParties(loadParties()); setItems(loadOpenItems()); setEntries(loadEntries()); setAccounts(treasuryAccounts(loadedAccounts)); }, []);
  const balanceRows = treasuryBalances(entries, accounts), liquidity = balanceRows.reduce((sum, current) => sum + current.balance, 0), plan = buildCashflowPlan(parties, items, asOf, liquidity), end = horizon === "7" ? plusDays(asOf, 7) : horizon === "30" ? plusDays(asOf, 30) : "9999-12-31";
  const visible = plan.schedule.filter((current) => (kind === "all" || current.item.kind === kind) && (horizon === "today" ? current.item.dueDate <= asOf : horizon === "all" || current.item.dueDate <= end));
  const completedToday = entries.filter((entry) => ["customer-collection", "supplier-payment"].includes(entry.transactionType) && entry.audit?.some((event) => event.at.slice(0, 10) === asOf));
  const record = (item: OpenItem, party: Party) => { const outstanding = itemOutstanding(item), input = prompt(ar ? `أدخل قيمة ${item.kind === "receivable" ? "التحصيل" : "السداد"}، المتبقي ${outstanding}` : `Enter amount, outstanding ${outstanding}`, String(outstanding)); if (!input) return; const value = Math.min(outstanding, Math.max(0, Number(input))), paymentAccount = accounts.find((account) => account.code === paymentAccountCode); if (!value) return; if (!paymentAccount) return setNotice(ar ? "اختر حساب الصندوق أو البنك أولًا." : "Select a cash or bank account first."); const entry = saveEntry({ ...generateJournalEntry({ type: item.kind === "receivable" ? "customer-collection" : "supplier-payment", amount: value, date: asOf, currency: item.currency, paymentMethod: paymentAccount.code === "1100" || paymentAccount.id === "cash" ? "cash" : "bank", paymentAccountCode: paymentAccount.code, paymentAccountNameAr: paymentAccount.nameAr, paymentAccountNameEn: paymentAccount.nameEn, customer: item.kind === "receivable" ? party.nameAr : undefined, supplier: item.kind === "payable" ? party.nameAr : undefined, notes: `${item.invoiceNumber} — ${party.nameAr}` }), workflowStatus: "draft" }), paid = item.paid + value, nextItems = items.map((current) => current.id === item.id ? { ...current, paid, status: paid >= current.amount ? "paid" as const : "partial" as const, linkedEntryId: entry.id } : current); saveOpenItems(nextItems); setItems(nextItems); setEntries([entry, ...entries]); setNotice(ar ? "تم إنشاء مسودة القيد على الحساب المحدد. الرصيد الرسمي سيتغير بعد الاعتماد والترحيل." : "Draft entry created for the selected account. The official balance changes after approval and posting."); };
  const whatsapp = (item: OpenItem, party: Party) => { const outstanding = itemOutstanding(item), text = item.kind === "receivable" ? (ar ? `مرحبًا ${party.nameAr}، نذكّركم باستحقاق الفاتورة ${item.invoiceNumber} بقيمة ${money(outstanding, locale)} ${item.currency}. نرجو الإفادة بموعد السداد.` : `Hello ${party.nameEn}, invoice ${item.invoiceNumber} has an outstanding balance of ${money(outstanding, locale)} ${item.currency}. Please confirm the payment date.`) : (ar ? `مرحبًا ${party.nameAr}، نرجو تأكيد بيانات استحقاق الفاتورة ${item.invoiceNumber} بقيمة ${money(outstanding, locale)} ${item.currency}.` : `Hello ${party.nameEn}, please confirm the payment details for invoice ${item.invoiceNumber}, ${money(outstanding, locale)} ${item.currency}.`), url = whatsappChatUrl(party.phone || "", text); if (!url) return setNotice(ar ? "لا يوجد رقم واتساب محفوظ لهذا الطرف؛ أضفه من ملف 360°." : "No WhatsApp number is saved; add it in the 360° profile."); window.open(url, "_blank", "noopener,noreferrer"); };
  return <div className="grid">
    <section className="grid four"><Metric title={ar ? "السيولة المتاحة الآن" : "Available liquidity"} value={`${money(liquidity, locale)} EGP`} /><Metric title={ar ? "تحصيلات متأخرة" : "Overdue receipts"} value={`${money(plan.overdueReceipts, locale)} EGP`} danger={plan.overdueReceipts > 0} /><Metric title={ar ? "مدفوعات متأخرة" : "Overdue payments"} value={`${money(plan.overduePayments, locale)} EGP`} danger={plan.overduePayments > 0} /><Metric title={ar ? "المتبقي المتوقع بعد 30 يومًا" : "Projected after 30 days"} value={`${money(plan.projected30, locale)} EGP`} danger={plan.projected30 < 0} /></section>
    <section className="card"><h2><Landmark size={20}/>{ar ? "الأرصدة الفعلية للصندوق والبنوك" : "Official cash and bank balances"}</h2><p className="muted">{ar ? "هذه الأرصدة محسوبة تلقائيًا من القيود المتوازنة والمرحلة فقط." : "These balances are calculated automatically from balanced, posted entries only."}</p><div className="grid three">{balanceRows.map((current) => <article className="card" key={current.account.id}>{current.kind === "cash" ? <Banknote size={20}/> : <Landmark size={20}/>}<h3>{ar ? current.account.nameAr : current.account.nameEn}</h3><p className="impact">{money(current.balance, locale)} EGP</p><small className="muted">{current.account.code}</small></article>)}</div><div className="section no-print"><label>{ar ? "الحساب المستخدم في التحصيل أو السداد الجديد" : "Account for the new collection or payment"}<select value={paymentAccountCode} onChange={(event) => setPaymentAccountCode(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.code}>{account.code} — {ar ? account.nameAr : account.nameEn}</option>)}</select></label></div>{!entries.some((entry) => !entry.workflowStatus || entry.workflowStatus === "posted") && <p className="warning">{ar ? "لا توجد قيود مرحلة بعد. سجّل رأس المال أو الرصيد الافتتاحي ثم اعتمد القيد ليظهر الرصيد هنا." : "No posted entries yet. Record opening capital or balances and post the entry to populate treasury balances."}</p>}</section>
    <section className="grid two"><article className="card"><h2><TrendingUp size={20}/>{ar ? "خطة 7 أيام" : "7-day plan"}</h2><FlowRow label={ar ? "تحصيلات متوقعة" : "Expected receipts"} value={plan.receipts7} locale={locale}/><FlowRow label={ar ? "مدفوعات مطلوبة" : "Required payments"} value={-plan.payments7} locale={locale}/><FlowRow label={ar ? "الرصيد المتوقع" : "Projected balance"} value={plan.projected7} locale={locale} strong/></article><article className="card"><h2><CalendarDays size={20}/>{ar ? "خطة 30 يومًا" : "30-day plan"}</h2><FlowRow label={ar ? "تحصيلات متوقعة" : "Expected receipts"} value={plan.receipts30} locale={locale}/><FlowRow label={ar ? "مدفوعات مطلوبة" : "Required payments"} value={-plan.payments30} locale={locale}/><FlowRow label={ar ? "الرصيد المتوقع" : "Projected balance"} value={plan.projected30} locale={locale} strong/></article></section>
    {(plan.shortfall7 > 0 || plan.shortfall30 > 0) && <section className="card warning error"><h2><AlertTriangle size={20}/>{ar ? "عجز سيولة متوقع" : "Expected liquidity shortfall"}</h2><p>{ar ? `العجز المتوقع خلال 7 أيام: ${money(plan.shortfall7, locale)} جنيه، وخلال 30 يومًا: ${money(plan.shortfall30, locale)} جنيه. ابدأ بتحصيل الفواتير المقترحة قبل اعتماد المدفوعات الأقل أولوية.` : `Expected shortfall: ${money(plan.shortfall7, locale)} in 7 days and ${money(plan.shortfall30, locale)} in 30 days. Start with the suggested collections.`}</p></section>}
    <section className="card"><h2>{ar ? "مقترحات التحصيل الذكية" : "Smart collection suggestions"}</h2><div className="grid three">{plan.collectionSuggestions.map((current) => <article className="card" key={current.item.id}><span className={current.priority === "critical" ? "badge error" : "badge"}>{current.daysLate ? `${current.daysLate} ${ar ? "يوم تأخير" : "days late"}` : (ar ? "قادم" : "Upcoming")}</span><h3>{ar ? current.party.nameAr : current.party.nameEn}</h3><p>{current.item.invoiceNumber} · <b>{money(current.outstanding, locale)} {current.item.currency}</b></p><div className="actions no-print"><button className="btn btn-primary" onClick={() => record(current.item, current.party)}>{ar ? "تسجيل تحصيل" : "Collect"}</button><button className="btn" onClick={() => whatsapp(current.item, current.party)}><MessageCircle size={16}/>{ar ? "واتساب" : "WhatsApp"}</button><Link className="btn" href={`/${locale}/parties/${current.party.id}`}>{ar ? "ملف 360°" : "360° profile"}</Link></div></article>)}{!plan.collectionSuggestions.length && <p className="muted">{ar ? "لا توجد تحصيلات مفتوحة." : "No open collections."}</p>}</div></section>
    <section className="card"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2>{ar ? "جدول التحصيلات والمدفوعات" : "Collections and payments schedule"}</h2><p className="muted">{ar ? "المتأخر يظهر ضمن مهام اليوم تلقائيًا." : "Overdue items are automatically included in today's work."}</p></div><div className="actions no-print"><select aria-label={ar ? "الفترة" : "Horizon"} value={horizon} onChange={(event) => setHorizon(event.target.value as typeof horizon)}><option value="today">{ar ? "اليوم والمتأخر" : "Today & overdue"}</option><option value="7">7 {ar ? "أيام" : "days"}</option><option value="30">30 {ar ? "يومًا" : "days"}</option><option value="all">{ar ? "الكل" : "All"}</option></select><select aria-label={ar ? "نوع الحركة" : "Cashflow type"} value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="all">{ar ? "تحصيلات ومدفوعات" : "All"}</option><option value="receivable">{ar ? "تحصيلات" : "Receipts"}</option><option value="payable">{ar ? "مدفوعات" : "Payments"}</option></select></div></div><div className="table-wrap"><table><thead><tr><th>{ar ? "الأولوية" : "Priority"}</th><th>{ar ? "الطرف" : "Party"}</th><th>{ar ? "الفاتورة" : "Invoice"}</th><th>{ar ? "الاستحقاق" : "Due"}</th><th>{ar ? "النوع" : "Type"}</th><th>{ar ? "المتبقي" : "Outstanding"}</th><th className="no-print"></th></tr></thead><tbody>{visible.map((current) => <tr key={current.item.id}><td><span className={current.priority === "critical" ? "badge error" : "badge"}>{current.priority === "critical" ? (ar ? "حرج" : "Critical") : current.priority === "high" ? (ar ? "متأخر" : "Overdue") : (ar ? "عادي" : "Normal")}</span></td><td><b>{ar ? current.party.nameAr : current.party.nameEn}</b></td><td>{current.item.invoiceNumber}</td><td>{current.item.dueDate}</td><td>{current.item.kind === "receivable" ? (ar ? "تحصيل" : "Receipt") : (ar ? "سداد" : "Payment")}</td><td><b>{money(current.outstanding, locale)} {current.item.currency}</b></td><td className="no-print"><div className="actions"><button className="btn btn-primary" onClick={() => record(current.item, current.party)}>{current.item.kind === "receivable" ? (ar ? "تحصيل" : "Collect") : (ar ? "سداد" : "Pay")}</button><button className="btn" onClick={() => whatsapp(current.item, current.party)}><MessageCircle size={15}/></button></div></td></tr>)}{!visible.length && <tr><td colSpan={7}>{ar ? "لا توجد مهام مطابقة لهذه الفترة." : "No matching tasks for this horizon."}</td></tr>}</tbody></table></div></section>
    <section className="card"><h2><CheckCircle2 size={20}/>{ar ? "ما تم تسجيله اليوم" : "Recorded today"}</h2><div className="grid three">{completedToday.map((entry) => <article className="card" key={entry.id}><span className="badge">{entry.transactionType === "customer-collection" ? (ar ? "تحصيل" : "Receipt") : (ar ? "سداد" : "Payment")}</span><h3>{ar ? entry.titleAr : entry.titleEn}</h3><p>{money(entry.totalDebit, locale)} {entry.currency}</p><Link className="btn" href={`/${locale}/operations/${entry.id}`}>{ar ? "فتح بطاقة العملية" : "Open operation dossier"}</Link></article>)}{!completedToday.length && <p className="muted">{ar ? "لم يتم تسجيل تحصيل أو سداد اليوم بعد." : "No collection or payment has been recorded today."}</p>}</div></section>
    {notice && <p className="warning">{notice}</p>}
  </div>;
}

function Metric({ title, value, danger = false }: { title: string; value: string; danger?: boolean }) { return <article className="card"><span className="muted">{title}</span><div className={danger ? "impact error" : "impact"}>{value}</div></article>; }
function FlowRow({ label, value, locale, strong = false }: { label: string; value: number; locale: Locale; strong?: boolean }) { return <p className="flex justify-between gap-4"><span>{value >= 0 ? <TrendingUp size={16}/> : <TrendingDown size={16}/>} {label}</span><b className={value < 0 ? "error" : ""} style={{ padding: strong ? 6 : 0 }}>{money(value, locale)} EGP</b></p>; }
