import type { MerchantAccountingData, MerchantCustomer, MerchantInventoryItem, MerchantLocalSubscription, MerchantPackage, MerchantSubscriptionCollection, MerchantSummary, MerchantSupplier, MerchantTask, MerchantTransaction, SmallMerchant } from "@/types";

const round=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
const effective=(transaction:MerchantTransaction)=>transaction.status==="posted";
const signed=(transaction:MerchantTransaction)=>transaction.status==="posted"?(transaction.originalTransactionId?-1:1):0;

export function emptyMerchantData(storeId:string):MerchantAccountingData{return{schemaVersion:1,storeId,merchants:[],transactions:[],customers:[],suppliers:[],inventory:[],categories:defaultCategories(),packages:defaultPackages(),subscriptions:[],alerts:[],tasks:[],updatedAt:new Date().toISOString()};}
export function defaultCategories(){return["إيجار","كهرباء","مياه","إنترنت","أجور","نقل","صيانة","تعبئة وتغليف","دعاية","عمولات","مصروفات بنكية","مصروفات حكومية","مصروفات أخرى"].map((name,index)=>({id:`expense-${index+1}`,name,active:true}));}
export function defaultPackages():MerchantPackage[]{const now=new Date().toISOString();return[
 {id:"basic",name:"الباقة الأساسية",description:"دخل ومصروف وملخص نقدية وتقرير أسبوعي",price:250,active:true,reportsPerMonth:4,branches:1,localUsers:1,features:["income-expense","cash-summary","weekly-report"],isDemo:true,createdAt:now},
 {id:"advanced",name:"الباقة المتقدمة",description:"عملاء وموردون وتقارير أسبوعية وشهرية وربح تقديري",price:450,active:true,reportsPerMonth:8,branches:2,localUsers:2,features:["customers","suppliers","profit","messages","monthly-report"],isDemo:true,createdAt:now},
 {id:"business",name:"باقة النشاط",description:"مخزون مبسط وتقارير شاملة ومقارنة الفترات",price:700,active:true,reportsPerMonth:20,branches:5,localUsers:5,features:["inventory","customers","suppliers","full-reports","period-comparison"],isDemo:true,createdAt:now},
];}

function transactionEffects(transaction:MerchantTransaction){const amount=transaction.amount*signed(transaction),cost=(transaction.costAmount||0)*signed(transaction);let cash=0,bank=0,wallet=0,sales=0,purchases=0,expenses=0,collections=0,supplierPayments=0,receivables=0,payables=0,revenue=0,costOfGoods=0;
 const pay=(direction:number)=>{if(transaction.paymentMethod==="cash")cash+=amount*direction;if(transaction.paymentMethod==="bank")bank+=amount*direction;if(transaction.paymentMethod==="wallet")wallet+=amount*direction;};
 switch(transaction.transactionType){
  case"cash-sale":sales+=amount;revenue+=amount;costOfGoods+=cost;pay(1);break;
  case"credit-sale":sales+=amount;revenue+=amount;costOfGoods+=cost;receivables+=amount;break;
  case"cash-purchase":purchases+=amount;pay(-1);break;
  case"credit-purchase":purchases+=amount;payables+=amount;break;
  case"expense":case"other-expense":expenses+=amount;pay(-1);break;
  case"customer-collection":collections+=amount;receivables-=amount;pay(1);break;
  case"supplier-payment":supplierPayments+=amount;payables-=amount;pay(-1);break;
  case"capital":pay(1);break;case"drawings":pay(-1);break;
  case"other-income":revenue+=amount;pay(1);break;
  case"cash-to-bank":cash-=amount;bank+=amount;break;case"bank-to-cash":bank-=amount;cash+=amount;break;
  case"cash-to-wallet":cash-=amount;wallet+=amount;break;case"wallet-to-cash":wallet-=amount;cash+=amount;break;
  case"opening-balance":pay(1);break;
  case"manual-adjustment":pay(1);break;
  case"sales-return":sales-=amount;revenue-=amount;receivables-=transaction.paymentMethod==="credit"?amount:0;if(transaction.paymentMethod!=="credit")pay(-1);break;
  case"purchase-return":purchases-=amount;payables-=transaction.paymentMethod==="credit"?amount:0;if(transaction.paymentMethod!=="credit")pay(1);break;
 }
 return{cash,bank,wallet,sales,purchases,expenses,collections,supplierPayments,receivables,payables,revenue,costOfGoods};}

export function calculateMerchantSummary(merchant:SmallMerchant,transactions:MerchantTransaction[],customers:MerchantCustomer[]=[],suppliers:MerchantSupplier[]=[]):MerchantSummary{
 const relevant=transactions.filter((item)=>item.merchantId===merchant.id&&effective(item));const total={cash:merchant.openingCash,bank:merchant.openingBank,wallet:merchant.openingWallet,sales:0,purchases:0,expenses:0,collections:0,supplierPayments:0,receivables:customers.filter(x=>x.merchantId===merchant.id&&x.active).reduce((s,x)=>s+x.openingBalance,0),payables:suppliers.filter(x=>x.merchantId===merchant.id&&x.active).reduce((s,x)=>s+x.openingBalance,0),revenue:0,costOfGoods:0};
 for(const transaction of relevant){const effect=transactionEffects(transaction);for(const key of Object.keys(effect) as Array<keyof typeof effect>)total[key]=round(total[key]+effect[key]);}
 const estimatedProfit=round(total.revenue-total.costOfGoods-total.expenses),missingCostData=relevant.some(item=>["cash-sale","credit-sale"].includes(item.transactionType)&&!(item.costAmount&&item.costAmount>0));
 return{...total,estimatedProfit,margin:total.revenue?round(estimatedProfit/total.revenue*100):0,transactionCount:relevant.length,missingCostData};
}

export function customerBalance(customer:MerchantCustomer,transactions:MerchantTransaction[]){return round(customer.openingBalance+transactions.filter(x=>x.customerId===customer.id&&effective(x)).reduce((sum,item)=>sum+(item.transactionType==="credit-sale"?item.amount:item.transactionType==="customer-collection"||item.transactionType==="sales-return"?-item.amount:0),0));}
export function supplierBalance(supplier:MerchantSupplier,transactions:MerchantTransaction[]){return round(supplier.openingBalance+transactions.filter(x=>x.supplierId===supplier.id&&effective(x)).reduce((sum,item)=>sum+(item.transactionType==="credit-purchase"?item.amount:item.transactionType==="supplier-payment"||item.transactionType==="purchase-return"?-item.amount:0),0));}
export function inventoryQuantity(item:MerchantInventoryItem,transactions:MerchantTransaction[]){return round(item.openingQuantity+transactions.filter(x=>x.inventoryItemId===item.id&&effective(x)).reduce((sum,row)=>sum+(["cash-purchase","credit-purchase","sales-return"].includes(row.transactionType)?row.quantity||0:["cash-sale","credit-sale","purchase-return"].includes(row.transactionType)?-(row.quantity||0):0),0));}

export function createMerchant(input:Omit<SmallMerchant,"id"|"code"|"createdAt"|"updatedAt"|"collectedAmount">,sequence:number):SmallMerchant{const now=new Date().toISOString();return{...input,id:crypto.randomUUID(),code:`M-${String(sequence).padStart(4,"0")}`,collectedAmount:0,createdAt:now,updatedAt:now};}
export function createSubscription(merchant:SmallMerchant,packageItem:MerchantPackage):MerchantLocalSubscription{return{id:crypto.randomUUID(),merchantId:merchant.id,packageId:packageItem.id,startDate:merchant.startDate,frequency:merchant.subscriptionFrequency,amount:merchant.subscriptionAmount||packageItem.price,due:merchant.subscriptionAmount||packageItem.price,collected:0,nextDueDate:merchant.nextDueDate||merchant.startDate,status:"local-demo",assignedEmployee:merchant.assignedCashier,collections:[]};}
export function collectSubscription(subscription:MerchantLocalSubscription,input:Omit<MerchantSubscriptionCollection,"id"|"subscriptionId"|"merchantId"|"receiptNumber">):MerchantLocalSubscription{const amount=Math.max(0,Math.min(input.amount,Math.max(0,subscription.due-subscription.collected))),collection={...input,id:crypto.randomUUID(),subscriptionId:subscription.id,merchantId:subscription.merchantId,amount,receiptNumber:`SUB-${Date.now().toString().slice(-8)}`};const collected=round(subscription.collected+amount);return{...subscription,collected,status:collected>=subscription.due?"active":collected>0?"partial":"due",collections:[collection,...subscription.collections]};}
export function reverseMerchantTransaction(transaction:MerchantTransaction,reason:string):MerchantTransaction{const now=new Date().toISOString();return{...transaction,id:crypto.randomUUID(),amount:transaction.amount,createdAt:now,updatedAt:now,status:"posted",description:`عكس: ${transaction.description}`,originalTransactionId:transaction.id,reversalReason:reason,transactionType:transaction.transactionType};}

export function merchantTasks(data:MerchantAccountingData,today=new Date().toISOString().slice(0,10)):MerchantTask[]{const tasks:MerchantTask[]=[];for(const merchant of data.merchants.filter(x=>x.status==="active")){const relevant=data.transactions.filter(x=>x.merchantId===merchant.id&&x.status==="posted");if(!relevant.some(x=>x.date===today))tasks.push({id:`daily-${merchant.id}-${today}`,merchantId:merchant.id,title:"بيانات اليوم لم تُسجل",dueDate:today,status:"open",isDemo:merchant.isDemo});const subscription=data.subscriptions.find(x=>x.merchantId===merchant.id&&!(["cancelled","paused"].includes(x.status)));if(subscription&&subscription.nextDueDate<=today&&subscription.collected<subscription.due)tasks.push({id:`sub-${subscription.id}`,merchantId:merchant.id,title:"الاشتراك مستحق أو متأخر",dueDate:subscription.nextDueDate,status:"open",isDemo:merchant.isDemo});const summary=calculateMerchantSummary(merchant,data.transactions,data.customers,data.suppliers);if(summary.missingCostData)tasks.push({id:`cost-${merchant.id}`,merchantId:merchant.id,title:"بيانات التكلفة غير مكتملة",dueDate:today,status:"open",isDemo:merchant.isDemo});}return tasks;}

export function validateMerchantBackup(value:unknown):value is MerchantAccountingData{if(!value||typeof value!=="object")return false;const data=value as Partial<MerchantAccountingData>;return data.schemaVersion===1&&typeof data.storeId==="string"&&Array.isArray(data.merchants)&&Array.isArray(data.transactions)&&Array.isArray(data.packages)&&Array.isArray(data.subscriptions);}

export function createMerchantDemoData(storeId:string):MerchantAccountingData{const data=emptyMerchantData(storeId),now=new Date().toISOString(),today=now.slice(0,10),activities=["بقالة","كافيه","ملابس","موبايلات","صيدلية","ورشة","توصيل","متجر إلكتروني"];data.merchants=activities.map((activity,index)=>({id:`demo-merchant-${index+1}`,code:`M-${String(index+1).padStart(4,"0")}`,name:["أحمد سالم","منى علي","حسام حسن","نور محمد","خالد عمر","سارة محمود","عمر نبيل","هند عادل"][index],businessName:`${activity} ${index+1}`,activityType:activity,phone:`0100000000${index}`,address:"القاهرة",branchCount:index<2?2:1,startDate:today,status:index===7?"paused":"active",packageId:data.packages[index%3].id,subscriptionAmount:data.packages[index%3].price,subscriptionFrequency:"monthly",nextDueDate:today,collectedAmount:index%3===0?data.packages[index%3].price:0,assignedCashier:index%2?"محمود":"كريم",inventoryEnabled:["بقالة","ملابس","موبايلات","صيدلية"].includes(activity),employeesEnabled:true,creditSalesEnabled:true,customersEnabled:true,suppliersEnabled:true,dailyReport:index%2===0,weeklyReport:true,monthlyReport:true,openingCash:3000+index*500,openingBank:1000,openingWallet:500,isDemo:true,createdAt:now,updatedAt:now}));data.transactions=data.merchants.flatMap((merchant,index)=>[
 {id:`demo-sale-${index}`,merchantId:merchant.id,date:today,transactionType:"cash-sale" as const,description:"مبيعات نقدية",amount:1200+index*175,costAmount:700+index*90,paymentMethod:"cash" as const,createdBy:merchant.assignedCashier||"كريم",createdAt:now,updatedAt:now,status:"posted" as const,isDemo:true},
 {id:`demo-expense-${index}`,merchantId:merchant.id,date:today,transactionType:"expense" as const,description:"مصروف تشغيل",amount:150+index*15,paymentMethod:"cash" as const,categoryId:"expense-7",reference:`EXP-${index+1}`,createdBy:merchant.assignedCashier||"كريم",createdAt:now,updatedAt:now,status:"posted" as const,isDemo:true},
 {id:`demo-credit-${index}`,merchantId:merchant.id,date:today,transactionType:"credit-sale" as const,description:"بيع آجل",amount:300+index*40,costAmount:index===5?undefined:180+index*20,paymentMethod:"credit" as const,customerId:`demo-customer-${index}`,createdBy:merchant.assignedCashier||"كريم",createdAt:now,updatedAt:now,status:"posted" as const,isDemo:true},
 ]);data.customers=data.merchants.map((merchant,index)=>({id:`demo-customer-${index}`,merchantId:merchant.id,name:`عميل ${index+1}`,phone:`0110000000${index}`,openingBalance:index*100,expectedCollectionDate:today,active:true,isDemo:true,createdAt:now}));data.suppliers=data.merchants.map((merchant,index)=>({id:`demo-supplier-${index}`,merchantId:merchant.id,name:`مورد ${index+1}`,openingBalance:index*75,expectedPaymentDate:today,active:true,isDemo:true,createdAt:now}));data.inventory=data.merchants.filter(x=>x.inventoryEnabled).map((merchant,index)=>({id:`demo-item-${index}`,merchantId:merchant.id,code:`IT-${index+1}`,name:`صنف تجريبي ${index+1}`,category:"عام",unit:"قطعة",openingQuantity:20+index*5,unitCost:50,sellingPrice:75,reorderLevel:10,active:true,isDemo:true,createdAt:now}));data.subscriptions=data.merchants.map(merchant=>{const pack=data.packages.find(x=>x.id===merchant.packageId)!;return{...createSubscription(merchant,pack),id:`demo-sub-${merchant.id}`,status:merchant.collectedAmount?"active":"overdue",collected:merchant.collectedAmount,isDemo:true};});data.alerts=[{id:"demo-alert-1",type:"missing-cost",severity:"high",description:"بيانات تكلفة مبيعات أحد التجار غير مكتملة",reason:"تعذر تأكيد الربح التقديري",detectedAt:now,status:"new",isDemo:true}];data.tasks=merchantTasks(data,today);return data;}
