"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, BadgeCheck, Banknote, Bell, BookOpenCheck, BriefcaseBusiness, Building2, CalendarDays, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, FileCheck2, FileSearch, Gauge, HeartPulse, ListChecks, Medal, ReceiptText, RotateCcw, ShieldCheck, Sparkles, Target, Trophy, UserRound } from "lucide-react";
import { ArenaNav } from "@/components/arena/arena-nav";
import { arenaTasks, companyChallenges, demoTalentCompanies } from "@/data/arena-tasks";
import { careerRankLabel, demoLeaderboard, seasonOne, workShifts } from "@/data/arena";
import { createTrainingAccountSnapshot, validateArenaJournal } from "@/lib/arena/account-adapter";
import { applyAttempt, createArenaProfile, loadArenaProfile, saveArenaProfile } from "@/lib/arena/profile";
import { calculateHiringReadiness, financialImpactFor, isExactTaskAnswer, scoreArenaTask } from "@/lib/arena/task-engine";
import { sortLeaderboard } from "@/lib/arena/engine";
import type { ArenaAttempt, ArenaProfile, ArenaTaskLine, Locale } from "@/types";

const workflow = [
  ["document", "راجع المستند", "Review document"], ["analysis", "حلل العملية", "Analyze"], ["accounts", "اختر الحسابات", "Select accounts"],
  ["journal", "ابنِ القيد", "Build journal"], ["impact", "راجع التأثير", "Review impact"], ["approval", "اعتمد المهمة", "Approve"],
] as const;

export function ArenaWorkspace({ locale, mode = "dashboard" }: { locale: Locale; mode?: "dashboard" | "mission" }) {
  const [profile, setProfile] = useState<ArenaProfile>(createArenaProfile());
  useEffect(() => setProfile(loadArenaProfile()), []);
  const commit = (next: ArenaProfile) => { setProfile(next); saveArenaProfile(next); };
  return <main className="arena-pro"><ArenaStatusBar locale={locale} profile={profile}/><ArenaNav locale={locale}/>{mode === "dashboard" ? <ArenaDashboard locale={locale} profile={profile}/> : <MissionWorkspace locale={locale} profile={profile} commit={commit}/>}<p className="arena-sandbox"><ShieldCheck size={15}/>{locale === "ar" ? "FINORA Training Sandbox — يستخدم قواعد ودليل حسابات FINORA دون الكتابة في بيانات الشركة الحقيقية." : "FINORA Training Sandbox—uses FINORA rules and chart of accounts without writing to real company data."}</p></main>;
}

function ArenaStatusBar({ locale, profile }: { locale: Locale; profile: ArenaProfile }) {
  const ar = locale === "ar", rows = sortLeaderboard([...demoLeaderboard, { id: "local", player: profile.displayName, careerRank: profile.careerRank, professionalScore: profile.professionalScore, accuracy: profile.accuracy, topSkill: "journal-entries", uniqueCases: profile.uniqueCases }]), position = rows.findIndex((row) => row.id === "local") + 1;
  return <header className="arena-status"><Link className="arena-status-brand" href={`/${locale}/arena`}><span>F</span><b>FINORA<small>ARENA</small></b></Link><div className="arena-status-chips"><Status icon={Gauge} label="Score" value={profile.professionalScore}/><Status icon={BriefcaseBusiness} label={ar ? "الرتبة" : "Rank"} value={careerRankLabel(profile.careerRank, ar)}/><Status icon={Target} label={ar ? "الدقة" : "Accuracy"} value={`${profile.accuracy}%`}/><Status icon={CalendarDays} label={ar ? "السلسلة" : "Streak"} value={`${profile.currentStreak}`}/><Status icon={Sparkles} label={ar ? "الموسم" : "Season"} value={`${Math.min(100, profile.uniqueCases * 4)}%`}/><Status icon={Trophy} label={ar ? "الترتيب" : "Rank"} value={`#${position}`}/></div><div className="arena-status-actions"><button aria-label={ar ? "الإشعارات" : "Notifications"}><Bell/></button><Link aria-label={ar ? "الملف المهني" : "Profile"} href={`/${locale}/arena/profile`}><UserRound/></Link></div></header>;
}
function Status({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string | number }) { return <div><Icon/><span><small>{label}</small><b>{value}</b></span></div>; }

function ArenaDashboard({ locale, profile }: { locale: Locale; profile: ArenaProfile }) {
  const ar = locale === "ar", task = arenaTasks[0], shift = workShifts[0];
  return <div className="arena-pro-shell"><section className="arena-pro-welcome"><div><span>{ar ? "مساحة عملك اليوم" : "YOUR WORKSPACE TODAY"}</span><h1>{ar ? `صباح الخير، ${profile.displayName}` : `Good morning, ${profile.displayName}`}</h1><p>{ar ? "لديك مهمة ذات أولوية داخل وردية العمليات. راجع المستند قبل اتخاذ أي قرار." : "You have a priority task in the operations shift. Review the document before making a decision."}</p></div><div className="season-progress"><span>{ar ? seasonOne.titleAr : seasonOne.titleEn}<b>{Math.min(100, profile.uniqueCases * 4)}%</b></span><i><em style={{ width: `${Math.min(100, profile.uniqueCases * 4)}%` }}/></i></div></section>
    <div className="arena-pro-grid"><section className="current-mission"><div className="current-mission-visual"><div className="invoice-scene"><ReceiptText/><span>INVOICE</span><b>{task.document.number}</b><i/><i/><i/></div><span className="priority-chip"><AlertTriangle/>{ar ? "أولوية مهمة" : "Important"}</span></div><div className="current-mission-copy"><span><Building2/>{ar ? task.companyAr : task.companyEn}</span><small>CURRENT MISSION · {task.difficulty.toUpperCase()}</small><h2>{ar ? task.titleAr : task.titleEn}</h2><p>{ar ? task.objectiveAr : task.objectiveEn}</p><div className="mission-facts"><span><Clock3/><small>{ar ? "الوقت" : "Time"}</small><b>{task.estimatedMinutes} {ar ? "دقائق" : "min"}</b></span><span><Banknote/><small>{ar ? "الإجمالي" : "Total"}</small><b dir="ltr">{task.document.total.toLocaleString()} EGP</b></span><span><FileCheck2/><small>{ar ? "المستند" : "Document"}</small><b>{ar ? "فاتورة مورد" : "Supplier invoice"}</b></span><span><Medal/><small>{ar ? "التقييم" : "Assessment"}</small><b>{task.reward}/1000</b></span></div><Link className="arena-cta arena-cta-primary" href={`/${locale}/arena/career`}><BriefcaseBusiness/>{ar ? "ابدأ التنفيذ" : "Start work"}{ar ? <ArrowLeft/> : <ArrowRight/>}</Link></div></section>
      <aside className="cfo-mentor"><Image src="/arena/cfo-mentor.png" alt={ar ? "مرشد المدير المالي" : "CFO mentor"} width={360} height={450} priority/><div><span>CFO MENTOR</span><h3>{ar ? "كريم منصور" : "Karim Mansour"}</h3><p>{ar ? "ركز اليوم على سبب اختيار الحساب، مش حفظ شكل القيد. راجع أثر القرار قبل الاعتماد." : "Focus on why you chose the account, not on memorizing the entry. Review the impact before approval."}</p><Link href={`/${locale}/arena/career`}><CircleHelp/>{ar ? "اسأل المدير المالي" : "Ask the CFO"}</Link></div></aside>
    </div>
    <section className="shift-board"><div className="arena-pro-section-title"><div><span>WORK SHIFT</span><h2>{ar ? shift.titleAr : shift.titleEn}</h2></div><b>0 / {shift.taskIds.length}</b></div><div className="shift-tasks">{shift.taskIds.map((id, index) => <article className={index === 0 ? "active" : ""} key={id}><span>{index + 1}</span><div><small>{index === 0 ? (ar ? "الحالية" : "Current") : (ar ? "قادمة" : "Queued")}</small><b>{ar ? ["فاتورة مورد", "تحصيل عميل", "مصروف إيجار", "تحويل بنكي", "مراجعة قيد"][index] : ["Supplier invoice", "Customer collection", "Rent expense", "Bank transfer", "Journal review"][index]}</b></div>{index === 0 ? <ChevronRight/> : <Clock3/>}</article>)}</div></section>
    <div className="arena-insight-grid"><HiringCard locale={locale} profile={profile}/><CompanyHealthCard locale={locale} profile={profile}/></div>
    <section className="company-challenges"><div className="arena-pro-section-title"><div><span>COMPANY CHALLENGES</span><h2>{ar ? "اختبارات مهنية من واقع العمل" : "Professional workplace assessments"}</h2></div></div><div>{companyChallenges.map(([id, titleAr, titleEn, skill], index) => <article key={id}><span>{String(index + 1).padStart(2, "0")}</span><FileSearch/><h3>{ar ? titleAr : titleEn}</h3><small>{skill.replace("-", " ")}</small><b>{index < 2 ? (ar ? "متاح" : "Available") : (ar ? "يتطلب تقدمًا" : "Requires progress")}</b></article>)}</div></section>
    <section className="talent-interest"><div><BadgeCheck/><span><b>{ar ? "شركات مهتمة بأفضل المواهب" : "Companies interested in top performers"}</b><small>{ar ? "عرض توضيحي فقط — لا توجد شركة تتابع حسابك فعليًا الآن." : "Demonstration only—no company is currently following your profile."}</small></span></div><div>{demoTalentCompanies.map((company) => <span key={company}>{company}<small>DEMO</small></span>)}</div></section>
  </div>;
}

function HiringCard({ locale, profile }: { locale: Locale; profile: ArenaProfile }) { const ar = locale === "ar", readiness = calculateHiringReadiness(profile); return <section className="hiring-card"><div className="arena-pro-section-title"><div><span>HIRING READINESS</span><h2>{ar ? "الجاهزية للعمل" : "Job readiness"}</h2></div><strong>{readiness.score}%</strong></div><div className="readiness-ring" style={{ "--score": `${readiness.score * 3.6}deg` } as React.CSSProperties}><span><b>{readiness.score}%</b><small>{readiness.level === "junior-ready" ? (ar ? "جاهز لمحاسب مبتدئ" : "Junior-ready") : readiness.level === "developing" ? (ar ? "قيد التطوير" : "Developing") : (ar ? "يبني الأساس" : "Building foundation")}</small></span></div><p>{ar ? "مؤشر مبني على تغطية المهارات والدقة والحالات الفريدة والإقفال والبنوك والقيود؛ ليس وعد توظيف." : "Evidence-based on skill coverage, accuracy, unique cases, close, banking, and journals; not an employment guarantee."}</p></section>; }

function CompanyHealthCard({ locale, profile }: { locale: Locale; profile: ArenaProfile }) { const ar = locale === "ar", labels = { cash: ["النقدية", "Cash"], receivables: ["العملاء", "Receivables"], payables: ["الموردون", "Payables"], profitIntegrity: ["سلامة الربح", "Profit integrity"], accountingAccuracy: ["دقة الحسابات", "Accounting accuracy"], compliance: ["الالتزام", "Compliance"], closingReadiness: ["جاهزية الإقفال", "Closing readiness"] } as const; return <section className="health-pro"><div className="arena-pro-section-title"><div><span>COMPANY HEALTH</span><h2>{ar ? "حالة شركة التدريب" : "Training company health"}</h2></div><HeartPulse/></div><div>{Object.entries(profile.companyHealth).map(([key, value]) => <article key={key}><span>{labels[key as keyof typeof labels][ar ? 0 : 1]}<b>{value}%</b></span><i><em style={{ width: `${value}%` }}/></i></article>)}</div></section>; }

function MissionWorkspace({ locale, profile, commit }: { locale: Locale; profile: ArenaProfile; commit: (profile: ArenaProfile) => void }) {
  const ar = locale === "ar", task = arenaTasks[0], allAccounts = useMemo(() => createTrainingAccountSnapshot(), []), relevantCodes = new Set(["1200", "1151", "2100", "1330", "5100", "1110", "5000"]), accounts = allAccounts.filter((account) => relevantCodes.has(account.code));
  const [step, setStep] = useState(0), [activeLine, setActiveLine] = useState(0), [hints, setHints] = useState(0), [showWhy, setShowWhy] = useState(false), [showImpact, setShowImpact] = useState(false), [result, setResult] = useState<ReturnType<typeof scoreArenaTask>>(), [approved, setApproved] = useState(false);
  const [lines, setLines] = useState<ArenaTaskLine[]>([{ accountCode: "", side: "debit", amount: 25000 }, { accountCode: "", side: "debit", amount: 3500 }, { accountCode: "", side: "credit", amount: 28500 }]);
  const validation = validateArenaJournal(lines), exact = isExactTaskAnswer(task, lines), impact = financialImpactFor(lines.filter((line) => line.accountCode));
  const updateLine = (index: number, patch: Partial<ArenaTaskLine>) => setLines(lines.map((line, current) => current === index ? { ...line, ...patch } : line));
  const verify = () => { const score = scoreArenaTask(task, lines, hints, 240); setResult(score); setStep(4); setShowImpact(true); };
  const approve = () => { if (!exact || approved) return; const score = result ?? scoreArenaTask(task, lines, hints, 240), attempt: ArenaAttempt = { caseId: task.id, mode: "work-shift", difficulty: task.difficulty, accuracy: score.accountingAccuracy, score: score.total * 10, hintsUsed: hints, durationSeconds: 240, completedAt: new Date().toISOString(), skills: task.skillIds, ranked: true }; commit(applyAttempt(profile, attempt)); setApproved(true); setStep(5); };
  const reset = () => { setLines([{ accountCode: "", side: "debit", amount: 25000 }, { accountCode: "", side: "debit", amount: 3500 }, { accountCode: "", side: "credit", amount: 28500 }]); setStep(0); setHints(0); setShowWhy(false); setShowImpact(false); setResult(undefined); setApproved(false); };
  return <div className="arena-task-shell"><div className="task-topline"><Link href={`/${locale}/arena`}>{ar ? <ArrowRight/> : <ArrowLeft/>}{ar ? "مساحة العمل" : "Workspace"}</Link><span>{ar ? task.companyAr : task.companyEn}</span><b>{ar ? "مهمة ذات أولوية" : "Priority task"}</b></div><div className="workflow-stepper">{workflow.map(([id, a, e], index) => <div className={index < step ? "done" : index === step ? "active" : ""} key={id}><span>{index < step ? <Check/> : index + 1}</span><small>{ar ? a : e}</small></div>)}</div>
    <header className="task-heading"><span>MISSION · {task.id.toUpperCase()}</span><h1>{ar ? task.titleAr : task.titleEn}</h1><p>{ar ? task.objectiveAr : task.objectiveEn}</p></header>
    <div className="task-workspace-grid"><section className="document-panel"><div className="document-toolbar"><span><ReceiptText/>{ar ? "فاتورة المورد" : "Supplier invoice"}</span><b>{task.document.number}</b></div><div className="paper-invoice"><header><div><b>{ar ? task.document.partyAr : task.document.partyEn}</b><small>{ar ? "توريد خامات صناعية" : "Industrial materials supply"}</small></div><span>INVOICE</span></header><dl><div><dt>{ar ? "رقم الفاتورة" : "Invoice no."}</dt><dd>{task.document.number}</dd></div><div><dt>{ar ? "التاريخ" : "Date"}</dt><dd>{task.document.date}</dd></div><div><dt>{ar ? "الوصف" : "Description"}</dt><dd>{ar ? "خامات تشغيل" : "Operating materials"}</dd></div></dl><table><tbody><tr><td>{ar ? "الصافي" : "Net"}</td><td>{task.document.net.toLocaleString()}</td></tr><tr><td>VAT 14%</td><td>{task.document.vat.toLocaleString()}</td></tr><tr><th>{ar ? "الإجمالي" : "Total"}</th><th>{task.document.total.toLocaleString()} EGP</th></tr></tbody></table></div>{step === 0 && <button className="arena-cta arena-cta-secondary" onClick={() => setStep(1)}><FileCheck2/>{ar ? "تمت مراجعة المستند" : "Document reviewed"}</button>}<div className="analysis-note"><CircleHelp/><p>{ar ? "هل خرجت نقدية؟ لا. الشركة استلمت خامات ولم تدفع بعد، إذن نشأ التزام للمورد." : "Did cash leave? No. The company received materials and has not paid, so a supplier liability arose."}</p></div></section>
      <section className="journal-workbench"><div className="workbench-head"><div><small>JOURNAL BUILDER</small><h2>{ar ? "كوّن القيد من حسابات FINORA" : "Build the entry with FINORA accounts"}</h2></div><span>{validation.valid ? <><CheckCircle2/>{ar ? "متوازن" : "Balanced"}</> : <><AlertTriangle/>{validation.totalDebit.toLocaleString()} / {validation.totalCredit.toLocaleString()}</>}</span></div><p>{ar ? "اختر السطر ثم اضغط بطاقة الحساب، أو استخدم القائمة كبديل. كل الحسابات مأخوذة من دليل FINORA الفعلي." : "Select a line, then tap an account card—or use the dropdown fallback. Every account comes from FINORA's real chart."}</p>
        <div className="journal-lines">{lines.map((line, index) => <article className={activeLine === index ? "active" : ""} onClick={() => setActiveLine(index)} key={index}><span>{index + 1}</span><select aria-label={ar ? `حساب السطر ${index + 1}` : `Line ${index + 1} account`} value={line.accountCode} onChange={(event) => updateLine(index, { accountCode: event.target.value })}><option value="">{ar ? "اختر الحساب" : "Select account"}</option>{allAccounts.map((account) => <option value={account.code} key={account.id}>{account.code} — {ar ? account.nameAr : account.nameEn}</option>)}</select><select aria-label={ar ? `جانب السطر ${index + 1}` : `Line ${index + 1} side`} value={line.side} onChange={(event) => updateLine(index, { side: event.target.value as "debit" | "credit" })}><option value="debit">{ar ? "مدين" : "Debit"}</option><option value="credit">{ar ? "دائن" : "Credit"}</option></select><input aria-label={ar ? `مبلغ السطر ${index + 1}` : `Line ${index + 1} amount`} type="number" min="0" value={line.amount} onChange={(event) => updateLine(index, { amount: Number(event.target.value) })}/></article>)}</div>
        <div className="real-account-cards">{accounts.map((account) => <button className={lines[activeLine].accountCode === account.code ? "selected" : ""} onClick={() => { updateLine(activeLine, { accountCode: account.code }); setStep(Math.max(step, 2)); }} key={account.id}><span>{account.code}</span><b>{ar ? account.nameAr : account.nameEn}</b><small>{ar ? account.descriptionAr : account.descriptionEn}</small><em>{account.type}</em></button>)}</div>
        <div className="journal-totals-pro"><span>{ar ? "إجمالي المدين" : "Total debit"}<b>{validation.totalDebit.toLocaleString()}</b></span><span>{ar ? "إجمالي الدائن" : "Total credit"}<b>{validation.totalCredit.toLocaleString()}</b></span><span>{ar ? "الفرق" : "Difference"}<b>{Math.abs(validation.totalDebit - validation.totalCredit).toLocaleString()}</b></span></div>
        {result && !exact && <div className="consequence-panel"><AlertTriangle/><div><b>{ar ? "لو سجلت العملية بالشكل ده، هيحصل إيه؟" : "What happens if you record it this way?"}</b><p>{ar ? "القيد قد يكون متوازنًا لكنه لا يعبر عن الفاتورة. اختيار مصروف بدل المخزون يخفض الربح رغم أن الخامات ما زالت تملكها الشركة، وإغفال VAT يخفي حقًا ضريبيًا." : "The entry may balance but still misstate the invoice. Expensing inventory reduces profit while the materials are still owned, and omitting VAT hides a tax asset."}</p></div></div>}
        <div className="workbench-actions"><button className="arena-cta arena-cta-ghost" onClick={reset}><RotateCcw/>{ar ? "إعادة تعيين" : "Reset"}</button><button className="arena-cta arena-cta-outline" onClick={() => { setHints(hints + 1); setShowWhy(true); }}><CircleHelp/>{ar ? "ليه؟" : "Why?"}</button><Link className="arena-cta arena-cta-outline" href={`/${locale}/academy/account-guide?return=arena`}><BookOpenCheck/>{ar ? "راجع طبيعة الحساب" : "Account nature"}</Link><button className="arena-cta arena-cta-primary" onClick={verify}><ListChecks/>{ar ? "تحقق من القيد" : "Check entry"}</button></div>
        {showWhy && <div className="why-panel"><b>{ar ? "ليه المخزون وضريبة المدخلات مدين؟" : "Why debit inventory and input VAT?"}</b><p>{ar ? "لأنهما أصلان زادا. وليه الموردون دائن؟ لأن التزام الشركة للمورد زاد." : "Because both assets increased. Why credit suppliers? Because the liability to the supplier increased."}</p></div>}
      </section>
    </div>
    {showImpact && <section className="impact-review"><div className="arena-pro-section-title"><div><span>FINANCIAL IMPACT</span><h2>{ar ? "راجع الأثر قبل الاعتماد" : "Review impact before approval"}</h2></div>{result && <strong>{result.total}/100</strong>}</div><div className="impact-cards">{impact.map((item, index) => <article key={`${item.accountCode}-${index}`}><span className={item.direction}>{item.direction === "increase" ? "+" : "−"}</span><div><small>{item.accountCode} · {item.type}</small><b>{ar ? item.accountNameAr : item.accountNameEn}</b></div><strong>{item.amount.toLocaleString()}</strong></article>)}<article><span className="none">—</span><div><small>PROFIT</small><b>{ar ? "صافي الربح" : "Net profit"}</b></div><strong>{ar ? "لا تغيير" : "No change"}</strong></article><article><span className="none">—</span><div><small>CASH</small><b>{ar ? "النقدية" : "Cash"}</b></div><strong>{ar ? "لا تغيير" : "No change"}</strong></article></div><div className="assessment-grid">{result && Object.entries(result).filter(([key]) => key !== "total").map(([key, value]) => <span key={key}><small>{key.replaceAll(/([A-Z])/g, " $1")}</small><b>{value}%</b></span>)}</div><button className="arena-cta arena-cta-success" disabled={!exact || approved} onClick={approve}>{approved ? <><Check/>{ar ? "تم اعتماد المهمة" : "Task approved"}</> : <><ShieldCheck/>{ar ? "اعتماد المهمة" : "Approve task"}</>}</button></section>}
  </div>;
}
