import { describe, expect, it } from "vitest";
import { defaultAccounts } from "@/data/accounts";
import { getAccountBalance, getAccountChildren, getPostingAccounts, hasCircularParent, previewAccountImport, suggestChildAccountCode, validateAccount, validateAccountCatalog } from "@/lib/accounting/accounts";
import { accountTemplates } from "@/data/account-templates";
import { removedUsedAccount } from "@/lib/accounting/integrity";
import { normalizeSheet } from "@/lib/spreadsheet/reader";
import { generateJournalEntry } from "@/rules";
import { validateJournalEntry } from "@/lib/accounting/validation";
import { createBankDraftEntry } from "@/lib/banking/draft-entry";
import type { ChartAccount } from "@/types";

describe("professional chart of accounts", () => {
  it("keeps every bundled template structurally valid", () => { for (const template of accountTemplates) expect(validateAccountCatalog(template.accounts), template.id).toEqual([]); });
  it("builds a real parent-child hierarchy", () => { expect(getAccountChildren(defaultAccounts, "assets").map((account) => account.id)).toContain("current-assets"); expect(getAccountChildren(defaultAccounts, "current-assets").length).toBeGreaterThan(1); });
  it("suggests the next unique child code", () => { const parent = { id: "bank-parent", code: "1102", nameAr: "بنوك", nameEn: "Banks", type: "asset", active: true } as ChartAccount; const accounts = [parent, { ...parent, id: "a", code: "110201", parentId: parent.id }, { ...parent, id: "b", code: "110202", parentId: parent.id }]; expect(suggestChildAccountCode(parent, accounts)).toBe("110203"); });
  it("blocks duplicate codes and circular parents", () => { const duplicate = { ...defaultAccounts[0], id: "duplicate" }; expect(validateAccount(duplicate, defaultAccounts)).toContain("Duplicate account code"); const rows = [{ ...defaultAccounts[0], parentId: "current-assets" }, ...defaultAccounts.slice(1)]; expect(hasCircularParent(rows, "assets", "current-assets")).toBe(true); });
  it("returns only active leaf posting accounts", () => { const posting = getPostingAccounts(defaultAccounts); expect(posting.some((account) => account.id === "assets" || account.id === "current-assets")).toBe(false); expect(posting.some((account) => account.id === "cash")).toBe(true); expect(getPostingAccounts(defaultAccounts.map((account) => account.id === "cash" ? { ...account, active: false } : account)).some((account) => account.id === "cash")).toBe(false); });
  it("blocks a parent account at journal validation even when allow posting is true", () => { const entry = generateJournalEntry({ type: "cash-sale", amount: 100 }), parent = defaultAccounts.find((account) => account.id === "current-assets")!; entry.lines[0] = { ...entry.lines[0], accountCode: parent.code, accountNameAr: parent.nameAr, accountNameEn: parent.nameEn }; expect(validateJournalEntry(entry, defaultAccounts).errors.some((issue) => issue.code === "blocked-account")).toBe(true); });
  it("blocks deleting a used account", () => { const entry = generateJournalEntry({ type: "cash-sale", amount: 100 }); const next = defaultAccounts.filter((account) => account.code !== "1100"); expect(removedUsedAccount(defaultAccounts, next, [entry])?.code).toBe("1100"); });
  it("uses the bank account selected from the central chart", () => { const custom = { ...defaultAccounts.find((account) => account.code === "1110")!, id: "cib", code: "111001", nameAr: "بنك CIB", nameEn: "CIB Bank" }; const entry = createBankDraftEntry({ id: "bank-custom", bankAccountId: custom.code, date: "2026-08-08", description: "Deposit", reference: "B-1", debit: 0, credit: 100, currency: "EGP", status: "unmatched" }, [...defaultAccounts, custom]); expect(entry.paymentAccountCode).toBe(custom.code); expect(entry.lines.find((line) => line.accountCode === custom.code)?.accountNameEn).toBe("CIB Bank"); });
  it("calculates balances from posted journal entries", () => { const entry = { ...generateJournalEntry({ type: "cash-sale", amount: 500 }), workflowStatus: "posted" as const }; const cash = defaultAccounts.find((account) => account.code === "1100")!; expect(getAccountBalance(cash, [entry])).toMatchObject({ balance: 500, totalDebit: 500, totalCredit: 0, movementCount: 1 }); });
  it("previews imports and rejects invalid rows without rejecting valid rows", () => { const sheet = normalizeSheet("Accounts", [["Code", "Arabic Name", "English Name", "Type", "Parent"], ["1900", "أصل جديد", "New asset", "asset", "11"], ["1900", "مكرر", "Duplicate", "asset", "11"], ["", "ناقص", "Missing", "asset", "11"], ["6100", "مصروف", "Expense", "expense", "999"]]); const preview = previewAccountImport(sheet, { code: "Code", nameAr: "Arabic Name", nameEn: "English Name", type: "Type", parent: "Parent" }, defaultAccounts); expect(preview.filter((row) => row.valid)).toHaveLength(0); expect(preview.some((row) => row.errors.includes("Duplicate account code"))).toBe(true); expect(preview.some((row) => row.errors.includes("Invalid parent code"))).toBe(true); });
  it("accepts a valid imported leaf and exposes it to selectors", () => { const sheet = normalizeSheet("Accounts", [["Code", "Arabic Name", "English Name", "Type", "Parent"], ["1160", "تأمينات", "Deposits", "asset", "11"]]); const row = previewAccountImport(sheet, { code: "Code", nameAr: "Arabic Name", nameEn: "English Name", type: "Type", parent: "Parent" }, defaultAccounts)[0]; expect(row.valid).toBe(true); expect(getPostingAccounts([...defaultAccounts, row.account!]).some((account) => account.code === "1160")).toBe(true); });
});
