import { describe, expect, it } from "vitest";
import { moneyFlowScenarios } from "@/data/money-flow/scenarios";
import { applyMoneyMovement, buildMoneyFlowTrainingEntry, calculateMoneyFlowScore, deriveJournalSide, getWrongMovementConsequence, isCorrectMoneyMovement, isQuestionAnswerCorrect, isReverseAnswerCorrect, resolveVariation, validateMoneyFlowJournal, validateMoneyFlowScenario } from "@/lib/money-flow/engine";

describe("FINORA Money Flow engine",()=>{
 it("contains seven valid bilingual scenarios",()=>{expect(moneyFlowScenarios).toHaveLength(7);moneyFlowScenarios.forEach((scenario)=>{expect(validateMoneyFlowScenario(scenario).valid).toBe(true);expect(scenario.titleAr).toBeTruthy();expect(scenario.titleEn).toBeTruthy();});});
 it.each(moneyFlowScenarios)("validates the correct movement for $slug",(scenario)=>{const move=scenario.correctMovement;expect(isCorrectMoneyMovement(scenario,move.tokenId,move.destinationAccountId,move.sourceAccountId)).toBe(true);expect(isCorrectMoneyMovement(scenario,move.tokenId,scenario.accounts.find((item)=>item.id!==move.destinationAccountId)!.id,move.sourceAccountId)).toBe(false);});
 it("applies increases and decreases without impossible negative balances",()=>{moneyFlowScenarios.forEach((scenario)=>applyMoneyMovement(scenario).forEach((account)=>expect(account.after).toBeGreaterThanOrEqual(0)));const rent=moneyFlowScenarios.find((item)=>item.slug==="rent-from-bank")!;expect(applyMoneyMovement(rent).find((item)=>item.id==="bank")?.after).toBe(8000);expect(applyMoneyMovement(rent).find((item)=>item.id==="rent")?.after).toBe(2000);});
 it("derives debit and credit from account type plus movement",()=>{expect(deriveJournalSide("asset",100)).toBe("debit");expect(deriveJournalSide("asset",-100)).toBe("credit");expect(deriveJournalSide("expense",100)).toBe("debit");expect(deriveJournalSide("liability",100)).toBe("credit");expect(deriveJournalSide("liability",-100)).toBe("debit");expect(deriveJournalSide("revenue",100)).toBe("credit");});
 it.each(moneyFlowScenarios)("keeps $slug journal balanced and isolated",(scenario)=>{const validation=validateMoneyFlowJournal(scenario),entry=buildMoneyFlowTrainingEntry(scenario);expect(validation.valid).toBe(true);expect(validation.totalDebit).toBe(validation.totalCredit);expect(entry.id).toContain("training-money-flow");expect(entry.workflowStatus).toBe("draft");});
 it("returns a meaningful wrong consequence",()=>{const sale=moneyFlowScenarios.find((item)=>item.slug==="credit-service-sale")!,consequence=getWrongMovementConsequence(sale,"bank");expect(consequence?.impacts.some((item)=>item.key==="bank")).toBe(true);expect(consequence?.reflectionAr).toContain("العميل");});
 it("validates every guided question",()=>{moneyFlowScenarios.forEach((scenario)=>scenario.questions.forEach((question)=>{expect(isQuestionAnswerCorrect(scenario,question.id,question.correctChoiceId)).toBe(true);expect(isQuestionAnswerCorrect(scenario,question.id,"missing")).toBe(false);}));});
 it("resolves the one-word variation",()=>{const collection=moneyFlowScenarios.find((item)=>item.slug==="customer-collection")!,variation=resolveVariation(collection);expect(variation.fromAccountEn).toContain("Receivable");expect(variation.toAccountEn).toContain("Revenue");});
 it("supports reverse entry-to-transaction learning",()=>{moneyFlowScenarios.forEach((scenario)=>{expect(isReverseAnswerCorrect(scenario,scenario.reverseQuestion.correctChoiceId)).toBe(true);expect(isReverseAnswerCorrect(scenario,"missing")).toBe(false);});});
 it("scores mistakes and hints with a safe floor",()=>{expect(calculateMoneyFlowScore(0,0)).toBe(100);expect(calculateMoneyFlowScore(2,1)).toBe(68);expect(calculateMoneyFlowScore(20,20)).toBe(40);});
 it("declares financial impact for every scenario",()=>moneyFlowScenarios.forEach((scenario)=>expect(scenario.financialImpact.length).toBeGreaterThanOrEqual(3)));
});
