import{describe,expect,it}from"vitest";import{analyzeSheet}from"@/lib/spreadsheet/analyzer";describe("spreadsheet analyzer",()=>{it("profiles numeric and categorical columns",()=>{const result=analyzeSheet({name:"Sales",headers:["Item","Amount"],rows:[["A",100],["A",200],["B",300]]});expect(result.numeric[0].sum).toBe(600);expect(result.categorical[0].topValues[0].percentage).toBe(66.67)});it("detects duplicates",()=>expect(analyzeSheet({name:"x",headers:["A"],rows:[[1],[1]]}).quality.some(x=>x.code==="duplicate-rows")).toBe(true))});

describe("large and vertical datasets",()=>{it("aggregates a vertical category and amount table",()=>{const result=analyzeSheet({name:"Expenses",headers:["Category","Amount"],rows:[["Rent",5000],["Utilities",2000],["Rent",1000]]});expect(result.breakdown?.total).toBe(8000);expect(result.breakdown?.items[0]).toMatchObject({label:"Rent",value:6000,percentage:75})});it("samples very large sheets while keeping numeric totals exact",()=>{const rows=Array.from({length:150_100},(_,index)=>[index%2?"A":"B",index]);const result=analyzeSheet({name:"Large",headers:["Category","Amount"],rows});expect(result.rowCount).toBe(150_100);expect(result.analyzedRows).toBe(60_000);expect(result.numeric.find(item=>item.column==="Amount")?.sum).toBe(rows.reduce((sum,row)=>sum+Number(row[1]),0));expect(result.sampled).toBe(true);expect(result.quality.some(issue=>issue.code==="sampled-analysis")).toBe(true)})});

describe("read quality and column interpretation",()=>{
  it("calculates a quality score and column roles",()=>{const result=analyzeSheet({name:"Sales",headers:["رقم العميل","التاريخ","إجمالي المبيعات"],rows:[["001","2026-08-01",100],["002","2026-08-02",200]]});expect(result.qualityScore).toBeGreaterThan(70);expect(result.columns.map(column=>column.role)).toEqual(["identifier","date","amount"])});
  it("detects formula errors",()=>{const result=analyzeSheet({name:"Broken",headers:["Item","Value"],rows:[["A","#REF!"],["B","#DIV/0!"]]});expect(result.quality.some(issue=>issue.code==="formula-errors")).toBe(true)});
  it("reports weak columns",()=>{const result=analyzeSheet({name:"Missing",headers:["Item","Amount"],rows:[["A",null],["B",null],["C",10]]});expect(result.columns.find(column=>column.column==="Amount")?.completeness).toBe(33.33)});
});
