"use client";
import { useEffect, useState } from "react";
import { Building2, Plus, ShieldCheck, Trash2, Users } from "lucide-react";
import { loadWorkspace, rolePermissions, saveWorkspace } from "@/lib/storage/workspace";
import type { Company, Locale, MemberRole, WorkspaceData, WorkspaceMember } from "@/types";

const newCompany = (): Company => ({ id: crypto.randomUUID(), nameAr: "", nameEn: "", country: "EG", currency: "EGP", fiscalYearStart: `${new Date().getFullYear()}-01-01`, active: true, createdAt: new Date().toISOString() });
const roles: MemberRole[] = ["owner", "manager", "accountant", "reviewer", "viewer"];

export function WorkspaceManager({ locale }: { locale: Locale }) {
  const ar = locale === "ar"; const [data, setData] = useState<WorkspaceData>({ companies: [], members: [] }); const [company, setCompany] = useState(newCompany); const [member, setMember] = useState({ name: "", email: "", role: "accountant" as MemberRole }); const [error, setError] = useState("");
  useEffect(() => { setData(loadWorkspace()); }, []);
  const commit = (next: WorkspaceData) => { setData(next); saveWorkspace(next); };
  const addCompany = () => { if (!company.nameAr.trim() || !company.nameEn.trim()) return setError(ar ? "أدخل اسم الشركة بالعربية والإنجليزية." : "Enter both company names."); const next = { ...company, nameAr: company.nameAr.trim(), nameEn: company.nameEn.trim() }; commit({ ...data, companies: [...data.companies, next], activeCompanyId: data.activeCompanyId || next.id }); setCompany(newCompany()); setError(""); };
  const active = data.companies.find((item) => item.id === data.activeCompanyId);
  const addMember = () => { if (!active || !member.name.trim() || !/^\S+@\S+\.\S+$/.test(member.email)) return setError(ar ? "اختر شركة وأدخل اسمًا وبريدًا صحيحًا." : "Select a company and enter a valid name and email."); const next: WorkspaceMember = { id: crypto.randomUUID(), companyId: active.id, name: member.name.trim(), email: member.email.trim().toLowerCase(), role: member.role, active: true, createdAt: new Date().toISOString() }; commit({ ...data, members: [...data.members, next] }); setMember({ name: "", email: "", role: "accountant" }); setError(""); };
  const roleLabel = (role: MemberRole) => ar ? ({ owner: "المالك", manager: "مدير", accountant: "محاسب", reviewer: "مراجع", viewer: "مشاهدة فقط" }[role]) : role;
  return <div className="grid"><section className="card"><h2><Building2 size={20} /> {ar ? "الشركات" : "Companies"}</h2><div className="grid three"><label>{ar ? "اسم الشركة بالعربية" : "Arabic company name"}<input value={company.nameAr} onChange={(event) => setCompany({ ...company, nameAr: event.target.value })} /></label><label>{ar ? "اسم الشركة بالإنجليزية" : "English company name"}<input value={company.nameEn} onChange={(event) => setCompany({ ...company, nameEn: event.target.value })} /></label><label>{ar ? "العملة" : "Currency"}<select value={company.currency} onChange={(event) => setCompany({ ...company, currency: event.target.value })}>{["EGP", "USD", "EUR", "SAR", "AED", "KWD", "QAR", "GBP"].map((item) => <option key={item}>{item}</option>)}</select></label><label>{ar ? "الدولة" : "Country"}<select value={company.country} onChange={(event) => setCompany({ ...company, country: event.target.value })}>{[["EG", "مصر", "Egypt"], ["SA", "السعودية", "Saudi Arabia"], ["AE", "الإمارات", "UAE"], ["OTHER", "أخرى", "Other"]].map(([code, a, e]) => <option value={code} key={code}>{ar ? a : e}</option>)}</select></label><label>{ar ? "بداية السنة المالية" : "Fiscal year start"}<input type="date" value={company.fiscalYearStart} onChange={(event) => setCompany({ ...company, fiscalYearStart: event.target.value })} /></label><label>{ar ? "الرقم الضريبي (اختياري)" : "Tax number (optional)"}<input value={company.taxNumber || ""} onChange={(event) => setCompany({ ...company, taxNumber: event.target.value })} /></label></div><button className="btn btn-primary" onClick={addCompany}><Plus size={17} />{ar ? "إضافة شركة" : "Add company"}</button>{error && <p className="warning error">{error}</p>}<div className="grid three section">{data.companies.map((item) => <article className="card" key={item.id}><span className={item.id === data.activeCompanyId ? "badge" : "muted"}>{item.id === data.activeCompanyId ? (ar ? "الشركة النشطة" : "Active company") : (ar ? "غير نشطة" : "Inactive")}</span><h3>{ar ? item.nameAr : item.nameEn}</h3><p className="muted">{item.currency} · {item.country}</p><div className="actions"><button className="btn" onClick={() => commit({ ...data, activeCompanyId: item.id })}>{ar ? "اختيار" : "Select"}</button><button className="btn btn-danger" onClick={() => commit({ ...data, companies: data.companies.filter((x) => x.id !== item.id), members: data.members.filter((x) => x.companyId !== item.id), activeCompanyId: data.activeCompanyId === item.id ? undefined : data.activeCompanyId })}><Trash2 size={16} /></button></div></article>)}</div></section>
    <section className="card"><h2><Users size={20} /> {ar ? "فريق الشركة" : "Company team"}</h2>{active ? <><p className="muted">{ar ? `الشركة النشطة: ${active.nameAr}` : `Active company: ${active.nameEn}`}</p><div className="grid three"><label>{ar ? "اسم العضو" : "Member name"}<input value={member.name} onChange={(event) => setMember({ ...member, name: event.target.value })} /></label><label>{ar ? "البريد الإلكتروني" : "Email"}<input type="email" value={member.email} onChange={(event) => setMember({ ...member, email: event.target.value })} /></label><label>{ar ? "الدور" : "Role"}<select value={member.role} onChange={(event) => setMember({ ...member, role: event.target.value as MemberRole })}>{roles.map((role) => <option value={role} key={role}>{roleLabel(role)}</option>)}</select></label></div><button className="btn btn-primary" onClick={addMember}><Plus size={17} />{ar ? "إضافة عضو" : "Add member"}</button><div className="table-wrap section"><table><thead><tr><th>{ar ? "العضو" : "Member"}</th><th>{ar ? "الدور" : "Role"}</th><th>{ar ? "الصلاحيات" : "Permissions"}</th><th>{ar ? "الحالة" : "Status"}</th><th></th></tr></thead><tbody>{data.members.filter((item) => item.companyId === active.id).map((item) => <tr key={item.id}><td>{item.name}<br /><small>{item.email}</small></td><td><select value={item.role} onChange={(event) => commit({ ...data, members: data.members.map((x) => x.id === item.id ? { ...x, role: event.target.value as MemberRole } : x) })}>{roles.map((role) => <option key={role} value={role}>{roleLabel(role)}</option>)}</select></td><td><small>{rolePermissions[item.role].join(" · ")}</small></td><td><button className="btn" onClick={() => commit({ ...data, members: data.members.map((x) => x.id === item.id ? { ...x, active: !x.active } : x) })}>{item.active ? (ar ? "نشط" : "Active") : (ar ? "موقوف" : "Disabled")}</button></td><td><button className="btn btn-danger" onClick={() => commit({ ...data, members: data.members.filter((x) => x.id !== item.id) })}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div></> : <p className="warning">{ar ? "أضف شركة واخترها أولًا." : "Add and select a company first."}</p>}</section>
    <section className="card"><h2><ShieldCheck size={20} /> {ar ? "ملاحظة مهمة" : "Important note"}</h2><p className="muted">{ar ? "هذه نسخة محلية لتجربة هيكل الشركات والصلاحيات. تسجيل الدخول والعزل الأمني الحقيقي بين الشركات سيُنفذان عند ربط قاعدة البيانات، ولا يجب اعتبار الصلاحيات المحلية حماية أمنية." : "This local version validates the company and permission model. Real authentication and tenant isolation will be implemented with the database; local roles are not a security boundary."}</p></section>
  </div>;
}
