import type { CloseAnalysis, CloseAnalysisInput, CloseRisk } from "@/types";
export function analyzeClose({entries,tasks,checklist,today}:CloseAnalysisInput):CloseAnalysis {
 const draftEntries=entries.filter(e=>e.workflowStatus==="draft").length; const reviewEntries=entries.filter(e=>e.workflowStatus==="review"||e.workflowStatus==="approved").length; const unbalancedEntries=entries.filter(e=>!e.isBalanced).length; const overdueTasks=tasks.filter(t=>t.dueDate<today&&t.status!=="completed").length; const completedItems=checklist.filter(i=>i.completed).length; const estimatedMinutes=checklist.filter(i=>!i.completed).reduce((s,i)=>s+i.estimatedMinutes,0)+(draftEntries*8)+(reviewEntries*5)+(overdueTasks*10); const risks:CloseRisk[]=[];
 if(unbalancedEntries)risks.push({id:"unbalanced",severity:"critical",titleAr:"قيود غير متوازنة",titleEn:"Unbalanced entries",detailAr:`يوجد ${unbalancedEntries} قيد غير متوازن يمنع الإقفال.`,detailEn:`${unbalancedEntries} unbalanced entries block close.`,actionHref:"review"});
 if(reviewEntries)risks.push({id:"pending-review",severity:"high",titleAr:"قيود لم تعتمد أو تُرحّل",titleEn:"Entries awaiting approval",detailAr:`يوجد ${reviewEntries} قيد في دورة المراجعة.`,detailEn:`${reviewEntries} entries remain in review.`,actionHref:"review"});
 if(draftEntries)risks.push({id:"drafts",severity:"medium",titleAr:"مسودات غير مكتملة",titleEn:"Incomplete drafts",detailAr:`يوجد ${draftEntries} قيد مسودة يحتاج قرارًا.`,detailEn:`${draftEntries} draft entries require action.`,actionHref:"review"});
 if(overdueTasks)risks.push({id:"overdue",severity:"high",titleAr:"مهام محاسبية متأخرة",titleEn:"Overdue accounting tasks",detailAr:`يوجد ${overdueTasks} مهمة متأخرة.`,detailEn:`${overdueTasks} overdue tasks remain.`,actionHref:"dashboard"});
 if(entries.length===0)risks.push({id:"no-entries",severity:"medium",titleAr:"لا توجد قيود للفترة",titleEn:"No period entries",detailAr:"تحقق من اختيار الشركة والفترة وصحة استيراد البيانات.",detailEn:"Check company, period, and data import.",actionHref:"generator"});
 const completion=checklist.length?completedItems/checklist.length:0; const penalty=Math.min(45,unbalancedEntries*20+reviewEntries*4+draftEntries*2+overdueTasks*3); const readiness=Math.max(0,Math.min(100,Math.round(completion*100-penalty)));
 return {readiness,estimatedMinutes,completedItems,totalItems:checklist.length,risks:risks.sort((a,b)=>["critical","high","medium","low"].indexOf(a.severity)-["critical","high","medium","low"].indexOf(b.severity)),draftEntries,reviewEntries,unbalancedEntries,overdueTasks};
}
