import type { ChartAccount, GeneratedJournalEntry } from "@/types";
import { assertValidJournalEntry } from "./validation";

export function reversePostedEntry(original: GeneratedJournalEntry, reason: string, accounts: ChartAccount[] = [], actor = "Local user", now = new Date().toISOString()) {
  if (original.workflowStatus !== "posted") throw new Error("يمكن عكس القيود المرحلة فقط.");
  if (!reason.trim()) throw new Error("اكتب سبب عكس القيد.");
  const reversalId = crypto.randomUUID(), lines = original.lines.map((line) => ({ ...line, id: crypto.randomUUID(), debit: line.credit, credit: line.debit, descriptionAr: `عكس: ${line.descriptionAr || original.narrationAr}`, descriptionEn: `Reversal: ${line.descriptionEn || original.narrationEn}` }));
  const reversal: GeneratedJournalEntry = { ...original, id: reversalId, entryNumber: `${original.entryNumber}-REV`, transactionType: "journal-reversal", titleAr: `عكس ${original.titleAr}`, titleEn: `Reversal of ${original.titleEn}`, narrationAr: `عكس القيد ${original.entryNumber} — ${reason}`, narrationEn: `Reversal of ${original.entryNumber} — ${reason}`, source: "adjustment", lines, totalDebit: original.totalCredit, totalCredit: original.totalDebit, isBalanced: original.isBalanced, workflowStatus: "posted", originalEntryId: original.id, reversalEntryId: undefined, reversalReason: reason, createdAt: now, createdBy: actor, approvedAt: now, postedAt: now, audit: [{ id: crypto.randomUUID(), entryId: reversalId, action: "created", at: now, actor, note: reason }, { id: crypto.randomUUID(), entryId: reversalId, action: "posted", at: now, actor, note: reason }], financialStatementImpact: { assets: -original.financialStatementImpact.assets, liabilities: -original.financialStatementImpact.liabilities, equity: -original.financialStatementImpact.equity, revenue: -original.financialStatementImpact.revenue, expenses: -original.financialStatementImpact.expenses, profit: -original.financialStatementImpact.profit, cash: -(original.financialStatementImpact.cash || 0), inventory: -(original.financialStatementImpact.inventory || 0), receivables: -(original.financialStatementImpact.receivables || 0), payables: -(original.financialStatementImpact.payables || 0) } };
  assertValidJournalEntry(reversal, accounts);
  const updatedOriginal: GeneratedJournalEntry = { ...original, workflowStatus: "reversed", reversalEntryId: reversal.id, reversedAt: now, reversalReason: reason, audit: [...(original.audit || []), { id: crypto.randomUUID(), entryId: original.id, action: "reversed", at: now, actor, note: reason }] };
  return { original: updatedOriginal, reversal };
}
