"use client";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Banknote, Landmark } from "lucide-react";
import type { ChartAccount, GeneratedJournalEntry, Locale, TransactionInput } from "@/types";
import { parseTransaction } from "@/lib/parser";
import { generateJournalEntry } from "@/rules";
import { transactions } from "@/data/transactions";
import { loadAccounts } from "@/lib/storage/accounting";
import { treasuryAccounts } from "@/lib/accounting/treasury";
import { JournalResult } from "@/components/journal/result";

const schema = z.object({ type: z.string().min(1), amount: z.number().positive(), date: z.string().optional(), currency: z.string().length(3), paymentMethod: z.enum(["cash", "bank", "cheque", "credit"]), paymentAccountCode: z.string().optional(), vatEnabled: z.boolean(), vatRate: z.number().min(0).max(100), vatIncluded: z.boolean(), commercialDiscount: z.number().min(0), withholdingEnabled: z.boolean(), withholdingRate: z.number().min(0).max(100), usefulLife: z.number().min(0), residualValue: z.number().min(0), notes: z.string().optional() });
type Form = z.infer<typeof schema>;

export function Generator({ locale, initialType }: { locale: Locale; initialType?: string }) {
  const ar = locale === "ar", [tab, setTab] = useState<"text" | "guided">("text"), [natural, setNatural] = useState(""), [entry, setEntry] = useState<GeneratedJournalEntry>(), [notice, setNotice] = useState(""), [accounts, setAccounts] = useState<ChartAccount[]>([]);
  const { register, handleSubmit, watch, setValue, formState: { errors }, reset } = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { type: initialType || "cash-sale", amount: 10000, date: new Date().toISOString().slice(0, 10), currency: "EGP", paymentMethod: "cash", paymentAccountCode: "1100", vatEnabled: false, vatRate: 14, vatIncluded: false, commercialDiscount: 0, withholdingEnabled: false, withholdingRate: 0, usefulLife: 5, residualValue: 0 } });
  useEffect(() => setAccounts(treasuryAccounts(loadAccounts())), []);
  const vat = watch("vatEnabled"), withholding = watch("withholdingEnabled"), type = watch("type"), paymentMethod = watch("paymentMethod"), paymentAccountCode = watch("paymentAccountCode");
  useEffect(() => { if (paymentMethod === "cash" && (!paymentAccountCode || paymentAccountCode === "1110")) setValue("paymentAccountCode", "1100"); if ((paymentMethod === "bank" || paymentMethod === "cheque") && (!paymentAccountCode || paymentAccountCode === "1100")) setValue("paymentAccountCode", "1110"); }, [paymentMethod, paymentAccountCode, setValue]);
  const submit = (value: Form) => { try { const selected = accounts.find((account) => account.code === value.paymentAccountCode), input: TransactionInput = { ...value, paymentAccountNameAr: selected?.nameAr, paymentAccountNameEn: selected?.nameEn }; setEntry(generateJournalEntry(input)); setNotice(""); } catch (error) { setNotice(error instanceof Error ? error.message : "Generation failed"); } };
  const parse = () => { const result = parseTransaction(natural); Object.entries(result.input).forEach(([key, value]) => { if (value !== undefined) setValue(key as keyof Form, value as never); }); setNotice((ar ? result.warningsAr : result.warningsEn).join(" ")); setTab("guided"); if (result.missingFields.length === 0) handleSubmit(submit)(); };
  return <div className="grid" style={{ gap: 22 }}><section className="card no-print"><div className="tabs"><button className={`btn ${tab === "text" ? "tab-active" : ""}`} onClick={() => setTab("text")}>{ar ? "اكتب العملية" : "Natural language"}</button><button className={`btn ${tab === "guided" ? "tab-active" : ""}`} onClick={() => setTab("guided")}>{ar ? "النموذج الموجّه" : "Guided form"}</button></div>
    {tab === "text" ? <div className="grid"><label>{ar ? "صف العملية المحاسبية" : "Describe the transaction"}<textarea rows={5} value={natural} onChange={(event) => setNatural(event.target.value)} placeholder={ar ? "مثال: دفعت مصروف صيانة 2,000 جنيه من البنك." : "Example: Paid 2,000 maintenance expense from the bank."}/></label><div className="actions">{[ar ? "بيع نقدي 10,000 وضريبة 14%" : "cash sale 10,000 VAT 14%", ar ? "شراء آجل 5,000" : "credit purchase 5,000", ar ? "مصروف صيانة 2,000 من البنك" : "maintenance expense 2,000 from bank"].map((example) => <button className="btn" key={example} onClick={() => setNatural(example)}>{example}</button>)}</div><button className="btn btn-primary" onClick={parse} disabled={!natural.trim()}>{ar ? "تحليل وإنشاء القيد" : "Analyze and generate"}</button></div>
      : <form className="grid" onSubmit={handleSubmit(submit)}><div className="grid three"><label>{ar ? "نوع العملية" : "Transaction type"}<select {...register("type")}>{transactions.map((transaction) => <option key={transaction.type} value={transaction.type}>{ar ? transaction.titleAr : transaction.titleEn}</option>)}</select></label><label>{ar ? "المبلغ" : "Amount"}<input type="number" step="0.01" {...register("amount")}/>{errors.amount && <small className="error">{ar ? "أدخل مبلغًا أكبر من صفر" : "Enter an amount greater than zero"}</small>}</label><label>{ar ? "العملة" : "Currency"}<select {...register("currency")}>{["EGP", "USD", "EUR", "SAR", "AED", "KWD", "QAR", "GBP"].map((currency) => <option key={currency}>{currency}</option>)}</select></label><label>{ar ? "التاريخ" : "Date"}<input type="date" {...register("date")}/></label><label>{ar ? "طريقة السداد أو التحصيل" : "Payment or receipt method"}<select {...register("paymentMethod")}><option value="cash">{ar ? "نقدي — صندوق" : "Cash"}</option><option value="bank">{ar ? "تحويل بنكي" : "Bank"}</option><option value="cheque">{ar ? "شيك — بنك" : "Cheque"}</option><option value="credit">{ar ? "آجل — عملاء/موردون" : "Credit"}</option></select></label><label>{ar ? "خصم تجاري" : "Commercial discount"}<input type="number" {...register("commercialDiscount")}/></label></div>
        {paymentMethod !== "credit" && <section className="card"><h3>{paymentMethod === "cash" ? <Banknote size={19}/> : <Landmark size={19}/>} {ar ? "الحساب الذي ستتحرك عليه الأموال" : "Treasury account affected"}</h3><label>{ar ? "اختر الصندوق أو الحساب البنكي" : "Select cash or bank account"}<select {...register("paymentAccountCode")}><option value="">—</option>{accounts.map((account) => <option key={account.id} value={account.code}>{account.code} — {ar ? account.nameAr : account.nameEn}</option>)}</select></label><p className="muted"><small>{ar ? "لن يتغير الرصيد الرسمي إلا بعد اعتماد القيد وترحيله." : "The official balance changes only after the entry is approved and posted."}</small></p></section>}
        <div className="actions"><label><input style={{ width: "auto" }} type="checkbox" {...register("vatEnabled")}/>{ar ? " تطبيق ضريبة قيمة مضافة" : " Apply VAT"}</label>{vat && <><label>{ar ? "النسبة %" : "Rate %"}<input type="number" {...register("vatRate")}/></label><label><input style={{ width: "auto" }} type="checkbox" {...register("vatIncluded")}/>{ar ? " المبلغ شامل الضريبة" : " VAT included"}</label></>}</div><div className="actions"><label><input style={{ width: "auto" }} type="checkbox" {...register("withholdingEnabled")}/>{ar ? " ضريبة خصم" : " Withholding tax"}</label>{withholding && <label>{ar ? "النسبة %" : "Rate %"}<input type="number" {...register("withholdingRate")}/></label>}</div>{type === "depreciation" && <div className="grid two"><label>{ar ? "العمر الإنتاجي" : "Useful life"}<input type="number" {...register("usefulLife")}/></label><label>{ar ? "القيمة التخريدية" : "Residual value"}<input type="number" {...register("residualValue")}/></label></div>}<label>{ar ? "ملاحظات" : "Notes"}<textarea {...register("notes")}/></label><div className="actions"><button className="btn btn-primary" type="submit">{ar ? "إنشاء القيد" : "Generate entry"}</button><button className="btn" type="button" onClick={() => { reset(); setEntry(undefined); }}>{ar ? "إعادة تعيين" : "Reset"}</button></div></form>}
    {notice && <p className="warning">{notice}</p>}</section>{entry && <JournalResult entry={entry} locale={locale}/>}</div>;
}
