import { roundCurrency } from "@/lib/accounting/calculations";
import type { GeneratedJournalEntry, VatAnalysis, VatConfiguration, VatPeriodFrequency, VatPeriodSummary } from "@/types";
import { isPostedJournalEntry } from "@/lib/accounting/journal";

export const DEFAULT_VAT_CONFIGURATION:VatConfiguration={inputAccountCodes:["1151"],outputAccountCodes:["2201"],nonDeductibleAccountCodes:["5119"],adjustmentAccountCodes:["2202"],defaultRate:14};
const posted=(entry:GeneratedJournalEntry)=>entry.workflowStatus==="approved"||isPostedJournalEntry(entry);
const valid=(entry:GeneratedJournalEntry)=>entry.workflowStatus!=="rejected";
const monthEnd=(year:number,month:number)=>new Date(Date.UTC(year,month,0)).toISOString().slice(0,10);

export function vatMovement(entry:GeneratedJournalEntry,configuration:VatConfiguration=DEFAULT_VAT_CONFIGURATION){let inputVat=0,outputVat=0,nonDeductibleInputVat=0,adjustments=0;for(const line of entry.lines){if(configuration.inputAccountCodes.includes(line.accountCode||""))inputVat+=line.debit-line.credit;if(configuration.outputAccountCodes.includes(line.accountCode||""))outputVat+=line.credit-line.debit;if(configuration.nonDeductibleAccountCodes.includes(line.accountCode||""))nonDeductibleInputVat+=line.debit-line.credit;if(configuration.adjustmentAccountCodes.includes(line.accountCode||""))adjustments+=line.credit-line.debit;}return{inputVat:roundCurrency(inputVat),outputVat:roundCurrency(outputVat),nonDeductibleInputVat:roundCurrency(nonDeductibleInputVat),adjustments:roundCurrency(adjustments)};}
function periodDefinition(year:number,frequency:VatPeriodFrequency,index:number){const months=frequency==="monthly"?1:3,startMonth=index*months+1,endMonth=startMonth+months-1,startDate=`${year}-${String(startMonth).padStart(2,"0")}-01`,arMonths=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];return{id:`${year}-${String(startMonth).padStart(2,"0")}`,startDate,endDate:monthEnd(year,endMonth),labelAr:frequency==="monthly"?`${arMonths[startMonth-1]} ${year}`:`الربع ${index+1} — ${year}`,labelEn:frequency==="monthly"?new Intl.DateTimeFormat("en",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${startDate}T00:00:00Z`)):`Q${index+1} ${year}`};}
export function analyzeVat(entries:GeneratedJournalEntry[],year:number,frequency:VatPeriodFrequency,configuration:VatConfiguration=DEFAULT_VAT_CONFIGURATION):VatAnalysis{const periods:VatPeriodSummary[]=Array.from({length:frequency==="monthly"?12:4},(_,index)=>({...periodDefinition(year,frequency,index),inputVat:0,outputVat:0,netVat:0,transactionCount:0,pendingInputVat:0,pendingOutputVat:0,nonDeductibleInputVat:0,adjustments:0}));for(const entry of entries.filter(valid)){if(!entry.date.startsWith(`${year}-`))continue;const month=Number(entry.date.slice(5,7));if(!month||month>12)continue;const period=periods[frequency==="monthly"?month-1:Math.floor((month-1)/3)],movement=vatMovement(entry,configuration);if(!Object.values(movement).some(Boolean))continue;if(posted(entry)){period.inputVat=roundCurrency(period.inputVat+movement.inputVat);period.outputVat=roundCurrency(period.outputVat+movement.outputVat);period.nonDeductibleInputVat=roundCurrency(period.nonDeductibleInputVat+movement.nonDeductibleInputVat);period.adjustments=roundCurrency(period.adjustments+movement.adjustments);period.transactionCount++;}else{period.pendingInputVat=roundCurrency(period.pendingInputVat+movement.inputVat);period.pendingOutputVat=roundCurrency(period.pendingOutputVat+movement.outputVat);}}for(const period of periods)period.netVat=roundCurrency(period.outputVat-period.inputVat+period.adjustments);const sum=(key:keyof Pick<VatPeriodSummary,"inputVat"|"outputVat"|"pendingInputVat"|"pendingOutputVat"|"nonDeductibleInputVat"|"adjustments">)=>roundCurrency(periods.reduce((total,period)=>total+period[key],0)),inputVat=sum("inputVat"),outputVat=sum("outputVat"),adjustments=sum("adjustments");return{year,frequency,inputVat,outputVat,netVat:roundCurrency(outputVat-inputVat+adjustments),pendingInputVat:sum("pendingInputVat"),pendingOutputVat:sum("pendingOutputVat"),nonDeductibleInputVat:sum("nonDeductibleInputVat"),adjustments,configuration,periods};}
export function entriesForVatPeriod(entries:GeneratedJournalEntry[],period:VatPeriodSummary,configuration:VatConfiguration=DEFAULT_VAT_CONFIGURATION){return entries.filter((entry)=>valid(entry)&&entry.date>=period.startDate&&entry.date<=period.endDate&&Object.values(vatMovement(entry,configuration)).some((value)=>value!==0));}
