"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, BookOpenCheck, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileText, GraduationCap, Lightbulb, ListChecks, RotateCcw, Target, Trophy, X } from "lucide-react";
import { academyLessonId } from "@/data/academy";
import { findAccountLearningGuide } from "@/data/account-learning-guide";
import { completeAcademyLesson, loadAcademyProgress } from "@/lib/academy/progress";
import type { AcademyCourse, AcademyLesson, Locale } from "@/types";

export function LessonViewer({ locale, course, lesson }: { locale: Locale; course: AcademyCourse; lesson: AcademyLesson }) {
  const ar = locale === "ar", lessons = course.modules.flatMap((module) => module.lessons), index = lessons.findIndex((item) => item.slug === lesson.slug);
  const id = academyLessonId(course.slug, lesson.slug), previous = lessons[index - 1], next = lessons[index + 1];
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [completed, setCompleted] = useState(false);
  const [completedIds, setCompletedIds] = useState<string[]>([]);
  useEffect(() => { const stored = loadAcademyProgress(); setCompleted(stored.completedLessonIds.includes(id)); setCompletedIds(stored.completedLessonIds); }, [id]);
  const score = useMemo(() => lesson.quiz.length ? Math.round(lesson.quiz.filter((question, questionIndex) => answers[questionIndex] === question.correctIndex).length / lesson.quiz.length * 100) : 100, [answers, lesson.quiz]);
  const finish = () => { setSubmitted(true); if (Object.keys(answers).length === lesson.quiz.length) { const updated = completeAcademyLesson(id, score); setCompleted(true); setCompletedIds(updated.completedLessonIds); } };
  const objectives = ar ? lesson.objectivesAr : lesson.objectivesEn, steps = ar ? lesson.stepsAr : lesson.stepsEn, mistakes = ar ? lesson.mistakesAr : lesson.mistakesEn;

  return <main className="academy-page lesson-page min-h-screen bg-daftar-bg"><div className="container lesson-shell grid items-start justify-center gap-7 py-10 lg:grid-cols-[275px_minmax(0,800px)] lg:pb-20">
    <aside className="lesson-sidebar overflow-hidden rounded-2xl border border-daftar-line bg-daftar-card lg:sticky lg:top-[92px] lg:max-h-[calc(100vh-115px)] lg:overflow-auto">
      <Link className="lesson-back" href={`/${locale}/academy/${course.slug}`}><GraduationCap/>{ar ? "العودة للمسار" : "Back to track"}</Link>
      <div className="lesson-side-course"><small>{ar ? "المسار" : "Track"}</small><b>{ar ? course.titleAr : course.titleEn}</b><div className="academy-progress-track"><i style={{width:`${(index + (completed ? 1 : 0)) / lessons.length * 100}%`}}/></div></div>
      <nav>{lessons.map((item, itemIndex) => { const itemDone = completedIds.includes(academyLessonId(course.slug, item.slug)); return <Link key={item.slug} className={`${item.slug === lesson.slug ? "active" : ""} ${itemDone ? "done" : ""}`} href={`/${locale}/academy/${course.slug}/${item.slug}`}><span>{itemDone ? <Check/> : itemIndex + 1}</span><b>{ar ? item.titleAr : item.titleEn}</b></Link>; })}</nav>
    </aside>

    <article className="lesson-content min-w-0">
      <div className="lesson-heading flex flex-col justify-between gap-5 border-b border-daftar-line py-7 sm:flex-row"><div><span>{ar ? `الدرس ${index + 1} من ${lessons.length}` : `Lesson ${index + 1} of ${lessons.length}`}</span><h1>{ar ? lesson.titleAr : lesson.titleEn}</h1><p>{ar ? lesson.summaryAr : lesson.summaryEn}</p></div><div className="lesson-time"><Clock3/>{lesson.duration} {ar ? "دقيقة" : "minutes"}</div></div>

      <section className="lesson-block objectives-block mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><div className="lesson-block-title"><Target/><div><span>{ar ? "هتتعلم إيه؟" : "Learning objectives"}</span><h2>{ar ? "بعد الدرس ده هتقدر" : "After this lesson you can"}</h2></div></div><ul>{objectives.map((item) => <li key={item}><CheckCircle2/>{item}</li>)}</ul></section>

      <section className="lesson-rule"><Lightbulb/><div><span>{ar ? "القاعدة الذهبية" : "Golden rule"}</span><p>{ar ? lesson.ruleAr : lesson.ruleEn}</p></div></section>

      <section className="lesson-block mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><div className="lesson-block-title"><ListChecks/><div><span>{ar ? "طريقة الحل" : "Method"}</span><h2>{ar ? "امشِ على الخطوات دي" : "Follow these steps"}</h2></div></div><ol className="lesson-steps">{steps.map((step, stepIndex) => <li key={step}><span>{stepIndex + 1}</span><p>{step}</p></li>)}</ol></section>

      <section className="mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><div className="lesson-block-title"><FileText/><div><span>{ar?"مكان الدرس في الشغل":"Where this fits at work"}</span><h2>{ar?"من المستند إلى القوائم المالية":"From source document to statements"}</h2></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[
        [ar?"1. المستند":"1. Source document",ar?"تأكد من وجود فاتورة أو سند أو عقد أو إذن يثبت العملية.":"Verify the invoice, voucher, contract, or authorization."],
        [ar?"2. المراجعة":"2. Review",ar?"راجع الطرف والتاريخ والمبلغ والضريبة والاعتماد وعدم التكرار.":"Review party, date, amount, tax, approval, and duplicates."],
        [ar?"3. تحليل الحسابات":"3. Account analysis",ar?"حدد كل حساب تأثر، نوعه، وهل زاد أم قل، ثم طبّق طبيعته.":"Identify each account, its type, movement, and normal balance."],
        [ar?"4. القيد والترحيل":"4. Entry and posting",ar?"أنشئ قيدًا متوازنًا ثم رحّل كل سطر إلى أستاذ الحساب.":"Create a balanced entry and post each line to the ledger."],
        [ar?"5. المراجعة والتسوية":"5. Reconcile",ar?"طابق الرصيد مع المستند والطرف والبنك أو المخزون حسب العملية.":"Reconcile the balance to documents and the relevant subledger."],
        [ar?"6. القوائم والإقفال":"6. Statements and close",ar?"يظهر الرصيد في ميزان المراجعة ثم قائمته الصحيحة ويُراجع قبل الإقفال.":"The balance reaches the trial balance and the correct statement."],
      ].map(([title,text])=><article className="rounded-xl border border-daftar-line p-4" key={title}><b className="text-daftar-primary">{title}</b><p className="mt-2 text-sm leading-7 text-daftar-muted">{text}</p></article>)}</div>
      {lesson.example && <div className="mt-5 rounded-xl bg-[color-mix(in_srgb,var(--primary)_5%,var(--card))] p-4"><b>{ar?"مستندات العملية دي تحديدًا":"Documents for this transaction"}</b><p className="mt-2 text-sm leading-7 text-daftar-muted">{Array.from(new Set(lesson.example.lines.map((line)=>findAccountLearningGuide(line.accountAr,line.accountEn)?.documentsAr).filter(Boolean))).join(" — ") || (ar?"المستند المؤيد للعملية وسجل الاعتماد.":"Supporting document and approval trail.")}</p></div>}
      </section>

      {lesson.example && <section className="lesson-block lesson-example mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><div className="lesson-block-title"><FileText/><div><span>{ar ? "مثال من الشغل" : "Work example"}</span><h2>{ar ? lesson.example.titleAr : lesson.example.titleEn}</h2></div></div><p className="example-scenario">{ar ? lesson.example.scenarioAr : lesson.example.scenarioEn}</p><div className="entry-table-wrap"><table className="entry-table"><thead><tr><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "مدين" : "Debit"}</th><th>{ar ? "دائن" : "Credit"}</th></tr></thead><tbody>{lesson.example.lines.map((line) => <tr key={`${line.accountEn}-${line.debit}-${line.credit}`}><td><b>{ar ? line.accountAr : line.accountEn}</b>{ar && <small>{line.accountEn}</small>}</td><td>{line.debit ? line.debit.toLocaleString(ar ? "ar-EG" : "en-US") : "—"}</td><td>{line.credit ? line.credit.toLocaleString(ar ? "ar-EG" : "en-US") : "—"}</td></tr>)}</tbody><tfoot><tr><th>{ar ? "الإجمالي" : "Total"}</th><th>{lesson.example.lines.reduce((sum, line) => sum + line.debit, 0).toLocaleString()}</th><th>{lesson.example.lines.reduce((sum, line) => sum + line.credit, 0).toLocaleString()}</th></tr></tfoot></table></div><div className="example-impact"><b>{ar ? "تأثير العملية على القوائم" : "Financial statement impact"}</b><ul>{(ar ? lesson.example.impactAr : lesson.example.impactEn).map((impact) => <li key={impact}><ArrowImpact/>{impact}</li>)}</ul></div></section>}

      {lesson.example && <section className="mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><div className="lesson-block-title"><BookOpenCheck/><div><span>{ar?"ليه الحساب مدين أو دائن؟":"Why debit or credit?"}</span><h2>{ar?"تحليل طبيعة حسابات القيد":"Entry account analysis"}</h2></div></div><div className="grid gap-4">{lesson.example.lines.map((line)=>{const guide=findAccountLearningGuide(line.accountAr,line.accountEn);const increased=line.debit>0?(guide?.increaseSideAr==="مدين"):(guide?.increaseSideAr==="دائن");return <article className="grid gap-4 rounded-2xl border border-daftar-line p-4 lg:grid-cols-[190px_120px_1fr]" key={`analysis-${line.accountEn}`}><div><b className="block">{ar?line.accountAr:line.accountEn}</b><small className="mt-1 block text-daftar-muted">{guide?.categoryAr ?? (ar?"حساب محاسبي":"Account")}</small></div><div><span className={`inline-flex rounded-full px-3 py-1 text-xs font-black ${line.debit?"bg-blue-100 text-blue-800":"bg-emerald-100 text-emerald-800"}`}>{line.debit?(ar?"مدين":"Debit"):(ar?"دائن":"Credit")}</span><small className="mt-2 block text-daftar-muted">{increased?(ar?"الحساب زاد":"Account increased"):(ar?"الحساب قل":"Account decreased")}</small></div><div className="grid gap-2 text-sm leading-6"><p><b>{ar?"السبب: ":"Reason: "}</b>{guide ? (increased?guide.increaseEffectAr:guide.decreaseEffectAr) : (ar?"تم تطبيق قاعدة طبيعة الحساب حسب نوعه وحركته.":"Normal-balance rule applied.")}</p>{guide&&<p className="text-daftar-muted"><b className="text-daftar-text">{ar?"يظهر في: ":"Appears in: "}</b>{guide.statementAr}</p>}</div></article>})}</div><Link className="btn mt-5" href={`/${locale}/academy/account-guide`}>{ar?"افتح جدول طبيعة كل الحسابات":"Open full account guide"}{ar?<ArrowLeft/>:<ArrowRight/>}</Link></section>}

      <section className="lesson-block mistakes-block mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><div className="lesson-block-title"><AlertTriangle/><div><span>{ar ? "خلي بالك" : "Watch out"}</span><h2>{ar ? "أخطاء شائعة" : "Common mistakes"}</h2></div></div><ul>{mistakes.map((mistake) => <li key={mistake}><X/>{mistake}</li>)}</ul></section>

      <details className="lesson-block quiz-block group mt-6 rounded-2xl border border-daftar-line bg-daftar-card p-5 sm:p-8"><summary className="flex list-none items-center justify-between gap-4"><span className="flex items-center gap-3"><Trophy className="text-daftar-primary"/><span><small className="block font-black text-daftar-primary">{ar?"مراجعة اختيارية بعد الشرح":"Optional review after studying"}</small><b className="mt-1 block text-lg">{ar?"افتح اختبارًا قصيرًا لو حابب تتأكد من فهمك":"Open a short check only when you are ready"}</b></span></span><span className="rounded-full bg-[color-mix(in_srgb,var(--primary)_8%,var(--card))] px-3 py-1 text-sm font-black text-daftar-primary group-open:hidden">{ar?"فتح":"Open"}</span></summary><div className="mt-5 border-t border-daftar-line pt-3">{lesson.quiz.map((question, questionIndex) => <div className="quiz-question" key={question.questionEn}><b>{questionIndex + 1}. {ar ? question.questionAr : question.questionEn}</b><div className="quiz-choices grid grid-cols-1 gap-3 sm:grid-cols-2">{(ar ? question.choicesAr : question.choicesEn).map((choice, choiceIndex) => { const selected = answers[questionIndex] === choiceIndex, state = submitted ? choiceIndex === question.correctIndex ? "correct" : selected ? "wrong" : "" : selected ? "selected" : ""; return <button type="button" className={state} key={choice} onClick={() => !submitted && setAnswers((value) => ({...value, [questionIndex]: choiceIndex}))}><span>{String.fromCharCode(65 + choiceIndex)}</span>{choice}{submitted && choiceIndex === question.correctIndex && <CheckCircle2/>}{submitted && selected && choiceIndex !== question.correctIndex && <X/>}</button>; })}</div>{submitted && <p className={answers[questionIndex] === question.correctIndex ? "quiz-explanation correct" : "quiz-explanation"}>{answers[questionIndex] === question.correctIndex ? <CheckCircle2/> : <Lightbulb/>}{ar ? question.explanationAr : question.explanationEn}</p>}</div>)}
        {!submitted ? <button className="btn btn-primary quiz-submit" onClick={finish}>{ar ? "اعرض النتيجة وأكمل الدرس" : "Show result and complete lesson"}</button> : <div className="quiz-result"><Trophy/><div><span>{ar ? "نتيجتك" : "Your result"}</span><b>{score}%</b><p>{score >= 70 ? (ar ? "ممتاز — الدرس اتسجل مكتمل." : "Great — lesson marked complete.") : (ar ? "راجع الشرح وحاول مرة ثانية." : "Review and try again.")}</p></div><button className="btn" onClick={() => {setAnswers({});setSubmitted(false);}}><RotateCcw/>{ar ? "إعادة الاختبار" : "Retry"}</button></div>}
      </div></details>

      <nav className="lesson-navigation">{previous ? <Link href={`/${locale}/academy/${course.slug}/${previous.slug}`}>{ar ? <ChevronRight/> : <ChevronLeft/>}<span><small>{ar ? "الدرس السابق" : "Previous lesson"}</small><b>{ar ? previous.titleAr : previous.titleEn}</b></span></Link> : <span/>}{next ? <Link className="next" href={`/${locale}/academy/${course.slug}/${next.slug}`}><span><small>{ar ? "الدرس التالي" : "Next lesson"}</small><b>{ar ? next.titleAr : next.titleEn}</b></span>{ar ? <ChevronLeft/> : <ChevronRight/>}</Link> : <Link className="next" href={`/${locale}/academy`}><span><small>{ar ? "أكملت المسار" : "Track complete"}</small><b>{ar ? "استكشف مسارًا جديدًا" : "Explore another track"}</b></span>{ar ? <ArrowLeft/> : <ArrowRight/>}</Link>}</nav>
    </article>
  </div></main>;
}

function ArrowImpact() { return <span className="impact-arrow">↗</span>; }
