"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Eye, Plus, Search, Trash2, WalletCards } from "lucide-react";
import { buildPartyBalances, itemOutstanding } from "@/lib/parties/aging";
import { createCustomerCollection, createCustomerInvoice } from "@/lib/parties/receivables";
import { duplicateInvoice, removedUsedParty } from "@/lib/accounting/integrity";
import { loadOpenItems, loadParties, saveOpenItems, saveParties } from "@/lib/storage/parties";
import { generateJournalEntry } from "@/rules";
import { loadAccounts, saveEntry } from "@/lib/storage/accounting";
import type { Locale, OpenItem, Party, PartyType } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
const addDays = (date: string, days: number) => { const value = new Date(date); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); };

export function PartyCenter({ locale }: { locale: Locale }) {
  const ar = locale === "ar", [parties, setParties] = useState<Party[]>([]), [items, setItems] = useState<OpenItem[]>([]), [tab, setTab] = useState<PartyType>("customer"), [query, setQuery] = useState(""), [message, setMessage] = useState("");
  const [draft, setDraft] = useState({ nameAr: "", nameEn: "", taxNumber: "", phone: "", email: "", creditDays: 30, creditLimit: 0 });
  const [invoice, setInvoice] = useState({ partyId: "", invoiceNumber: "", invoiceDate: today(), amount: 0, currency: "EGP" });
  useEffect(() => { setParties(loadParties()); setItems(loadOpenItems()); }, []);
  const commitParties = (next: Party[]) => { setParties(next); saveParties(next); }, commitItems = (next: OpenItem[]) => { setItems(next); saveOpenItems(next); };
  const addParty = () => { if (!draft.nameAr || !draft.nameEn) return setMessage(ar ? "اكتب اسم الطرف بالعربية والإنجليزية." : "Enter Arabic and English names."); const sameType = parties.filter((party) => party.type === tab), party: Party = { id: crypto.randomUUID(), type: tab, code: `${tab === "customer" ? "C" : "S"}-${String(sameType.length + 1).padStart(4, "0")}`, nameAr: draft.nameAr, nameEn: draft.nameEn, taxNumber: draft.taxNumber || undefined, phone: draft.phone || undefined, email: draft.email || undefined, creditDays: draft.creditDays, creditLimit: draft.creditLimit || undefined, accountCode: `${tab === "customer" ? "112" : "210"}${sameType.length + 1}`, active: true, createdAt: new Date().toISOString() }; commitParties([...parties, party]); setDraft({ nameAr: "", nameEn: "", taxNumber: "", phone: "", email: "", creditDays: 30, creditLimit: 0 }); setMessage(ar ? "تم إنشاء الطرف وملف 360° والحساب الفرعي." : "Party, 360° profile, and subaccount created."); };
  const addInvoice = () => { const party = parties.find((item) => item.id === invoice.partyId); if (!party || invoice.amount <= 0 || !invoice.invoiceNumber) return setMessage(ar ? "أكمل بيانات الفاتورة." : "Complete the invoice data."); if (duplicateInvoice(items, party.id, invoice.invoiceNumber)) return setMessage(ar ? "رقم الفاتورة مسجل سابقًا لهذا الطرف." : "This invoice number already exists for the party."); if (party.type === "customer") { try { const result = createCustomerInvoice(party, { invoiceNumber: invoice.invoiceNumber, invoiceDate: invoice.invoiceDate, dueDate: addDays(invoice.invoiceDate, party.creditDays), description: `فاتورة ${invoice.invoiceNumber}`, netAmount: invoice.amount, vatRate: 0, currency: invoice.currency, revenueAccountCode: "4100" }, items, loadAccounts()), entry = saveEntry(result.entry); commitItems([{ ...result.item, linkedEntryId: entry.id, invoiceEntryId: entry.id }, ...items]); setInvoice({ ...invoice, invoiceNumber: "", amount: 0 }); setMessage(ar ? `تمت إضافة الفاتورة وإنشاء مسودة القيد ${entry.entryNumber}.` : `Invoice added with draft ${entry.entryNumber}.`); } catch (cause) { setMessage(cause instanceof Error ? cause.message : String(cause)); } return; } const generated = generateJournalEntry({ type: "credit-purchase", amount: invoice.amount, date: invoice.invoiceDate, currency: invoice.currency, paymentMethod: "credit", supplier: party.nameAr, notes: `${invoice.invoiceNumber} — ${party.nameAr}` }), entry = saveEntry({ ...generated, workflowStatus: "draft", partyId: party.id, partyName: party.nameAr, reference: invoice.invoiceNumber }), item: OpenItem = { id: crypto.randomUUID(), partyId: party.id, kind: "payable", invoiceNumber: invoice.invoiceNumber, invoiceDate: invoice.invoiceDate, dueDate: addDays(invoice.invoiceDate, party.creditDays), currency: invoice.currency, amount: invoice.amount, paid: 0, status: "open", linkedEntryId: entry.id, invoiceEntryId: entry.id, createdAt: new Date().toISOString() }; commitItems([item, ...items]); setInvoice({ ...invoice, invoiceNumber: "", amount: 0 }); setMessage(ar ? `تمت إضافة الفاتورة وإنشاء مسودة القيد ${entry.entryNumber}.` : `Invoice added with draft ${entry.entryNumber}.`); };
  const pay = (item: OpenItem) => { const outstanding = itemOutstanding(item), text = prompt(ar ? `أدخل قيمة الدفعة، المتبقي ${outstanding}` : `Enter payment, outstanding ${outstanding}`, String(outstanding)); if (!text) return; const value = Math.min(outstanding, Math.max(0, Number(text))); if (!value) return; const party = parties.find((current) => current.id === item.partyId); if (!party) return; if (party.type === "customer") { const result = createCustomerCollection(party, item, { date: today(), amount: value, paymentAccountCode: "1110", reference: item.invoiceNumber }, loadAccounts()), entry = saveEntry(result.entry), updated = { ...result.item, collectionEntryIds: [...(item.collectionEntryIds || []), entry.id], allocations: [...(item.allocations || []), { ...result.allocation, linkedEntryId: entry.id }] }; commitItems(items.map((current) => current.id === item.id ? updated : current)); setMessage(ar ? "تم تسجيل التحصيل وإنشاء مسودة قيد مرتبطة بالفاتورة." : "Collection and linked draft entry created."); return; } const entry = saveEntry({ ...generateJournalEntry({ type: "supplier-payment", amount: value, date: today(), currency: item.currency, paymentMethod: "bank", supplier: party.nameAr, notes: `${item.invoiceNumber} — ${party.nameAr}` }), workflowStatus: "draft", partyId: party.id, partyName: party.nameAr }); const paid = item.paid + value; commitItems(items.map((current) => current.id === item.id ? { ...current, paid, status: paid >= item.amount ? "paid" : "partial", collectionEntryIds: [...(current.collectionEntryIds || []), entry.id] } : current)); setMessage(ar ? "تم تسجيل الدفعة وإنشاء مسودة قيد وبطاقة عملية." : "Payment, draft entry, and operation dossier created."); };
  const removeParty = (party: Party) => { const next = parties.filter((item) => item.id !== party.id); if (removedUsedParty(parties, next, items)) return setMessage(ar ? "لا يمكن حذف طرف مرتبط بفواتير؛ يمكنك إيقافه بدلًا من ذلك." : "A party linked to invoices cannot be deleted; deactivate it instead."); commitParties(next); };
  const filtered = parties.filter((party) => party.type === tab && `${party.nameAr} ${party.nameEn} ${party.code}`.toLowerCase().includes(query.toLowerCase())), balances = useMemo(() => buildPartyBalances(filtered, items, today()), [filtered, items]), total = balances.reduce((sum, balance) => sum + balance.aging.total, 0);
  return <div className="grid">
    <section className="grid four"><Metric title={ar ? "عدد الأطراف" : "Parties"} value={filtered.length} /><Metric title={ar ? "إجمالي الرصيد" : "Total balance"} value={total.toLocaleString()} /><Metric title={ar ? "متأخر أكثر من 90 يومًا" : "Over 90 days"} value={balances.reduce((sum, balance) => sum + balance.aging.over90, 0).toLocaleString()} /><Metric title={ar ? "فواتير مفتوحة" : "Open invoices"} value={balances.reduce((sum, balance) => sum + balance.openItems, 0)} /></section>
    <section className="card"><div className="tabs"><button className={`btn ${tab === "customer" ? "tab-active" : ""}`} onClick={() => { setTab("customer"); setInvoice({ ...invoice, partyId: "" }); }}>{ar ? "العملاء" : "Customers"}</button><button className={`btn ${tab === "supplier" ? "tab-active" : ""}`} onClick={() => { setTab("supplier"); setInvoice({ ...invoice, partyId: "" }); }}>{ar ? "الموردون" : "Suppliers"}</button></div><h2>{ar ? "إضافة طرف" : "Add party"}</h2><div className="grid four"><label>{ar ? "الاسم بالعربية" : "Arabic name"}<input value={draft.nameAr} onChange={(event) => setDraft({ ...draft, nameAr: event.target.value })}/></label><label>{ar ? "الاسم بالإنجليزية" : "English name"}<input value={draft.nameEn} onChange={(event) => setDraft({ ...draft, nameEn: event.target.value })}/></label><label>{ar ? "الرقم الضريبي" : "Tax number"}<input value={draft.taxNumber} onChange={(event) => setDraft({ ...draft, taxNumber: event.target.value })}/></label><label>{ar ? "رقم واتساب" : "WhatsApp number"}<input value={draft.phone} onChange={(event) => setDraft({ ...draft, phone: event.target.value })}/></label><label>{ar ? "البريد الإلكتروني" : "Email"}<input type="email" value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })}/></label><label>{ar ? "أيام الائتمان" : "Credit days"}<input type="number" value={draft.creditDays} onChange={(event) => setDraft({ ...draft, creditDays: Number(event.target.value) })}/></label><label>{ar ? "حد الائتمان" : "Credit limit"}<input type="number" value={draft.creditLimit || ""} onChange={(event) => setDraft({ ...draft, creditLimit: Number(event.target.value) })}/></label></div><button className="btn btn-primary" onClick={addParty}><Plus size={16}/>{ar ? "إضافة وإنشاء ملف 360°" : "Add with 360° profile"}</button>{message && <p className="warning">{message}</p>}</section>
    <section className="card"><h2>{ar ? "إضافة فاتورة مفتوحة" : "Add open invoice"}</h2><div className="grid four"><label>{ar ? "الطرف" : "Party"}<select value={invoice.partyId} onChange={(event) => setInvoice({ ...invoice, partyId: event.target.value })}><option value="">—</option>{parties.filter((party) => party.type === tab).map((party) => <option key={party.id} value={party.id}>{ar ? party.nameAr : party.nameEn}</option>)}</select></label><label>{ar ? "رقم الفاتورة" : "Invoice number"}<input value={invoice.invoiceNumber} onChange={(event) => setInvoice({ ...invoice, invoiceNumber: event.target.value })}/></label><label>{ar ? "التاريخ" : "Date"}<input type="date" value={invoice.invoiceDate} onChange={(event) => setInvoice({ ...invoice, invoiceDate: event.target.value })}/></label><label>{ar ? "المبلغ" : "Amount"}<input type="number" value={invoice.amount || ""} onChange={(event) => setInvoice({ ...invoice, amount: Number(event.target.value) })}/></label></div><button className="btn btn-primary" onClick={addInvoice}><Plus size={16}/>{ar ? "إضافة الفاتورة" : "Add invoice"}</button></section>
    <section className="card"><label><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={ar ? "بحث بالاسم أو الكود" : "Search name or code"}/></label><div className="table-wrap section"><table><thead><tr><th>{ar ? "الطرف" : "Party"}</th><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "غير مستحق" : "Current"}</th><th>1-30</th><th>31-60</th><th>61-90</th><th>+90</th><th>{ar ? "الإجمالي" : "Total"}</th><th>{ar ? "الإجراء" : "Action"}</th></tr></thead><tbody>{balances.map(({ party, aging }) => <tr key={party.id}><td><b>{ar ? party.nameAr : party.nameEn}</b><br/><small>{party.code}</small></td><td>{party.accountCode}</td><td>{aging.current || "—"}</td><td>{aging.days30 || "—"}</td><td>{aging.days60 || "—"}</td><td>{aging.days90 || "—"}</td><td>{aging.over90 || "—"}</td><td><b>{aging.total}</b></td><td><div className="actions"><Link className="btn btn-primary" href={`/${locale}/parties/${party.id}`}><Eye size={15}/>{ar ? "ملف 360°" : "360° profile"}</Link><button className="btn btn-danger" onClick={() => removeParty(party)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></section>
    <section className="card"><h2><WalletCards size={20}/>{ar ? "الفواتير والتحصيلات والمدفوعات" : "Invoices and payments"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "الفاتورة" : "Invoice"}</th><th>{ar ? "الطرف" : "Party"}</th><th>{ar ? "الاستحقاق" : "Due"}</th><th>{ar ? "المبلغ" : "Amount"}</th><th>{ar ? "المدفوع" : "Paid"}</th><th>{ar ? "المتبقي" : "Outstanding"}</th><th></th></tr></thead><tbody>{items.filter((item) => parties.find((party) => party.id === item.partyId)?.type === tab).map((item) => { const party = parties.find((current) => current.id === item.partyId); return <tr key={item.id}><td>{item.invoiceNumber}</td><td>{party ? (ar ? party.nameAr : party.nameEn) : "—"}</td><td>{item.dueDate}</td><td>{item.amount}</td><td>{item.paid}</td><td>{itemOutstanding(item)}</td><td><div className="actions">{itemOutstanding(item) > 0 && <button className="btn btn-primary" onClick={() => pay(item)}>{tab === "customer" ? (ar ? "تسجيل تحصيل" : "Collect") : (ar ? "تسجيل سداد" : "Pay")}</button>}{party && <Link className="btn" href={`/${locale}/parties/${party.id}`}>{ar ? "فتح الملف" : "Open profile"}</Link>}</div></td></tr>; })}</tbody></table></div></section>
  </div>;
}

function Metric({ title, value }: { title: string; value: string | number }) { return <div className="card"><span className="muted">{title}</span><div className="impact">{value}</div></div>; }
