"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpenCheck, CalendarClock, FileText, Mail, MessageCircle, Phone, Printer, Save, WalletCards } from "lucide-react";
import { buildPartyProfile, whatsappChatUrl } from "@/lib/parties/profile";
import { itemOutstanding } from "@/lib/parties/aging";
import { loadBusinessDocuments } from "@/lib/storage/business-documents";
import { buildCustomerStatement, createCustomerCollection, customerEntries } from "@/lib/parties/receivables";
import { loadOpenItems, loadParties, saveOpenItems, saveParties } from "@/lib/storage/parties";
import { loadAccounts, loadEntries, saveEntry } from "@/lib/storage/accounting";
import { JOURNAL_STATUS_LABELS } from "@/lib/accounting/journal";
import { generateJournalEntry } from "@/rules";
import type { GeneratedJournalEntry, Locale, OpenItem, Party } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
const money = (value: number, locale: Locale) => value.toLocaleString(locale === "ar" ? "ar-EG" : "en-US", { maximumFractionDigits: 2 });

export function PartyProfile360({ id, locale }: { id: string; locale: Locale }) {
  const ar = locale === "ar", [parties, setParties] = useState<Party[]>([]), [items, setItems] = useState<OpenItem[]>([]), [entries, setEntries] = useState<GeneratedJournalEntry[]>([]), [loaded, setLoaded] = useState(false), [message, setMessage] = useState(""), [notice, setNotice] = useState("");
  useEffect(() => { setParties(loadParties()); setItems(loadOpenItems()); setEntries(loadEntries()); setLoaded(true); }, []);
  const party = parties.find((item) => item.id === id), documents = useMemo(() => loaded ? loadBusinessDocuments() : [], [loaded]);
  const profile = useMemo(() => party ? buildPartyProfile(party, items, documents, today()) : undefined, [party, items, documents]);
  useEffect(() => { if (!profile || message) return; setMessage(ar ? `مرحبًا ${profile.party.nameAr}، نرجو مراجعة الرصيد الحالي بقيمة ${money(profile.outstanding, locale)} جنيه، والفواتير المستحقة. شكرًا لتعاونكم.` : `Hello ${profile.party.nameEn}, please review the current outstanding balance of ${money(profile.outstanding, locale)} EGP and the due invoices. Thank you.`); }, [ar, locale, message, profile]);
  if (!loaded) return <section className="card">{ar ? "جارٍ تحميل ملف الطرف…" : "Loading party profile…"}</section>;
  if (!party || !profile) return <section className="card warning">{ar ? "لم يتم العثور على العميل أو المورد." : "Customer or supplier was not found."}</section>;
  const updateParty = (patch: Partial<Party>) => { const next = parties.map((item) => item.id === party.id ? { ...item, ...patch } : item); setParties(next); saveParties(next); setNotice(ar ? "تم حفظ بيانات التواصل والائتمان." : "Contact and credit details saved."); };
  const recordPayment = (item: OpenItem) => { const outstanding = itemOutstanding(item), input = prompt(ar ? `أدخل قيمة ${party.type === "customer" ? "التحصيل" : "السداد"}، المتبقي ${outstanding}` : `Enter payment amount, outstanding ${outstanding}`, String(outstanding)); if (!input) return; const value = Math.min(outstanding, Math.max(0, Number(input))); if (!value) return; if (party.type === "customer") { const result = createCustomerCollection(party, item, { date: today(), amount: value, paymentAccountCode: "1110", reference: item.invoiceNumber }, loadAccounts()), entry = saveEntry(result.entry), nextItem = { ...result.item, collectionEntryIds: [...(item.collectionEntryIds || []), entry.id], allocations: [...(item.allocations || []), { ...result.allocation, linkedEntryId: entry.id }] }, next = items.map((current) => current.id === item.id ? nextItem : current); setEntries([entry, ...entries]); setItems(next); saveOpenItems(next); setNotice(ar ? "تم تسجيل التحصيل وإنشاء مسودة قيد مرتبطة بالفاتورة." : "Collection recorded with a linked draft entry."); return; } const entry = saveEntry({ ...generateJournalEntry({ type: "supplier-payment", amount: value, date: today(), currency: item.currency, paymentMethod: "bank", supplier: party.nameAr, notes: `${item.invoiceNumber} — ${party.nameAr}` }), workflowStatus: "draft", partyId: party.id, partyName: party.nameAr }); const paid = item.paid + value, next = items.map((current) => current.id === item.id ? { ...current, paid, status: paid >= current.amount ? "paid" as const : "partial" as const, linkedEntryId: entry.id } : current); setEntries([entry, ...entries]); setItems(next); saveOpenItems(next); setNotice(ar ? "تم تسجيل الحركة وإنشاء مسودة قيد، ويمكن فتح بطاقة العملية." : "Payment recorded and a draft entry was created."); };
  const openWhatsapp = () => { const url = whatsappChatUrl(party.phone || "", message); if (!url) return setNotice(ar ? "اكتب رقم واتساب أولًا واحفظه." : "Enter and save a WhatsApp number first."); window.open(url, "_blank", "noopener,noreferrer"); };
  const utilization = profile.creditUtilization ?? 0, currency = profile.items[0]?.currency || profile.documents[0]?.currency || "EGP", statement = party.type === "customer" ? buildCustomerStatement(party.id, items) : [], linkedEntries = customerEntries(party.id, entries);
  return <div className="grid">
    <section className="card"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="actions"><span className="badge">{party.type === "customer" ? (ar ? "عميل" : "Customer") : (ar ? "مورد" : "Supplier")}</span><span className="badge">{party.code}</span><span className={party.active ? "badge" : "badge error"}>{party.active ? (ar ? "نشط" : "Active") : (ar ? "موقوف" : "Inactive")}</span></div><h1>{ar ? party.nameAr : party.nameEn}</h1><p className="muted">{party.accountCode} · {party.taxNumber || (ar ? "لا يوجد رقم ضريبي" : "No tax number")}</p></div><div className="actions no-print"><Link className="btn" href={`/${locale}/${party.type === "customer" ? "receivables" : "parties"}`}><ArrowLeft size={16}/>{party.type === "customer" ? (ar ? "حسابات العملاء" : "Customer receivables") : (ar ? "حسابات الموردين" : "Supplier payables")}</Link><button className="btn" onClick={() => window.print()}><Printer size={16}/>{ar ? "طباعة / PDF" : "Print / PDF"}</button></div></div></section>
    <section className="grid four"><Metric title={ar ? "الرصيد الحالي" : "Current balance"} value={`${money(profile.outstanding, locale)} ${currency}`} /><Metric title={ar ? "إجمالي الفواتير" : "Total invoices"} value={`${money(profile.invoiced, locale)} ${currency}`} /><Metric title={ar ? "المسدد" : "Paid"} value={`${money(profile.paid, locale)} ${currency}`} /><Metric title={ar ? "المتأخر" : "Overdue"} value={`${money(profile.overdue, locale)} ${currency}`} danger={profile.overdue > 0} /></section>
    <section className="grid three"><article className="card"><h2>{ar ? "ملخص التعامل" : "Relationship summary"}</h2><Info title={ar ? (party.type === "customer" ? "صافي المبيعات المسجلة" : "صافي المشتريات المسجلة") : "Net recorded business volume"} value={`${money(profile.netBusinessVolume, locale)} ${currency}`} /><Info title={ar ? "آخر تعامل" : "Last transaction"} value={profile.lastTransactionDate || "—"} /><Info title={ar ? "الاستحقاق القادم" : "Next due date"} value={profile.nextDueDate || "—"} /><Info title={ar ? "متوسط فترة الائتمان" : "Average credit term"} value={`${profile.averageCreditDays} ${ar ? "يوم" : "days"}`} /></article>
      <article className="card"><h2>{ar ? "حد الائتمان والمخاطر" : "Credit and risk"}</h2><label>{ar ? "حد الائتمان" : "Credit limit"}<input type="number" value={party.creditLimit || ""} onChange={(event) => setParties(parties.map((item) => item.id === party.id ? { ...item, creditLimit: Number(event.target.value) || undefined } : item))} onBlur={() => saveParties(parties)} /></label><p>{ar ? "استهلاك الحد" : "Limit utilization"}: <b>{party.creditLimit ? `${utilization}%` : "—"}</b></p><div style={{ height: 12, background: "var(--line)", borderRadius: 99, overflow: "hidden" }}><div style={{ height: "100%", width: `${Math.min(100, utilization)}%`, background: utilization > 100 ? "#b42318" : "var(--primary)", borderRadius: 99 }} /></div>{utilization > 100 && <p className="warning error">{ar ? "تم تجاوز حد الائتمان؛ راجع العمليات الجديدة قبل اعتمادها." : "Credit limit exceeded; review new transactions before approval."}</p>}<p className="muted">{profile.overdueCount} {ar ? "فاتورة متأخرة" : "overdue invoices"}</p></article>
      <article className="card"><h2>{ar ? "بيانات التواصل" : "Contact details"}</h2><label><Phone size={15}/>{ar ? "الهاتف / واتساب" : "Phone / WhatsApp"}<input value={party.phone || ""} onChange={(event) => setParties(parties.map((item) => item.id === party.id ? { ...item, phone: event.target.value } : item))} /></label><label><Mail size={15}/>{ar ? "البريد الإلكتروني" : "Email"}<input type="email" value={party.email || ""} onChange={(event) => setParties(parties.map((item) => item.id === party.id ? { ...item, email: event.target.value } : item))} /></label><button className="btn" onClick={() => updateParty({ phone: party.phone, email: party.email, creditLimit: party.creditLimit })}><Save size={16}/>{ar ? "حفظ البيانات" : "Save details"}</button></article></section>
    <section className="card no-print"><h2><MessageCircle size={20}/>{ar ? "التواصل عبر WhatsApp Web" : "Contact through WhatsApp Web"}</h2><p className="muted">{ar ? "اكتب أو عدّل الرسالة هنا، ثم افتح المحادثة على الكمبيوتر. لن تُرسل الرسالة إلا بعد ضغط إرسال داخل واتساب." : "Compose the message here, then open the chat on your computer. It is not sent until you press Send in WhatsApp."}</p><textarea rows={4} value={message} onChange={(event) => setMessage(event.target.value)} /><div className="actions"><button className="btn btn-primary" onClick={openWhatsapp}><MessageCircle size={17}/>{ar ? "فتح المحادثة وإرسال الرسالة" : "Open chat with message"}</button><button className="btn" onClick={() => setMessage(ar ? `مرحبًا ${party.nameAr}، نرجو إرسال كشف حساب محدث حتى تاريخ ${today()}.` : `Hello ${party.nameEn}, please send an updated statement as of ${today()}.`)}>{ar ? "طلب كشف حساب" : "Request statement"}</button><button className="btn" onClick={() => setMessage(ar ? `مرحبًا ${party.nameAr}، نذكّركم بأن الرصيد المستحق حاليًا ${money(profile.outstanding, locale)} ${currency}. نرجو الإفادة بموعد السداد.` : `Hello ${party.nameEn}, the current outstanding balance is ${money(profile.outstanding, locale)} ${currency}. Please confirm the payment date.`)}>{ar ? "تذكير بالرصيد" : "Balance reminder"}</button></div></section>
    {notice && <p className="warning">{notice}</p>}
    <section className="card"><h2><WalletCards size={20}/>{ar ? "كشف الحساب والفواتير" : "Statement and invoices"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "الفاتورة" : "Invoice"}</th><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "الاستحقاق" : "Due"}</th><th>{ar ? "المبلغ" : "Amount"}</th><th>{ar ? "المسدد" : "Paid"}</th><th>{ar ? "المتبقي" : "Outstanding"}</th><th>{ar ? "الحالة" : "Status"}</th><th className="no-print"></th></tr></thead><tbody>{profile.items.map((item) => { const outstanding = itemOutstanding(item), overdue = outstanding > 0 && item.dueDate < today(); return <tr key={item.id}><td><b>{item.invoiceNumber}</b></td><td>{item.invoiceDate}</td><td>{item.dueDate}</td><td>{money(item.amount, locale)} {item.currency}</td><td>{money(item.paid, locale)}</td><td><b>{money(outstanding, locale)}</b></td><td><span className={overdue ? "badge error" : "badge"}>{outstanding === 0 ? (ar ? "مسددة" : "Paid") : overdue ? (ar ? "متأخرة" : "Overdue") : (ar ? "مفتوحة" : "Open")}</span></td><td className="no-print"><div className="actions">{outstanding > 0 && <button className="btn btn-primary" onClick={() => recordPayment(item)}>{party.type === "customer" ? (ar ? "تسجيل تحصيل" : "Collect") : (ar ? "تسجيل سداد" : "Pay")}</button>}{item.linkedEntryId && <Link className="btn" href={`/${locale}/operations/${item.linkedEntryId}`}>{ar ? "بطاقة العملية" : "Operation dossier"}</Link>}</div></td></tr>; })}{!profile.items.length && <tr><td colSpan={8}>{ar ? "لا توجد فواتير مسجلة لهذا الطرف." : "No invoices recorded for this party."}</td></tr>}</tbody></table></div></section>
    {party.type === "customer" && <section className="card"><h2><BookOpenCheck size={20}/>{ar ? "كشف حركة حساب العميل" : "Customer account statement"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "النوع" : "Type"}</th><th>{ar ? "المرجع" : "Reference"}</th><th>{ar ? "البيان" : "Description"}</th><th>{ar ? "مدين" : "Debit"}</th><th>{ar ? "دائن" : "Credit"}</th><th>{ar ? "الرصيد" : "Balance"}</th><th></th></tr></thead><tbody>{statement.map((row) => <tr key={row.id}><td>{row.date}</td><td>{row.type === "invoice" ? (ar ? "فاتورة آجلة" : "Credit invoice") : (ar ? "تحصيل" : "Collection")}</td><td dir="ltr">{row.reference}</td><td>{row.description}</td><td>{row.debit ? money(row.debit, locale) : "—"}</td><td>{row.credit ? money(row.credit, locale) : "—"}</td><td><b>{money(row.balance, locale)}</b></td><td>{row.entryId && <Link className="btn" href={`/${locale}/journal?entry=${row.entryId}`}>{ar ? "القيد" : "Entry"}</Link>}</td></tr>)}{!statement.length && <tr><td colSpan={8}>{ar ? "لا توجد حركات بعد." : "No movements yet."}</td></tr>}</tbody></table></div><h3 className="mt-6">{ar ? "القيود المرتبطة بالعميل" : "Linked customer entries"}</h3><div className="table-wrap"><table><thead><tr><th>{ar ? "رقم القيد" : "Entry"}</th><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "البيان" : "Narration"}</th><th>{ar ? "الحالة" : "Status"}</th><th>{ar ? "الإجمالي" : "Total"}</th></tr></thead><tbody>{linkedEntries.map((entry) => <tr key={entry.id}><td><Link href={`/${locale}/journal?entry=${entry.id}`} dir="ltr">{entry.entryNumber}</Link></td><td>{entry.date}</td><td>{ar ? entry.narrationAr : entry.narrationEn}</td><td><span className="badge">{entry.workflowStatus ? (ar ? JOURNAL_STATUS_LABELS[entry.workflowStatus].ar : JOURNAL_STATUS_LABELS[entry.workflowStatus].en) : "—"}</span></td><td>{money(entry.totalDebit, locale)} {entry.currency}</td></tr>)}{!linkedEntries.length && <tr><td colSpan={5}>{ar ? "لا توجد قيود مرتبطة بعد." : "No linked entries yet."}</td></tr>}</tbody></table></div></section>}
    <section className="card"><h2><CalendarClock size={20}/>{ar ? "أعمار الديون" : "Aging analysis"}</h2><div className="grid five">{[[ar ? "غير مستحق" : "Current", profile.aging.current], ["1–30", profile.aging.days30], ["31–60", profile.aging.days60], ["61–90", profile.aging.days90], ["+90", profile.aging.over90]].map(([label, value]) => <div key={String(label)}><small className="muted">{label}</small><div className="impact">{money(Number(value), locale)}</div></div>)}</div></section>
    <section className="card"><h2><FileText size={20}/>{ar ? "المستندات المرتبطة" : "Linked documents"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "الرقم" : "Number"}</th><th>{ar ? "النوع" : "Type"}</th><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "الإجمالي" : "Total"}</th><th>{ar ? "الحالة" : "Status"}</th><th></th></tr></thead><tbody>{profile.documents.map((document) => <tr key={document.id}><td>{document.number}</td><td>{document.type}</td><td>{document.date}</td><td>{money(document.grandTotal, locale)} {document.currency}</td><td><span className="badge">{document.status}</span></td><td>{document.linkedEntryId && <Link className="btn" href={`/${locale}/operations/${document.linkedEntryId}`}>{ar ? "القيد والتأثير" : "Entry & impact"}</Link>}</td></tr>)}{!profile.documents.length && <tr><td colSpan={6}>{ar ? "لا توجد مستندات مرتبطة بعد." : "No linked documents yet."}</td></tr>}</tbody></table></div></section>
  </div>;
}

function Metric({ title, value, danger = false }: { title: string; value: string; danger?: boolean }) { return <article className="card"><span className="muted">{title}</span><div className={danger ? "impact error" : "impact"}>{value}</div></article>; }
function Info({ title, value }: { title: string; value: string }) { return <p><small className="muted">{title}</small><br/><b>{value}</b></p>; }
