"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Eye, Plus, Search, Trash2, WalletCards } from "lucide-react";
import { buildPartyBalances, itemOutstanding } from "@/lib/parties/aging";
import { duplicateInvoice, removedUsedParty } from "@/lib/accounting/integrity";
import { loadOpenItems, loadParties, saveOpenItems, saveParties } from "@/lib/storage/parties";
import { generateJournalEntry } from "@/rules";
import { saveEntry } from "@/lib/storage/accounting";
import type { Locale, OpenItem, Party } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
const addDays = (date: string, days: number) => { const value = new Date(date); value.setDate(value.getDate() + days); return value.toISOString().slice(0, 10); };

export function PartyCenter({ locale }: { locale: Locale }) {
  const ar = locale === "ar", [parties, setParties] = useState<Party[]>([]), [items, setItems] = useState<OpenItem[]>([]), [query, setQuery] = useState(""), [message, setMessage] = useState("");
  const [draft, setDraft] = useState({ nameAr: "", nameEn: "", taxNumber: "", phone: "", email: "", creditDays: 30, creditLimit: 0 });
  const [invoice, setInvoice] = useState({ partyId: "", invoiceNumber: "", invoiceDate: today(), amount: 0, currency: "EGP" });
  useEffect(() => { setParties(loadParties()); setItems(loadOpenItems()); }, []);
  const commitParties = (next: Party[]) => { setParties(next); saveParties(next); }, commitItems = (next: OpenItem[]) => { setItems(next); saveOpenItems(next); };
  const addParty = () => { if (!draft.nameAr || !draft.nameEn) return setMessage(ar ? "اكتب اسم المورد بالعربية والإنجليزية." : "Enter Arabic and English supplier names."); const suppliers = parties.filter((party) => party.type === "supplier"), party: Party = { id: crypto.randomUUID(), type: "supplier", code: `S-${String(suppliers.length + 1).padStart(4, "0")}`, nameAr: draft.nameAr, nameEn: draft.nameEn, taxNumber: draft.taxNumber || undefined, phone: draft.phone || undefined, email: draft.email || undefined, creditDays: draft.creditDays, creditLimit: draft.creditLimit || undefined, accountCode: `210${suppliers.length + 1}`, active: true, createdAt: new Date().toISOString() }; commitParties([...parties, party]); setDraft({ nameAr: "", nameEn: "", taxNumber: "", phone: "", email: "", creditDays: 30, creditLimit: 0 }); setMessage(ar ? "تم إنشاء المورد وملف 360° والحساب الفرعي." : "Supplier, 360° profile, and subaccount created."); };
  const addInvoice = () => { const party = parties.find((item) => item.id === invoice.partyId && item.type === "supplier"); if (!party || invoice.amount <= 0 || !invoice.invoiceNumber) return setMessage(ar ? "أكمل بيانات فاتورة المورد." : "Complete the supplier invoice data."); if (duplicateInvoice(items, party.id, invoice.invoiceNumber)) return setMessage(ar ? "رقم الفاتورة مسجل سابقًا لهذا المورد." : "This invoice number already exists for the supplier."); const generated = generateJournalEntry({ type: "credit-purchase", amount: invoice.amount, date: invoice.invoiceDate, currency: invoice.currency, paymentMethod: "credit", supplier: party.nameAr, notes: `${invoice.invoiceNumber} — ${party.nameAr}` }), entry = saveEntry({ ...generated, workflowStatus: "draft", partyId: party.id, partyName: party.nameAr, reference: invoice.invoiceNumber }), item: OpenItem = { id: crypto.randomUUID(), partyId: party.id, kind: "payable", invoiceNumber: invoice.invoiceNumber, invoiceDate: invoice.invoiceDate, dueDate: addDays(invoice.invoiceDate, party.creditDays), currency: invoice.currency, amount: invoice.amount, paid: 0, status: "open", linkedEntryId: entry.id, invoiceEntryId: entry.id, createdAt: new Date().toISOString() }; commitItems([item, ...items]); setInvoice({ ...invoice, invoiceNumber: "", amount: 0 }); setMessage(ar ? `تمت إضافة فاتورة المورد وإنشاء مسودة القيد ${entry.entryNumber}.` : `Supplier invoice added with draft ${entry.entryNumber}.`); };
  const pay = (item: OpenItem) => { const outstanding = itemOutstanding(item), text = prompt(ar ? `أدخل قيمة السداد، المتبقي ${outstanding}` : `Enter payment, outstanding ${outstanding}`, String(outstanding)); if (!text) return; const value = Math.min(outstanding, Math.max(0, Number(text))); if (!value) return; const party = parties.find((current) => current.id === item.partyId && current.type === "supplier"); if (!party) return; const entry = saveEntry({ ...generateJournalEntry({ type: "supplier-payment", amount: value, date: today(), currency: item.currency, paymentMethod: "bank", supplier: party.nameAr, notes: `${item.invoiceNumber} — ${party.nameAr}` }), workflowStatus: "draft", partyId: party.id, partyName: party.nameAr }); const paid = item.paid + value; commitItems(items.map((current) => current.id === item.id ? { ...current, paid, status: paid >= item.amount ? "paid" : "partial", collectionEntryIds: [...(current.collectionEntryIds || []), entry.id] } : current)); setMessage(ar ? "تم تسجيل سداد المورد وإنشاء مسودة قيد وبطاقة عملية." : "Supplier payment, draft entry, and operation dossier created."); };
  const removeParty = (party: Party) => { const next = parties.filter((item) => item.id !== party.id); if (removedUsedParty(parties, next, items)) return setMessage(ar ? "لا يمكن حذف طرف مرتبط بفواتير؛ يمكنك إيقافه بدلًا من ذلك." : "A party linked to invoices cannot be deleted; deactivate it instead."); commitParties(next); };
  const suppliers = parties.filter((party) => party.type === "supplier"), filtered = suppliers.filter((party) => `${party.nameAr} ${party.nameEn} ${party.code}`.toLowerCase().includes(query.toLowerCase())), balances = buildPartyBalances(filtered, items, today()), total = balances.reduce((sum, balance) => sum + balance.aging.total, 0);
  return <div className="grid">
    <section className="grid four"><Metric title={ar ? "عدد الموردين" : "Suppliers"} value={filtered.length} /><Metric title={ar ? "إجمالي المستحق للموردين" : "Total payables"} value={total.toLocaleString()} /><Metric title={ar ? "متأخر أكثر من 90 يومًا" : "Over 90 days"} value={balances.reduce((sum, balance) => sum + balance.aging.over90, 0).toLocaleString()} /><Metric title={ar ? "فواتير موردين مفتوحة" : "Open supplier invoices"} value={balances.reduce((sum, balance) => sum + balance.openItems, 0)} /></section>
    <section className="card"><h2>{ar ? "إضافة مورد" : "Add supplier"}</h2><p className="muted">{ar ? "العملاء الآجلون موجودون في قسم حسابات العملاء الآجلين؛ هذا المركز مخصص للموردين والمبالغ المستحقة لهم." : "Credit customers are managed in Customer Receivables; this center is dedicated to suppliers and payables."}</p><div className="grid four"><label>{ar ? "الاسم بالعربية" : "Arabic name"}<input value={draft.nameAr} onChange={(event) => setDraft({ ...draft, nameAr: event.target.value })}/></label><label>{ar ? "الاسم بالإنجليزية" : "English name"}<input value={draft.nameEn} onChange={(event) => setDraft({ ...draft, nameEn: event.target.value })}/></label><label>{ar ? "الرقم الضريبي" : "Tax number"}<input value={draft.taxNumber} onChange={(event) => setDraft({ ...draft, taxNumber: event.target.value })}/></label><label>{ar ? "رقم واتساب" : "WhatsApp number"}<input value={draft.phone} onChange={(event) => setDraft({ ...draft, phone: event.target.value })}/></label><label>{ar ? "البريد الإلكتروني" : "Email"}<input type="email" value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })}/></label><label>{ar ? "أيام الائتمان" : "Credit days"}<input type="number" value={draft.creditDays} onChange={(event) => setDraft({ ...draft, creditDays: Number(event.target.value) })}/></label><label>{ar ? "حد الائتمان" : "Credit limit"}<input type="number" value={draft.creditLimit || ""} onChange={(event) => setDraft({ ...draft, creditLimit: Number(event.target.value) })}/></label></div><button className="btn btn-primary" onClick={addParty}><Plus size={16}/>{ar ? "إضافة المورد وإنشاء ملف 360°" : "Add supplier with 360° profile"}</button>{message && <p className="warning">{message}</p>}</section>
    <section className="card"><h2>{ar ? "إضافة فاتورة مورد آجلة" : "Add credit supplier invoice"}</h2><div className="grid four"><label>{ar ? "المورد" : "Supplier"}<select value={invoice.partyId} onChange={(event) => setInvoice({ ...invoice, partyId: event.target.value })}><option value="">—</option>{suppliers.map((party) => <option key={party.id} value={party.id}>{ar ? party.nameAr : party.nameEn}</option>)}</select></label><label>{ar ? "رقم الفاتورة" : "Invoice number"}<input value={invoice.invoiceNumber} onChange={(event) => setInvoice({ ...invoice, invoiceNumber: event.target.value })}/></label><label>{ar ? "التاريخ" : "Date"}<input type="date" value={invoice.invoiceDate} onChange={(event) => setInvoice({ ...invoice, invoiceDate: event.target.value })}/></label><label>{ar ? "المبلغ" : "Amount"}<input type="number" value={invoice.amount || ""} onChange={(event) => setInvoice({ ...invoice, amount: Number(event.target.value) })}/></label></div><button className="btn btn-primary" onClick={addInvoice}><Plus size={16}/>{ar ? "إضافة فاتورة المورد" : "Add supplier invoice"}</button></section>
    <section className="card"><label><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={ar ? "بحث بالاسم أو الكود" : "Search name or code"}/></label><div className="table-wrap section"><table><thead><tr><th>{ar ? "الطرف" : "Party"}</th><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "غير مستحق" : "Current"}</th><th>1-30</th><th>31-60</th><th>61-90</th><th>+90</th><th>{ar ? "الإجمالي" : "Total"}</th><th>{ar ? "الإجراء" : "Action"}</th></tr></thead><tbody>{balances.map(({ party, aging }) => <tr key={party.id}><td><b>{ar ? party.nameAr : party.nameEn}</b><br/><small>{party.code}</small></td><td>{party.accountCode}</td><td>{aging.current || "—"}</td><td>{aging.days30 || "—"}</td><td>{aging.days60 || "—"}</td><td>{aging.days90 || "—"}</td><td>{aging.over90 || "—"}</td><td><b>{aging.total}</b></td><td><div className="actions"><Link className="btn btn-primary" href={`/${locale}/parties/${party.id}`}><Eye size={15}/>{ar ? "ملف 360°" : "360° profile"}</Link><button className="btn btn-danger" onClick={() => removeParty(party)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div></section>
    <section className="card"><h2><WalletCards size={20}/>{ar ? "فواتير الموردين والمدفوعات" : "Supplier invoices and payments"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "الفاتورة" : "Invoice"}</th><th>{ar ? "المورد" : "Supplier"}</th><th>{ar ? "الاستحقاق" : "Due"}</th><th>{ar ? "المبلغ" : "Amount"}</th><th>{ar ? "المدفوع" : "Paid"}</th><th>{ar ? "المتبقي" : "Outstanding"}</th><th></th></tr></thead><tbody>{items.filter((item) => parties.find((party) => party.id === item.partyId)?.type === "supplier").map((item) => { const party = parties.find((current) => current.id === item.partyId); return <tr key={item.id}><td>{item.invoiceNumber}</td><td>{party ? (ar ? party.nameAr : party.nameEn) : "—"}</td><td>{item.dueDate}</td><td>{item.amount}</td><td>{item.paid}</td><td>{itemOutstanding(item)}</td><td><div className="actions">{itemOutstanding(item) > 0 && <button className="btn btn-primary" onClick={() => pay(item)}>{ar ? "تسجيل سداد" : "Pay"}</button>}{party && <Link className="btn" href={`/${locale}/parties/${party.id}`}>{ar ? "فتح ملف المورد" : "Open supplier profile"}</Link>}</div></td></tr>; })}</tbody></table></div></section>
  </div>;
}

function Metric({ title, value }: { title: string; value: string | number }) { return <div className="card"><span className="muted">{title}</span><div className="impact">{value}</div></div>; }
