"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowUpRight, CalendarRange, FileCheck2, Printer, ReceiptText, Scale } from "lucide-react";
import { analyzeVat, entriesForVatPeriod } from "@/lib/tax/vat";
import { loadEntries, subscribeToEntries } from "@/lib/storage/accounting";
import type { GeneratedJournalEntry, Locale, VatPeriodFrequency } from "@/types";

const money = (value: number) => new Intl.NumberFormat("ar-EG", { maximumFractionDigits: 2 }).format(value);

export function VatCenter({ locale }: { locale: Locale }) {
  const ar = locale === "ar", currentYear = new Date().getFullYear();
  const [entries, setEntries] = useState<GeneratedJournalEntry[]>([]), [year, setYear] = useState(currentYear), [frequency, setFrequency] = useState<VatPeriodFrequency>("monthly"), [selected, setSelected] = useState("");
  useEffect(() => { setEntries(loadEntries()); return subscribeToEntries(setEntries); }, []);
  const analysis = useMemo(() => analyzeVat(entries, year, frequency), [entries, year, frequency]);
  const active = analysis.periods.find((period) => period.id === selected) || analysis.periods.find((period) => period.transactionCount > 0) || analysis.periods[0];
  const detail = active ? entriesForVatPeriod(entries, active) : [];
  return <div className="grid" id="vat-report" data-no-bilingual>
    <section className="card no-print">
      <div className="actions" style={{ justifyContent: "space-between", alignItems: "start" }}><div><h1><ReceiptText size={24}/>{ar ? "مركز ضريبة القيمة المضافة" : "VAT center"}</h1><p className="muted">{ar ? "يجمع ضريبة المدخلات والمخرجات من القيود المعتمدة ويعرض صافي كل فترة، مع فصل القيود التي ما زالت تحت المراجعة." : "Analyze input and output VAT from approved entries and separate pending entries."}</p></div><button className="btn" onClick={() => window.print()}><Printer size={17}/>{ar ? "طباعة التقرير" : "Print report"}</button></div>
      <div className="grid three"><label>{ar ? "السنة الضريبية" : "Tax year"}<input type="number" min="2000" max="2100" value={year} onChange={(event) => setYear(Number(event.target.value) || currentYear)}/></label><label>{ar ? "دورية العرض" : "Period frequency"}<select value={frequency} onChange={(event) => { setFrequency(event.target.value as VatPeriodFrequency); setSelected(""); }}><option value="monthly">{ar ? "شهري" : "Monthly"}</option><option value="quarterly">{ar ? "ربع سنوي" : "Quarterly"}</option></select></label><label>{ar ? "الفترة المعروضة" : "Displayed period"}<select value={active?.id || ""} onChange={(event) => setSelected(event.target.value)}>{analysis.periods.map((period) => <option value={period.id} key={period.id}>{ar ? period.labelAr : period.labelEn}</option>)}</select></label></div>
    </section>
    <section className="grid four"><Metric icon={ArrowDownLeft} tone="green" title={ar ? "ضريبة المدخلات القابلة للمراجعة" : "Input VAT"} value={analysis.inputVat}/><Metric icon={ArrowUpRight} tone="red" title={ar ? "ضريبة المخرجات" : "Output VAT"} value={analysis.outputVat}/><Metric icon={Scale} tone={analysis.netVat >= 0 ? "red" : "green"} title={analysis.netVat >= 0 ? (ar ? "صافي مستحق" : "Net payable") : (ar ? "رصيد ضريبي دائن" : "VAT credit")} value={Math.abs(analysis.netVat)}/><Metric icon={FileCheck2} tone="amber" title={ar ? "حركة تحت المراجعة" : "Pending VAT"} value={Math.abs(analysis.pendingInputVat) + Math.abs(analysis.pendingOutputVat)}/></section>
    <section className="card"><h2><CalendarRange size={21}/>{ar ? "الفترات الضريبية" : "Tax periods"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "الفترة" : "Period"}</th><th>{ar ? "من" : "From"}</th><th>{ar ? "إلى" : "To"}</th><th>{ar ? "المدخلات" : "Input VAT"}</th><th>{ar ? "المخرجات" : "Output VAT"}</th><th>{ar ? "الصافي" : "Net"}</th><th>{ar ? "عدد القيود" : "Entries"}</th><th>{ar ? "الحالة" : "Status"}</th></tr></thead><tbody>{analysis.periods.map((period) => <tr key={period.id} onClick={() => setSelected(period.id)} style={{ cursor: "pointer" }}><td><b>{ar ? period.labelAr : period.labelEn}</b></td><td>{period.startDate}</td><td>{period.endDate}</td><td>{money(period.inputVat)}</td><td>{money(period.outputVat)}</td><td><b className={period.netVat > 0 ? "text-red-600" : "text-emerald-700"}>{money(Math.abs(period.netVat))} {period.netVat > 0 ? (ar ? "مستحق" : "payable") : period.netVat < 0 ? (ar ? "دائن" : "credit") : "—"}</b></td><td>{period.transactionCount}</td><td>{period.pendingInputVat || period.pendingOutputVat ? <span className="warning">{ar ? "توجد قيود للمراجعة" : "Pending review"}</span> : <span className="badge">{ar ? "مُحدّث" : "Updated"}</span>}</td></tr>)}</tbody></table></div></section>
    {active && <section className="card"><h2>{ar ? `تفاصيل ${active.labelAr}` : `${active.labelEn} details`}</h2><p className="muted">{ar ? "تظهر هنا القيود التي حركت حساب ضريبة المدخلات 1151 أو ضريبة المخرجات 2201." : "Entries moving input VAT 1151 or output VAT 2201."}</p><div className="table-wrap"><table><thead><tr><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "رقم القيد" : "Entry"}</th><th>{ar ? "البيان" : "Description"}</th><th>{ar ? "مدخلات" : "Input"}</th><th>{ar ? "مخرجات" : "Output"}</th><th>{ar ? "الحالة" : "Status"}</th></tr></thead><tbody>{detail.map((entry) => { const input = entry.lines.filter((line) => line.accountCode === "1151").reduce((sum, line) => sum + line.debit - line.credit, 0), output = entry.lines.filter((line) => line.accountCode === "2201").reduce((sum, line) => sum + line.credit - line.debit, 0); return <tr key={entry.id}><td>{entry.date}</td><td>{entry.entryNumber}</td><td>{ar ? entry.narrationAr : entry.narrationEn}</td><td>{input ? money(input) : "—"}</td><td>{output ? money(output) : "—"}</td><td><span className={["approved", "posted"].includes(entry.workflowStatus || "") ? "badge" : "warning"}>{entry.workflowStatus || "draft"}</span></td></tr>; })}{!detail.length && <tr><td colSpan={6}>{ar ? "لا توجد حركات ضريبية في هذه الفترة." : "No VAT movements in this period."}</td></tr>}</tbody></table></div></section>}
    <section className="warning"><b>{ar ? "مهم:" : "Important:"}</b> {ar ? "هذا التقرير أداة مراجعة محاسبية داخلية. موعد الإقرار وقابلية خصم المدخلات يعتمدان على الدولة والمستندات والقواعد الضريبية السارية، لذلك راجع الإقرار قبل التقديم." : "This is an internal accounting review. Filing deadlines and input VAT eligibility depend on local rules and supporting documents."}</section>
  </div>;
}

function Metric({ icon: Icon, title, value, tone }: { icon: typeof Scale; title: string; value: number; tone: "green" | "red" | "amber" }) {
  const color = tone === "green" ? "text-emerald-700" : tone === "red" ? "text-red-600" : "text-amber-700";
  return <article className="card"><Icon className={color}/><span className="muted">{title}</span><div className={`impact ${color}`}>{money(value)}</div></article>;
}
