"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, CircleHelp, Eye, Lightbulb, RotateCcw, ShieldCheck, Sparkles, Target, Trophy, X } from "lucide-react";
import { missions } from "@/data/missions";
import { calculateMissionAccuracy, calculateMissionScore, isMissionAnswerCorrect, missionFeedback, missionReflection, resolveMissionImpact, validateTrainingJournal } from "@/lib/missions/engine";
import { loadMissionsProgress, recordMissionResult } from "@/lib/storage/missions";
import type { Locale, MissionDefinition, MissionImpactItem } from "@/types";

type Stage = "scenario" | "decision" | "consequence" | "journal" | "explanation" | "result";
const stages: Stage[] = ["scenario","decision","consequence","journal","explanation","result"];
const money = (value?: number) => value === undefined ? "" : value.toLocaleString("en-US");

export function MissionPlayer({ mission, locale }: { mission: MissionDefinition; locale: Locale }) {
  const ar = locale === "ar", [stage, setStage] = useState<Stage>("scenario"), [selected, setSelected] = useState<string[]>([]), [creditAmount, setCreditAmount] = useState(mission.balanceFix?.initialCreditAmount || 0), [attempts, setAttempts] = useState(0), [hintsUsed, setHintsUsed] = useState(0), [viewedSolution, setViewedSolution] = useState(false), [correct, setCorrect] = useState(false), [answerSnapshot, setAnswerSnapshot] = useState<string[]>([]), [result, setResult] = useState<{score:number;accuracy:number;elapsed:number;previousBest:number;totalScore:number}>();
  const startedAt = useRef(0), step = stages.indexOf(stage) + 1, answerIds = mission.interaction === "balance-fix" ? [String(creditAmount)] : selected;
  const impacts = useMemo(() => resolveMissionImpact(mission, answerSnapshot, correct), [answerSnapshot, correct, mission]);
  const toggle = (id: string) => setSelected((current) => mission.interaction === "multi-select" ? (current.includes(id) ? current.filter((item) => item !== id) : [...current,id]) : [id]);
  const submit = () => { if (!answerIds.length) return; const nextAttempts = attempts + 1, isCorrect = isMissionAnswerCorrect(mission, answerIds); setAttempts(nextAttempts); setCorrect(isCorrect); setAnswerSnapshot(answerIds); setStage("consequence"); };
  const retry = () => { setSelected([]); setStage("decision"); };
  const showSolution = () => { setViewedSolution(true); setAttempts((value) => value + 1); setCorrect(true); setAnswerSnapshot(mission.correctAnswerIds); setSelected(mission.correctAnswerIds); if (mission.balanceFix) setCreditAmount(mission.balanceFix.expectedCreditAmount); setStage("consequence"); };
  const finish = () => { const elapsed = Math.max(1, Math.round((Date.now() - (startedAt.current || Date.now())) / 1000)), score = calculateMissionScore({ correct:true, attempts:Math.max(1,attempts), hintsUsed, viewedSolution }), accuracy = calculateMissionAccuracy(1, Math.max(1,attempts)), previous = loadMissionsProgress().records[mission.id]?.bestScore || 0; const progress = recordMissionResult({ missionId:mission.id,score,accuracy,attempts:Math.max(1,attempts),hintsUsed,elapsedSeconds:elapsed,completedAt:new Date().toISOString(),viewedSolution }); setResult({score,accuracy,elapsed,previousBest:previous,totalScore:Object.values(progress.records).reduce((sum,record)=>sum+record.bestScore,0)}); setStage("result"); };
  const nextMission = missions[(missions.findIndex((item) => item.id === mission.id) + 1) % missions.length];

  return <div className="mission-play-page"><div className="mission-play-shell">
    <header className="mission-play-head"><Link href={`/${locale}/missions`}>{ar ? <ArrowRight/> : <ArrowLeft/>}<span>{ar ? "كل المهمات" : "All missions"}</span></Link><div><span>CASE #{mission.caseNumber}</span><b>{ar ? mission.titleAr : mission.titleEn}</b></div><div className="mission-step"><small>{ar ? "الخطوة" : "Step"}</small><b>{step} / {stages.length}</b></div></header>
    <div className="mission-progress"><i style={{width:`${step/stages.length*100}%`}}/></div>

    {stage === "scenario" && <section className="mission-stage mission-scenario"><span><Target/> CASE #{mission.caseNumber}</span><h1>{ar ? mission.titleAr : mission.titleEn}</h1><p>{ar ? mission.scenarioAr : mission.scenarioEn}</p>{mission.balanceFix && <BalancePreview mission={mission} locale={locale} creditAmount={mission.balanceFix.initialCreditAmount}/>}<button className="mission-primary" onClick={() => { startedAt.current=Date.now();setStage("decision"); }}>{ar ? "اتخذ القرار" : "Make the decision"}{ar ? <ArrowLeft/> : <ArrowRight/>}</button></section>}

    {stage === "decision" && <section className="mission-stage"><span className="mission-stage-label">{ar ? "قرارك" : "Your decision"}</span><h2>{ar ? mission.questionAr : mission.questionEn}</h2>
      {mission.interaction === "balance-fix" && mission.balanceFix ? <div className="mission-balance-fix"><BalancePreview mission={mission} locale={locale} creditAmount={creditAmount}/><label>{ar ? "قيمة الدائن الصحيحة" : "Correct credit amount"}<input inputMode="decimal" type="number" value={creditAmount || ""} onChange={(event)=>setCreditAmount(Number(event.target.value))}/></label></div> : <div className="mission-choices">{mission.choices?.map((choice)=><button className={selected.includes(choice.id)?"selected":""} onClick={()=>toggle(choice.id)} key={choice.id}><span>{selected.includes(choice.id)?<Check/>:mission.interaction==="multi-select"?<span/>:String.fromCharCode(65+mission.choices!.indexOf(choice))}</span><b>{ar?choice.labelAr:choice.labelEn}</b></button>)}</div>}
      <div className="mission-decision-actions"><button className="mission-primary" disabled={!answerIds.length} onClick={submit}>{ar ? "نفّذ القرار" : "Apply decision"}</button><HintButton mission={mission} locale={locale} used={hintsUsed} onUse={()=>setHintsUsed((value)=>Math.min(3,value+1))}/><button className="mission-text-btn" onClick={showSolution}><Eye/>{ar?"عرض الحل":"View solution"}</button></div>
      {hintsUsed>0&&<div className="mission-hint"><Lightbulb/><div><b>{ar?`مساعدة ${hintsUsed}`:`Hint ${hintsUsed}`}</b><p>{ar?mission.hints[hintsUsed-1].textAr:mission.hints[hintsUsed-1].textEn}</p></div></div>}
    </section>}

    {stage === "consequence" && <section className="mission-stage"><div className={correct?"mission-feedback success":"mission-feedback error"}>{correct?<CheckCircle2/>:<X/>}<div><span>{correct?(ar?"قرار سليم":"Sound decision"):(ar?"شوف نتيجة قرارك":"See the consequence")}</span><h2>{missionFeedback(mission,answerSnapshot,correct,locale)}</h2></div></div><ImpactPanel impacts={impacts} locale={locale}/>{!correct&&<div className="mission-reflection"><CircleHelp/><p>{missionReflection(mission,answerSnapshot,locale)}</p></div>}<div className="mission-decision-actions">{correct?<button className="mission-primary" onClick={()=>setStage(mission.journalEntry?"journal":"explanation")}>{ar?"شوف القيد":"See the entry"}{ar?<ArrowLeft/>:<ArrowRight/>}</button>:<button className="mission-primary" onClick={retry}><RotateCcw/>{ar?"فكر تاني":"Think again"}</button>}{!correct&&<button className="mission-text-btn" onClick={showSolution}><Eye/>{ar?"عرض الحل":"View solution"}</button>}</div></section>}

    {stage === "journal" && mission.journalEntry && <section className="mission-stage"><span className="mission-stage-label"><ShieldCheck/>{ar?"Training Sandbox — مش هيدخل قيود الشركة":"Training Sandbox — never saved to company books"}</span><h2>{ar?"القيد الصحيح":"Correct journal entry"}</h2><JournalVisualizer mission={mission} locale={locale}/><button className="mission-primary" onClick={()=>setStage("explanation")}>{ar?"ليه ده الحل؟":"Why is this right?"}{ar?<ArrowLeft/>:<ArrowRight/>}</button></section>}

    {stage === "explanation" && <section className="mission-stage mission-explanation"><span><Sparkles/>{ar?"الفكرة في سطرين":"The idea in two lines"}</span><h2>{ar?mission.correctFeedbackAr:mission.correctFeedbackEn}</h2><p>{ar?mission.explanationAr:mission.explanationEn}</p><div className="mission-skills">{(ar?mission.skillsAr:mission.skillsEn).map((skill)=><b key={skill}>{skill}</b>)}</div><button className="mission-primary" onClick={finish}>{ar?"اعرض النتيجة":"Show result"}{ar?<ArrowLeft/>:<ArrowRight/>}</button></section>}

    {stage === "result" && result && <section className="mission-stage mission-result"><div className="mission-result-icon"><Trophy/></div><span>{ar?"CASE SOLVED":"CASE SOLVED"}</span><h1>{ar?"تم حل المهمة ✅":"Case solved ✅"}</h1><div className="mission-result-grid"><ResultMetric label={ar?"الدقة":"Accuracy"} value={`${result.accuracy}%`}/><ResultMetric label={ar?"نتيجة المهمة":"Mission score"} value={String(result.score)}/><ResultMetric label={ar?"الوقت":"Time"} value={formatTime(result.elapsed)}/><ResultMetric label={ar?"المساعدات":"Hints"} value={String(hintsUsed)}/></div><p>{ar?`أفضل نتيجة سابقة: ${result.previousBest} · إجمالي نقاطك: ${result.totalScore}`:`Previous best: ${result.previousBest} · Total score: ${result.totalScore}`}</p><div className="mission-skills">{(ar?mission.skillsAr:mission.skillsEn).map((skill)=><b key={skill}>{skill}</b>)}</div><div className="missions-actions"><Link className="mission-primary" href={`/${locale}/missions/${nextMission.slug}`}>{ar?"المهمة التالية":"Next mission"}{ar?<ArrowLeft/>:<ArrowRight/>}</Link><button className="mission-secondary" onClick={()=>window.location.reload()}><RotateCcw/>{ar?"إعادة المحاولة":"Replay"}</button></div></section>}
  </div></div>;
}

function HintButton({mission,locale,used,onUse}:{mission:MissionDefinition;locale:Locale;used:number;onUse:()=>void}) { return <button className="mission-secondary" disabled={used>=mission.hints.length} onClick={onUse}><Lightbulb/>{locale==="ar"?(used>=3?"استخدمت كل المساعدات":"مساعدة"):used>=3?"All hints used":"Hint"}</button>; }
function BalancePreview({mission,locale,creditAmount}:{mission:MissionDefinition;locale:Locale;creditAmount:number}) { const row=mission.balanceFix!,diff=Math.abs(row.debitAmount-creditAmount);return <div className="mission-balance-preview"><div><span>{locale==="ar"?"مدين":"Debit"}</span><b>{locale==="ar"?row.debitAccountAr:row.debitAccountEn}</b><strong>{money(row.debitAmount)}</strong></div><div><span>{locale==="ar"?"دائن":"Credit"}</span><b>{locale==="ar"?row.creditAccountAr:row.creditAccountEn}</b><strong>{money(creditAmount)}</strong></div><footer><span>{locale==="ar"?"إجمالي المدين":"Total debit"}: {money(row.debitAmount)}</span><span>{locale==="ar"?"إجمالي الدائن":"Total credit"}: {money(creditAmount)}</span><b>{locale==="ar"?"الفرق":"Difference"}: {money(diff)}</b></footer></div>; }
function ImpactPanel({impacts,locale}:{impacts:MissionImpactItem[];locale:Locale}) { return <div className="mission-impact-panel"><h3>{locale==="ar"?"تأثير القرار على الشركة":"Impact on the company"}</h3><div>{impacts.map((item,index)=><article className={item.incorrect?"incorrect":""} key={`${item.key}-${index}`}><span className={`impact-direction ${item.direction}`}>{item.direction==="up"?"↑":item.direction==="down"?"↓":"—"}</span><b>{locale==="ar"?item.labelAr:item.labelEn}</b><strong>{item.direction==="none"?(locale==="ar"?"لا تغيير":"No change"):`${item.direction==="up"?"+":"-"}${money(item.amount)}`}</strong></article>)}</div></div>; }
function JournalVisualizer({mission,locale}:{mission:MissionDefinition;locale:Locale}) { const entry=mission.journalEntry!,validation=validateTrainingJournal(entry,mission.id);return <div className="mission-journal"><div className="mission-journal-head"><span>{locale==="ar"?entry.narrationAr:entry.narrationEn}</span><b className={validation.valid?"balanced":"unbalanced"}>{validation.valid?(locale==="ar"?"قيد متوازن ✓":"Balanced entry ✓"):(locale==="ar"?"غير متوازن":"Unbalanced")}</b></div>{entry.lines.map((line,index)=><div className="mission-journal-line" key={line.accountCode}><span>{index===0?(locale==="ar"?"مدين":"Debit"):(locale==="ar"?"دائن":"Credit")}</span><b>{locale==="ar"?line.accountNameAr:line.accountNameEn}<small dir="ltr">{line.accountCode}</small></b><strong>{money(line.debit||line.credit)}</strong></div>)}<footer><span>{locale==="ar"?"إجمالي المدين":"Total debit"}<b>{money(validation.totalDebit)}</b></span><span>{locale==="ar"?"إجمالي الدائن":"Total credit"}<b>{money(validation.totalCredit)}</b></span></footer></div>; }
function ResultMetric({label,value}:{label:string;value:string}) { return <div><span>{label}</span><b>{value}</b></div>; }
function formatTime(seconds:number){return `${Math.floor(seconds/60)}m ${seconds%60}s`;}
