"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useTheme } from "next-themes";
import {
  Activity, AlertTriangle, BarChart3, Bell, BookOpenCheck,
  Building2, CheckCircle2, ChevronLeft, ClipboardCheck,
  FileCheck2, FileText, GraduationCap, LayoutDashboard, Menu, Moon,
  Plus, Printer, Search, ShieldCheck, Sparkles, Sun, Users, X,
} from "lucide-react";
import { officeActivities, officeClients, officeEntries, officeTasks, officeTeam } from "@/data/accounting-office";
import type { Locale } from "@/types";

type View = "dashboard" | "clients" | "tasks" | "review" | "team" | "training" | "reports";
type Icon = typeof LayoutDashboard;

const views: { id: View; ar: string; en: string; icon: Icon }[] = [
  { id:"dashboard", ar:"الرئيسية", en:"Overview", icon:LayoutDashboard },
  { id:"clients", ar:"العملاء والمستندات", en:"Clients & documents", icon:Building2 },
  { id:"tasks", ar:"المهام", en:"Tasks", icon:ClipboardCheck },
  { id:"review", ar:"مراجع القيود", en:"Entry reviewer", icon:ShieldCheck },
  { id:"team", ar:"الموظفون", en:"Team", icon:Users },
  { id:"training", ar:"التدريب العملي", en:"Practice", icon:GraduationCap },
  { id:"reports", ar:"تقارير المكتب", en:"Office reports", icon:BarChart3 },
];

export function AccountingOfficeHub({ locale }: { locale: Locale }) {
  const ar = locale === "ar", { resolvedTheme, setTheme } = useTheme();
  const [view, setView] = useState<View>("dashboard"), [menuOpen, setMenuOpen] = useState(false);
  const [query, setQuery] = useState(""), [notice, setNotice] = useState("");
  const active = views.find((item) => item.id === view)!;
  const changeView = (next: View) => { setView(next); setMenuOpen(false); setNotice(""); };
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };

  return <div className="min-h-[calc(100vh-68px)] bg-daftar-bg" data-no-bilingual>
    <div className="mx-auto flex max-w-[1530px] gap-0 px-3 py-5 lg:px-5">
      <aside className={`${menuOpen ? "fixed inset-0 z-50 flex bg-slate-950/35 p-3" : "hidden"} lg:sticky lg:top-[88px] lg:flex lg:h-[calc(100vh-108px)] lg:w-[250px] lg:shrink-0 lg:bg-transparent lg:p-0`}>
        <div className="flex h-full w-[270px] flex-col overflow-hidden rounded-3xl bg-[#0d315c] text-white shadow-2xl lg:w-full">
          <div className="flex items-center justify-between border-b border-white/10 p-5"><div><small className="text-white/55">FINORA OFFICE</small><b className="mt-1 block">{ar ? "مكتب رؤية للمحاسبة" : "Vision Accounting"}</b></div><button className="rounded-xl p-2 hover:bg-white/10 lg:hidden" onClick={()=>setMenuOpen(false)}><X/></button></div>
          <nav className="grid gap-1 overflow-auto p-3">{views.map((item)=>{const Icon=item.icon; return <button key={item.id} onClick={()=>changeView(item.id)} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-start text-sm font-bold transition ${view===item.id?"bg-white text-[#0d315c] shadow-lg":"text-white/75 hover:bg-white/10 hover:text-white"}`}><Icon size={19}/><span>{ar?item.ar:item.en}</span></button>;})}</nav>
          <div className="mt-auto m-3 rounded-2xl bg-white/10 p-4"><div className="flex items-center gap-2 text-emerald-300"><Sparkles size={17}/><b>{ar?"جاهزية المكتب":"Office readiness"}</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><i className="block h-full w-[86%] rounded-full bg-emerald-400"/></div><div className="mt-2 flex justify-between text-xs text-white/65"><span>{ar?"إقفال يوليو":"July close"}</span><b className="text-white">86%</b></div></div>
        </div>
      </aside>

      <div className="min-w-0 flex-1 lg:ps-5">
        <header className="mb-5 flex flex-wrap items-center gap-3 rounded-2xl border border-daftar-line bg-daftar-card p-3 shadow-sm">
          <button className="grid h-11 w-11 place-items-center rounded-xl border border-daftar-line lg:hidden" onClick={()=>setMenuOpen(true)}><Menu/></button>
          <div className="me-auto"><small className="text-daftar-muted">{ar?"مركز تشغيل مكتب المحاسبة":"Accounting office command center"}</small><h1 className="m-0 text-xl font-black">{ar?active.ar:active.en}</h1></div>
          <label className="hidden min-w-[260px] grid-cols-[auto_1fr] items-center gap-2 rounded-xl border border-daftar-line px-3 md:grid"><Search size={18} className="text-daftar-muted"/><input className="border-0 bg-transparent p-1 shadow-none" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={ar?"ابحث عن عميل أو مهمة...":"Search clients or tasks..."}/></label>
          <button className="relative grid h-11 w-11 place-items-center rounded-xl border border-daftar-line"><Bell size={19}/><i className="absolute end-2 top-2 h-2 w-2 rounded-full bg-red-500"/></button>
          <button className="grid h-11 w-11 place-items-center rounded-xl border border-daftar-line" onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")}>{resolvedTheme==="dark"?<Sun size={19}/>:<Moon size={19}/>}</button>
          <button className="btn btn-primary" onClick={()=>flash(ar?"تم فتح نموذج مهمة تجريبي":"Demo task form opened")}><Plus size={18}/>{ar?"مهمة جديدة":"New task"}</button>
        </header>

        {notice&&<div className="fixed bottom-6 start-1/2 z-[70] flex -translate-x-1/2 items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 font-bold text-white shadow-2xl"><CheckCircle2 className="text-emerald-400" size={19}/>{notice}</div>}
        {view==="dashboard"&&<OfficeDashboard ar={ar} go={changeView}/>} 
        {view==="clients"&&<ClientsView ar={ar} query={query} flash={flash}/>} 
        {view==="tasks"&&<TasksView ar={ar} query={query} flash={flash}/>} 
        {view==="review"&&<ReviewView ar={ar} flash={flash}/>} 
        {view==="team"&&<TeamView ar={ar}/>} 
        {view==="training"&&<TrainingView ar={ar} locale={locale}/>} 
        {view==="reports"&&<ReportsView ar={ar}/>} 
      </div>
    </div>
  </div>;
}

function OfficeDashboard({ ar, go }: { ar:boolean; go:(view:View)=>void }) {
  const stats = [
    ["21",ar?"عميل نشط":"Active clients",Building2,"text-blue-700 bg-blue-50"],
    ["28",ar?"مهمة مفتوحة":"Open tasks",ClipboardCheck,"text-violet-700 bg-violet-50"],
    ["4",ar?"مهام متأخرة":"Overdue tasks",AlertTriangle,"text-red-700 bg-red-50"],
    ["17",ar?"مستندًا ناقصًا":"Missing documents",FileText,"text-amber-700 bg-amber-50"],
    ["3",ar?"قيود للمراجعة":"Entries to review",ShieldCheck,"text-cyan-700 bg-cyan-50"],
    ["86%",ar?"إنجاز الشهر":"Monthly completion",CheckCircle2,"text-emerald-700 bg-emerald-50"],
  ] as const;
  return <div className="grid gap-5">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-l from-[#0d315c] via-[#124d83] to-[#0e7490] p-6 text-white shadow-xl md:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-white/80">{ar?"الأربعاء، 15 يوليو 2026":"Wednesday, 15 July 2026"}</span><h2 className="mt-4 text-3xl font-black">{ar?"صباح الخير، أ/ كريم":"Good morning, Kareem"}</h2><p className="mt-2 max-w-2xl text-white/70">{ar?"المكتب مستقر اليوم. توجد 3 قيود تحتاج اعتمادك و4 مهام تجاوزت موعدها.":"The office is stable. 3 entries need approval and 4 tasks are overdue."}</p></div><button onClick={()=>go("review")} className="flex items-center gap-3 self-start rounded-2xl bg-white px-5 py-3 font-black text-[#0d315c]"><ShieldCheck/>{ar?"ابدأ مراجعة اليوم":"Start today’s review"}<ChevronLeft size={17}/></button></div></section>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{stats.map(([value,label,Icon,color])=><article key={label} className="rounded-2xl border border-daftar-line bg-daftar-card p-4 shadow-sm"><span className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon size={20}/></span><b className="mt-4 block text-2xl font-black">{value}</b><small className="text-daftar-muted">{label}</small></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.45fr_.85fr]">
      <article className="rounded-3xl border border-daftar-line bg-daftar-card p-6 shadow-sm"><div className="flex items-center justify-between"><div><small className="font-bold text-daftar-primary">{ar?"أداء التنفيذ":"Execution performance"}</small><h3 className="mt-1 text-xl font-black">{ar?"المكتمل والمتأخر خلال 6 أشهر":"Completed vs overdue — 6 months"}</h3></div><BarChart3 className="text-daftar-muted"/></div><div className="mt-8 flex h-52 items-end justify-between gap-3">{[[58,12],[70,10],[66,17],[82,8],[76,14],[91,6]].map(([done,late],i)=><div className="flex h-full flex-1 items-end justify-center gap-1" key={i}><i style={{height:`${done}%`}} className="w-3 rounded-t-lg bg-[#1769aa] sm:w-5"/><i style={{height:`${late*2.4}%`}} className="w-3 rounded-t-lg bg-rose-400 sm:w-5"/></div>)}</div><div className="mt-3 flex justify-between text-xs text-daftar-muted">{(ar?["فبراير","مارس","أبريل","مايو","يونيو","يوليو"]:["Feb","Mar","Apr","May","Jun","Jul"]).map(x=><span key={x}>{x}</span>)}</div><div className="mt-5 flex gap-5 text-xs"><span><i className="me-2 inline-block h-2 w-2 rounded-full bg-[#1769aa]"/>{ar?"مكتملة":"Completed"}</span><span><i className="me-2 inline-block h-2 w-2 rounded-full bg-rose-400"/>{ar?"متأخرة":"Overdue"}</span></div></article>
      <article className="rounded-3xl border border-daftar-line bg-daftar-card p-6 shadow-sm"><small className="font-bold text-daftar-primary">{ar?"تحتاج تدخل المدير":"Needs manager action"}</small><h3 className="mt-1 text-xl font-black">{ar?"أولويات اليوم":"Today’s priorities"}</h3><div className="mt-5 grid gap-3">{[["إقرار ضريبة جاهز للاعتماد","شركة النيل للتوريدات","حرج"],["7 مستندات لم تصل","مطاعم بيت المذاق","متأخر"],["فرق في قيد صيانة","مركز الصفوة الطبي","250 ج.م"]].map(([title,client,badge],i)=><div key={title} className="flex gap-3 rounded-2xl border border-daftar-line p-4"><span className={`mt-1 h-3 w-3 shrink-0 rounded-full ${i===0?"bg-red-500":i===1?"bg-amber-500":"bg-blue-500"}`}/><span className="min-w-0 flex-1"><b className="block">{title}</b><small className="text-daftar-muted">{client}</small></span><small className="font-bold text-daftar-primary">{badge}</small></div>)}</div></article>
    </section>
    <section className="grid gap-5 xl:grid-cols-2"><PanelTitle title={ar?"آخر أنشطة المكتب":"Latest office activity"} icon={Activity}/><div className="-mt-3 grid gap-0 rounded-3xl border border-daftar-line bg-daftar-card p-5">{officeActivities.map((x,i)=><div className="flex gap-3 border-b border-daftar-line py-4 last:border-0" key={x}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-700">{i+1}</span><div><b className="text-sm">{x}</b><small className="mt-1 block text-daftar-muted">{i*12+8} {ar?"دقيقة":"min"}</small></div></div>)}</div></section>
  </div>;
}

function ClientsView({ ar, query, flash }: { ar:boolean; query:string; flash:(s:string)=>void }) {
  const clients=useMemo(()=>officeClients.filter(x=>(x.name+x.activity+x.accountant).includes(query)),[query]);
  return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm md:p-7"><PanelTitle title={ar?"ملفات العملاء ومستندات الشهر":"Client files & monthly documents"} icon={Building2} action={<button className="btn btn-primary" onClick={()=>flash(ar?"تم فتح نموذج إضافة عميل":"Client form opened")}><Plus size={17}/>{ar?"إضافة عميل":"Add client"}</button>}/><div className="mt-6 overflow-x-auto"><table className="min-w-[900px]"><thead><tr><th>{ar?"العميل":"Client"}</th><th>{ar?"المحاسب المسؤول":"Accountant"}</th><th>{ar?"اكتمال المستندات":"Documents"}</th><th>{ar?"الناقص":"Missing"}</th><th>{ar?"الحالة":"Status"}</th><th>{ar?"آخر رفع":"Last upload"}</th><th/></tr></thead><tbody>{clients.map(client=><tr key={client.id}><td><b>{client.name}</b><small className="mt-1 block text-daftar-muted">{client.id} · {client.activity}</small></td><td>{client.accountant}</td><td><div className="flex items-center gap-3"><div className="h-2 w-28 overflow-hidden rounded-full bg-slate-100"><i style={{width:`${client.completion}%`}} className="block h-full rounded-full bg-emerald-500"/></div><b>{client.completion}%</b></div></td><td><b className={client.missing>4?"text-red-600":"text-amber-600"}>{client.missing}</b></td><td><StatusBadge status={client.status}/></td><td className="text-sm text-daftar-muted">{client.lastUpload}</td><td><button className="btn" onClick={()=>flash(`${ar?"تم فتح ملف":"Opened"} ${client.name}`)}>{ar?"فتح الملف":"Open"}</button></td></tr>)}</tbody></table></div>
    <div className="mt-6 grid gap-3 md:grid-cols-3">{["فواتير المبيعات","كشف البنك","المستندات الضريبية"].map((title,i)=><article className="rounded-2xl border border-daftar-line p-4" key={title}><div className="flex items-center justify-between"><FileCheck2 className={i===1?"text-amber-500":"text-emerald-600"}/><StatusBadge status={i===1?"قيد المراجعة":"تم الرفع"}/></div><b className="mt-4 block">{title}</b><small className="text-daftar-muted">{i===1?"3 ملفات بانتظار المراجعة":"مكتمل لهذا الشهر"}</small></article>)}</div></section>;
}

function TasksView({ ar, query, flash }: { ar:boolean; query:string; flash:(s:string)=>void }) {
  const [mode,setMode]=useState<"kanban"|"table">("kanban");
  const tasks=officeTasks.filter(x=>(x.title+x.client+x.assignee).includes(query)); const columns=["جديدة","جاري العمل","انتظار العميل","جاهزة للمراجعة","مكتملة"] as const;
  return <section><PanelTitle title={ar?"إدارة مهام المكتب":"Office task management"} icon={ClipboardCheck} action={<div className="flex gap-2"><button className={`btn ${mode==="kanban"?"tab-active":""}`} onClick={()=>setMode("kanban")}>{ar?"لوحة":"Board"}</button><button className={`btn ${mode==="table"?"tab-active":""}`} onClick={()=>setMode("table")}>{ar?"جدول":"Table"}</button></div>}/>
    {mode==="kanban"?<div className="mt-6 grid gap-4 overflow-x-auto xl:grid-cols-5">{columns.map(col=><div className="min-w-[245px] rounded-2xl bg-[color-mix(in_srgb,var(--primary)_4%,var(--card))] p-3" key={col}><div className="mb-3 flex items-center justify-between"><b>{col}</b><span className="grid h-7 w-7 place-items-center rounded-full bg-daftar-card text-xs font-black">{tasks.filter(x=>x.status===col).length}</span></div><div className="grid gap-3">{tasks.filter(x=>x.status===col).map(task=><button onClick={()=>flash(`${ar?"تم فتح المهمة":"Opened task"} ${task.id}`)} className="rounded-2xl border border-daftar-line bg-daftar-card p-4 text-start shadow-sm transition hover:-translate-y-1 hover:shadow-lg" key={task.id}><span className="flex items-center justify-between gap-2"><small className="font-bold text-daftar-primary">{task.id}</small><Priority value={task.priority}/></span><b className="mt-3 block leading-6">{task.title}</b><small className="mt-2 block text-daftar-muted">{task.client}</small><div className="mt-4 flex items-center justify-between border-t border-daftar-line pt-3 text-xs"><span>{task.assignee}</span><span className={task.due==="14 يوليو"?"text-red-600":"text-daftar-muted"}>{task.due}</span></div></button>)}</div></div>)}</div>:<div className="mt-6 overflow-x-auto rounded-3xl border border-daftar-line bg-daftar-card"><table className="min-w-[950px]"><thead><tr><th>{ar?"المهمة":"Task"}</th><th>{ar?"العميل":"Client"}</th><th>{ar?"المسؤول":"Owner"}</th><th>{ar?"الأولوية":"Priority"}</th><th>{ar?"الحالة":"Status"}</th><th>{ar?"الإنجاز":"Progress"}</th></tr></thead><tbody>{tasks.map(x=><tr key={x.id}><td><b>{x.title}</b><small className="block text-daftar-muted">{x.id}</small></td><td>{x.client}</td><td>{x.assignee}</td><td><Priority value={x.priority}/></td><td><StatusBadge status={x.status}/></td><td><b>{x.progress}%</b></td></tr>)}</tbody></table></div>}
  </section>;
}

function ReviewView({ ar, flash }: { ar:boolean; flash:(s:string)=>void }) {
  const [selected,setSelected]=useState<(typeof officeEntries)[number]>(officeEntries[1]);
  return <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm"><PanelTitle title={ar?"قائمة القيود المطلوب مراجعتها":"Entries pending review"} icon={ShieldCheck}/><div className="mt-5 overflow-x-auto"><table className="min-w-[760px]"><thead><tr><th>{ar?"رقم القيد":"Entry"}</th><th>{ar?"العميل والمستند":"Client & document"}</th><th>{ar?"البيان":"Description"}</th><th>{ar?"الإجماليات":"Totals"}</th><th>{ar?"الحالة":"Status"}</th></tr></thead><tbody>{officeEntries.map(entry=><tr className={`cursor-pointer ${selected.id===entry.id?"bg-blue-50/70 dark:bg-blue-950/20":""}`} onClick={()=>setSelected(entry)} key={entry.id}><td><b className="text-daftar-primary">{entry.id}</b></td><td><b>{entry.client}</b><small className="block text-daftar-muted">{entry.document}</small></td><td>{entry.description}</td><td><span className={entry.debit!==entry.credit?"font-black text-red-600":""}>{entry.debit.toLocaleString()} / {entry.credit.toLocaleString()}</span></td><td><StatusBadge status={entry.risk}/></td></tr>)}</tbody></table></div></section>
    <aside className="rounded-3xl border border-daftar-line bg-daftar-card p-6 shadow-sm"><div className="flex items-center justify-between"><span><small className="text-daftar-muted">{ar?"تقرير الفحص":"Review report"}</small><h3 className="mt-1 text-xl font-black">{selected.id}</h3></span><span className={`grid h-12 w-12 place-items-center rounded-2xl ${selected.errors?"bg-red-50 text-red-600":"bg-emerald-50 text-emerald-600"}`}>{selected.errors?<AlertTriangle/>:<CheckCircle2/>}</span></div><div className="mt-6 grid gap-3"><InfoRow label={ar?"العميل":"Client"} value={selected.client}/><InfoRow label={ar?"رقم المستند":"Document"} value={selected.document}/><InfoRow label={ar?"عدد الأخطاء":"Errors"} value={String(selected.errors)}/></div>{selected.errors?<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-900"><b>{ar?"القيد غير متزن":"Entry is unbalanced"}</b><p className="mt-2 text-sm leading-6">{ar?`فرق ${Math.abs(selected.debit-selected.credit).toLocaleString()} ج.م. راجع حساب الدائن وقيمة الضريبة قبل الاعتماد.`:"Review credit and tax amount before approval."}</p></div>:<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-emerald-900"><b>{ar?"لم يتم اكتشاف أخطاء":"No errors detected"}</b></div>}<div className="mt-5 grid grid-cols-2 gap-2"><button className="btn" onClick={()=>flash(ar?"تم إرجاع القيد للتعديل":"Entry returned")}>{ar?"إرجاع":"Return"}</button><button disabled={selected.errors>0} className="btn btn-primary" onClick={()=>flash(ar?"تم اعتماد القيد تجريبيًا":"Entry approved")}>{ar?"اعتماد":"Approve"}</button></div></aside>
  </div>;
}

function TeamView({ ar }: { ar:boolean }) { return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-6 shadow-sm"><PanelTitle title={ar?"فريق المكتب والأحمال":"Team performance & workload"} icon={Users}/><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{officeTeam.map((person,i)=><article className="rounded-2xl border border-daftar-line p-5" key={person.name}><div className="flex items-center gap-3"><span className={`grid h-12 w-12 place-items-center rounded-2xl text-lg font-black ${["bg-blue-100 text-blue-700","bg-emerald-100 text-emerald-700","bg-violet-100 text-violet-700","bg-amber-100 text-amber-700"][i]}`}>{person.name.split(" ").map(x=>x[0]).join("")}</span><span><b className="block">{person.name}</b><small className="text-daftar-muted">{person.role}</small></span></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric label={ar?"عملاء":"Clients"} value={person.clients}/><Metric label={ar?"مفتوحة":"Open"} value={person.open}/><Metric label={ar?"متأخرة":"Late"} value={person.late}/></div><div className="mt-5 flex items-center justify-between"><span className="text-sm text-daftar-muted">{ar?"معدل الأداء":"Performance"}</span><b className="text-emerald-600">{person.performance}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-emerald-500" style={{width:`${person.performance}%`}}/></div></article>)}</div></section>; }

function TrainingView({ ar, locale }: { ar:boolean; locale:Locale }) { const [checked,setChecked]=useState(false); return <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><section className="rounded-3xl bg-[#0d315c] p-7 text-white shadow-xl"><GraduationCap size={34}/><small className="mt-6 block text-white/60">{ar?"تمرين عملي — مستوى متوسط":"Practice — intermediate"}</small><h2 className="mt-2 text-2xl font-black">{ar?"سجل قيد شراء أصل ثابت":"Record a fixed-asset purchase"}</h2><p className="mt-3 leading-7 text-white/70">{ar?"اشترت شركة النيل جهاز حاسب بمبلغ 30,000 ج.م وضريبة 14%، وتم السداد من البنك.":"A client purchased a computer for EGP 30,000 plus 14% VAT, paid by bank."}</p><div className="mt-6 flex gap-5 text-sm"><span><b className="block text-xl">15</b>{ar?"نقطة":"points"}</span><span><b className="block text-xl">8</b>{ar?"دقائق":"minutes"}</span></div></section><section className="rounded-3xl border border-daftar-line bg-daftar-card p-6 shadow-sm"><PanelTitle title={ar?"حل المتدرب":"Trainee answer"} icon={BookOpenCheck}/><div className="mt-5 overflow-x-auto"><table className="min-w-[620px]"><thead><tr><th>{ar?"الحساب":"Account"}</th><th>{ar?"مدين":"Debit"}</th><th>{ar?"دائن":"Credit"}</th></tr></thead><tbody><tr><td>{ar?"أجهزة الحاسب":"Computer equipment"}</td><td>30,000</td><td>—</td></tr><tr><td>{ar?"ضريبة مدخلات":"Input VAT"}</td><td>4,200</td><td>—</td></tr><tr><td>{ar?"البنك":"Bank"}</td><td>—</td><td>34,200</td></tr></tbody></table></div>{checked&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-900"><div className="flex items-center gap-2"><CheckCircle2/><b>{ar?"إجابة صحيحة — 15/15":"Correct — 15/15"}</b></div><p className="mt-2 text-sm leading-6">{ar?"الأصل وضريبة المدخلات زادا في الجانب المدين، والبنك انخفض في الجانب الدائن. يزيد إجمالي الأصول غير المتداولة 30,000 وتنتقل 4,200 كرصيد ضريبي قابل للخصم وفق المعالجة المعتمدة.":"Asset and input VAT increase on debit; bank decreases on credit."}</p></div>}<div className="mt-5 flex gap-2"><button className="btn btn-primary" onClick={()=>setChecked(true)}>{ar?"تحقق من الحل":"Check answer"}</button><Link className="btn" href={`/${locale}/academy`}>{ar?"فتح الأكاديمية":"Open academy"}</Link></div></section></div>; }

function ReportsView({ ar }: { ar:boolean }) { const reports=[["حالة العملاء","21 عميلًا"],["المستندات الناقصة","17 مستندًا"],["المهام المتأخرة","4 مهام"],["أداء الموظفين","متوسط 90%"],["أخطاء القيود","3 قيود"],["نتائج المتدربين","84% متوسط"]]; return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-6 shadow-sm print:border-0 print:shadow-none"><PanelTitle title={ar?"تقارير إدارة المكتب":"Office management reports"} icon={BarChart3} action={<button className="btn btn-primary no-print" onClick={()=>window.print()}><Printer size={17}/>{ar?"طباعة التقرير":"Print report"}</button>}/><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reports.map(([name,value],i)=><article className="rounded-2xl border border-daftar-line p-5" key={name}><span className={`grid h-10 w-10 place-items-center rounded-xl ${i%2?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}><FileText size={20}/></span><b className="mt-4 block">{name}</b><strong className="mt-2 block text-2xl">{value}</strong><small className="text-daftar-muted">{ar?"الفترة: يوليو 2026":"July 2026"}</small></article>)}</div><div className="mt-6 rounded-2xl border border-daftar-line p-5"><div className="flex items-center justify-between"><b>{ar?"إنجاز خدمات المكتب":"Service completion"}</b><span className="text-sm text-daftar-muted">{ar?"يوليو 2026":"July 2026"}</span></div><div className="mt-7 grid gap-4">{[["إمساك الدفاتر",91],["الضرائب",83],["الرواتب",76],["مراجعة القيود",88]].map(([name,value])=><div className="grid grid-cols-[120px_1fr_45px] items-center gap-3" key={String(name)}><span className="text-sm">{name}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-[#1769aa]" style={{width:`${value}%`}}/></div><b>{value}%</b></div>)}</div></div></section>; }

function PanelTitle({ title, icon:Icon, action }: { title:string; icon:Icon; action?:React.ReactNode }) { return <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-[#1769aa]"><Icon size={21}/></span><h2 className="m-0 text-xl font-black">{title}</h2></div>{action}</div>; }
function StatusBadge({ status }: { status:string }) { const color=status==="منتظم"||status==="تم الرفع"||status==="مكتملة"||status==="سليم"?"bg-emerald-100 text-emerald-800":status==="متأخر"||status==="حرج"?"bg-red-100 text-red-800":status==="قيد المراجعة"||status==="جاري العمل"?"bg-blue-100 text-blue-800":"bg-amber-100 text-amber-800"; return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-black ${color}`}>{status}</span>; }
function Priority({ value }: { value:string }) { const color=value==="حرجة"?"bg-red-100 text-red-700":value==="عالية"?"bg-amber-100 text-amber-700":value==="متوسطة"?"bg-blue-100 text-blue-700":"bg-slate-100 text-slate-600"; return <span className={`rounded-full px-2 py-1 text-[11px] font-black ${color}`}>{value}</span>; }
function InfoRow({ label,value }: { label:string; value:string }) { return <div className="flex justify-between gap-4 border-b border-daftar-line pb-3"><span className="text-sm text-daftar-muted">{label}</span><b className="text-sm">{value}</b></div>; }
function Metric({ label,value }: { label:string; value:number }) { return <span className="rounded-xl bg-daftar-bg p-2"><b className="block text-lg">{value}</b><small className="text-daftar-muted">{label}</small></span>; }
