import type { CellValue, SheetData } from "@/types";

export interface SpreadsheetReadProgress { stage: "opening" | "parsing" | "normalizing" | "done"; percent: number; sheet?: string }
export interface SpreadsheetReadOptions { onProgress?: (progress: SpreadsheetReadProgress) => void }
const MAX_BROWSER_FILE_BYTES = 120 * 1024 * 1024;
const yieldToBrowser = () => new Promise<void>((resolve) => window.setTimeout(resolve, 0));

export const spreadsheetCellValue = (value: unknown): CellValue => {
  if (value === null || value === undefined || value === "") return null;
  if (value instanceof Date || typeof value === "number" || typeof value === "boolean") return value as CellValue;
  const text = String(value).replace(/[\u200E\u200F\u202A-\u202E]/g, "").replace(/\u00a0/g, " ").trim(), percentage = /[%٪]$/.test(text), negative = /^\(.*\)$/.test(text) || /-$/.test(text);
  const western = text.replace(/[٠-٩]/g, (digit) => String("٠١٢٣٤٥٦٧٨٩".indexOf(digit))).replace(/[۰-۹]/g, (digit) => String("۰۱۲۳۴۵۶۷۸۹".indexOf(digit)));
  if (/^0\d{2,}$/.test(western.replace(/\s/g,""))) return text;
  let normalized = western.replace(/^(egp|usd|sar|aed|ج\.?م|ر\.?س)\s*/i, "").replace(/\s*(egp|usd|sar|aed|ج\.?م|ر\.?س)$/i, "").replace(/[\s()]/g, "").replace(/[٪%]$/g, "").replace(/-$/, "").replace(/٫/g, ".").replace(/٬/g, ",");
  if (normalized.includes(",") && normalized.includes(".")) normalized = normalized.lastIndexOf(",") > normalized.lastIndexOf(".") ? normalized.replace(/\./g, "").replace(",", ".") : normalized.replace(/,/g, "");
  else if ((normalized.match(/,/g)||[]).length === 1 && /,\d{1,2}$/.test(normalized)) normalized = normalized.replace(",", "."); else normalized = normalized.replace(/,/g, "");
  const number = Number(normalized);
  if (text && Number.isFinite(number) && /[\d٠-٩۰-۹]/.test(text)) { const result = negative ? -Math.abs(number) : number; return percentage ? result / 100 : result; }
  return text;
};

function detectDelimiter(text: string) {
  const lines = text.slice(0, 40_000).split(/\r?\n/).filter(Boolean).slice(0, 30), candidates = [",", ";", "\t", "|"];
  return candidates.map((delimiter) => { const counts = lines.map((line) => line.split(delimiter).length - 1), positive = counts.filter(Boolean), average = positive.reduce((sum, count) => sum + count, 0) / Math.max(1, positive.length), variance = positive.reduce((sum, count) => sum + Math.abs(count - average), 0) / Math.max(1, positive.length); return { delimiter, score: positive.length * 10 + average - variance }; }).sort((a, b) => b.score - a.score)[0].delimiter;
}

function parseDelimited(text: string): CellValue[][] {
  const delimiter = detectDelimiter(text), rows: CellValue[][] = [], row: string[] = []; let value = "", quoted = false;
  const pushCell = () => { row.push(value.trim()); value = ""; };
  for (let index = 0; index < text.length; index++) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { value += '"'; index++; } else quoted = !quoted; continue; } if (char === delimiter && !quoted) { pushCell(); continue; } if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index++; pushCell(); if (row.some((cell) => cell !== "")) rows.push(row.map(spreadsheetCellValue)); row.length = 0; continue; } value += char; }
  pushCell(); if (row.some((cell) => cell !== "")) rows.push(row.map(spreadsheetCellValue)); return rows;
}

const headerWords=/(date|description|amount|total|name|code|category|account|debit|credit|balance|qty|quantity|price|التاريخ|البيان|الوصف|المبلغ|الإجمالي|الاجمالي|الاسم|الكود|الحساب|مدين|دائن|الرصيد|الكمية|السعر)/i;
function headerScore(row: CellValue[], following:CellValue[][]) { const values = row.filter((value) => value !== null && value !== ""), strings = values.filter((value) => typeof value === "string"), unique = new Set(strings.map((value) => String(value).trim().toLowerCase())).size; if (values.length < 2) return -Infinity; const density=values.length/Math.max(1,row.length), known=strings.filter(value=>headerWords.test(String(value))).length, nextDensity=following.length?following.reduce((sum,next)=>sum+next.filter(value=>value!==null&&value!=="").length/Math.max(1,row.length),0)/following.length:0; return strings.length*4+unique*2+values.length+known*5+density*4+nextDensity*5-values.filter(value=>typeof value==="number").length*4-(values.length===1?20:0); }
function uniqueHeaders(values: CellValue[], width: number) { const seen = new Map<string, number>(); return Array.from({ length: width }, (_, index) => { const raw = String(values[index] ?? "").trim() || `Column ${index + 1}`, count = (seen.get(raw) || 0) + 1; seen.set(raw, count); return count === 1 ? raw : `${raw} (${count})`; }); }
export function normalizeSheet(name: string, matrix: CellValue[][]): SheetData { const nonEmpty: CellValue[][] = []; let width = 0; for (const row of matrix) { if (!row.some((value) => value !== null && value !== "")) continue; nonEmpty.push(row); width = Math.max(width, row.length); } if (!nonEmpty.length) return { name, headers: [], rows: [],readDiagnostics:{headerConfidence:0,titleRowsSkipped:0,blankRowsRemoved:matrix.length,blankColumnsRemoved:0,sourceColumnCount:0,warnings:["Empty sheet"]} }; const searchLimit = Math.min(60, nonEmpty.length), ranked:Array<{index:number;score:number}>=[]; for (let index = 0; index < searchLimit; index++) ranked.push({index,score:headerScore(nonEmpty[index],nonEmpty.slice(index+1,index+7))-index*.12}); ranked.sort((a,b)=>b.score-a.score); const best=ranked[0]?.index||0,bestScore=ranked[0]?.score||0,secondScore=ranked[1]?.score||0; const used = new Uint8Array(width); for (let rowIndex = best; rowIndex < nonEmpty.length; rowIndex++) for (let column = 0; column < nonEmpty[rowIndex].length; column++) if (nonEmpty[rowIndex][column] !== null && nonEmpty[rowIndex][column] !== "") used[column] = 1; const keepColumns = Array.from({ length: width }, (_, index) => index).filter((index) => used[index]); const headers = uniqueHeaders(keepColumns.map((index) => nonEmpty[best][index]), keepColumns.length), rows = nonEmpty.slice(best + 1).map((row) => keepColumns.map((index) => row[index] ?? null)).filter((row) => row.some((value) => value !== null && value !== "")); const headerConfidence=Math.max(20,Math.min(99,Math.round(62+(bestScore-secondScore)*3+(headers.filter(header=>!/^Column \d+$/.test(header)).length/Math.max(1,headers.length))*25))); const warnings:string[]=[]; if(headerConfidence<65)warnings.push("Header row needs review");if(best>0)warnings.push(`${best} title or note rows skipped`);const blankColumnsRemoved=width-keepColumns.length;if(blankColumnsRemoved)warnings.push(`${blankColumnsRemoved} empty columns removed`); return { name: name || "Sheet", headers, rows, headerRowIndex: best, sourceRowCount: nonEmpty.length,readDiagnostics:{headerConfidence,titleRowsSkipped:best,blankRowsRemoved:matrix.length-nonEmpty.length,blankColumnsRemoved,sourceColumnCount:width,warnings} }; }

export async function readSpreadsheet(file: File, options: SpreadsheetReadOptions = {}): Promise<SheetData[]> { const report = (stage: SpreadsheetReadProgress["stage"], percent: number, sheet?: string) => options.onProgress?.({ stage, percent, sheet }), lower = file.name.toLowerCase(); if (file.size > MAX_BROWSER_FILE_BYTES) throw new Error("The workbook is over 120 MB. Split it into smaller workbooks for safe browser analysis."); if (lower.endsWith(".xls")) throw new Error("Legacy .xls is not supported. Save the workbook as .xlsx first."); report("opening", 5); if (lower.endsWith(".csv") || file.type.includes("csv")) { const buffer = await file.arrayBuffer(); let text = new TextDecoder("utf-8").decode(buffer); if ((text.match(/\uFFFD/g) || []).length > 2) try { text = new TextDecoder("windows-1256").decode(buffer); } catch {} text = text.replace(/^\uFEFF/, ""); report("parsing", 35); await yieldToBrowser(); const result = normalizeSheet(file.name.replace(/\.csv$/i, ""), parseDelimited(text)); report("done", 100, result.name); return [result]; } if (!lower.endsWith(".xlsx")) throw new Error("Supported formats are .xlsx and .csv"); report("parsing", 15); const excelReader = await import("read-excel-file/browser"), workbook = await excelReader.default(file), sheets: SheetData[] = []; for (let index = 0; index < workbook.length; index++) { const sheet = workbook[index]; report("normalizing", 25 + Math.round(index / Math.max(1, workbook.length) * 70), sheet.sheet); await yieldToBrowser(); sheets.push(normalizeSheet(sheet.sheet, sheet.data.map((row) => row.map(spreadsheetCellValue)))); } report("done", 100); return sheets; }
