"use client";
import { useEffect, useMemo, useState } from "react";
import { Landmark, MapPinned, Scale, TrendingDown, TrendingUp } from "lucide-react";
import { analyzeEntryImpact } from "@/lib/accounting/impact";
import { loadAccounts } from "@/lib/storage/accounting";
import type { ChartAccount, FinancialStatementSection, GeneratedJournalEntry, Locale } from "@/types";

const sections: Record<FinancialStatementSection, { ar: string; en: string }> = {
  "current-assets": { ar: "الميزانية ← الأصول المتداولة", en: "Balance sheet → Current assets" }, "non-current-assets": { ar: "الميزانية ← الأصول غير المتداولة", en: "Balance sheet → Non-current assets" },
  "current-liabilities": { ar: "الميزانية ← الالتزامات المتداولة", en: "Balance sheet → Current liabilities" }, "non-current-liabilities": { ar: "الميزانية ← الالتزامات غير المتداولة", en: "Balance sheet → Non-current liabilities" },
  equity: { ar: "الميزانية ← حقوق الملكية", en: "Balance sheet → Equity" }, "operating-revenue": { ar: "قائمة الدخل ← إيرادات النشاط", en: "Income statement → Operating revenue" },
  "other-revenue": { ar: "قائمة الدخل ← الإيرادات الأخرى", en: "Income statement → Other revenue" }, "cost-of-sales": { ar: "قائمة الدخل ← تكلفة المبيعات", en: "Income statement → Cost of sales" },
  "operating-expenses": { ar: "قائمة الدخل ← المصروفات التشغيلية", en: "Income statement → Operating expenses" }, "other-expenses": { ar: "قائمة الدخل ← المصروفات الأخرى", en: "Income statement → Other expenses" },
};
const signed = (value: number, ar: boolean) => value === 0 ? "—" : `${value > 0 ? "↑" : "↓"} ${Math.abs(value).toLocaleString(ar ? "ar-EG" : "en-US")}`;

export function EntryImpact({ entry, locale, title }: { entry: GeneratedJournalEntry; locale: Locale; title?: string }) {
  const ar = locale === "ar", [accounts, setAccounts] = useState<ChartAccount[]>([]);
  useEffect(() => { setAccounts(loadAccounts()); }, []);
  const impact = useMemo(() => analyzeEntryImpact(entry, accounts), [entry, accounts]);
  return <section className="card" data-entry-impact-id={entry.id} style={{ borderInlineStart: "5px solid var(--primary)" }}><h2><Landmark size={21} /> {title || (ar ? "أين سيظهر هذا القيد وما تأثيره؟" : "Where will this entry appear?")}</h2><p className="muted">{ar ? "التحليل مبني على الحسابات الفعلية داخل القيد ويتغير تلقائيًا عند تغيير أي حساب." : "Calculated from the actual accounts in this entry and updates when an account changes."}</p>
    <div className="grid four"><ImpactMetric title={ar ? "صافي الأصول" : "Net assets"} value={impact.assets} ar={ar} /><ImpactMetric title={ar ? "صافي الالتزامات" : "Net liabilities"} value={impact.liabilities} ar={ar} /><ImpactMetric title={ar ? "صافي الربح" : "Net profit"} value={impact.profit} ar={ar} /><ImpactMetric title={ar ? "إجمالي أثر حقوق الملكية" : "Total equity effect"} value={impact.totalEquity} ar={ar} /></div>
    <div className="table-wrap section"><table><thead><tr><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "ماذا حدث؟" : "Movement"}</th><th>{ar ? "يظهر فين بالضبط؟" : "Exact location"}</th><th>{ar ? "أثره النهائي" : "Final effect"}</th></tr></thead><tbody>{impact.lines.map((line) => <tr key={line.lineId}><td><b>{line.code || "—"} — {ar ? line.nameAr : line.nameEn}</b><br /><small className="muted">{line.debit ? `${ar ? "مدين" : "Debit"}: ${line.debit.toLocaleString()}` : `${ar ? "دائن" : "Credit"}: ${line.credit.toLocaleString()}`}</small></td><td><span className={line.movement === "increase" ? "badge" : "badge error"}>{line.movement === "increase" ? <TrendingUp size={15} /> : <TrendingDown size={15} />}{line.movement === "increase" ? (ar ? "زاد" : "Increased") : (ar ? "نقص" : "Decreased")} {line.amount.toLocaleString()}</span></td><td><span className="actions"><MapPinned size={16} />{ar ? sections[line.section].ar : sections[line.section].en}</span></td><td>{explainLine(line.type, line.statementDelta, ar)}</td></tr>)}</tbody></table></div>
    <div className="grid two"><div className="warning"><b><Scale size={17} /> {ar ? "معادلة الميزانية بعد القيد" : "Accounting equation effect"}</b><p>{ar ? `الأصول ${signed(impact.assets, ar)} = الالتزامات ${signed(impact.liabilities, ar)} + حقوق الملكية ${signed(impact.totalEquity, ar)}` : `Assets ${signed(impact.assets, ar)} = Liabilities ${signed(impact.liabilities, ar)} + Equity ${signed(impact.totalEquity, ar)}`}</p><span className={impact.balancedEffect ? "badge" : "badge error"}>{impact.balancedEffect ? (ar ? "الأثر متوازن" : "Balanced effect") : (ar ? "راجع تصنيف الحسابات" : "Review account mapping")}</span></div><div className="warning"><b>{ar ? "الخلاصة" : "Summary"}</b><p>{summary(impact, ar)}</p>{impact.cash !== 0 && <p><b>{ar ? "النقدية:" : "Cash:"}</b> {impact.cash > 0 ? (ar ? "زادت" : "increased") : (ar ? "نقصت" : "decreased")} {Math.abs(impact.cash).toLocaleString()}</p>}</div></div>
  </section>;
}

function ImpactMetric({ title, value, ar }: { title: string; value: number; ar: boolean }) { return <div><small className="muted">{title}</small><div className="impact" style={{ color: value > 0 ? "#087443" : value < 0 ? "#b42318" : "inherit" }}>{signed(value, ar)}</div></div>; }
function explainLine(type: string, delta: number, ar: boolean) { const up = delta >= 0, amount = Math.abs(delta).toLocaleString(); if (type === "expense") return ar ? `${up ? "يزيد المصروف ويخفض" : "يخفض المصروف ويرفع"} الربح وحقوق الملكية بمبلغ ${amount}` : `${up ? "Raises expense and reduces" : "Reduces expense and raises"} profit and equity by ${amount}`; if (type === "revenue") return ar ? `${up ? "يزيد" : "يخفض"} الإيراد والربح وحقوق الملكية بمبلغ ${amount}` : `${up ? "Raises" : "Reduces"} revenue, profit, and equity by ${amount}`; const label = ar ? ({ asset: "الأصول", liability: "الالتزامات", equity: "حقوق الملكية" } as Record<string, string>)[type] : type; return ar ? `${up ? "يزيد" : "يخفض"} ${label} بمبلغ ${amount}` : `${up ? "Increases" : "Decreases"} ${label} by ${amount}`; }
function summary(impact: ReturnType<typeof analyzeEntryImpact>, ar: boolean) { if (impact.profit === 0 && impact.assets === 0 && impact.liabilities === 0 && impact.totalEquity === 0) return ar ? "إعادة تصنيف بين حسابات داخل نفس القائمة؛ لا يغيّر إجمالي الميزانية أو الربح." : "A reclassification with no change to total assets, liabilities, equity, or profit."; if (impact.profit !== 0) return ar ? `القيد ${impact.profit > 0 ? "يرفع" : "يخفض"} صافي الربح بمبلغ ${Math.abs(impact.profit).toLocaleString()}، وينعكس بنفس القيمة على حقوق الملكية.` : `The entry ${impact.profit > 0 ? "increases" : "decreases"} profit by ${Math.abs(impact.profit).toLocaleString()} and equity by the same amount.`; return ar ? "القيد يؤثر على بنود الميزانية فقط ولا يؤثر مباشرة على الربح." : "The entry affects balance-sheet items only and has no direct profit impact."; }
