"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Copy, Download, Eye, FileCheck2, Printer, RotateCcw, Search, Send, X } from "lucide-react";
import { JOURNAL_SOURCE_LABELS, JOURNAL_STATUS_LABELS } from "@/lib/accounting/journal";
import { validateJournalEntry } from "@/lib/accounting/validation";
import { loadAccounts, loadEntries, reverseStoredEntry, saveEntry, subscribeToEntries, transitionStoredEntry } from "@/lib/storage/accounting";
import type { ChartAccount, EntryWorkflowStatus, GeneratedJournalEntry, JournalEntrySource, Locale } from "@/types";

const statuses = Object.keys(JOURNAL_STATUS_LABELS) as EntryWorkflowStatus[];
const sources = Object.keys(JOURNAL_SOURCE_LABELS) as JournalEntrySource[];
const money = (value: number, ar: boolean) => value.toLocaleString(ar ? "ar-EG" : "en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const tone = (status: EntryWorkflowStatus) => status === "posted" ? "success" : status === "rejected" || status === "reversed" ? "error" : "badge";

export function JournalCenter({ locale }: { locale: Locale }) {
  const ar = locale === "ar", [entries, setEntries] = useState<GeneratedJournalEntry[]>([]), [accounts, setAccounts] = useState<ChartAccount[]>([]), [selectedId, setSelectedId] = useState(""), [message, setMessage] = useState("");
  const [query, setQuery] = useState(""), [statusFilter, setStatusFilter] = useState("all"), [sourceFilter, setSourceFilter] = useState("all"), [period, setPeriod] = useState(""), [account, setAccount] = useState(""), [party, setParty] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState("");
  useEffect(() => { setEntries(loadEntries()); setAccounts(loadAccounts()); return subscribeToEntries(setEntries); }, []);
  const selected = entries.find((entry) => entry.id === selectedId);
  const filtered = useMemo(() => entries.filter((entry) => {
    const haystack = `${entry.entryNumber} ${entry.reference || ""} ${entry.narrationAr} ${entry.narrationEn} ${entry.partyName || ""}`.toLowerCase();
    return (!query || haystack.includes(query.toLowerCase())) && (statusFilter === "all" || (entry.workflowStatus || "draft") === statusFilter) && (sourceFilter === "all" || entry.source === sourceFilter) && (!period || entry.fiscalPeriodId === period) && (!from || entry.date >= from) && (!to || entry.date <= to) && (!account || entry.lines.some((line) => line.accountCode === account)) && (!party || (entry.partyName || "").toLowerCase().includes(party.toLowerCase()));
  }), [entries, query, statusFilter, sourceFilter, period, from, to, account, party]);
  const count = (status: EntryWorkflowStatus) => entries.filter((entry) => (entry.workflowStatus || "draft") === status).length;
  const act = (entry: GeneratedJournalEntry, next: EntryWorkflowStatus) => { try { const note = next === "rejected" ? prompt(ar ? "اكتب سبب الرفض" : "Rejection reason") || "" : undefined; if (next === "rejected" && !note) return; const updated = transitionStoredEntry(entry.id, next, note); setSelectedId(updated.id); setMessage(ar ? "تم تحديث حالة القيد وحفظها في سجل المراجعة." : "Entry status and audit trail updated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update entry"); } };
  const reverse = (entry: GeneratedJournalEntry) => { const reason = prompt(ar ? "اكتب سبب العكس" : "Reversal reason"); if (!reason) return; try { const result = reverseStoredEntry(entry.id, reason); setSelectedId(result.reversal.id); setMessage(ar ? "تم إنشاء قيد عكسي مرتبط بالأصل وترحيله، ولم يُحذف القيد الأصلي." : "A linked reversal was created and posted; the original was retained."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not reverse entry"); } };
  const duplicate = (entry: GeneratedJournalEntry) => { const copy = saveEntry({ ...entry, id: crypto.randomUUID(), entryNumber: "", workflowStatus: "draft", originalEntryId: undefined, reversalEntryId: undefined, approvedAt: undefined, postedAt: undefined, rejectedAt: undefined, reversedAt: undefined, audit: [], reference: entry.reference ? `${entry.reference}-COPY` : undefined, lines: entry.lines.map((line) => ({ ...line, id: crypto.randomUUID() })) }); setSelectedId(copy.id); setMessage(ar ? "تم إنشاء نسخة جديدة كمسودة." : "A new draft copy was created."); };
  const edit = (entry: GeneratedJournalEntry) => { const narration = prompt(ar ? "عدّل بيان القيد" : "Edit narration", ar ? entry.narrationAr : entry.narrationEn); if (!narration) return; const reference = prompt(ar ? "عدّل المرجع" : "Edit reference", entry.reference || "") ?? entry.reference; const updated = saveEntry({ ...entry, narrationAr: ar ? narration : entry.narrationAr, narrationEn: ar ? entry.narrationEn : narration, reference }); setSelectedId(updated.id); setMessage(ar ? "تم حفظ تعديل المسودة." : "Draft changes saved."); };
  const exportEntry = (entry: GeneratedJournalEntry) => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(entry, null, 2)], { type: "application/json" })); link.download = `${entry.entryNumber}.json`; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="grid journal-center">
    <section className="grid four">{statuses.map((status) => <button key={status} className="card text-start" onClick={() => setStatusFilter(status)}><span className="muted">{ar ? JOURNAL_STATUS_LABELS[status].ar : JOURNAL_STATUS_LABELS[status].en}</span><strong className="impact">{count(status)}</strong></button>)}</section>
    <section className="card no-print"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2>{ar ? "البحث والتصفية" : "Search and filters"}</h2><p className="muted">{ar ? `إجمالي القيود: ${entries.length}` : `Total entries: ${entries.length}`}</p></div><button className="btn" onClick={() => window.print()}><Printer size={16}/>{ar ? "طباعة" : "Print"}</button></div>
      <div className="grid four"><label><span>{ar ? "بحث" : "Search"}</span><span className="input-icon"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={ar ? "رقم القيد أو المرجع أو البيان" : "Entry, reference, or narration"}/></span></label><label>{ar ? "الحالة" : "Status"}<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">{ar ? "كل الحالات" : "All statuses"}</option>{statuses.map((item) => <option key={item} value={item}>{ar ? JOURNAL_STATUS_LABELS[item].ar : JOURNAL_STATUS_LABELS[item].en}</option>)}</select></label><label>{ar ? "المصدر" : "Source"}<select value={sourceFilter} onChange={(event) => setSourceFilter(event.target.value)}><option value="all">{ar ? "كل المصادر" : "All sources"}</option>{sources.map((item) => <option key={item} value={item}>{ar ? JOURNAL_SOURCE_LABELS[item].ar : JOURNAL_SOURCE_LABELS[item].en}</option>)}</select></label><label>{ar ? "الفترة" : "Period"}<input type="month" value={period} onChange={(event) => setPeriod(event.target.value)}/></label><label>{ar ? "من تاريخ" : "From"}<input type="date" value={from} onChange={(event) => setFrom(event.target.value)}/></label><label>{ar ? "إلى تاريخ" : "To"}<input type="date" value={to} onChange={(event) => setTo(event.target.value)}/></label><label>{ar ? "الحساب" : "Account"}<select value={account} onChange={(event) => setAccount(event.target.value)}><option value="">{ar ? "كل الحسابات" : "All accounts"}</option>{accounts.filter((item) => item.active).map((item) => <option key={item.id} value={item.code}>{item.code} — {ar ? item.nameAr : item.nameEn}</option>)}</select></label><label>{ar ? "الطرف" : "Party"}<input value={party} onChange={(event) => setParty(event.target.value)} placeholder={ar ? "عميل أو مورد" : "Customer or supplier"}/></label></div>
    </section>
    {message && <div className="warning">{message}</div>}
    <section className="card"><div className="table-wrap"><table><thead><tr><th>{ar ? "رقم القيد" : "Entry No."}</th><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "البيان" : "Narration"}</th><th>{ar ? "المصدر" : "Source"}</th><th>{ar ? "المرجع" : "Reference"}</th><th>{ar ? "المدين" : "Debit"}</th><th>{ar ? "الدائن" : "Credit"}</th><th>{ar ? "الحالة" : "Status"}</th><th className="no-print">{ar ? "التفاصيل" : "Details"}</th></tr></thead><tbody>{filtered.map((entry) => { const status = entry.workflowStatus || "draft"; return <tr key={entry.id}><td dir="ltr"><b>{entry.entryNumber}</b></td><td dir="ltr">{entry.date}</td><td>{ar ? entry.narrationAr : entry.narrationEn}</td><td>{ar ? JOURNAL_SOURCE_LABELS[entry.source || "legacy"].ar : JOURNAL_SOURCE_LABELS[entry.source || "legacy"].en}</td><td dir="ltr">{entry.reference || "—"}</td><td>{money(entry.totalDebit, ar)}</td><td>{money(entry.totalCredit, ar)}</td><td><span className={`badge ${tone(status)}`}>{ar ? JOURNAL_STATUS_LABELS[status].ar : JOURNAL_STATUS_LABELS[status].en}</span></td><td className="no-print"><button className="btn" onClick={() => setSelectedId(entry.id)}><Eye size={15}/>{ar ? "فتح" : "Open"}</button></td></tr>; })}{!filtered.length && <tr><td colSpan={9}>{ar ? "لا توجد قيود مطابقة." : "No matching entries."}</td></tr>}</tbody></table></div></section>
    {selected && <JournalDetails entry={selected} locale={locale} accounts={accounts} onClose={() => setSelectedId("")} onAct={act} onEdit={edit} onReverse={reverse} onDuplicate={duplicate} onExport={exportEntry}/>} 
  </div>;
}

function JournalDetails({ entry, locale, accounts, onClose, onAct, onEdit, onReverse, onDuplicate, onExport }: { entry: GeneratedJournalEntry; locale: Locale; accounts: ChartAccount[]; onClose: () => void; onAct: (entry: GeneratedJournalEntry, next: EntryWorkflowStatus) => void; onEdit: (entry: GeneratedJournalEntry) => void; onReverse: (entry: GeneratedJournalEntry) => void; onDuplicate: (entry: GeneratedJournalEntry) => void; onExport: (entry: GeneratedJournalEntry) => void }) {
  const ar = locale === "ar", status = entry.workflowStatus || "draft", validation = validateJournalEntry(entry, accounts), source = JOURNAL_SOURCE_LABELS[entry.source || "legacy"];
  const timeline: EntryWorkflowStatus[] = ["draft", "review", "approved", "posted"], reached = status === "rejected" ? 1 : status === "reversed" ? 3 : timeline.indexOf(status);
  return <section className="card journal-details" id="journal-entry-details"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="badge">{ar ? JOURNAL_STATUS_LABELS[status].ar : JOURNAL_STATUS_LABELS[status].en}</span><h2 dir="ltr">{entry.entryNumber}</h2><p>{ar ? entry.narrationAr : entry.narrationEn}</p></div><button className="btn no-print" onClick={onClose}><X size={17}/>{ar ? "إغلاق" : "Close"}</button></div>
    <div className="grid four"><Info label={ar ? "التاريخ" : "Date"} value={entry.date} ltr/><Info label={ar ? "الفترة" : "Period"} value={entry.fiscalPeriodId || entry.date.slice(0, 7)} ltr/><Info label={ar ? "المصدر" : "Source"} value={ar ? source.ar : source.en}/><Info label={ar ? "المرجع" : "Reference"} value={entry.reference || "—"} ltr/></div>
    <div className="journal-timeline">{timeline.map((item, index) => <div key={item} className={index <= reached ? "timeline-step complete" : "timeline-step"}><span>{index <= reached ? <Check size={15}/> : index + 1}</span><b>{ar ? JOURNAL_STATUS_LABELS[item].ar : JOURNAL_STATUS_LABELS[item].en}</b></div>)}</div>
    <div className="table-wrap"><table><thead><tr><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "البيان" : "Description"}</th><th>{ar ? "مركز التكلفة" : "Cost center"}</th><th>{ar ? "الطرف" : "Party"}</th><th>{ar ? "مدين" : "Debit"}</th><th>{ar ? "دائن" : "Credit"}</th></tr></thead><tbody>{entry.lines.map((line) => <tr key={line.id}><td><span dir="ltr">{line.accountCode}</span><br/>{ar ? line.accountNameAr : line.accountNameEn}</td><td>{ar ? line.descriptionAr || "—" : line.descriptionEn || "—"}</td><td>{line.costCenterName || "—"}</td><td>{line.partyName || entry.partyName || "—"}</td><td>{line.debit ? money(line.debit, ar) : "—"}</td><td>{line.credit ? money(line.credit, ar) : "—"}</td></tr>)}<tr><th colSpan={4}>{ar ? "الإجمالي" : "Total"}</th><th>{money(entry.totalDebit, ar)}</th><th>{money(entry.totalCredit, ar)}</th></tr></tbody></table></div>
    {!validation.valid && <div className="warning error"><b>{ar ? "موانع الترحيل" : "Posting blockers"}</b><ul>{validation.errors.map((item) => <li key={`${item.code}-${item.field}`}>{ar ? item.messageAr : item.messageEn}</li>)}</ul></div>}
    {(entry.originalEntryId || entry.reversalEntryId || entry.linkedTransactionIds?.length) && <div className="card"><b>{ar ? "الروابط" : "Links"}</b><p dir="ltr">{entry.originalEntryId ? `Original: ${entry.originalEntryId}` : ""} {entry.reversalEntryId ? `Reversal: ${entry.reversalEntryId}` : ""} {(entry.linkedTransactionIds || []).join(", ")}</p></div>}
    <details><summary><b>{ar ? "سجل الحالة والمراجعة" : "Status and audit trail"}</b></summary><ul>{(entry.audit || []).map((event) => <li key={event.id}><span dir="ltr">{new Date(event.at).toLocaleString()}</span> — {event.action} — {event.actor}{event.note ? ` — ${event.note}` : ""}</li>)}</ul></details>
    {status === "draft" && <div className="actions no-print"><button className="btn" onClick={() => onEdit(entry)}>{ar ? "تعديل المسودة" : "Edit Draft"}</button></div>}
    <div className="actions no-print">{status === "draft" && <button className="btn btn-primary" onClick={() => onAct(entry, "review")}><Send size={16}/>{ar ? "إرسال للمراجعة" : "Submit for Review"}</button>}{status === "review" && <><button className="btn btn-primary" onClick={() => onAct(entry, "approved")}><FileCheck2 size={16}/>{ar ? "اعتماد" : "Approve"}</button><button className="btn" onClick={() => onAct(entry, "rejected")}><X size={16}/>{ar ? "رفض" : "Reject"}</button></>}{status === "approved" && <><button className="btn btn-primary" onClick={() => onAct(entry, "posted")}><Check size={16}/>{ar ? "ترحيل" : "Post"}</button><button className="btn" onClick={() => onAct(entry, "rejected")}><X size={16}/>{ar ? "رفض" : "Reject"}</button></>}{status === "rejected" && <button className="btn" onClick={() => onAct(entry, "draft")}><RotateCcw size={16}/>{ar ? "إعادة كمسودة" : "Return to Draft"}</button>}{status === "posted" && <button className="btn" onClick={() => onReverse(entry)}><RotateCcw size={16}/>{ar ? "إنشاء قيد عكسي" : "Create Reversal"}</button>}<button className="btn" onClick={() => onDuplicate(entry)}><Copy size={16}/>{ar ? "تكرار كمسودة" : "Duplicate"}</button><button className="btn" onClick={() => window.print()}><Printer size={16}/>{ar ? "طباعة" : "Print"}</button><button className="btn" onClick={() => onExport(entry)}><Download size={16}/>{ar ? "تصدير" : "Export"}</button></div>
  </section>;
}
function Info({ label, value, ltr }: { label: string; value: string; ltr?: boolean }) { return <div className="card"><small className="muted">{label}</small><b className="block" dir={ltr ? "ltr" : undefined}>{value}</b></div>; }
