"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowUp, FileText, Link2, Printer, UserRound } from "lucide-react";
import { buildOperationDossier } from "@/lib/accounting/operation-dossier";
import { loadAccounts, loadEntries } from "@/lib/storage/accounting";
import { loadBusinessDocuments } from "@/lib/storage/business-documents";
import { loadDocuments } from "@/lib/storage/documents";
import { loadCustodies } from "@/lib/storage/custody";
import { loadBankTransactions } from "@/lib/storage/banking";
import { loadOpenItems, loadParties } from "@/lib/storage/parties";
import { AccountingCycleTrace } from "@/components/accounting/accounting-cycle-trace";
import { EntryImpact } from "@/components/accounting/entry-impact";
import type { Locale, OperationDossier } from "@/types";

export function OperationDossierView({ id, locale }: { id: string; locale: Locale }) {
  const ar = locale === "ar", [dossier, setDossier] = useState<OperationDossier>();
  useEffect(() => { const entries = loadEntries(), entry = entries.find((item) => item.id === id); if (!entry) return; const periods = [...new Set(entries.map((item) => item.date.slice(0, 7)))]; setDossier(buildOperationDossier({ entry, entries, accounts: loadAccounts(), businessDocuments: loadBusinessDocuments(), documents: loadDocuments(), custodies: loadCustodies(), parties: loadParties(), openItems: loadOpenItems(), bankTransactions: periods.flatMap(loadBankTransactions) })); }, [id]);
  if (!dossier) return <section className="card warning">{ar ? "لم يتم العثور على العملية في بيانات الشركة الحالية." : "Operation was not found in the current company data."}</section>;
  const { entry, source } = dossier, posted = !entry.workflowStatus || entry.workflowStatus === "posted";
  return <div className="grid"><section className="card"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="actions"><span className={posted ? "badge" : "warning"}>{posted ? (ar ? "مرحّل" : "Posted") : (ar ? "الدورة قيد التنفيذ" : "Cycle pending")}</span><span className="badge">{entry.entryNumber}</span></div><h1>{ar ? entry.titleAr : entry.titleEn}</h1><p className="muted">{entry.date} · {entry.currency} · {entry.totalDebit.toLocaleString()}</p><p>{ar ? entry.narrationAr : entry.narrationEn}</p></div><button className="btn no-print" onClick={() => window.print()}><Printer size={17} />{ar ? "طباعة البطاقة" : "Print dossier"}</button></div></section>
    <section className="card"><h2><FileText size={20} />{ar ? "مصدر العملية والمستند المرتبط" : "Source and linked document"}</h2><div className="grid four"><Info title={ar ? "نوع المصدر" : "Source type"} value={sourceTitle(source.kind, ar)} /><Info title={ar ? "المرجع" : "Reference"} value={source.reference || "—"} /><Info title={ar ? "التاريخ" : "Date"} value={source.date || entry.date} /><Info title={ar ? "القيمة" : "Amount"} value={source.amount !== undefined ? `${source.amount.toLocaleString()} ${source.currency || entry.currency}` : `${entry.totalDebit.toLocaleString()} ${entry.currency}`} /></div>{(source.partyAr || source.partyEn) && <p className="actions"><UserRound size={17} /><b>{ar ? source.partyAr : source.partyEn}</b></p>}<p className="muted">{ar ? source.detailAr : source.detailEn}</p></section>
    <AccountingCycleTrace entry={{ ...entry, workflowStatus: entry.workflowStatus || "posted" }} locale={locale} title={ar ? "مسار العملية داخل الدورة المحاسبية" : "Operation path through the accounting cycle"} />
    <EntryImpact entry={entry} locale={locale} title={ar ? "تأثير العملية ومكان ظهورها" : "Operation impact and statement location"} />
    <section className="card"><h2>{ar ? "أرصدة الحسابات قبل العملية وبعدها" : "Account balances before and after"}</h2><p className="muted">{posted ? (ar ? "الأرصدة التالية فعلية بعد الترحيل." : "These balances are official after posting.") : (ar ? "عمود «بعد الترحيل» متوقع ولن يصبح رسميًا إلا عند ترحيل القيد." : "The after-posting column is projected until the entry is posted.")}</p><div className="table-wrap"><table><thead><tr><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "قبل العملية" : "Before"}</th><th>{ar ? "الحركة" : "Movement"}</th><th>{ar ? "بعد الترحيل" : "After posting"}</th><th>{ar ? "الرصيد الرسمي الآن" : "Official now"}</th></tr></thead><tbody>{dossier.balances.map((balance) => <tr key={`${balance.code}-${balance.nameEn}`}><td><b>{balance.code} — {ar ? balance.nameAr : balance.nameEn}</b></td><td>{balance.before.toLocaleString()}</td><td><span className={balance.movement >= 0 ? "badge" : "badge error"}>{balance.movement >= 0 ? <ArrowUp size={14} /> : <ArrowDown size={14} />}{Math.abs(balance.movement).toLocaleString()}</span></td><td>{balance.afterPosting.toLocaleString()}</td><td><b>{balance.officialAfter.toLocaleString()}</b></td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>{ar ? "القيد وسجل المراجعة" : "Entry and audit trail"}</h2><div className="table-wrap"><table><thead><tr><th>{ar ? "الكود" : "Code"}</th><th>{ar ? "الحساب" : "Account"}</th><th>{ar ? "مدين" : "Debit"}</th><th>{ar ? "دائن" : "Credit"}</th></tr></thead><tbody>{entry.lines.map((line) => <tr key={line.id}><td>{line.accountCode || "—"}</td><td>{ar ? line.accountNameAr : line.accountNameEn}</td><td>{line.debit || "—"}</td><td>{line.credit || "—"}</td></tr>)}</tbody></table></div><h3>{ar ? "من فعل ماذا ومتى؟" : "Who did what and when?"}</h3><ol>{(entry.audit || []).map((event) => <li key={event.id}>{new Date(event.at).toLocaleString(ar ? "ar-EG" : "en-US")} — {event.actor} — {event.action}</li>)}</ol>{!entry.audit?.length && <p className="muted">{ar ? "لا يوجد سجل قديم متاح لهذا القيد." : "No legacy audit history is available."}</p>}</section>
    <section className="card no-print"><h2><Link2 size={18} />{ar ? "الانتقال إلى التقارير المتأثرة" : "Open affected reports"}</h2><div className="actions"><Link className="btn" href={`/${locale}/journal`}>{ar ? "دفتر اليومية" : "Journal"}</Link><Link className="btn" href={`/${locale}/reports`}>{ar ? "الأستاذ والقوائم" : "Ledger & statements"}</Link><Link className="btn" href={`/${locale}/trial-balance`}>{ar ? "ميزان المراجعة" : "Trial balance"}</Link><Link className="btn" href={`/${locale}/review`}>{ar ? "مركز الاعتماد" : "Review center"}</Link></div></section>
  </div>;
}
function Info({ title, value }: { title: string; value: string }) { return <div><small className="muted">{title}</small><div className="impact">{value}</div></div>; }
function sourceTitle(kind: string, ar: boolean) { const value: Record<string, string> = ar ? { "business-document": "دورة مستندية", "uploaded-document": "مستند مرفوع", custody: "عهدة موظف", bank: "كشف بنك", manual: "قيد مباشر" } : { "business-document": "Document cycle", "uploaded-document": "Uploaded document", custody: "Employee custody", bank: "Bank statement", manual: "Direct entry" }; return value[kind] || kind; }
