"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, BookOpenCheck, CheckCircle2, FileSearch, Save, SlidersHorizontal, WalletCards } from "lucide-react";
import { accountingCategoryDefaultCode, accountingCategoryLabels, accountingRowToJournalEntry, analyzeAccountingSheet } from "@/lib/spreadsheet/accounting-intelligence";
import { getPostingAccounts } from "@/lib/accounting/accounts";
import { loadAccounts, loadEntries, saveEntries } from "@/lib/storage/accounting";
import type { AccountingSpreadsheetCategory, AccountingSpreadsheetMapping, AccountingSpreadsheetRow, ChartAccount, Locale, SheetAnalysis } from "@/types";

const fields: (keyof AccountingSpreadsheetMapping)[] = ["date", "description", "amount", "debit", "credit", "category", "accountCode", "counterAccountCode", "reference", "party"];
const categories = Object.keys(accountingCategoryLabels) as AccountingSpreadsheetCategory[];
const money = (value: number) => new Intl.NumberFormat("ar-EG", { maximumFractionDigits: 2 }).format(value);

export function AccountingIntelligence({ analysis, locale }: { analysis: SheetAnalysis; locale: Locale }) {
  const ar = locale === "ar", [accounts] = useState<ChartAccount[]>(() => loadAccounts()), [mapping, setMapping] = useState<AccountingSpreadsheetMapping>({});
  const initial = useMemo(() => analyzeAccountingSheet({ name: analysis.name, headers: analysis.headers, rows: analysis.rows, headerRowIndex: analysis.headerRowIndex }, accounts, mapping), [analysis, accounts, mapping]);
  const [overrides, setOverrides] = useState<Record<string, Partial<AccountingSpreadsheetRow>>>({}), [selected, setSelected] = useState<Set<string>>(() => new Set(initial.rows.filter((row) => row.confidence >= 70).slice(0, 500).map((row) => row.id)));
  const [categoryFilter, setCategoryFilter] = useState<"all" | AccountingSpreadsheetCategory>("all"), [reviewOnly, setReviewOnly] = useState(false), [page, setPage] = useState(0), [message, setMessage] = useState("");
  const postingAccounts = getPostingAccounts(accounts), rows = initial.rows.map((row) => ({ ...row, ...overrides[row.id] }));
  const filtered = rows.filter((row) => (categoryFilter === "all" || row.category === categoryFilter) && (!reviewOnly || row.warnings.length > 0 || row.confidence < 70)), pageSize = 25, pages = Math.max(1, Math.ceil(filtered.length / pageSize)), visible = filtered.slice(page * pageSize, page * pageSize + pageSize);
  const summary = summarize(rows);

  const update = (row: AccountingSpreadsheetRow, patch: Partial<AccountingSpreadsheetRow>) => setOverrides((current) => ({ ...current, [row.id]: { ...current[row.id], ...patch } }));
  const changeCategory = (row: AccountingSpreadsheetRow, category: AccountingSpreadsheetCategory) => { const label = accountingCategoryLabels[category], suggested = postingAccounts.find((account) => account.code === accountingCategoryDefaultCode(category)); update(row, { category, categoryAr: label.ar, categoryEn: label.en, accountCode: suggested?.code || row.accountCode, confidence: category === "unclassified" ? 35 : Math.max(90, row.confidence), warnings: category === "unclassified" ? [...new Set([...row.warnings, "unclassified"])] : row.warnings.filter((warning) => warning !== "unclassified") }); };
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else if (next.size < 500) next.add(id); return next; });
  const selectVisible = () => setSelected((current) => { const next = new Set(current); for (const row of filtered) { if (next.size >= 500) break; next.add(row.id); } return next; });
  const createDrafts = () => {
    const chosen = rows.filter((row) => selected.has(row.id)); if (!chosen.length) return setMessage(ar ? "اختر حركة واحدة على الأقل." : "Select at least one transaction.");
    if (chosen.some((row) => row.category === "unclassified")) return setMessage(ar ? "صنّف الحركات المحددة التي عليها «تحتاج تصنيف» أولًا." : "Classify selected rows marked Needs classification first.");
    if (chosen.some((row) => row.accountCode === row.counterAccountCode)) return setMessage(ar ? "اختر حسابين مختلفين للمدين والدائن في الحركات المحددة." : "Choose different debit and credit accounts for selected rows.");
    try { const existing = loadEntries(), created = chosen.reduce<ReturnType<typeof accountingRowToJournalEntry>[]>((list, row) => [...list, accountingRowToJournalEntry(row, accounts, [...existing, ...list], analysis.name)], []); saveEntries([...created.reverse(), ...existing]); setMessage(ar ? `تم إنشاء ${created.length} قيد متوازن كمسودات. راجعها من مركز القيود قبل الاعتماد والترحيل.` : `${created.length} balanced draft entries created for review.`); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Could not create entries"); }
  };

  return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm md:p-7" id="accounting-spreadsheet-tool">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><span className="text-sm font-bold text-daftar-primary">{ar ? "أداة التحليل المحاسبي" : "Accounting intelligence tool"}</span><h2 className="mt-1 text-2xl font-black">{ar ? "من صفوف Excel إلى تحليل وقيود يومية" : "From Excel rows to analysis and journal drafts"}</h2><p className="mt-2 max-w-4xl text-sm leading-7 text-daftar-muted">{ar ? "يصنّف الإيرادات والمصروفات الإدارية والبنكية والرواتب والضرائب والأصول والمخزون، ثم يقترح حسابي المدين والدائن لكل حركة. لا يتم الترحيل تلقائيًا؛ القيود تُحفظ كمسودات للمراجعة." : "Classifies financial activity and proposes debit and credit accounts. Entries are saved as drafts, never posted automatically."}</p></div><span className="rounded-2xl bg-blue-50 px-4 py-3 text-sm font-black text-blue-800"><FileSearch className="inline-block me-2" size={18}/>{rows.length.toLocaleString()} {ar ? "حركة مالية" : "financial rows"}</span></div>

    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><AccountingMetric icon={ArrowDownLeft} title={ar ? "إجمالي الداخل" : "Total inflow"} value={money(summary.totalIn)} tone="green"/><AccountingMetric icon={ArrowUpRight} title={ar ? "إجمالي الخارج" : "Total outflow"} value={money(summary.totalOut)} tone="red"/><AccountingMetric icon={WalletCards} title={ar ? "صافي الحركة" : "Net movement"} value={money(summary.netCashFlow)} tone={summary.netCashFlow >= 0 ? "green" : "red"}/><AccountingMetric icon={CheckCircle2} title={ar ? "مصنفة" : "Classified"} value={String(summary.categorized)} tone="blue"/><AccountingMetric icon={AlertTriangle} title={ar ? "تحتاج مراجعة" : "Needs review"} value={String(summary.needsReview)} tone={summary.needsReview ? "amber" : "green"}/></div>

    <details className="mt-5 rounded-2xl border border-daftar-line p-4 no-print"><summary className="cursor-pointer font-black"><SlidersHorizontal className="inline-block me-2" size={18}/>{ar ? "مراجعة ربط أعمدة الشيت" : "Review column mapping"}</summary><p className="mt-2 text-sm text-daftar-muted">{ar ? "النظام اكتشف الأعمدة تلقائيًا. غيّر أي اختيار إذا كانت عناوين ملفك مختلفة." : "Columns were detected automatically. Correct any field if needed."}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{fields.map((field) => <label key={field}><span>{mappingLabel(field, ar)}</span><select value={mapping[field] || initial.mapping[field] || ""} onChange={(event) => { setMapping((current) => ({ ...current, [field]: event.target.value || undefined })); setOverrides({}); setPage(0); }}><option value="">—</option>{analysis.headers.map((header, index) => <option value={header} key={`${header}-${index}`}>{header}</option>)}</select></label>)}</div></details>

    <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{summary.categories.slice(0, 12).map((item) => <button type="button" onClick={() => { setCategoryFilter(item.category); setPage(0); }} className={`rounded-2xl border p-4 text-start ${categoryFilter === item.category ? "border-daftar-primary bg-blue-50" : "border-daftar-line"}`} key={item.category}><small className="text-daftar-muted">{ar ? item.labelEn : item.labelAr}</small><b className="mt-1 block">{ar ? item.labelAr : item.labelEn}</b><span className="mt-2 flex justify-between text-sm"><span>{item.count} {ar ? "حركة" : "rows"}</span><strong>{money(item.amount)}</strong></span></button>)}</div>

    <div className="mt-6 flex flex-wrap items-end justify-between gap-3 no-print"><div className="flex flex-wrap gap-3"><label><span>{ar ? "التصنيف" : "Category"}</span><select value={categoryFilter} onChange={(event) => { setCategoryFilter(event.target.value as typeof categoryFilter); setPage(0); }}><option value="all">{ar ? "كل التصنيفات" : "All categories"}</option>{categories.map((category) => <option value={category} key={category}>{ar ? accountingCategoryLabels[category].ar : accountingCategoryLabels[category].en}</option>)}</select></label><label className="flex items-center gap-2 self-end rounded-xl border border-daftar-line px-4 py-3"><input className="w-auto" type="checkbox" checked={reviewOnly} onChange={(event) => { setReviewOnly(event.target.checked); setPage(0); }}/>{ar ? "تحتاج مراجعة فقط" : "Review only"}</label></div><div className="actions"><button className="btn" onClick={selectVisible}>{ar ? "اختيار النتائج" : "Select results"}</button><button className="btn" onClick={() => setSelected(new Set())}>{ar ? "إلغاء الاختيار" : "Clear selection"}</button><span className="badge">{selected.size} / 500</span></div></div>

    <div className="mt-4 overflow-x-auto rounded-2xl border border-daftar-line"><table className="min-w-[1450px]"><thead><tr><th className="no-print">✓</th><th>#</th><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "البيان" : "Description"}</th><th>{ar ? "المبلغ والاتجاه" : "Amount / direction"}</th><th>{ar ? "التصنيف" : "Category"}</th><th>{ar ? "حساب العملية" : "Transaction account"}</th><th>{ar ? "الحساب المقابل" : "Counter account"}</th><th>{ar ? "القيد المقترح" : "Proposed entry"}</th><th>{ar ? "الثقة" : "Confidence"}</th></tr></thead><tbody>{visible.map((row) => <AccountingRow key={row.id} row={row} ar={ar} accounts={postingAccounts} selected={selected.has(row.id)} toggle={() => toggle(row.id)} update={(patch) => update(row, patch)} changeCategory={(category) => changeCategory(row, category)}/>)}</tbody></table></div>
    {!filtered.length && <p className="py-8 text-center text-daftar-muted">{ar ? "لا توجد حركات مطابقة للفلاتر أو لم يتم اكتشاف عمود مبلغ." : "No financial rows match the current mapping or filters."}</p>}
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 no-print"><span className="text-sm text-daftar-muted">{ar ? `صفحة ${page + 1} من ${pages} — يتم عرض 25 حركة للحفاظ على وضوح الصفحة` : `Page ${page + 1} of ${pages}`}</span><div className="actions"><button className="btn" disabled={page === 0} onClick={() => setPage((value) => value - 1)}>{ar ? "السابق" : "Previous"}</button><button className="btn" disabled={page >= pages - 1} onClick={() => setPage((value) => value + 1)}>{ar ? "التالي" : "Next"}</button></div></div>

    <div className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><b className="text-blue-950">{ar ? "الخطوة المحاسبية التالية" : "Next accounting step"}</b><p className="mt-1 text-sm text-blue-900/70">{ar ? "راجع التصنيف والحسابات، ثم أنشئ القيود كمسودات. ستظهر في مركز القيود وتدخل دورة المراجعة ← الاعتماد ← الترحيل ← الأستاذ والتقارير." : "Review mappings, then create draft entries for the unified journal lifecycle."}</p></div><button className="btn btn-primary" onClick={createDrafts}><Save size={17}/>{ar ? `إنشاء ${selected.size} قيد كمسودة` : `Create ${selected.size} drafts`}</button></div>{message && <p className="mt-4 rounded-xl bg-white p-3 font-bold text-blue-950">{message} {message.includes("تم إنشاء") && <Link className="ms-2 underline" href={`/${locale}/journal`}><BookOpenCheck className="inline-block" size={16}/> {ar ? "فتح مركز القيود" : "Open Journal Center"}</Link>}</p>}</div>
  </section>;
}

function AccountingRow({ row, ar, accounts, selected, toggle, update, changeCategory }: { row: AccountingSpreadsheetRow; ar: boolean; accounts: ChartAccount[]; selected: boolean; toggle: () => void; update: (patch: Partial<AccountingSpreadsheetRow>) => void; changeCategory: (category: AccountingSpreadsheetCategory) => void }) {
  const primary = accounts.find((account) => account.code === row.accountCode), counter = accounts.find((account) => account.code === row.counterAccountCode), debit = row.direction === "out" ? primary : counter, credit = row.direction === "out" ? counter : primary;
  return <tr className={row.confidence < 70 ? "bg-amber-50/40" : ""}><td className="no-print"><input className="w-auto" type="checkbox" checked={selected} onChange={toggle}/></td><td>{row.rowNumber}</td><td><input type="date" value={row.date} onChange={(event) => update({ date: event.target.value })}/></td><td><textarea className="min-h-20 min-w-64" value={row.description} onChange={(event) => update({ description: event.target.value })}/>{row.reference && <small className="block text-daftar-muted" dir="ltr">{row.reference}</small>}</td><td><b className={row.direction === "in" ? "text-emerald-700" : "text-red-700"}>{row.direction === "in" ? "↓" : "↑"} {money(row.amount)}</b><select className="mt-2" value={row.direction} onChange={(event) => update({ direction: event.target.value as "in" | "out" })}><option value="in">{ar ? "داخل" : "Inflow"}</option><option value="out">{ar ? "خارج" : "Outflow"}</option></select></td><td><select value={row.category} onChange={(event) => changeCategory(event.target.value as AccountingSpreadsheetCategory)}>{categories.map((category) => <option value={category} key={category}>{ar ? accountingCategoryLabels[category].ar : accountingCategoryLabels[category].en}</option>)}</select><small className="mt-1 block text-daftar-muted">{ar ? row.categoryEn : row.categoryAr}</small></td><td><AccountSelect accounts={accounts} value={row.accountCode} ar={ar} onChange={(accountCode) => update({ accountCode })}/></td><td><AccountSelect accounts={accounts} value={row.counterAccountCode} ar={ar} onChange={(counterAccountCode) => update({ counterAccountCode })}/></td><td><small className="block text-emerald-700">{ar ? "مدين" : "Debit"}: {debit?.code} — {ar ? debit?.nameAr : debit?.nameEn}</small><small className="mt-2 block text-red-700">{ar ? "دائن" : "Credit"}: {credit?.code} — {ar ? credit?.nameAr : credit?.nameEn}</small></td><td><b className={row.confidence >= 80 ? "text-emerald-700" : row.confidence >= 60 ? "text-amber-700" : "text-red-700"}>{row.confidence}%</b>{row.warnings.map((warning) => <small className="mt-1 block text-amber-700" key={warning}>{warningLabel(warning, ar)}</small>)}</td></tr>;
}
function AccountSelect({ accounts, value, ar, onChange }: { accounts: ChartAccount[]; value: string; ar: boolean; onChange: (value: string) => void }) { return <select value={value} onChange={(event) => onChange(event.target.value)}>{accounts.map((account) => <option value={account.code} key={account.id}>{account.code} — {ar ? account.nameAr : account.nameEn}</option>)}</select>; }
function AccountingMetric({ icon: Icon, title, value, tone }: { icon: typeof WalletCards; title: string; value: string; tone: "green" | "red" | "blue" | "amber" }) { const styles = { green: "bg-emerald-50 text-emerald-800", red: "bg-red-50 text-red-800", blue: "bg-blue-50 text-blue-800", amber: "bg-amber-50 text-amber-900" }; return <article className={`rounded-2xl p-4 ${styles[tone]}`}><Icon size={20}/><b className="mt-3 block text-2xl">{value}</b><small>{title}</small></article>; }
function summarize(rows: AccountingSpreadsheetRow[]) { const categoriesMap = new Map<AccountingSpreadsheetCategory, { count: number; amount: number }>(); for (const row of rows) { const value = categoriesMap.get(row.category) || { count: 0, amount: 0 }; value.count++; value.amount += row.amount; categoriesMap.set(row.category, value); } const totalIn = rows.filter((row) => row.direction === "in").reduce((sum, row) => sum + row.amount, 0), totalOut = rows.filter((row) => row.direction === "out").reduce((sum, row) => sum + row.amount, 0); return { totalIn, totalOut, netCashFlow: totalIn - totalOut, categorized: rows.filter((row) => row.category !== "unclassified").length, needsReview: rows.filter((row) => row.warnings.length || row.confidence < 70).length, categories: [...categoriesMap.entries()].map(([category, value]) => ({ category, labelAr: accountingCategoryLabels[category].ar, labelEn: accountingCategoryLabels[category].en, ...value })).sort((a, b) => b.amount - a.amount) }; }
function mappingLabel(field: keyof AccountingSpreadsheetMapping, ar: boolean) { const labels: Record<keyof AccountingSpreadsheetMapping, [string, string]> = { date: ["التاريخ", "Date"], description: ["البيان", "Description"], amount: ["المبلغ الموحد", "Amount"], debit: ["مدين / سحب", "Debit"], credit: ["دائن / إيداع", "Credit"], category: ["التصنيف", "Category"], accountCode: ["كود الحساب", "Account code"], counterAccountCode: ["الحساب المقابل", "Counter account"], reference: ["المرجع", "Reference"], party: ["الطرف", "Party"] }; return labels[field][ar ? 0 : 1]; }
function warningLabel(value: string, ar: boolean) { if (!ar) return value; return ({ "missing-description": "البيان ناقص", "missing-date": "استخدم تاريخ اليوم", unclassified: "يحتاج تصنيف يدوي", "invalid-account-code": "كود الحساب غير صالح", "same-account": "اختر حسابين مختلفين" } as Record<string, string>)[value] || value; }
