"use client";

import { useState } from "react";
import {
  AlertTriangle, BarChart3, CheckCircle2, Database, Download, FileSpreadsheet,
  Filter, Layers3, LoaderCircle, Search, Table2, TrendingUp,
} from "lucide-react";
import { readSpreadsheet, type SpreadsheetReadProgress } from "@/lib/spreadsheet/reader";
import { analyzeSheet } from "@/lib/spreadsheet/analyzer";
import type { CategoryBreakdown, DataQualityIssue, Locale, SheetAnalysis } from "@/types";

const colors=["#1769aa","#10b981","#f59e0b","#8b5cf6","#ef4444","#06b6d4","#84cc16","#ec4899","#64748b","#14b8a6","#f97316","#6366f1","#94a3b8"];
const number=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2,notation:Math.abs(value)>=1_000_000?"compact":"standard"}).format(value);

export function SpreadsheetAnalyzer({locale}:{locale:Locale}){
  const ar=locale==="ar";
  const [analyses,setAnalyses]=useState<SheetAnalysis[]>([]),[active,setActive]=useState(0),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[progress,setProgress]=useState<SpreadsheetReadProgress|undefined>(),[fileInfo,setFileInfo]=useState<{name:string;size:string}|undefined>();
  const upload=async(file?:File)=>{if(!file)return;try{setBusy(true);setAnalyses([]);setMessage(ar?"جارٍ تجهيز الملف للتحليل…":"Preparing workbook…");setFileInfo({name:file.name,size:`${(file.size/1024/1024).toFixed(2)} MB`});const sheets=await readSpreadsheet(file,{onProgress:setProgress});const results:SheetAnalysis[]=[];for(let index=0;index<sheets.length;index++){const sheet=sheets[index];if(!sheet.headers.length)continue;setMessage(ar?`جارٍ تحليل ورقة ${sheet.name} (${index+1}/${sheets.length})…`:`Analyzing ${sheet.name} (${index+1}/${sheets.length})…`);await new Promise<void>(resolve=>window.setTimeout(resolve,0));results.push(analyzeSheet(sheet));}setAnalyses(results);setActive(0);setMessage(results.length?(ar?`تم تحليل ${results.length} ورقة.`:`Analyzed ${results.length} sheets.`):(ar?"لم يتم العثور على جدول واضح داخل الملف.":"No clear table was found."));}catch(error){setMessage(localError(error,ar));}finally{setBusy(false);setProgress(undefined);}};
  const analysis=analyses[active];
  return <div className="spreadsheet-analyzer grid min-w-0 max-w-full gap-5 overflow-hidden" id="spreadsheet-analysis-report" data-no-bilingual>
    <section className="overflow-hidden rounded-3xl border border-daftar-line bg-daftar-card shadow-sm"><div className="grid gap-6 bg-gradient-to-l from-[#0d315c] to-[#1769aa] p-6 text-white md:grid-cols-[1fr_auto] md:items-center md:p-8"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold"><Layers3 size={15}/>{ar?"محرك تحليل محلي للملفات الكبيرة":"Local large-workbook engine"}</span><h1 className="mt-4 text-3xl font-black">{ar?"حلّل أي شيت Excel بدون لخبطة":"Analyze any Excel workbook clearly"}</h1><p className="mt-2 max-w-3xl text-white/70">{ar?"اكتشاف تلقائي للعناوين وأنواع الأعمدة، إحصاءات وجودة بيانات ورسومات تلخّص أهم البنود بدل عرض آلاف النقاط.":"Automatic headers, column types, statistics, data quality, and charts that summarize rather than overload."}</p></div><label className="cursor-pointer rounded-2xl bg-white px-6 py-4 text-center font-black text-[#0d315c] shadow-xl transition hover:-translate-y-1"><FileSpreadsheet className="mx-auto mb-2"/>{busy?(ar?"جارٍ التحليل…":"Analyzing…"):(ar?"اختيار ملف XLSX أو CSV":"Choose XLSX or CSV")}<input className="sr-only" disabled={busy} type="file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={event=>upload(event.target.files?.[0])}/></label></div>
      {(message||fileInfo)&&<div className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><span className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${busy?"bg-blue-50 text-blue-700":"bg-emerald-50 text-emerald-700"}`}>{busy?<LoaderCircle className="animate-spin"/>:<CheckCircle2/>}</span><span><b className="block">{message}</b>{fileInfo&&<small className="text-daftar-muted">{fileInfo.name} · {fileInfo.size} · {ar?"لا يغادر جهازك":"stays on your device"}</small>}</span></span>{progress&&<b className="text-daftar-primary">{progress.percent}%</b>}</div>{progress&&<div className="mt-4 h-2 overflow-hidden rounded-full bg-daftar-line"><i className="block h-full rounded-full bg-daftar-primary transition-all" style={{width:`${progress.percent}%`}}/></div>}</div>}
    </section>

    {analysis&&<>
      <section className="no-print flex flex-wrap items-end justify-between gap-3 rounded-2xl border border-daftar-line bg-daftar-card p-4"><label className="min-w-[260px] flex-1"><span>{ar?"ورقة العمل":"Worksheet"}</span><select value={active} onChange={event=>setActive(Number(event.target.value))}>{analyses.map((sheet,index)=><option value={index} key={`${sheet.name}-${index}`}>{sheet.name} — {sheet.rowCount.toLocaleString()} {ar?"صف":"rows"}</option>)}</select></label><PdfExportButton analysisName={analysis.name} ar={ar}/></section>

      <section className="spreadsheet-kpi-grid"><Metric icon={Database} title={ar?"إجمالي الصفوف":"Rows"} value={analysis.rowCount.toLocaleString()}/><Metric icon={Table2} title={ar?"الأعمدة":"Columns"} value={String(analysis.columnCount)}/><Metric icon={TrendingUp} title={ar?"أعمدة رقمية":"Numeric"} value={String(analysis.numeric.length)}/><Metric icon={Layers3} title={ar?"أعمدة وصفية":"Categories"} value={String(analysis.categorical.length)}/><Metric icon={CheckCircle2} title={ar?"اكتمال البيانات":"Completeness"} value={`${analysis.completeness}%`} positive={analysis.completeness>=80}/><Metric icon={AlertTriangle} title={ar?"تنبيهات الجودة":"Quality alerts"} value={String(analysis.quality.length)} positive={!analysis.quality.length}/></section>

      {analysis.sampled&&<div className="flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4 text-blue-900"><Database className="shrink-0"/><div><b>{ar?"وضع تحليل الملفات الكبيرة":"Large-sheet analysis mode"}</b><p className="mt-1 text-sm">{ar?`تم تحليل عينة موزعة من ${analysis.analyzedRows.toLocaleString()} صف بدل تجميد الصفحة، مع الاحتفاظ بعدد الصفوف الحقيقي ${analysis.rowCount.toLocaleString()}.`:`A representative ${analysis.analyzedRows.toLocaleString()}-row sample was analyzed from ${analysis.rowCount.toLocaleString()} total rows.`}</p></div></div>}

      <SmartCharts analysis={analysis} ar={ar}/>
      <QualityPanel issues={analysis.quality} completeness={analysis.completeness} duplicateRows={analysis.duplicateRows} ar={ar}/>
      <NumericTable analysis={analysis} ar={ar}/>
      <DataPreview analysis={analysis} ar={ar}/>
    </>}
  </div>;
}

function SmartCharts({analysis,ar}:{analysis:SheetAnalysis;ar:boolean}){
  const [numericColumn,setNumericColumn]=useState(analysis.numeric[0]?.column||""),[categoryColumn,setCategoryColumn]=useState(analysis.categorical.find(x=>x.unique>1&&x.unique<=100)?.column||analysis.categorical[0]?.column||"");
  const numeric=analysis.numeric.find(x=>x.column===numericColumn)||analysis.numeric[0], category=analysis.categorical.find(x=>x.column===categoryColumn)||analysis.categorical[0];
  return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="text-sm font-bold text-daftar-primary">{ar?"رسومات ذكية قابلة للتحكم":"Controlled smart charts"}</span><h2 className="mt-1 text-2xl font-black">{ar?"الصورة المهمة بدون زحمة":"The important picture, without clutter"}</h2><p className="mt-1 text-sm text-daftar-muted">{ar?"يتم عرض أعلى 12 بندًا وتجميع الباقي في «أخرى» حتى يظل الرسم مقروءًا.":"Top 12 categories are shown; the rest are grouped as Other."}</p></div><BarChart3 className="text-daftar-primary" size={28}/></div>
    {analysis.breakdown&&<BreakdownChart breakdown={analysis.breakdown} ar={ar}/>} 
    <div className="mt-7 grid gap-5 xl:grid-cols-2">
      <article className="rounded-2xl border border-daftar-line p-5"><label className="mb-5"><span>{ar?"اختر العمود الرقمي":"Numeric column"}</span><select value={numeric?.column||""} onChange={e=>setNumericColumn(e.target.value)}>{analysis.numeric.map((item,index)=><option key={`${item.column}-${index}`}>{item.column}</option>)}</select></label>{numeric?<NumericProfileChart profile={numeric} ar={ar}/>:<EmptyChart ar={ar}/>}</article>
      <article className="rounded-2xl border border-daftar-line p-5"><label className="mb-5"><span>{ar?"اختر عمود التصنيف":"Category column"}</span><select value={category?.column||""} onChange={e=>setCategoryColumn(e.target.value)}>{analysis.categorical.map((item,index)=><option key={`${item.column}-${index}`}>{item.column}</option>)}</select></label>{category?<CategoryChart profile={category}/>:<EmptyChart ar={ar}/>}</article>
    </div>
  </section>;
}

function BreakdownChart({breakdown,ar}:{breakdown:CategoryBreakdown;ar:boolean}){const max=Math.max(...breakdown.items.map(item=>item.value),1);return <div className="mt-7 rounded-2xl bg-[color-mix(in_srgb,var(--primary)_3%,var(--card))] p-5"><div className="flex flex-wrap items-center justify-between gap-2"><span><small className="text-daftar-muted">{ar?"التحليل الرئيسي المكتشف":"Detected primary breakdown"}</small><h3 className="mt-1 text-xl font-black">{breakdown.title}</h3></span><span className="rounded-xl bg-daftar-primary px-4 py-2 font-black text-white">{ar?"الإجمالي":"Total"} {number(breakdown.total)}</span></div><div className="mt-6 grid gap-3">{breakdown.items.map((item,index)=><div className="grid items-center gap-2 md:grid-cols-[minmax(120px,220px)_1fr_130px]" key={`${item.label}-${index}`}><b className="truncate text-sm" title={item.label}>{item.label}</b><div className="h-8 overflow-hidden rounded-lg bg-daftar-line"><i className="flex h-full min-w-1 items-center justify-end rounded-lg px-2 text-xs font-bold text-white transition-all" style={{width:`${item.value/max*100}%`,background:colors[index%colors.length]}}>{item.percentage>=8?`${item.percentage}%`:""}</i></div><span className="text-sm font-black md:text-end">{number(item.value)} · {item.percentage}%</span></div>)}</div></div>;}

function NumericProfileChart({profile,ar}:{profile:SheetAnalysis["numeric"][number];ar:boolean}){const data=[[ar?"الأدنى":"Min",profile.minimum],[ar?"المتوسط":"Average",profile.average],[ar?"الوسيط":"Median",profile.median],[ar?"الأعلى":"Max",profile.maximum]] as const,max=Math.max(...data.map(([,value])=>Math.abs(value)),1);return <div><div className="mb-4 flex justify-between"><b>{profile.column}</b><small className="text-daftar-muted">{ar?"مجموع":"Sum"}: {number(profile.sum)}</small></div><div className="grid gap-4">{data.map(([label,value],index)=><div key={label}><div className="mb-1 flex justify-between text-sm"><span>{label}</span><b>{number(value)}</b></div><div className="h-3 overflow-hidden rounded-full bg-daftar-line"><i className="block h-full rounded-full" style={{width:`${Math.max(1,Math.abs(value)/max*100)}%`,background:colors[index]}}/></div></div>)}</div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-sm"><span className="rounded-xl bg-daftar-bg p-2"><b className="block">{profile.count.toLocaleString()}</b>{ar?"قيمة":"values"}</span><span className="rounded-xl bg-daftar-bg p-2"><b className="block text-red-600">{profile.negative.toLocaleString()}</b>{ar?"سالبة":"negative"}</span><span className="rounded-xl bg-daftar-bg p-2"><b className="block">{profile.zero.toLocaleString()}</b>{ar?"صفر":"zero"}</span></div></div>;}
function CategoryChart({profile}:{profile:SheetAnalysis["categorical"][number]}){const max=Math.max(...profile.topValues.map(item=>item.count),1);return <div><div className="mb-4 flex justify-between"><b>{profile.column}</b><small className="text-daftar-muted">{profile.unique.toLocaleString()} unique</small></div><div className="grid gap-3">{profile.topValues.slice(0,10).map((item,index)=><div key={`${item.value}-${index}`}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate" title={item.value}>{item.value}</span><b>{item.count.toLocaleString()} · {item.percentage}%</b></div><div className="h-2.5 overflow-hidden rounded-full bg-daftar-line"><i className="block h-full rounded-full" style={{width:`${item.count/max*100}%`,background:colors[index%colors.length]}}/></div></div>)}</div></div>;}

function QualityPanel({issues,completeness,duplicateRows,ar}:{issues:DataQualityIssue[];completeness:number;duplicateRows:number;ar:boolean}){const [filter,setFilter]=useState<"all"|DataQualityIssue["severity"]>("all"),shown=issues.filter(item=>filter==="all"||item.severity===filter);return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm md:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-sm font-bold text-daftar-primary">{ar?"تدقيق جودة البيانات":"Data quality audit"}</span><h2 className="mt-1 text-2xl font-black">{ar?"ما الذي يحتاج تنظيفًا؟":"What needs cleaning?"}</h2></div><div className="flex gap-2 no-print"><Filter size={18} className="self-center"/>{(["all","high","medium","low"] as const).map(value=><button className={`btn px-3 py-2 text-xs ${filter===value?"tab-active":""}`} onClick={()=>setFilter(value)} key={value}>{value==="all"?(ar?"الكل":"All"):severityLabel(value,ar)}</button>)}</div></div><div className="mt-5 grid grid-cols-3 gap-3"><MiniMetric label={ar?"الاكتمال":"Completeness"} value={`${completeness}%`}/><MiniMetric label={ar?"الصفوف المكررة":"Duplicates"} value={duplicateRows.toLocaleString()}/><MiniMetric label={ar?"تنبيهات حرجة":"High alerts"} value={String(issues.filter(x=>x.severity==="high").length)}/></div>{shown.length?<div className="mt-5 grid gap-3 md:grid-cols-2">{shown.map((issue,index)=><div className={`rounded-2xl border p-4 ${issue.severity==="high"?"border-red-200 bg-red-50 text-red-900":issue.severity==="medium"?"border-amber-200 bg-amber-50 text-amber-900":"border-blue-200 bg-blue-50 text-blue-900"}`} key={`${issue.code}-${issue.column}-${index}`}><div className="flex items-center justify-between gap-2"><b>{issue.column||qualityTitle(issue.code,ar)}</b><span className="rounded-full bg-white/70 px-2 py-1 text-[11px] font-black">{severityLabel(issue.severity,ar)}</span></div><p className="mt-2 text-sm leading-6">{qualityMessage(issue,ar)}</p></div>)}</div>:<div className="mt-5 flex items-center gap-3 rounded-2xl bg-emerald-50 p-5 text-emerald-900"><CheckCircle2/><b>{ar?"لا توجد مشكلات ضمن هذا التصنيف.":"No issues in this category."}</b></div>}</section>;}

function NumericTable({analysis,ar}:{analysis:SheetAnalysis;ar:boolean}){const [query,setQuery]=useState(""),rows=analysis.numeric.filter(profile=>profile.column.toLowerCase().includes(query.toLowerCase()));return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm md:p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="text-sm font-bold text-daftar-primary">{ar?"ملف كل عمود":"Column profiles"}</span><h2 className="mt-1 text-2xl font-black">{ar?"الإحصاءات الرقمية":"Numeric statistics"}</h2></div><label className="grid min-w-[230px] grid-cols-[auto_1fr] items-center gap-2 rounded-xl border border-daftar-line px-3 no-print"><Search size={17}/><input className="border-0 bg-transparent shadow-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder={ar?"ابحث عن عمود...":"Find column..."}/></label></div><div className="mt-5 overflow-x-auto"><table className="min-w-[900px]"><thead><tr><th>{ar?"العمود":"Column"}</th><th>{ar?"المجموع":"Sum"}</th><th>{ar?"المتوسط":"Average"}</th><th>{ar?"الوسيط":"Median"}</th><th>{ar?"الأدنى":"Min"}</th><th>{ar?"الأعلى":"Max"}</th><th>{ar?"المفقود":"Missing"}</th></tr></thead><tbody>{rows.map((profile,index)=><tr key={`${profile.column}-${index}`}><td><b>{profile.column}</b><small className="block text-daftar-muted">{profile.count.toLocaleString()} {ar?"قيمة":"values"}</small></td><td>{number(profile.sum)}</td><td>{number(profile.average)}</td><td>{number(profile.median)}</td><td>{number(profile.minimum)}</td><td>{number(profile.maximum)}</td><td>{profile.missing.toLocaleString()}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="py-8 text-center text-daftar-muted">{ar?"لا توجد أعمدة رقمية مطابقة.":"No matching numeric columns."}</p>}</section>;}

function DataPreview({analysis,ar}:{analysis:SheetAnalysis;ar:boolean}){const [page,setPage]=useState(0),pageSize=10,pages=Math.max(1,Math.ceil(analysis.preview.length/pageSize)),rows=analysis.preview.slice(page*pageSize,(page+1)*pageSize);return <section className="rounded-3xl border border-daftar-line bg-daftar-card p-5 shadow-sm md:p-7"><div className="flex items-center justify-between"><div><span className="text-sm font-bold text-daftar-primary">{ar?"معاينة آمنة":"Lightweight preview"}</span><h2 className="mt-1 text-2xl font-black">{ar?"أول 25 صفًا":"First 25 rows"}</h2></div><Table2/></div><div className="mt-5 max-h-[520px] overflow-auto rounded-2xl border border-daftar-line"><table className="min-w-max"><thead className="sticky top-0 z-10"><tr>{analysis.headers.map((header,index)=><th className="min-w-[150px]" key={`${header}-${index}`}>{header}</th>)}</tr></thead><tbody>{rows.map((row,rowIndex)=><tr key={rowIndex}>{analysis.headers.map((_,index)=><td key={index}>{formatCell(row[index])}</td>)}</tr>)}</tbody></table></div><div className="mt-4 flex items-center justify-between no-print"><span className="text-sm text-daftar-muted">{ar?`صفحة ${page+1} من ${pages}`:`Page ${page+1} of ${pages}`}</span><div className="flex gap-2"><button className="btn" disabled={page===0} onClick={()=>setPage(value=>value-1)}>{ar?"السابق":"Previous"}</button><button className="btn" disabled={page>=pages-1} onClick={()=>setPage(value=>value+1)}>{ar?"التالي":"Next"}</button></div></div></section>;}

function PdfExportButton({analysisName,ar}:{analysisName:string;ar:boolean}){const [exporting,setExporting]=useState(false),[error,setError]=useState("");const exportPdf=async()=>{const element=document.getElementById("spreadsheet-analysis-report");if(!element)return;try{setExporting(true);setError("");const [{default:html2canvas},{jsPDF}]=await Promise.all([import("html2canvas"),import("jspdf")]);const canvas=await html2canvas(element,{scale:1.45,useCORS:true,backgroundColor:"#ffffff",onclone:doc=>{const report=doc.getElementById("spreadsheet-analysis-report");if(!report)return;report.firstElementChild?.remove();report.querySelectorAll(".no-print").forEach(node=>node.remove());report.style.cssText+=";--bg:#fff;--card:#fff;--text:#12213a;--muted:#60708a;--line:#dce3ed;background:#fff;color:#12213a;padding:20px";}});const pdf=new jsPDF({orientation:"portrait",unit:"mm",format:"a4"}),margin=8,width=194,pageHeight=281,height=canvas.height*width/canvas.width,image=canvas.toDataURL("image/jpeg",.9);for(let offset=0,page=0;offset<height;offset+=pageHeight,page++){if(page)pdf.addPage();pdf.addImage(image,"JPEG",margin,margin-offset,width,height,undefined,"FAST");}pdf.save(`${analysisName||"spreadsheet"}-analysis.pdf`);}catch(caught){console.error("PDF export failed",caught);setError(ar?"تعذر إنشاء PDF لهذا العرض. حاول تقليل الأعمدة الظاهرة.":"PDF creation failed. Try reducing visible columns.");}finally{setExporting(false);}};return <div><button className="btn btn-primary" disabled={exporting} onClick={exportPdf}>{exporting?<LoaderCircle className="animate-spin" size={17}/>:<Download size={17}/>} {exporting?(ar?"جارٍ إنشاء PDF…":"Creating PDF…"):(ar?"تحميل تقرير PDF":"Download PDF")}</button>{error&&<p className="mt-2 text-xs text-red-600">{error}</p>}</div>;}

function Metric({icon:Icon,title,value,positive}:{icon:typeof Database;title:string;value:string;positive?:boolean}){return <article className="rounded-2xl border border-daftar-line bg-daftar-card p-4 shadow-sm"><Icon className={positive===false?"text-red-500":positive?"text-emerald-500":"text-daftar-primary"} size={20}/><b className="mt-3 block text-2xl font-black">{value}</b><small className="text-daftar-muted">{title}</small></article>;}
function MiniMetric({label,value}:{label:string;value:string}){return <span className="rounded-xl bg-daftar-bg p-3 text-center"><b className="block text-xl">{value}</b><small className="text-daftar-muted">{label}</small></span>;}
function EmptyChart({ar}:{ar:boolean}){return <div className="grid min-h-52 place-items-center rounded-xl border border-dashed border-daftar-line text-center text-daftar-muted"><span><BarChart3 className="mx-auto mb-2"/>{ar?"لا توجد أعمدة مناسبة لهذا الرسم.":"No suitable columns for this chart."}</span></div>;}
function formatCell(value:unknown){if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="number")return number(value);return String(value??"");}
function severityLabel(value:DataQualityIssue["severity"],ar:boolean){return ar?({high:"حرج",medium:"تحذير",low:"ملاحظة"}[value]):value;}
function qualityTitle(code:string,ar:boolean){if(!ar)return code;return ({"sparse-data":"بيانات ناقصة","duplicate-rows":"صفوف مكررة","sampled-analysis":"تحليل بالعينة","mixed-types":"أنواع بيانات مختلطة","extreme-value":"قيم شاذة"} as Record<string,string>)[code]||"تنبيه جودة";}
function qualityMessage(issue:DataQualityIssue,ar:boolean){if(!ar)return issue.message;const messages:Record<string,string>={"sparse-data":"أكثر من 20% من الخلايا فارغة؛ راجع الأعمدة الإلزامية.","duplicate-rows":"تم اكتشاف صفوف متكررة قد تؤثر في المجاميع والنسب.","sampled-analysis":"الورقة كبيرة؛ استخدم النظام عينة موزعة لحماية المتصفح مع الاحتفاظ بالعدد الحقيقي للصفوف.","mixed-types":"العمود يجمع أرقامًا ونصوصًا؛ وحّد تنسيق الخلايا قبل الاعتماد.","extreme-value":"توجد قيم بعيدة جدًا عن الوسيط؛ راجع احتمال خطأ الإدخال.","many-missing":"أكثر من 30% من قيم هذا العمود مفقودة."};return messages[issue.code]||issue.message;}
function localError(error:unknown,ar:boolean){const message=error instanceof Error?error.message:"Analysis failed";if(!ar)return message;if(message.includes("120 MB"))return"الملف أكبر من 120 ميجابايت. قسّمه إلى ملفات أصغر حتى لا يتوقف المتصفح.";if(message.includes("Legacy .xls"))return"صيغة XLS القديمة غير مدعومة؛ احفظ الملف بصيغة XLSX ثم ارفعه.";if(message.includes("Supported formats"))return"ارفع ملفًا بصيغة XLSX أو CSV فقط.";return`تعذر تحليل الملف: ${message}`;}

