"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, CircleDollarSign, Plus, ReceiptText, RotateCcw, WalletCards } from "lucide-react";
import { custodyOutstanding, custodyReimbursementDue, issueCustody, reimburseCustody, settleCustody } from "@/lib/custody/settlement";
import { loadCustodies, saveCustodies } from "@/lib/storage/custody";
import { loadAccounts, saveEntry } from "@/lib/storage/accounting";
import { EntryImpact } from "@/components/accounting/entry-impact";
import { AccountingCycleTrace } from "@/components/accounting/accounting-cycle-trace";
import type { ChartAccount, CustodyAdvance, CustodyIssueInput, CustodySettlementInput, GeneratedJournalEntry, Locale } from "@/types";

const today = () => new Date().toISOString().slice(0, 10);
const emptyIssue = (): CustodyIssueInput => ({ employee: "", purpose: "", issueDate: today(), amount: 0, currency: "EGP", paymentAccountId: "cash" });

export function CustodyCenter({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  const [items, setItems] = useState<CustodyAdvance[]>([]), [accounts, setAccounts] = useState<ChartAccount[]>([]), [draft, setDraft] = useState<CustodyIssueInput>(emptyIssue), [filter, setFilter] = useState("open"), [message, setMessage] = useState(""), [error, setError] = useState(""), [lastEntry, setLastEntry] = useState<GeneratedJournalEntry>();
  useEffect(() => { setItems(loadCustodies()); setAccounts(loadAccounts()); }, []);
  const commit = (next: CustodyAdvance[]) => { saveCustodies(next); setItems(next); };
  const paymentAccounts = accounts.filter((account) => account.active && account.allowPosting !== false && account.type === "asset" && ["cash", "bank"].includes(account.id));
  const expenseAccounts = accounts.filter((account) => account.active && account.allowPosting !== false && account.type === "expense");
  const visible = useMemo(() => items.filter((item) => filter === "all" || (filter === "open" ? item.status !== "settled" : item.status === filter)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [items, filter]);
  const issue = () => { try { setError(""); const result = issueCustody(draft, accounts); saveEntry(result.entry); commit([result.custody, ...items]); setLastEntry(result.entry); setDraft(emptyIssue()); setMessage(ar ? `تم صرف العهدة ${result.custody.number} وإنشاء القيد وترحيله لليومية.` : `${result.custody.number} issued and posted to the journal.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Failed to issue custody"); } };
  const saveSettlement = (item: CustodyAdvance, input: CustodySettlementInput) => { try { setError(""); const result = settleCustody(item, input, accounts); saveEntry(result.entry); commit(items.map((current) => current.id === item.id ? result.custody : current)); setLastEntry(result.entry); const due = custodyReimbursementDue(result.custody); setMessage(due > 0 ? (ar ? `تمت تسوية العهدة، وأصبح مبلغ ${due.toLocaleString()} ${item.currency} مستحقًا للموظف.` : `Custody settled; ${due.toLocaleString()} ${item.currency} is due to the employee.`) : result.custody.status === "settled" ? (ar ? `تمت تسوية وإقفال العهدة ${item.number} تلقائيًا.` : `${item.number} settled and closed automatically.`) : (ar ? `تم تسجيل التسوية. المتبقي ${custodyOutstanding(result.custody).toLocaleString()} ${item.currency}.` : `Settlement posted. Remaining: ${custodyOutstanding(result.custody).toLocaleString()} ${item.currency}.`)); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Settlement failed"); return false; } };
  const payReimbursement = (item: CustodyAdvance) => { try { setError(""); const result = reimburseCustody(item, today(), item.paymentAccountId, accounts); saveEntry(result.entry); commit(items.map((current) => current.id === item.id ? result.custody : current)); setLastEntry(result.entry); setMessage(ar ? `تم سداد فرق العهدة إلى ${item.employee} وإقفالها.` : `Employee reimbursement paid and custody closed.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Reimbursement failed"); } };
  const openItems = items.filter((item) => item.status !== "settled"), totalOutstanding = openItems.reduce((sum, item) => sum + custodyOutstanding(item), 0), totalIssued = items.reduce((sum, item) => sum + item.amount, 0), totalReimbursementDue = items.reduce((sum, item) => sum + custodyReimbursementDue(item), 0);

  return <div className="grid">
    <section className="grid four"><Metric title={ar ? "إجمالي العهد المصروفة" : "Total issued"} value={totalIssued.toLocaleString()} /><Metric title={ar ? "العهد المفتوحة" : "Open custodies"} value={openItems.length} /><Metric title={ar ? "الرصيد لدى الموظفين" : "Outstanding"} value={totalOutstanding.toLocaleString()} /><Metric title={ar ? "مستحق للموظفين" : "Due to employees"} value={totalReimbursementDue.toLocaleString()} /></section>

    <section className="card no-print"><h2><WalletCards size={21} /> {ar ? "صرف عهدة جديدة" : "Issue employee custody"}</h2><div className="grid three">
      <label>{ar ? "اسم مستلم العهدة" : "Employee / custodian"}<input list="custody-employees" value={draft.employee} onChange={(event) => setDraft({ ...draft, employee: event.target.value })} placeholder={ar ? "مثال: أحمد محمد" : "Example: Ahmed Mohamed"} /><datalist id="custody-employees">{[...new Set(items.map((item) => item.employee))].map((employee) => <option key={employee} value={employee} />)}</datalist></label>
      <label>{ar ? "الغرض من العهدة" : "Purpose"}<input value={draft.purpose} onChange={(event) => setDraft({ ...draft, purpose: event.target.value })} placeholder={ar ? "شراء أدوات مكتبية" : "Office supplies"} /></label>
      <label>{ar ? "تاريخ الصرف" : "Issue date"}<input type="date" value={draft.issueDate} onChange={(event) => setDraft({ ...draft, issueDate: event.target.value })} /></label>
      <label>{ar ? "قيمة العهدة" : "Amount"}<input type="number" min="0" step="0.01" value={draft.amount || ""} onChange={(event) => setDraft({ ...draft, amount: Number(event.target.value) })} /></label>
      <label>{ar ? "الصرف من" : "Paid from"}<select value={draft.paymentAccountId} onChange={(event) => setDraft({ ...draft, paymentAccountId: event.target.value })}>{paymentAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {ar ? account.nameAr : account.nameEn}</option>)}</select></label>
      <label>{ar ? "العملة" : "Currency"}<select value={draft.currency} onChange={(event) => setDraft({ ...draft, currency: event.target.value })}>{["EGP", "USD", "EUR", "SAR", "AED"].map((currency) => <option key={currency}>{currency}</option>)}</select></label>
    </div><button className="btn btn-primary" onClick={issue}><Plus size={17} />{ar ? "صرف العهدة وإنشاء القيد" : "Issue and post entry"}</button></section>

    {(message || error) && <section className={`warning ${error ? "error" : ""}`}>{error || message}</section>}
    {lastEntry && <><AccountingCycleTrace entry={lastEntry} locale={locale} title={ar ? "الدورة المحاسبية لآخر عملية عهدة" : "Latest custody accounting cycle"} /><EntryImpact entry={lastEntry} locale={locale} title={ar ? "تأثير آخر عملية عهدة" : "Latest custody entry impact"} /></>}
    <section className="card no-print"><div className="actions" style={{ justifyContent: "space-between" }}><h2><ReceiptText size={20} /> {ar ? "سجل العهد والتسويات" : "Custody register"}</h2><label>{ar ? "الحالة" : "Status"}<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="open">{ar ? "المفتوحة والجزئية" : "Open & partial"}</option><option value="settled">{ar ? "المقفلة" : "Closed"}</option><option value="all">{ar ? "الكل" : "All"}</option></select></label></div></section>

    {visible.map((item) => { const outstanding = custodyOutstanding(item), percentage = item.amount ? Math.min(100, Math.round((item.amount - outstanding) / item.amount * 100)) : 0; return <article className="card" key={item.id}>
      <div className="actions" style={{ justifyContent: "space-between", alignItems: "start" }}><div><span className={item.status === "settled" ? "badge" : item.status === "reimbursement-due" ? "warning error" : item.status === "partial" ? "warning" : "badge error"}>{item.status === "settled" ? (ar ? "مقفلة" : "Closed") : item.status === "reimbursement-due" ? (ar ? "مستحق للموظف" : "Employee due") : item.status === "partial" ? (ar ? "مسواة جزئيًا" : "Partial") : (ar ? "مفتوحة" : "Open")}</span><h2>{item.number} — {item.employee}</h2><p className="muted">{item.issueDate} · {item.purpose}</p></div><div style={{ textAlign: "end" }}><small className="muted">{ar ? "المتبقي من العهدة" : "Custody outstanding"}</small><div className="impact">{outstanding.toLocaleString()} {item.currency}</div></div></div>
      <div className="grid four"><Mini title={ar ? "المصروف" : "Issued"} value={item.amount} /><Mini title={ar ? "المسوى من العهدة" : "Applied to custody"} value={item.settledAmount} /><Mini title={ar ? "مبلغ مرتجع" : "Returned"} value={item.returnedAmount} /><Mini title={ar ? "مستحق للموظف" : "Employee due"} value={custodyReimbursementDue(item)} /><Mini title={ar ? "نسبة التسوية" : "Settlement"} value={`${percentage}%`} /></div><div style={{ height: 9, background: "var(--line)", borderRadius: 99 }}><div style={{ height: "100%", width: `${percentage}%`, background: item.status === "settled" ? "#10b981" : "#f59e0b", borderRadius: 99 }} /></div>
      {item.settlements.length > 0 && <div className="table-wrap section"><table><thead><tr><th>{ar ? "التاريخ" : "Date"}</th><th>{ar ? "البيان" : "Description"}</th><th>{ar ? "المستند" : "Document"}</th><th>{ar ? "الصافي" : "Net"}</th><th>{ar ? "الضريبة" : "VAT"}</th><th>{ar ? "المرتجع" : "Returned"}</th><th>{ar ? "زيادة دفعها الموظف" : "Employee excess"}</th></tr></thead><tbody>{item.settlements.map((settlement) => <tr key={settlement.id}><td>{settlement.date}</td><td>{settlement.description}</td><td>{settlement.documentReference || "—"}</td><td>{settlement.netAmount.toLocaleString()}</td><td>{settlement.vatAmount.toLocaleString()}</td><td>{settlement.returnedAmount.toLocaleString()}</td><td>{(settlement.excessAmount || 0).toLocaleString()}</td></tr>)}</tbody></table></div>}
      {item.status === "reimbursement-due" ? <div className="warning error no-print"><b>{ar ? `الشركة مدينة للموظف بمبلغ ${custodyReimbursementDue(item).toLocaleString()} ${item.currency}` : `Company owes employee ${custodyReimbursementDue(item).toLocaleString()} ${item.currency}`}</b><div className="actions"><button className="btn btn-primary" onClick={() => payReimbursement(item)}>{ar ? "سداد الفرق من الخزينة وإقفال العهدة" : "Pay difference and close"}</button></div></div> : item.status !== "settled" ? <SettlementForm item={item} accounts={expenseAccounts} ar={ar} onSave={(input) => saveSettlement(item, input)} /> : <p className="badge"><CheckCircle2 size={16} />{ar ? "رصيد العهدة صفر وتم إقفالها تلقائيًا" : "Zero balance — closed automatically"}</p>}
      <div className="actions no-print"><Link className="btn" href={`/${locale}/journal`}>{ar ? "عرض القيود في اليومية" : "View journal entries"}</Link></div>
    </article>; })}
    {!visible.length && <section className="card"><p className="muted">{ar ? "لا توجد عهد بهذه الحالة." : "No custody records in this status."}</p></section>}
  </div>;
}

function SettlementForm({ item, accounts, ar, onSave }: { item: CustodyAdvance; accounts: ChartAccount[]; ar: boolean; onSave: (input: CustodySettlementInput) => boolean }) {
  const empty = (): CustodySettlementInput => ({ date: today(), description: "", expenseAccountId: accounts[0]?.id, netAmount: 0, vatAmount: 0, returnedAmount: 0, documentReference: "" });
  const [draft, setDraft] = useState<CustodySettlementInput>(empty);
  const closeWithReturn = () => setDraft({ ...draft, netAmount: 0, vatAmount: 0, returnedAmount: custodyOutstanding(item), description: ar ? "رد المتبقي إلى الخزينة" : "Return remaining cash" });
  return <details className="no-print" style={{ marginTop: 18 }}><summary className="btn btn-primary"><RotateCcw size={16} />{ar ? "إضافة فاتورة أو تسوية العهدة" : "Add receipt or settle"}</summary><div className="card section"><h3>{ar ? "تسجيل مستند التسوية" : "Record settlement document"}</h3><div className="grid three">
    <label>{ar ? "التاريخ" : "Date"}<input type="date" value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} /></label><label>{ar ? "البيان / ما تم شراؤه" : "What was purchased"}<input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder={ar ? "مثال: أقلام وأدوات مكتبية" : "Pens and office supplies"} /></label><label>{ar ? "رقم الفاتورة أو المستند" : "Invoice / document no."}<input value={draft.documentReference || ""} onChange={(event) => setDraft({ ...draft, documentReference: event.target.value })} /></label>
    <label>{ar ? "حساب المصروف" : "Expense account"}<select value={draft.expenseAccountId} onChange={(event) => setDraft({ ...draft, expenseAccountId: event.target.value })}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {ar ? account.nameAr : account.nameEn}</option>)}</select></label><label>{ar ? "الصافي قبل الضريبة" : "Net amount"}<input type="number" min="0" step="0.01" value={draft.netAmount || ""} onChange={(event) => setDraft({ ...draft, netAmount: Number(event.target.value) })} /></label><label>{ar ? "قيمة الضريبة" : "VAT amount"}<input type="number" min="0" step="0.01" value={draft.vatAmount || ""} onChange={(event) => setDraft({ ...draft, vatAmount: Number(event.target.value) })} /></label><label>{ar ? "النقدية المرتجعة" : "Cash returned"}<input type="number" min="0" step="0.01" value={draft.returnedAmount || ""} onChange={(event) => setDraft({ ...draft, returnedAmount: Number(event.target.value) })} /></label>
  </div><p className="muted">{ar ? `رصيد العهدة: ${custodyOutstanding(item).toLocaleString()} ${item.currency}. يمكنك إدخال فاتورة أكبر من الرصيد وسيُسجل الفرق مستحقًا للموظف.` : `Custody balance: ${custodyOutstanding(item).toLocaleString()} ${item.currency}. A larger receipt records the excess as due to the employee.`}</p><div className="actions"><button className="btn btn-primary" onClick={() => { if (onSave(draft)) setDraft(empty()); }}><CircleDollarSign size={17} />{ar ? "إنشاء قيد التسوية" : "Post settlement"}</button><button className="btn" onClick={closeWithReturn}>{ar ? "رد كامل المتبقي" : "Return all remaining"}</button></div></div></details>;
}

function Metric({ title, value }: { title: string; value: string | number }) { return <div className="card"><span className="muted">{title}</span><div className="impact">{value}</div></div>; }
function Mini({ title, value }: { title: string; value: string | number }) { return <div><small className="muted">{title}</small><div><b>{typeof value === "number" ? value.toLocaleString() : value}</b></div></div>; }
