import { roundCurrency } from "@/lib/accounting/calculations";
import type { ChartAccount, CustodyAdvance, CustodyIssueInput, CustodySettlementInput, GeneratedJournalEntry, JournalEntryLine } from "@/types";

const account = (accounts: ChartAccount[], id: string) => { const found = accounts.find((item) => item.id === id); if (!found) throw new Error(`Missing account: ${id}`); return found; };
const line = (item: ChartAccount, debit = 0, credit = 0): JournalEntryLine => ({ id: crypto.randomUUID(), accountCode: item.code, accountNameAr: item.nameAr, accountNameEn: item.nameEn, debit: roundCurrency(debit), credit: roundCurrency(credit) });
const entry = (data: { date: string; type: string; titleAr: string; titleEn: string; narrationAr: string; narrationEn: string; currency: string; lines: JournalEntryLine[]; expenses?: number; cash?: number }): GeneratedJournalEntry => {
  const totalDebit = roundCurrency(data.lines.reduce((sum, item) => sum + item.debit, 0)), totalCredit = roundCurrency(data.lines.reduce((sum, item) => sum + item.credit, 0));
  return { id: crypto.randomUUID(), entryNumber: `CUS-${Date.now().toString().slice(-6)}-${Math.floor(Math.random() * 90 + 10)}`, date: data.date, transactionType: data.type, titleAr: data.titleAr, titleEn: data.titleEn, narrationAr: data.narrationAr, narrationEn: data.narrationEn, currency: data.currency, lines: data.lines, totalDebit, totalCredit, isBalanced: Math.abs(totalDebit - totalCredit) < .01, explanationAr: ["تم إنشاء القيد تلقائيًا من دورة العهد."], explanationEn: ["Automatically generated by the employee custody workflow."], assumptionsAr: [], assumptionsEn: [], warningsAr: [], warningsEn: [], accountingRuleAr: "تتم متابعة العهدة كأصل متداول حتى تقديم المستندات أو رد النقدية.", accountingRuleEn: "The advance remains a current asset until documented or returned.", financialStatementImpact: { assets: -(data.expenses || 0), liabilities: 0, equity: -(data.expenses || 0), revenue: 0, expenses: data.expenses || 0, profit: -(data.expenses || 0), cash: data.cash || 0 }, cashFlowCategory: "operating", confidence: 1, workflowStatus: "posted" };
};

export function custodyOutstanding(item: CustodyAdvance) { return Math.max(0, roundCurrency(item.amount - item.settledAmount - item.returnedAmount)); }
export function custodyReimbursementDue(item: CustodyAdvance) { return Math.max(0, roundCurrency((item.reimbursementAmount || 0) - (item.reimbursedAmount || 0))); }

export function issueCustody(input: CustodyIssueInput, accounts: ChartAccount[]) {
  if (!input.employee.trim() || !input.purpose.trim()) throw new Error("Employee and purpose are required");
  if (!Number.isFinite(input.amount) || input.amount <= 0) throw new Error("Amount must be greater than zero");
  const custodyAccount = account(accounts, "employee-advances"), paymentAccount = account(accounts, input.paymentAccountId);
  const journalEntry = entry({ date: input.issueDate, type: "custody-issue", titleAr: `صرف عهدة إلى ${input.employee.trim()}`, titleEn: `Custody advance to ${input.employee.trim()}`, narrationAr: `صرف عهدة إلى ${input.employee.trim()} — ${input.purpose.trim()}`, narrationEn: `Custody advance to ${input.employee.trim()} — ${input.purpose.trim()}`, currency: input.currency, lines: [line(custodyAccount, input.amount), line(paymentAccount, 0, input.amount)], cash: -input.amount });
  const custody: CustodyAdvance = { id: crypto.randomUUID(), number: `CU-${Date.now().toString().slice(-6)}`, employee: input.employee.trim(), purpose: input.purpose.trim(), issueDate: input.issueDate, amount: roundCurrency(input.amount), currency: input.currency, paymentAccountId: input.paymentAccountId, status: "open", settledAmount: 0, returnedAmount: 0, issueEntryId: journalEntry.id, settlements: [], createdAt: new Date().toISOString() };
  return { custody, entry: journalEntry };
}

export function settleCustody(item: CustodyAdvance, input: CustodySettlementInput, accounts: ChartAccount[]) {
  if (item.status === "settled") throw new Error("Custody is already settled");
  const net = roundCurrency(Number(input.netAmount) || 0), vat = roundCurrency(Number(input.vatAmount) || 0), returned = roundCurrency(Number(input.returnedAmount) || 0), documented = roundCurrency(net + vat), outstanding = custodyOutstanding(item);
  if (net < 0 || vat < 0 || returned < 0 || documented + returned <= 0) throw new Error("Settlement amount must be greater than zero");
  if (returned - outstanding > .01) throw new Error("Returned cash exceeds outstanding custody balance");
  if ((net > 0 || vat > 0) && !input.description.trim()) throw new Error("Settlement description is required");
  if (net > 0 && !input.expenseAccountId) throw new Error("Expense account is required");
  const custodyAccount = account(accounts, "employee-advances"), paymentAccount = account(accounts, item.paymentAccountId), availableForCosts = roundCurrency(outstanding - returned), appliedToCosts = Math.min(documented, availableForCosts), excess = roundCurrency(documented - appliedToCosts), appliedToCustody = roundCurrency(appliedToCosts + returned), lines: JournalEntryLine[] = [];
  if (net > 0) lines.push(line(account(accounts, input.expenseAccountId!), net));
  if (vat > 0) lines.push(line(account(accounts, "input-vat"), vat));
  if (returned > 0) lines.push(line(paymentAccount, returned));
  if (appliedToCustody > 0) lines.push(line(custodyAccount, 0, appliedToCustody));
  if (excess > 0) lines.push(line(account(accounts, "employee-reimbursements-payable"), 0, excess));
  const journalEntry = entry({ date: input.date, type: "custody-settlement", titleAr: `تسوية عهدة ${item.employee}`, titleEn: `Custody settlement — ${item.employee}`, narrationAr: `تسوية العهدة ${item.number} — ${input.description.trim() || "رد نقدية"}`, narrationEn: `Settlement of ${item.number} — ${input.description.trim() || "Cash return"}`, currency: item.currency, lines, expenses: net, cash: returned });
  const nextSettled = roundCurrency(item.settledAmount + appliedToCosts), nextReturned = roundCurrency(item.returnedAmount + returned), nextReimbursement = roundCurrency((item.reimbursementAmount || 0) + excess), remaining = roundCurrency(item.amount - nextSettled - nextReturned);
  const updated: CustodyAdvance = { ...item, settledAmount: nextSettled, returnedAmount: nextReturned, reimbursementAmount: nextReimbursement, reimbursedAmount: item.reimbursedAmount || 0, status: remaining <= .01 ? (nextReimbursement > (item.reimbursedAmount || 0) ? "reimbursement-due" : "settled") : "partial", settlements: [...item.settlements, { id: crypto.randomUUID(), date: input.date, description: input.description.trim() || "رد نقدية", expenseAccountId: input.expenseAccountId, netAmount: net, vatAmount: vat, returnedAmount: returned, excessAmount: excess, documentReference: input.documentReference?.trim() || undefined, entryId: journalEntry.id, createdAt: new Date().toISOString() }] };
  return { custody: updated, entry: journalEntry };
}

export function reimburseCustody(item: CustodyAdvance, date: string, paymentAccountId: string, accounts: ChartAccount[]) {
  const due = custodyReimbursementDue(item); if (due <= 0) throw new Error("No reimbursement is due");
  const payable = account(accounts, "employee-reimbursements-payable"), payment = account(accounts, paymentAccountId);
  const journalEntry = entry({ date, type: "custody-reimbursement", titleAr: `سداد فرق عهدة إلى ${item.employee}`, titleEn: `Custody reimbursement — ${item.employee}`, narrationAr: `سداد المبلغ المستحق للموظف عن العهدة ${item.number}`, narrationEn: `Payment of employee reimbursement for ${item.number}`, currency: item.currency, lines: [line(payable, due), line(payment, 0, due)], cash: -due });
  return { custody: { ...item, reimbursedAmount: roundCurrency((item.reimbursedAmount || 0) + due), status: "settled" as const }, entry: journalEntry };
}
