import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, BarChart3, BookOpen, BriefcaseBusiness, Building2, Calculator, Check, CheckCircle2, ChevronDown, CircleDollarSign, ClipboardCheck, Clock3, CloudOff, FileCheck2, FileSearch, FileSpreadsheet, Gauge, HardDrive, Landmark, Languages, LayoutDashboard, ListChecks, PackageCheck, ReceiptText, RefreshCcw, ScanLine, ShieldAlert, ShieldCheck, Smartphone, Store, Users, WalletCards, Workflow, Zap } from "lucide-react";
import { posOperationTypes, posProviders } from "@/data/pos";
import { servicePointCommercialConfig } from "@/data/service-point-plans";
import { HawallyBrand } from "@/components/brand/hawally-brand";
import { AccountingPreview, HeroProductPreview, OwnerDashboardPreview } from "@/components/marketing/product-previews";
import type { Locale } from "@/types";

type Copy = { ar: string; en: string };
const copy = (value: Copy, locale: Locale) => value[locale];
const DirectionArrow = ({ ar }: { ar: boolean }) => ar ? <ArrowLeft size={18}/> : <ArrowRight size={18}/>;

const pillars = [
  { icon: Store, eyebrow: { ar: "تشغيل نقطة الخدمات", en: "Service Point Operations" }, title: { ar: "من أول الوردية لحد تسليمها", en: "From shift open to handover" }, text: { ar: "سجّل عمليات العملاء، تابع الخزنة وأرصدة الخدمات، طابق الفروق واقفل الوردية بصورة واضحة.", en: "Record customer operations, track cash and provider balances, reconcile differences, and close every shift clearly." }, points: [{ ar: "عمليات العملاء", en: "Customer operations" }, { ar: "أرصدة مستقلة", en: "Separate balances" }, { ar: "مطابقة وتسليم", en: "Reconciliation & handover" }] },
  { icon: BookOpen, eyebrow: { ar: "العمليات المحاسبية", en: "Accounting Operations" }, title: { ar: "كل حركة توصل لحساباتها", en: "Every movement reaches the books" }, text: { ar: "دورة قيد كاملة من المستند والمراجعة حتى الأستاذ وميزان المراجعة والقوائم والإقفال.", en: "A complete journal workflow from documents and review through ledger, trial balance, statements, and close." }, points: [{ ar: "قيود ومراجعة", en: "Entries & review" }, { ar: "تقارير وقوائم", en: "Reports & statements" }, { ar: "فترات وإقفال", en: "Periods & close" }] },
  { icon: LayoutDashboard, eyebrow: { ar: "رقابة المالك", en: "Owner Control" }, title: { ar: "اعرف اللي حصل من شاشة واحدة", en: "See what happened from one screen" }, text: { ar: "الربح والسيولة وصحة الأرصدة والاستثناءات وأداء الوردية والكاشير في ملخص عملي قابل للطباعة.", en: "Profit, liquidity, balance health, exceptions, shifts, and cashier facts in one practical printable view." }, points: [{ ar: "حزمة المالك", en: "Daily owner pack" }, { ar: "استثناءات وتنبيهات", en: "Exceptions & alerts" }, { ar: "ربحية وسيولة", en: "Profit & liquidity" }] },
];

const intelligence = [
  [Gauge, { ar: "صحة مقدمي الخدمة", en: "Provider Health" }], [WalletCards, { ar: "تحسين السيولة", en: "Liquidity Optimizer" }],
  [ShieldAlert, { ar: "معاينة مخاطر العملية", en: "Operation Risk Preview" }], [BarChart3, { ar: "ربحية الرسوم", en: "Fee Profitability" }],
  [Calculator, { ar: "نقطة التعادل", en: "Break-even" }], [Clock3, { ar: "مدى كفاية الرصيد", en: "Balance Runway" }],
  [FileCheck2, { ar: "الملخص اليومي الذكي", en: "Smart Daily Brief" }], [RefreshCcw, { ar: "مقارنة الورديات", en: "Shift Comparison" }],
] as const;

const controls = [
  [WalletCards, { ar: "حركات المالك والمدير", en: "Owner & manager movements" }], [Calculator, { ar: "ميزانيات المصروفات", en: "Expense budgets" }],
  [ShieldAlert, { ar: "سجل الحوادث", en: "Incident register" }], [ClipboardCheck, { ar: "قوائم الفتح والإغلاق", en: "Opening & closing checklists" }],
  [Clock3, { ar: "الخط الزمني للوردية", en: "Shift timeline" }], [PackageCheck, { ar: "حزمة المالك اليومية", en: "Daily owner pack" }],
  [Landmark, { ar: "كشف مقدم الخدمة", en: "Provider statement" }], [ListChecks, { ar: "مركز الاستثناءات", en: "Exception center" }],
] as const;

const accountingModules = [
  [BookOpen, { ar: "دليل الحسابات", en: "Chart of Accounts" }], [Workflow, { ar: "دورة القيود", en: "Journal Workflow" }],
  [ShieldCheck, { ar: "المراجعة والاعتماد", en: "Review & Approval" }], [FileSpreadsheet, { ar: "الأستاذ وميزان المراجعة", en: "Ledger & Trial Balance" }],
  [BarChart3, { ar: "القوائم المالية", en: "Financial Statements" }], [ReceiptText, { ar: "الدورة المستندية", en: "Business Documents" }],
  [ScanLine, { ar: "قراءة الفواتير", en: "Invoice Capture" }], [Landmark, { ar: "مطابقة البنك", en: "Bank Reconciliation" }],
  [Users, { ar: "العملاء والموردون", en: "Customers & Suppliers" }], [CircleDollarSign, { ar: "التحصيلات والسيولة", en: "Receivables & Cash Flow" }],
  [BriefcaseBusiness, { ar: "العهد", en: "Custody" }], [Calculator, { ar: "القيمة المضافة", en: "VAT" }],
  [Clock3, { ar: "الفترات والإقفال", en: "Periods & Close" }], [FileSearch, { ar: "تحليل الجداول", en: "Spreadsheet Analysis" }],
  [Building2, { ar: "مكتب المحاسبة", en: "Accounting Office" }],
] as const;

export function LandingPage({ locale }: { locale: Locale }) {
  const ar = locale === "ar", demoHref = `/${locale}/service-point/demo`, serviceHref = `/${locale}/service-point`;
  return <div className="marketing-page">
    <section className="marketing-hero" id="product"><div className="marketing-grid-lines" aria-hidden="true"/><div className="container marketing-hero-grid">
      <div className="marketing-hero-copy"><span className="marketing-kicker"><Zap size={15}/>{ar ? "تشغيل · محاسبة · رقابة مالية" : "Operations · Accounting · Financial Control"}</span><h1>{ar ? <>شغّل نقطة خدماتك.<br/><em>راقب فلوسك.</em><br/>وافهم حساباتك.</> : <>Run the counter.<br/><em>Control the money.</em><br/>Understand the books.</>}</h1><p>{ar ? "حوّلي يجمع عمليات العملاء والخزنة وأرصدة الخدمات والورديات والتسوية والربحية والمحاسبة في نظام تشغيل واحد لنقاط الخدمات والمنشآت الصغيرة." : "Hawally brings customer operations, cash, provider balances, shifts, reconciliation, profitability, and accounting into one operating system for service points and small businesses."}</p><div className="marketing-actions"><Link className="btn btn-primary marketing-primary" href={demoHref}>{ar ? "جرّب حوّلي الآن" : "Try Hawally now"}<DirectionArrow ar={ar}/></Link><Link className="btn marketing-secondary" href={serviceHref}>{ar ? "استكشف نقطة الخدمات" : "Explore Service Point"}</Link></div><div className="marketing-hero-note"><ShieldCheck size={17}/><span>{ar ? "تجربة محلية بلا تسجيل، وبلا ربط مباشر بحسابات مقدمي الخدمة." : "A local demo with no signup and no direct provider-account integration."}</span></div></div>
      <HeroProductPreview locale={locale}/>
    </div></section>

    <section className="marketing-trust" aria-label={ar ? "قدرات المنتج" : "Product capabilities"}><div className="container">{[[Languages,{ar:"عربي + English",en:"Arabic + English"}],[Workflow,{ar:"RTL + LTR",en:"RTL + LTR"}],[Smartphone,{ar:"PWA قابلة للتثبيت",en:"Installable PWA"}],[HardDrive,{ar:"Local-first",en:"Local-first"}],[BookOpen,{ar:"محرك محاسبي",en:"Accounting engine"}],[ShieldCheck,{ar:"Light + Dark",en:"Light + Dark"}]].map(([Icon,label])=>{const FeatureIcon=Icon as typeof Languages;return <span key={(label as Copy).en}><FeatureIcon size={18}/>{copy(label as Copy,locale)}</span>;})}</div></section>

    <section className="marketing-section" id="pillars"><div className="container"><SectionHeading locale={locale} eyebrow={{ar:"منتج واحد، ثلاث طبقات",en:"One product, three layers"}} title={{ar:"التشغيل اليومي والحسابات وقرار المالك — متصلين",en:"Daily operations, accounting, and owner decisions — connected"}} text={{ar:"حوّلي لا يسجل العملية فقط؛ يربط أثرها بالخزنة ورصيد الخدمة والربح والقيد والمتابعة.",en:"Hawally does more than record a transaction; it connects the impact on cash, provider balance, profit, accounting, and follow-up."}}/><div className="marketing-pillars">{pillars.map((pillar,index)=>{const Icon=pillar.icon;return <article key={pillar.eyebrow.en}><span className="marketing-card-index">0{index+1}</span><Icon/><small>{copy(pillar.eyebrow,locale)}</small><h3>{copy(pillar.title,locale)}</h3><p>{copy(pillar.text,locale)}</p><ul>{pillar.points.map(point=><li key={point.en}><Check size={15}/>{copy(point,locale)}</li>)}</ul></article>;})}</div></div></section>

    <section className="marketing-section marketing-service-section" id="service-point"><div className="container"><div className="marketing-section-grid"><div><SectionHeading locale={locale} eyebrow={{ar:"Hawally Service Point",en:"Hawally Service Point"}} title={{ar:"من أول الوردية لحد ما تسلّمها",en:"From opening the shift to handing it over"}} text={{ar:"كل خطوة في يوم المحل تؤثر فورًا على الخزنة أو رصيد الخدمة والربح والقيد المرتبط، مع بقاء المعلقة والفاشلة خارج الأرصدة الحية.",en:"Every step affects cash or a provider balance, profit, and the linked entry, while pending and failed operations stay outside live balances."}}/><Link className="marketing-text-link" href={serviceHref}>{ar?"افتح مساحة التشغيل":"Open the operations workspace"}<DirectionArrow ar={ar}/></Link></div><div className="marketing-flow">{[{ar:"اختيار المحل",en:"Select store"},{ar:"فتح الوردية",en:"Open shift"},{ar:"تسجيل العملية",en:"Record operation"},{ar:"أثر الرصيد والربح",en:"Balance & profit impact"},{ar:"مراجعة الاستثناءات",en:"Review exceptions"},{ar:"المطابقة",en:"Reconcile"},{ar:"الإقفال والتسليم",en:"Close & hand over"}].map((step,index)=><div key={step.en}><span>{String(index+1).padStart(2,"0")}</span><b>{copy(step,locale)}</b>{index<6&&<i><DirectionArrow ar={ar}/></i>}</div>)}</div></div>
      <div className="marketing-provider-showcase"><div><h3>{ar?"سبعة أرصدة واضحة — لا تكاملات ندّعيها":"Seven clear balances — no integrations we do not have"}</h3><p>{ar?"حوّلي يدير عمليات وأرصدة هذه الخدمات محليًا داخل المحل. لا توجد في النسخة الحالية واجهات API رسمية أو مزامنة مباشرة معها.":"Hawally manages these services and balances locally in the store. The current edition has no official provider APIs or direct synchronization."}</p></div><div className="marketing-provider-grid">{posProviders.map(provider=><span key={provider.id} style={{"--provider":provider.color} as React.CSSProperties}><i/>{ar?provider.nameAr:provider.nameEn}</span>)}</div></div>
      <div className="marketing-operation-grid">{posOperationTypes.map((operation,index)=>{const icons=[ArrowRight,WalletCards,ReceiptText,Smartphone,RefreshCcw,Workflow,CircleDollarSign];const Icon=icons[index];return <article key={operation.id}><Icon/><b>{ar?operation.nameAr:operation.nameEn}</b><span>{String(index+1).padStart(2,"0")}</span></article>;})}</div>
    </div></section>

    <section className="marketing-section marketing-logic-section"><div className="container marketing-logic-grid"><SectionHeading locale={locale} eyebrow={{ar:"الربح الحقيقي، مش حجم الحركة",en:"Real profit, not transaction volume"}} title={{ar:"قيمة العملية ليست إيرادًا",en:"Transaction value is not revenue"}} text={{ar:"حوّلي يفصل بين أصل المبلغ والعمولة والتكلفة والمصروف، حتى لا يبدو دوران الأموال وكأنه ربح.",en:"Hawally separates principal, customer fee, provider cost, and store expense so money movement never masquerades as profit."}}/><div className="marketing-equations"><div><span>{ar?"عمولة العميل":"Customer fee"}</span><i>−</i><span>{ar?"تكلفة مقدم الخدمة":"Provider cost"}</span><i>=</i><strong>{ar?"ربح العملية":"Operation profit"}</strong></div><div><span>{ar?"أرباح العمليات":"Operation profits"}</span><i>−</i><span>{ar?"مصروفات المحل":"Store expenses"}</span><i>=</i><strong>{ar?"الربح التشغيلي":"Operating profit"}</strong></div></div></div></section>

    <section className="marketing-section" id="owner"><div className="container marketing-showcase-grid"><OwnerDashboardPreview locale={locale}/><div><SectionHeading locale={locale} eyebrow={{ar:"لوحة المالك",en:"Owner Control"}} title={{ar:"اعرف اللي حصل في المحل من شاشة واحدة",en:"Know what happened in the store from one screen"}} text={{ar:"راجع ربح اليوم وحجم العمليات والخزنة وأرصدة الخدمات والمعلقة والفروق وصحة مقدمي الخدمة وأداء الكاشير — ثم اطبع حزمة المالك اليومية.",en:"Review today’s profit, volume, cash, provider balances, pending items, variances, provider health, and cashier facts — then print the daily owner pack."}}/><ul className="marketing-check-list">{(ar?["ربحية وسيولة وفروق","مقارنة فترات وورديات","توصيات تشغيلية مبنية على قواعد","حزمة يومية قابلة للطباعة"]:["Profit, liquidity, and variances","Period and shift comparisons","Rule-based operating recommendations","Printable daily owner pack"]).map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul><Link className="btn" href={`/${locale}/service-point/owner-dashboard`}>{ar?"استكشف لوحة المالك":"Explore Owner Dashboard"}<DirectionArrow ar={ar}/></Link></div></div></section>

    <section className="marketing-section marketing-intelligence-section"><div className="container"><SectionHeading locale={locale} eyebrow={{ar:"تحليلات تشغيلية تعمل محليًا",en:"Operational intelligence that runs locally"}} title={{ar:"قرارات أوضح من البيانات الموجودة على جهازك",en:"Clearer decisions from the data on your device"}} text={{ar:"حسابات حتمية قائمة على قواعد المنتج — بلا خدمة ذكاء اصطناعي خارجية وبلا وعود غير قابلة للتتبع.",en:"Deterministic, rule-based product calculations — no external AI service and no untraceable claims."}}/><div className="marketing-intelligence-grid">{intelligence.map(([Icon,label])=><article key={label.en}><Icon/><b>{copy(label,locale)}</b></article>)}</div></div></section>

    <section className="marketing-section" id="control"><div className="container"><div className="marketing-control-head"><SectionHeading locale={locale} eyebrow={{ar:"تحكم تشغيلي مكتمل",en:"Completed operations control"}} title={{ar:"اليوم العادي والاستثناء — في نفس السجل",en:"Routine work and exceptions — in the same record"}} text={{ar:"هذه الأدوات منفذة داخل حزمة Service Point الحالية، وتُحفظ مع النسخة الاحتياطية المحلية لكل متجر.",en:"These controls are implemented in the current Service Point suite and included in each store’s local backup."}}/><div className="marketing-mode-switch"><span>{ar?"صباحي":"Morning"}</span><span>{ar?"مسائي":"Evening"}</span></div></div><div className="marketing-control-grid">{controls.map(([Icon,label])=><article key={label.en}><span><Icon/></span><b>{copy(label,locale)}</b><CheckCircle2/></article>)}</div></div></section>

    <section className="marketing-section marketing-accounting-section" id="accounting"><div className="container"><div className="marketing-showcase-grid reverse"><div><SectionHeading locale={locale} eyebrow={{ar:"Hawally Accounting",en:"Hawally Accounting"}} title={{ar:"من المستند إلى القوائم والإقفال",en:"From document to statements and close"}} text={{ar:"الجزء المحاسبي ليس إضافة صغيرة؛ هو دورة تشغيل كاملة للمستند والقيد والمراجعة والترحيل والتقارير والفترة المالية.",en:"Accounting is not a small add-on; it is a complete operating cycle for documents, entries, review, posting, reporting, and periods."}}/><Link className="btn" href={`/${locale}/dashboard`}>{ar?"افتح مساحة المحاسبة":"Open accounting workspace"}<DirectionArrow ar={ar}/></Link></div><AccountingPreview locale={locale}/></div><div className="marketing-accounting-modules">{accountingModules.map(([Icon,label])=><span key={label.en}><Icon/>{copy(label,locale)}</span>)}</div><div className="marketing-accounting-flow">{[{ar:"عملية أو مستند",en:"Transaction / Document"},{ar:"قيد موحّد",en:"Unified Entry"},{ar:"مراجعة",en:"Review"},{ar:"اعتماد",en:"Approval"},{ar:"ترحيل",en:"Posting"},{ar:"أستاذ",en:"Ledger"},{ar:"ميزان مراجعة",en:"Trial Balance"},{ar:"تقارير",en:"Reports"},{ar:"إقفال",en:"Close"}].map((step,index)=><div key={step.en}><span>{index+1}</span><b>{copy(step,locale)}</b>{index<8&&<ChevronDown/>}</div>)}</div></div></section>

    <section className="marketing-section"><div className="container marketing-tools-grid"><article><ScanLine/><h3>{ar?"المستندات والبيانات تدخل بأقل تكرار":"Documents and data, with less re-entry"}</h3><p>{ar?"قراءة PDF وOCR محلي، تحليل Excel وCSV، التقاط الفاتورة، استيراد كشف البنك، وبصمات للمستندات وحماية من التكرار.":"PDF reading, local OCR, Excel and CSV analysis, invoice capture, bank-statement import, document fingerprints, and duplicate protection."}</p><div>{["PDF","OCR","Excel / CSV",ar?"كشف بنك":"Bank CSV"].map(item=><span key={item}>{item}</span>)}</div></article><article className="marketing-local-card"><CloudOff/><h3>{ar?"بياناتك على جهازك في النسخة الحالية":"Your data stays on your device in the current edition"}</h3><p>{ar?"حفظ محلي، Backup واستعادة يدويان، PWA قابلة للتثبيت وOffline shell. لا توجد مزامنة سحابية أو صلاحيات خادمية أو ربط مباشر بمقدمي الخدمة.":"Local persistence, manual backup and restore, an installable PWA, and an offline shell. There is no cloud sync, server authorization, or direct provider connection."}</p><Link href={`/${locale}/privacy`}>{ar?"اقرأ سياسة الخصوصية":"Read the privacy policy"}<DirectionArrow ar={ar}/></Link></article></div></section>

    <section className="marketing-section marketing-pwa-section"><div className="container marketing-pwa-grid"><div><span className="marketing-kicker"><Smartphone/>{ar?"على شاشة المحل أو في جيب المالك":"At the counter or in the owner’s pocket"}</span><h2>{ar?"واجهة متجاوبة، وService Point قابل للتثبيت":"Responsive by design, with an installable Service Point PWA"}</h2><p>{ar?"نفّذ العملية السريعة، راجع الرصيد، وانتقل بلوحة تنقل مناسبة للهاتف. التثبيت لا يعني مزامنة بين الأجهزة؛ البيانات تظل محلية في النسخة الحالية.":"Run a quick operation, review a balance, and move through touch-friendly mobile navigation. Installation does not add cross-device sync; data remains local in the current edition."}</p></div><div className="marketing-pwa-phone"><div><b>H</b><span>Hawally</span></div><small>{ar?"وردية أحمد — مفتوحة":"Ahmed’s shift — open"}</small><h3>{ar?"إجمالي السيولة":"Total liquidity"}</h3><strong>{ar?"٤٢٬٤٣٦ ج.م":"EGP 42,436"}</strong><section><span>{ar?"فوري":"Fawry"}<b>{ar?"٤١٧":"417"}</b></span><span>{ar?"فودافون كاش":"Vodafone Cash"}<b>{ar?"١٨٬٧٩٧":"18,797"}</b></span></section><button type="button" tabIndex={-1}>+ {ar?"عملية جديدة":"New operation"}</button></div></div></section>

    <section className="marketing-section" id="plans"><div className="container"><SectionHeading locale={locale} eyebrow={{ar:"باقات Service Point",en:"Service Point plans"}} title={{ar:"ابدأ بالحجم المناسب لطريقة شغلك",en:"Start with the level that fits your operation"}} text={{ar:`الأسعار والإمكانات من إعداد المنتج الحالي. التفعيل يدوي، ولا توجد بوابة دفع داخل النسخة الحالية. الاشتراك السنوي يوفر شهرين.`,en:`Prices and limits come from the current product configuration. Activation is manual and there is no in-product payment gateway. Annual billing includes ${servicePointCommercialConfig.annualFreeMonths} free months.`}}/><div className="marketing-pricing-grid">{servicePointCommercialConfig.plans.map(plan=><article className={plan.featured?"featured":""} key={plan.id}>{plan.featured&&<span className="marketing-popular">{ar?"الأكثر اختيارًا":"Most popular"}</span>}<h3>{ar?plan.nameAr:plan.nameEn}</h3><div><strong>{plan.monthlyPrice.toLocaleString(ar?"ar-EG":"en-US")}</strong><span>{ar?"ج.م / شهر":"EGP / month"}</span></div><p>{ar?`${plan.storeLimit} محل · ${plan.userLimit} مستخدم محلي`:`${plan.storeLimit} store${plan.storeLimit>1?"s":""} · ${plan.userLimit} local users`}</p><ul>{(ar?plan.featuresAr:plan.featuresEn).slice(0,3).map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><Link className={`btn ${plan.featured?"btn-primary":""}`} href={`/${locale}/service-point/plans`}>{ar?"راجع الباقة":"Review plan"}</Link></article>)}</div></div></section>

    <section className="marketing-section marketing-why-section" id="how-it-works"><div className="container"><SectionHeading locale={locale} eyebrow={{ar:"ليه حوّلي؟",en:"Why Hawally?"}} title={{ar:"بدل ما يوم المحل يتوزع بين دفاتر وشاشات منفصلة",en:"Replace scattered notebooks and screens with one operating flow"}}/><div className="marketing-before-after"><div><small>{ar?"قبل":"Before"}</small>{(ar?["دفتر خزنة منفصل","أرصدة محافظ مكتوبة يدويًا","ملاحظات وردية متناثرة","حساب ربح على الآلة الحاسبة","ملف محاسبة منفصل"]:["Separate cash notebook","Manually written wallet balances","Scattered shift notes","Calculator-based profit","A separate accounting file"]).map(item=><span key={item}><AlertTriangle/>{item}</span>)}</div><i><DirectionArrow ar={ar}/></i><div><small>{ar?"مع حوّلي":"With Hawally"}</small><strong>{ar?"عملية واحدة. أثر واحد واضح. وسجل يرجع له المالك والمحاسب.":"One operation. One clear impact. One record for the owner and accountant."}</strong><Link href={demoHref}>{ar?"شاهد الدورة في الديمو":"See the flow in the demo"}<DirectionArrow ar={ar}/></Link></div></div></div></section>

    <section className="marketing-final"><div className="container"><div><span>{ar?"جاهز تبدأ؟":"Ready to start?"}</span><h2>{ar?"شغّل يومك من مكان واحد.":"Run the whole day from one place."}</h2><p>{ar?"جرّب دورة حوّلي من فتح الوردية وحتى تقرير المالك — داخل متصفحك وببيانات Demo جاهزة.":"Try the Hawally flow from opening a shift to the owner report — in your browser with ready demo data."}</p></div><div className="marketing-actions"><Link className="btn btn-primary" href={demoHref}>{ar?"جرّب الديمو":"Try the demo"}<DirectionArrow ar={ar}/></Link><Link className="btn" href={serviceHref}>{ar?"استكشف النظام":"Explore the system"}</Link></div></div></section>

    <footer className="marketing-footer"><div className="container marketing-footer-grid"><div><HawallyBrand locale={locale} href={`/${locale}`}/><p>{ar?"تشغيل ومحاسبة ورقابة مالية لنقاط الخدمات والمنشآت الصغيرة.":"Operations, accounting, and financial control for service points and small businesses."}</p></div><nav><b>{ar?"المنتج":"Product"}</b><a href="#service-point">{ar?"نقطة الخدمات":"Service Point"}</a><a href="#accounting">{ar?"المحاسبة":"Accounting"}</a><a href="#owner">{ar?"لوحة المالك":"Owner Control"}</a></nav><nav><b>{ar?"ابدأ":"Start"}</b><Link href={demoHref}>{ar?"الديمو":"Demo"}</Link><Link href={`/${locale}/service-point/plans`}>{ar?"الباقات":"Plans"}</Link><Link href={`/${locale}/dashboard`}>{ar?"مساحة المحاسبة":"Accounting workspace"}</Link></nav><nav><b>{ar?"معلومات":"Information"}</b><Link href={`/${locale}/about`}>{ar?"عن حوّلي":"About"}</Link><Link href={`/${locale}/privacy`}>{ar?"الخصوصية":"Privacy"}</Link><Link href={`/${locale}/terms`}>{ar?"الشروط":"Terms"}</Link></nav></div><div className="container marketing-footer-bottom"><span>© 2026 Hawally · حوّلي</span><Link href={`/${ar?"en":"ar"}`}>{ar?"English":"العربية"}<Languages size={15}/></Link></div></footer>
  </div>;
}

function SectionHeading({ locale, eyebrow, title, text }: { locale: Locale; eyebrow: Copy; title: Copy; text?: Copy }) {
  return <header className="marketing-heading"><span>{copy(eyebrow,locale)}</span><h2>{copy(title,locale)}</h2>{text&&<p>{copy(text,locale)}</p>}</header>;
}
