
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import {
  Activity, ArrowLeft, ArrowRight, BarChart3, BookOpen, Building2, CheckCircle2,
  CircleDollarSign, FileBarChart, FileSpreadsheet, GraduationCap, Landmark, LayoutDashboard,
  Pause, Play, Printer, ReceiptText, ScanText, ShieldCheck, Sparkles, Store, Users, WalletCards, Workflow,
} from "lucide-react";
import type { Locale } from "@/types";

type Copy = { ar: string; en: string };
const t = (copy: Copy, locale: Locale) => copy[locale];

const features = [
  { icon: GraduationCap, title: { ar: "أكاديمية فينورا للمحاسبة", en: "FINORA Accounting Academy" }, text: { ar: "مسارات ودروس وأمثلة قيود واختبارات ومعمل تدريب يبني محاسبًا عمليًا من الصفر.", en: "Tracks, lessons, journal examples, quizzes, and a practice lab that build real accounting skill." } },
  { icon: Activity, title: { ar: "لوحة عمل المحاسب اليومية", en: "Daily accountant workspace" }, text: { ar: "مهام اليوم، الاستحقاقات، القيود المنتظرة والمخاطر في شاشة واحدة.", en: "Daily tasks, due items, pending entries, and risks in one workspace." } },
  { icon: ReceiptText, title: { ar: "دورة مستندية متكاملة", en: "Complete document cycle" }, text: { ar: "بيع وشراء وقبض وصرف، ثم مراجعة واعتماد وترحيل تلقائي.", en: "Sales, purchases, receipts, and payments through review, approval, and posting." } },
  { icon: ScanText, title: { ar: "قراءة الفواتير والمستندات", en: "Invoice and document capture" }, text: { ar: "ارفع صورة أو PDF، راجع البيانات المستخرجة، ثم أنشئ مسودة القيد.", en: "Upload an image or PDF, review extracted data, then create the draft entry." } },
  { icon: BookOpen, title: { ar: "دليل حسابات احترافي", en: "Professional chart of accounts" }, text: { ar: "دليل جاهز قابل للتخصيص، بأكواد وأقسام القوائم بالعربي والإنجليزي.", en: "A customizable coded chart mapped to statements in Arabic and English." } },
  { icon: WalletCards, title: { ar: "العهد المؤقتة والدائمة", en: "Temporary and permanent custody" }, text: { ar: "صرف وتسوية وإقفال العهد المؤقتة، وإدارة حد العهدة الدائمة وتغذيتها بعد مراجعة المصروفات.", en: "Settle temporary custody and replenish permanent imprest balances after expense review." } },
  { icon: Landmark, title: { ar: "الصندوق والبنوك والمطابقة", en: "Treasury and reconciliation" }, text: { ar: "كل عملية تتحرك على حساب الصندوق أو البنك الصحيح مع مطابقة كشف البنك.", en: "Every transaction hits the right cash or bank account with statement reconciliation." } },
  { icon: Users, title: { ar: "ملف 360° للعملاء والموردين", en: "Customer and supplier 360°" }, text: { ar: "الرصيد، الفواتير، الأعمار، العمليات والتواصل عبر واتساب من مكان واحد.", en: "Balances, invoices, aging, operations, and WhatsApp contact in one profile." } },
  { icon: CircleDollarSign, title: { ar: "التحصيلات والسيولة", en: "Collections and cashflow" }, text: { ar: "خطة 7 و30 يومًا، تنبيه العجز، وأولويات التحصيل والسداد.", en: "7- and 30-day plans, shortfall alerts, and collection/payment priorities." } },
  { icon: FileSpreadsheet, title: { ar: "تحليل ملفات Excel الكبيرة", en: "Large Excel workbook analysis" }, text: { ar: "فهم صف العناوين والأرقام العربية، درجة لجودة القراءة، خريطة لكل عمود، إجماليات دقيقة ورسوم واضحة حتى مع مئات الآلاف من الصفوف.", en: "Header detection, localized numbers, read-quality scoring, column mapping, exact totals, and clear charts across very large workbooks." } },
  { icon: ReceiptText, title: { ar: "تحليل القيمة المضافة والفترات", en: "VAT analysis and periods" }, text: { ar: "مدخلات ومخرجات وصافي مستحق أو دائن لكل شهر أو ربع سنة، مع فصل القيود غير المعتمدة.", en: "Input, output, payable or credit VAT by month or quarter, with pending entries separated." } },
  { icon: Workflow, title: { ar: "بطاقة العملية المحاسبية", en: "Accounting operation dossier" }, text: { ar: "قصة العملية كاملة: المستند والقيد والأثر والاعتماد والترحيل في ملف واحد.", en: "The full story: document, entry, impact, approval, and posting in one dossier." } },
  { icon: FileBarChart, title: { ar: "قوائم وتقارير تلقائية", en: "Automatic statements and reports" }, text: { ar: "اليومية والأستاذ وميزان المراجعة والدخل والميزانية من القيود المرحلة.", en: "Journal, ledger, trial balance, income statement, and balance sheet from posted entries." } },
  { icon: Sparkles, title: { ar: "الإقفال الذكي", en: "Smart close" }, text: { ar: "يقيس جاهزية الإقفال ويجمع القيود الناقصة والحسابات غير المراجعة والمخاطر.", en: "Measures close readiness and surfaces missing entries, unchecked accounts, and risks." } },
  { icon: BarChart3, title: { ar: "محاكي القرارات المالية", en: "Financial decision simulator" }, text: { ar: "قارن النقدي والآجل قبل التنفيذ وشاهد أثر القرار على السيولة والربح والضريبة.", en: "Compare cash and credit before execution across liquidity, profit, and tax." } },
  { icon: ShieldCheck, title: { ar: "مراجعة واعتماد وأثر واضح", en: "Review, approval, and clear impact" }, text: { ar: "كل قيد يشرح ما زاد وما نقص وأين ظهر في القوائم قبل الترحيل.", en: "Every entry explains what changed and where it appears before posting." } },
];

const latestFeatures = [
  { icon: Building2, title: { ar: "مركز تشغيل مكاتب المحاسبة", en: "Accounting firm command center" }, text: { ar: "إدارة العملاء والمستندات والمهام والموظفين ومراجعة القيود والتدريب والتقارير من مساحة واحدة مصممة لشغل المكتب الحقيقي.", en: "Run clients, documents, tasks, staff, entry review, training, and reporting from one purpose-built workspace." } },
  { icon: Store, title: { ar: "مركز قيادة فوري والمحافظ", en: "Fawry and wallet command center" }, text: { ar: "وردية وخزنة ومحافظ مستقلة، ربحية كل شركة، دوران وسيولة، تحويل داخلي، تنبيهات تكرار وفروق، و22 تقريرًا تشغيليًا بدون اشتراك خارجي.", en: "Independent shifts, cash and wallets, provider profitability, liquidity, internal transfers, controls, and 22 operational reports." } },
  { icon: Printer, title: { ar: "تقارير نقاط الخدمات القابلة للطباعة", en: "Printable service point reports" }, text: { ar: "تقرير يومي أو أسبوعي أو شهري يجمع كل العمليات وحركة الخزنة والمحافظ والعمولات والقيود المحاسبية المرتبطة.", en: "Daily, weekly, or monthly reports covering operations, balances, commissions, and linked journal entries." } },
  { icon: BookOpen, title: { ar: "مرجع طبيعة الحسابات الموسع", en: "Expanded account nature guide" }, text: { ar: "أكثر من 180 حسابًا مصنفًا، مع طبيعة الحساب والزيادة والنقص ومكانه في القوائم ومثال القيد والدورة المستندية.", en: "More than 180 categorized accounts with movement, statements, journal examples, and document cycle." } },
  { icon: ScanText, title: { ar: "قراءة فواتير OCR وترحيل الدورة كاملة", en: "OCR invoice capture and full posting" }, text: { ar: "قراءة PDF والصور، استخراج البنود والمجاميع، منع الأرقام الوهمية، ثم ترحيل المستند والمورد والقيد والأستاذ والقوائم.", en: "Read PDFs and images, validate lines and totals, then post the document, supplier, entry, ledger, and statements." } },
];

const allFeatures = [...latestFeatures, ...features];

const scenes = [
  { icon: ScanText, kicker: { ar: "01 — المستند يدخل", en: "01 — Document in" }, title: { ar: "ارفع الفاتورة، وفينورا يقرأها", en: "Upload the invoice. FINORA reads it." }, text: { ar: "المورد والتاريخ والصافي والضريبة والإجمالي تتحول إلى بيانات قابلة للمراجعة.", en: "Supplier, date, net, VAT, and total become reviewable structured data." }, visual: "invoice" },
  { icon: Workflow, kicker: { ar: "02 — القيد يتكون", en: "02 — Entry generated" }, title: { ar: "اقتراح القيد وشرح تأثيره", en: "Suggested entry with full impact" }, text: { ar: "يعرض المدين والدائن، وحركة الصندوق أو البنك، وتأثير الميزانية والدخل.", en: "See debit, credit, treasury movement, and balance sheet and income impact." }, visual: "entry" },
  { icon: CircleDollarSign, kicker: { ar: "03 — السيولة تتحرك", en: "03 — Cash moves" }, title: { ar: "تابع ما لك وما عليك قبل الموعد", en: "Know what is due before it is late" }, text: { ar: "تحصيلات ومدفوعات وأولويات وتنبيه مبكر لأي عجز متوقع.", en: "Collections, payments, priorities, and early warning for expected shortfalls." }, visual: "cash" },
  { icon: BarChart3, kicker: { ar: "04 — القرار يُختبر", en: "04 — Decision tested" }, title: { ar: "جرّب القرار قبل ما تدفع", en: "Test the decision before paying" }, text: { ar: "قارن النقدي والآجل والمختلط خلال 7 و30 و90 يومًا.", en: "Compare cash, credit, and split options across 7, 30, and 90 days." }, visual: "decision" },
  { icon: FileBarChart, kicker: { ar: "05 — الشهر يُقفل", en: "05 — Month closed" }, title: { ar: "من القيد إلى القوائم والإقفال", en: "From entry to statements and close" }, text: { ar: "تتحدث اليومية والأستاذ والقوائم تلقائيًا، ويظهر ما يمنع الإقفال.", en: "Journal, ledger, and statements update automatically while close blockers surface." }, visual: "close" },
];

export function LandingPage({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  return <div className="landing-page">
    <section className="landing-hero">
      <div className="landing-orb landing-orb-one"/><div className="landing-orb landing-orb-two"/>
      <div className="container landing-hero-grid">
        <div className="landing-hero-copy">
          <span className="landing-eyebrow"><Sparkles size={16}/>{ar ? "من أول مستند لآخر قائمة مالية" : "From the first document to the final statements"}</span>
          <h1>{ar ? "نظام تشغيل يوم المحاسب، مش مجرد مولّد قيود" : "The accountant’s operating system — not just an entry generator"}</h1>
          <p>{ar ? "فينورا يجمع المستندات والقيود والعهد والعملاء والموردين والبنوك والتقارير والإقفال في دورة واحدة واضحة، علشان المحاسب ينجز أسرع والإدارة تشوف الصورة كاملة." : "FINORA brings documents, entries, custody, parties, banking, reporting, and closing into one clear cycle so accountants finish faster and management sees the full picture."}</p>
          <div className="actions landing-hero-actions"><Link className="btn btn-primary" href={`/${locale}/dashboard`}>{ar ? "افتح لوحة العمل" : "Open workspace"}{ar ? <ArrowLeft size={18}/> : <ArrowRight size={18}/>}</Link><a className="btn" href="#product-tour"><Play size={17}/>{ar ? "شاهد العرض الدعائي" : "Watch product tour"}</a></div>
          <div className="landing-trust"><span><CheckCircle2 size={16}/>{ar ? "عربي وإنجليزي" : "Arabic & English"}</span><span><CheckCircle2 size={16}/>{ar ? "بدون API مدفوع" : "No paid API required"}</span><span><CheckCircle2 size={16}/>{ar ? "جاهز للمكاتب والشركات" : "Built for firms and companies"}</span></div>
        </div>
        <HeroDashboard locale={locale}/>
      </div>
    </section>

    <section className="landing-proof"><div className="container"><p>{ar ? "مصمم ليلائم طريقة شغل المحاسب الحقيقية" : "Designed around the way accountants actually work"}</p><div className="landing-audiences"><span><Building2/>{ar ? "الشركات" : "Companies"}</span><span><Users/>{ar ? "مكاتب المحاسبة" : "Accounting firms"}</span><span><Landmark/>{ar ? "الإدارات المالية" : "Finance teams"}</span><span><ReceiptText/>{ar ? "المنشآت الصغيرة والمتوسطة" : "SMEs"}</span></div></div></section>

    <section className="section landing-tour-section" id="product-tour"><div className="container"><SectionTitle locale={locale} eyebrow={{ ar: "جولة داخل فينورا", en: "Inside FINORA" }} title={{ ar: "شاهد الدورة المحاسبية وهي تتحرك أمامك", en: "Watch the accounting cycle move in real time" }} text={{ ar: "عرض دعائي تفاعلي يشرح كيف تتحول العملية اليومية من مستند خام إلى معلومة مالية جاهزة للقرار.", en: "An interactive product tour showing how daily work becomes decision-ready financial information." }}/><ProductTour locale={locale}/></div></section>

    <section className="section" id="workflow"><div className="container"><SectionTitle locale={locale} eyebrow={{ ar: "دورة واحدة مترابطة", en: "One connected cycle" }} title={{ ar: "كل خطوة تسلّم الخطوة اللي بعدها تلقائيًا", en: "Every step hands off to the next automatically" }} text={{ ar: "بدل إعادة كتابة نفس البيانات في أكثر من شاشة، العملية تكمل رحلتها داخل النظام.", en: "Stop re-entering the same data across screens; each transaction continues through the system." }}/><div className="landing-cycle">{[
      ["01", { ar: "مستند", en: "Document" }, { ar: "فاتورة أو سند أو عهدة", en: "Invoice, voucher, or custody" }],
      ["02", { ar: "مراجعة", en: "Review" }, { ar: "بيانات وضريبة وطرف", en: "Data, tax, and party" }],
      ["03", { ar: "قيد", en: "Entry" }, { ar: "مدين ودائن متوازن", en: "Balanced debit and credit" }],
      ["04", { ar: "اعتماد", en: "Approval" }, { ar: "صلاحيات وسجل حركة", en: "Workflow and audit trail" }],
      ["05", { ar: "ترحيل", en: "Posting" }, { ar: "أستاذ وأرصدة", en: "Ledger and balances" }],
      ["06", { ar: "قوائم وإقفال", en: "Statements & close" }, { ar: "نتيجة جاهزة للإدارة", en: "Management-ready result" }],
    ].map(([number, title, text], index) => <div className="landing-cycle-step" key={String(number)}><span>{String(number)}</span><div><b>{t(title as Copy, locale)}</b><small>{t(text as Copy, locale)}</small></div>{index < 5 && <i>{ar ? "←" : "→"}</i>}</div>)}</div></div></section>

    <section className="section landing-showcase-section"><div className="container landing-showcase-grid"><ShowcaseCopy locale={locale} eyebrow={{ ar: "المستندات والقيود", en: "Documents and entries" }} title={{ ar: "الفاتورة تدخل مرة واحدة… وتكمل رحلتها", en: "Enter the invoice once — it completes the journey" }} text={{ ar: "فينورا يقرأ الفاتورة، يعرض البيانات المستخرجة، يقترح القيد، ثم يترك للمحاسب قرار المراجعة والاعتماد. كل خطوة محفوظة داخل بطاقة العملية.", en: "FINORA extracts invoice data, suggests the entry, and leaves review and approval to the accountant. Every step stays inside the operation dossier." }} points={ar ? ["قراءة صور وPDF", "اقتراح المورد والحساب", "شرح أثر القيد قبل الترحيل", "سجل مراجعة واعتماد"] : ["Image and PDF capture", "Suggested party and account", "Impact explained before posting", "Review and approval history"]} href={`/${locale}/invoice-capture`} link={ar ? "جرّب قراءة فاتورة" : "Try invoice capture"}/><InvoiceMock locale={locale}/></div></section>

    <section className="section"><div className="container landing-showcase-grid reverse"><DecisionMock locale={locale}/><ShowcaseCopy locale={locale} eyebrow={{ ar: "ميزة تجارية مختلفة", en: "A differentiated capability" }} title={{ ar: "اسأل: لو نفذت القرار ده، هيحصل إيه؟", en: "Ask: what happens if we make this decision?" }} text={{ ar: "المحاكي يقارن بدائل الدفع أو التحصيل على الرصيد الفعلي والاستحقاقات الحالية، ثم يعرض أثر 7 و30 و90 يومًا ويقترح البديل الأكثر أمانًا.", en: "The simulator compares payment or collection options against real balances and due items, then projects 7, 30, and 90 days and recommends the safer option." }} points={ar ? ["نقدي مقابل آجل", "حد أمان للسيولة", "أثر الربح والضريبة والميزانية", "تحويل القرار لمسودة قيد"] : ["Cash versus credit", "Minimum cash reserve", "Profit, tax, and balance-sheet impact", "Turn the decision into a draft entry"]} href={`/${locale}/scenario-simulator`} link={ar ? "افتح محاكي القرارات" : "Open decision simulator"}/></div></section>

    <section className="section landing-showcase-section"><div className="container landing-showcase-grid"><ShowcaseCopy locale={locale} eyebrow={{ ar: "الإقفال والتقارير", en: "Close and reporting" }} title={{ ar: "اعرف قبل نهاية الشهر: هل أنت جاهز للإقفال؟", en: "Know before month-end: are you ready to close?" }} text={{ ar: "مركز الإقفال يجمع القيود الناقصة والحسابات غير المراجعة ومشكلات البنك والمستندات المفتوحة، بينما القوائم المالية تتحدث من القيود المرحلة.", en: "The close center brings together missing entries, unchecked accounts, bank issues, and open documents while statements update from posted entries." }} points={ar ? ["نسبة جاهزية واضحة", "مخاطر مرتبة حسب الأولوية", "ميزان مراجعة وقائمة دخل وميزانية", "تتبع مصدر كل رقم"] : ["Clear readiness score", "Prioritized close risks", "Trial balance, income statement, balance sheet", "Trace every number to its source"]} href={`/${locale}/close`} link={ar ? "افتح مركز الإقفال" : "Open smart close"}/><CloseMock locale={locale}/></div></section>

    <section className="section landing-showcase-section"><div className="container landing-showcase-grid"><ShowcaseCopy locale={locale} eyebrow={{ ar: "منتج مستقل للمحلات", en: "A retail product of its own" }} title={{ ar: "شغّل فوري والمحافظ واعرف الربح الحقيقي لكل وردية", en: "Run Fawry and wallets with real shift profit" }} text={{ ar: "افتح الوردية برصيد الخزنة وكل خدمة، سجل التحويل والسحب والشحن ودفع الفواتير، ثم طابق الموجود فعليًا مع المتوقع. كل عملية تنشئ قيدها وتدخل التقرير اليومي والأسبوعي والشهري.", en: "Open with actual cash and provider balances, record every service, reconcile the shift, and post every operation to accounting." }} points={ar ? ["فوري و5 محافظ وخدمات مستقلة", "عمولة العميل وتكلفة مقدم الخدمة", "إقفال وعجز أو زيادة تلقائية", "طباعة العمليات والقيود في تقرير واحد"] : ["Fawry and five provider wallets", "Customer fee and provider cost", "Automatic close and variance", "Operations and entries in one printable report"]} href={`/${locale}/service-point`} link={ar ? "افتح نظام نقاط الخدمات" : "Open service point"}/><ServicePointMock locale={locale}/></div></section>

    <section className="section landing-office-section"><div className="container landing-showcase-grid reverse"><OfficeMock locale={locale}/><ShowcaseCopy locale={locale} eyebrow={{ ar: "نظام تشغيل لمكتب المحاسبة", en: "Accounting firm operating system" }} title={{ ar: "كل عميل ومهمة ومستند ومراجعة… تحت سيطرة المكتب", en: "Every client, task, document, and review — under control" }} text={{ ar: "واجهة مستقلة لمدير المكتب تجمع أحمال الفريق، المستندات الناقصة، القيود الحرجة، المواعيد والتدريب في لوحة واحدة. تعرف أين يتعطل العمل قبل أن يشتكي العميل أو يفوت الموعد.", en: "A dedicated command center for workload, missing documents, risky entries, deadlines, and team training — before work slips or clients complain." }} points={ar ? ["ملف شهري واضح لكل عميل", "مهام وجدول وKanban للفريق", "مراجع قيود بدرجات خطورة", "تقارير أداء وتشغيل قابلة للطباعة"] : ["A monthly file for every client", "Table and Kanban task views", "Risk-based entry review", "Printable operations and performance reports"]} href={`/${locale}/accounting-office`} link={ar ? "ادخل مركز المكتب التجريبي" : "Open the office demo"}/></div></section>

    <section className="section" id="features"><div className="container"><SectionTitle locale={locale} eyebrow={{ ar: "كل ما تم بناؤه", en: "Everything built so far" }} title={{ ar: "منظومة يومية كاملة للمحاسب والمحلات", en: "A complete daily system for accountants and stores" }} text={{ ar: "كل ميزة مرتبطة بالدورة المحاسبية، وليست شاشة منفصلة بلا أثر.", en: "Every feature connects to the accounting cycle instead of living as an isolated screen." }}/><div className="landing-feature-grid">{allFeatures.map((feature, index) => { const Icon = feature.icon; return <article className="landing-feature" key={feature.title.en}><span className="landing-feature-number">{String(index + 1).padStart(2, "0")}</span><Icon/><h3>{t(feature.title, locale)}</h3><p>{t(feature.text, locale)}</p></article>; })}</div></div></section>

    <section className="section landing-segments"><div className="container"><SectionTitle locale={locale} eyebrow={{ ar: "قيمة واضحة لكل فريق", en: "Clear value for every team" }} title={{ ar: "نفس الحقيقة المالية… برؤية تناسب كل شخص", en: "One financial truth — a view for every role" }}/><div className="grid three"><Segment icon={Users} locale={locale} title={{ ar: "للمحاسب", en: "For accountants" }} points={ar ? ["إدخال أقل ومراجعة أسرع", "مهام اليوم واضحة", "شرح كامل لكل قيد"] : ["Less entry, faster review", "A clear daily queue", "Full explanation per entry"]}/><Segment icon={Building2} locale={locale} title={{ ar: "لصاحب الشركة", en: "For business owners" }} points={ar ? ["سيولة ومخاطر لحظية", "قرارات قبل التنفيذ", "تقارير مفهومة"] : ["Live liquidity and risk", "Decisions tested first", "Reports that make sense"]}/><Segment icon={Landmark} locale={locale} title={{ ar: "لمكتب المحاسبة", en: "For accounting firms" }} points={ar ? ["إدارة أكثر من شركة", "ملف موحد لكل عملية", "خدمة احترافية قابلة للتوسع"] : ["Manage multiple companies", "One dossier per operation", "A scalable professional service"]}/></div></div></section>

    <section className="section"><div className="container landing-cta"><div><span className="landing-eyebrow"><ShieldCheck size={16}/>{ar ? "ابدأ من بيانات تجريبية" : "Start with demo data"}</span><h2>{ar ? "خلّي يوم المحاسب أقصر… والمعلومة أوضح" : "Make the accountant’s day shorter — and the numbers clearer"}</h2><p>{ar ? "ادخل لوحة العمل، جرّب إنشاء عملية، وشاهد كيف تنتقل من المستند إلى القيد والتقرير." : "Open the workspace, create a transaction, and see it move from document to entry to report."}</p></div><div className="actions"><Link className="btn btn-primary" href={`/${locale}/dashboard`}>{ar ? "ابدأ الجولة داخل النظام" : "Start inside the system"}{ar ? <ArrowLeft/> : <ArrowRight/>}</Link><Link className="btn" href={`/${locale}/generator`}>{ar ? "أنشئ أول قيد" : "Create first entry"}</Link></div></div></section>

    <section className="section landing-faq"><div className="container"><SectionTitle locale={locale} eyebrow={{ ar: "أسئلة سريعة", en: "Quick answers" }} title={{ ar: "قبل ما تبدأ", en: "Before you start" }}/><div className="grid two">{[
      [{ ar: "هل يحتاج API مدفوع؟", en: "Does it require a paid API?" }, { ar: "الوظائف الحالية الأساسية تعمل محليًا داخل المتصفح ولا تتطلب API مدفوعًا. بعض التكاملات المستقبلية الخارجية قد يكون لها تسعير مستقل.", en: "Core current features run locally in the browser without a paid API. Future external integrations may have separate pricing." }],
      [{ ar: "هل يدعم العربي والإنجليزي؟", en: "Does it support Arabic and English?" }, { ar: "نعم، الواجهة وأسماء الحسابات والقيود والمصطلحات المحاسبية متاحة باللغتين.", en: "Yes. The interface, accounts, entries, and accounting terminology support both languages." }],
      [{ ar: "هل القيود تؤثر في التقارير؟", en: "Do entries update reports?" }, { ar: "نعم، بعد المراجعة والاعتماد والترحيل تظهر الحركة في اليومية والأستاذ وميزان المراجعة والقوائم.", en: "Yes. After review, approval, and posting, movements appear in the journal, ledger, trial balance, and statements." }],
      [{ ar: "هل يناسب مكتب محاسبة؟", en: "Does it fit an accounting firm?" }, { ar: "تم تصميم مساحات عمل للشركات وسجل عمليات ومهام ومراجعة تساعد المكتب على خدمة أكثر من عميل بنظام واحد.", en: "Company workspaces, operation dossiers, tasks, and review workflows help firms serve multiple clients in one system." }],
    ].map(([question, answer]) => <details className="landing-faq-item" key={t(question as Copy, locale)}><summary>{t(question as Copy, locale)}</summary><p>{t(answer as Copy, locale)}</p></details>)}</div></div></section>
  </div>;
}

function SectionTitle({ locale, eyebrow, title, text }: { locale: Locale; eyebrow: Copy; title: Copy; text?: Copy }) { return <div className="landing-section-title"><span>{t(eyebrow, locale)}</span><h2>{t(title, locale)}</h2>{text && <p>{t(text, locale)}</p>}</div>; }

function HeroDashboard({ locale }: { locale: Locale }) { const ar = locale === "ar"; return <div className="landing-hero-visual"><div className="browser-top"><i/><i/><i/><span>FINORA / {ar ? "لوحة العمل" : "Dashboard"}</span></div><div className="mock-dashboard"><div className="mock-kpis"><div><span>{ar ? "جاهزية الإقفال" : "Close readiness"}</span><b>86%</b><small className="positive">+12%</small></div><div><span>{ar ? "السيولة المتاحة" : "Available cash"}</span><b>248,500</b><small>EGP</small></div><div><span>{ar ? "مهام اليوم" : "Today’s tasks"}</span><b>7</b><small className="negative">2 {ar ? "عاجلة" : "urgent"}</small></div></div><div className="mock-dashboard-body"><div className="mock-chart"><div className="mock-chart-title"><b>{ar ? "حركة السيولة — 30 يوم" : "Cashflow — 30 days"}</b><span className="badge">{ar ? "محدث الآن" : "Live"}</span></div><svg viewBox="0 0 480 190" role="img" aria-label={ar ? "رسم حركة السيولة" : "Cashflow chart"}><defs><linearGradient id="heroArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity=".28"/><stop offset="1" stopColor="var(--primary)" stopOpacity="0"/></linearGradient></defs><path d="M10 154 C70 140 78 95 132 112 S220 158 270 92 S372 74 470 22 L470 180 L10 180Z" fill="url(#heroArea)"/><path d="M10 154 C70 140 78 95 132 112 S220 158 270 92 S372 74 470 22" fill="none" stroke="var(--primary)" strokeWidth="5" strokeLinecap="round"/><circle cx="470" cy="22" r="7" fill="var(--primary)"/></svg><div className="mock-chart-axis"><span>{ar ? "اليوم" : "Today"}</span><span>+7</span><span>+14</span><span>+21</span><span>+30</span></div></div><div className="mock-tasks"><b>{ar ? "الأولوية الآن" : "Priority now"}</b>{[["فاتورة شراء #284","14,250"],[ar?"مطابقة بنك CIB":"CIB reconciliation","3"],[ar?"تسوية عهدة أحمد":"Ahmed custody","1,200"]].map(([name,value],i)=><div key={String(name)}><i className={i===0?"urgent":""}/><span>{name}<small>{i===0?(ar?"تحتاج مراجعة":"Needs review"):(ar?"مهمة مفتوحة":"Open task")}</small></span><b>{value}</b></div>)}</div></div></div><div className="landing-float-card float-one"><CheckCircle2/><span>{ar ? "تم ترحيل القيد" : "Entry posted"}<b>JE-00428</b></span></div><div className="landing-float-card float-two"><Sparkles/><span>{ar ? "قرار أكثر أمانًا" : "Safer option"}<b>{ar ? "50% نقدي / 50% آجل" : "50% cash / 50% credit"}</b></span></div></div>; }

function ProductTour({ locale }: { locale: Locale }) { const ar = locale === "ar", [active, setActive] = useState(0), [playing, setPlaying] = useState(true); useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setActive((value) => (value + 1) % scenes.length), 4500); return () => window.clearInterval(timer); }, [playing]); const scene = scenes[active], Icon = scene.icon; return <div className="product-tour"><div className="product-tour-screen"><div className="product-tour-copy"><span>{t(scene.kicker, locale)}</span><Icon/><h3>{t(scene.title, locale)}</h3><p>{t(scene.text, locale)}</p></div><TourVisual type={scene.visual} locale={locale}/></div><div className="product-tour-controls"><button className="btn" onClick={() => setPlaying(!playing)} aria-label={playing ? (ar ? "إيقاف العرض" : "Pause tour") : (ar ? "تشغيل العرض" : "Play tour")}>{playing ? <Pause size={17}/> : <Play size={17}/>} {playing ? (ar ? "إيقاف" : "Pause") : (ar ? "تشغيل" : "Play")}</button><div className="product-tour-steps">{scenes.map((item,index)=><button key={item.visual} className={index===active?"active":""} onClick={()=>setActive(index)} aria-label={t(item.title,locale)}><i/><span>{String(index+1).padStart(2,"0")}</span></button>)}</div><span className="muted">{active+1} / {scenes.length}</span></div></div>; }

function TourVisual({ type, locale }: { type: string; locale: Locale }) { const ar = locale === "ar"; if(type==="invoice") return <div className="tour-visual invoice-tour"><div className="paper"><ReceiptText/><b>Invoice #INV-2026-184</b><span>Delta Office Supplies</span><hr/><span>Net <b>10,000</b></span><span>VAT 14% <b>1,400</b></span><span>Total <b>11,400 EGP</b></span></div><div className="scan-line"/><span className="scan-status"><ScanText/>{ar?"جاري استخراج البيانات":"Extracting data"}</span></div>; if(type==="entry") return <div className="tour-visual entry-tour"><div className="entry-head"><span>{ar?"قيد مقترح":"Suggested entry"}</span><b className="badge"><CheckCircle2/>{ar?"متوازن":"Balanced"}</b></div><div><span>{ar?"المخزون · Inventory":"Inventory"}</span><b>{ar?"مدين · Debit":"Debit"} 10,000</b></div><div><span>{ar?"ضريبة مدخلات · Input VAT":"Input VAT"}</span><b>{ar?"مدين · Debit":"Debit"} 1,400</b></div><div><span>{ar?"الموردون · Payables":"Payables"}</span><b>{ar?"دائن · Credit":"Credit"} 11,400</b></div></div>; if(type==="cash") return <div className="tour-visual cash-tour"><div className="cash-bars">{[62,78,50,88,72,96].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div><div className="cash-alert"><ShieldCheck/><span>{ar?"الرصيد المتوقع بعد 30 يومًا":"Projected cash after 30 days"}<b>186,750 EGP</b></span></div></div>; if(type==="decision") return <div className="tour-visual decision-tour">{[[ar?"نقدي الآن":"Cash now","72"],[ar?"آجل 30 يومًا":"30-day credit","84"],[ar?"حل مختلط":"Split option","91"]].map(([label,score],index)=><div className={index===2?"winner":""} key={label}><span>{label}{index===2&&<small>{ar?"الأنسب":"Recommended"}</small>}</span><b>{score}/100</b><i><em style={{width:`${score}%`}}/></i></div>)}</div>; return <div className="tour-visual close-tour"><div className="close-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50"/><circle className="progress" cx="60" cy="60" r="50"/></svg><span><b>86%</b>{ar?"جاهز":"Ready"}</span></div><div className="close-list"><span><CheckCircle2/>{ar?"ميزان المراجعة متوازن":"Trial balance balanced"}</span><span><CheckCircle2/>{ar?"البنك مطابق":"Bank reconciled"}</span><span className="pending"><Activity/>{ar?"مستندان يحتاجان مراجعة":"2 documents need review"}</span></div></div>; }

function ShowcaseCopy({ locale, eyebrow, title, text, points, href, link }: { locale: Locale; eyebrow: Copy; title: Copy; text: Copy; points: string[]; href: string; link: string }) { const ar=locale==="ar"; return <div className="showcase-copy"><span>{t(eyebrow,locale)}</span><h2>{t(title,locale)}</h2><p>{t(text,locale)}</p><ul>{points.map(point=><li key={point}><CheckCircle2/>{point}</li>)}</ul><Link className="btn btn-primary" href={href}>{link}{ar?<ArrowLeft/>:<ArrowRight/>}</Link></div>; }

function InvoiceMock({ locale }: { locale: Locale }) { const ar=locale==="ar"; return <div className="showcase-window"><div className="showcase-window-top"><i/><i/><i/><span>{ar?"قراءة فاتورة":"Invoice capture"}</span></div><div className="invoice-mock"><div className="invoice-upload"><ScanText/><span>{ar?"تمت قراءة الفاتورة بنجاح":"Invoice read successfully"}</span><b>kareem-office.pdf</b></div><div className="grid two"><label>{ar?"المورد · Supplier":"Supplier"}<span>{ar?"كريم للأدوات المكتبية · Kareem Office":"Kareem Office"}</span></label><label>{ar?"رقم الفاتورة · Invoice no.":"Invoice no."}<span>INV-2048</span></label><label>{ar?"الإجمالي · Total":"Total"}<span>11,400 EGP</span></label><label>{ar?"الثقة · Confidence":"Confidence"}<span className="positive">96%</span></label></div><div className="invoice-entry-preview"><b>{ar?"القيد المقترح · Suggested entry":"Suggested entry"}</b><span><em>{ar?"مخزون · Inventory":"Inventory"}</em><strong>10,000</strong></span><span><em>{ar?"ضريبة مدخلات · Input VAT":"Input VAT"}</em><strong>1,400</strong></span><span><em>{ar?"الموردون · Payables":"Payables"}</em><strong>11,400</strong></span></div></div></div>; }

function DecisionMock({ locale }: { locale: Locale }) { const ar=locale==="ar"; return <div className="showcase-window"><div className="showcase-window-top"><i/><i/><i/><span>{ar?"محاكي القرارات":"Decision simulator"}</span></div><div className="decision-mock"><div className="decision-mock-head"><span>{ar?"شراء مخزون · Inventory purchase":"Inventory purchase"}<b>50,000 EGP</b></span><span>{ar?"حد الأمان · Safety reserve":"Safety reserve"}<b>20,000 EGP</b></span></div><div className="decision-options">{[[ar?"نقدي الآن · Cash now":"Cash now","68",false],[ar?"آجل 30 يومًا · 30-day credit":"30-day credit","78",false],[ar?"50% الآن / 50% آجل · Split":"50% now / 50% credit","91",true]].map(([name,score,winner])=><div className={winner?"winner":""} key={String(name)}>{winner&&<small><Sparkles/>{ar?"الأنسب":"Recommended"}</small>}<span>{name}</span><b>{score}/100</b><i><em style={{width:`${score}%`}}/></i></div>)}</div><svg className="decision-lines" viewBox="0 0 620 170"><path d="M20 45 C150 55 170 130 310 110 S500 60 600 82"/><path d="M20 92 C140 80 185 42 310 58 S500 120 600 104"/><path d="M20 120 C140 110 205 85 310 84 S490 75 600 70"/></svg><div className="decision-axis"><span>{ar?"الآن":"Now"}</span><span>7 {ar?"أيام":"days"}</span><span>30 {ar?"يومًا":"days"}</span><span>90 {ar?"يومًا":"days"}</span></div></div></div>; }

function CloseMock({ locale }: { locale: Locale }) { const ar=locale==="ar"; return <div className="showcase-window"><div className="showcase-window-top"><i/><i/><i/><span>{ar?"مركز الإقفال الذكي":"Smart close center"}</span></div><div className="close-mock"><div className="close-mock-score"><div className="close-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50"/><circle className="progress" cx="60" cy="60" r="50"/></svg><span><b>86%</b>{ar?"جاهزية":"Readiness"}</span></div><div><span>{ar?"إقفال يوليو 2026 · July close":"July 2026 close"}</span><h3>{ar?"متبقي 4 عناصر قبل الإقفال":"4 items remain before close"}</h3><p>{ar?"الوقت المتوقع: ساعتان و20 دقيقة":"Estimated time: 2h 20m"}</p></div></div><div className="close-checks">{[[ar?"ميزان المراجعة · Trial balance":"Trial balance","100%"],[ar?"مطابقة البنوك · Bank reconciliation":"Bank reconciliation","92%"],[ar?"مراجعة المستندات · Document review":"Document review","76%"],[ar?"القيود الدورية · Recurring entries":"Recurring entries","84%"]].map(([name,value])=><div key={name}><span>{name}</span><b>{value}</b><i><em style={{width:value}}/></i></div>)}</div><div className="close-warning"><Activity/><span>{ar?"أعلى أولوية: فاتورتان بدون اعتماد":"Top priority: 2 unapproved invoices"}</span><button>{ar?"فتح للمراجعة":"Open review"}</button></div></div></div>; }

function ServicePointMock({ locale }: { locale: Locale }) { const ar=locale==="ar"; return <div className="showcase-window" data-no-bilingual><div className="showcase-window-top"><i/><i/><i/><span>{ar?"وردية نقطة الخدمات":"Service point shift"}</span></div><div className="p-6"><div className="grid grid-cols-3 gap-3"><div className="rounded-xl bg-emerald-50 p-3"><small>{ar?"الخزنة":"Cash"}</small><b className="mt-2 block text-xl">18,450</b></div><div className="rounded-xl bg-blue-50 p-3"><small>{ar?"حجم العمليات":"Volume"}</small><b className="mt-2 block text-xl">42,000</b></div><div className="rounded-xl bg-amber-50 p-3"><small>{ar?"صافي الربح":"Net profit"}</small><b className="mt-2 block text-xl">386</b></div></div><div className="mt-5 grid gap-2">{[["فودافون كاش","12,800","+96"],["فوري","8,400","+74"],["أورنج كاش","6,250","+48"]].map(([name,balance,profit])=><div className="flex items-center justify-between rounded-xl border border-daftar-line p-3" key={name}><b>{name}</b><span>{balance} EGP</span><strong className="text-emerald-600">{profit}</strong></div>)}</div><div className="mt-5 flex items-center justify-between rounded-xl bg-daftar-primary p-4 text-white"><span><Printer className="inline me-2" size={18}/>{ar?"تقرير العمليات والقيود":"Operations & entries report"}</span><b>PDF</b></div></div></div>; }

function OfficeMock({ locale }: { locale: Locale }) { const ar=locale==="ar"; return <div className="showcase-window office-showcase-window" data-no-bilingual><div className="showcase-window-top"><i/><i/><i/><span>{ar?"مركز تشغيل المكتب":"Office command center"}</span></div><div className="grid grid-cols-[92px_1fr] bg-[#f7f9fc] text-[#12213a]"><aside className="grid content-start gap-2 bg-[#0d315c] p-3 text-white">{[LayoutDashboard,Users,Workflow,ShieldCheck,BarChart3].map((Icon,i)=><span className={`grid h-9 place-items-center rounded-lg ${i===0?"bg-white text-[#0d315c]":"bg-white/5 text-white/65"}`} key={i}><Icon size={16}/></span>)}</aside><div className="p-5"><div className="grid grid-cols-3 gap-2">{[["21",ar?"عميل":"Clients"],["28",ar?"مهمة":"Tasks"],["86%",ar?"إنجاز":"Complete"]].map(([value,label])=><div className="rounded-xl bg-white p-3 shadow-sm" key={label}><small className="text-slate-500">{label}</small><b className="mt-1 block text-xl">{value}</b></div>)}</div><div className="mt-4 grid grid-cols-[1.3fr_.7fr] gap-3"><div className="rounded-xl bg-white p-4 shadow-sm"><b className="text-xs">{ar?"أداء المكتب":"Office performance"}</b><div className="mt-4 flex h-24 items-end gap-2">{[48,72,60,88,76,94].map((height,i)=><i className="flex-1 rounded-t bg-[#1769aa]" style={{height:`${height}%`,opacity:.55+i*.07}} key={i}/>)}</div></div><div className="grid gap-2">{[["3",ar?"قيود للمراجعة":"Entries"],["17",ar?"مستند ناقص":"Missing docs"],["4",ar?"مهام متأخرة":"Overdue"]].map(([value,label],i)=><div className={`rounded-xl p-3 ${i===2?"bg-red-50 text-red-800":"bg-white"}`} key={label}><b>{value}</b><small className="ms-2">{label}</small></div>)}</div></div><div className="mt-4 flex items-center justify-between rounded-xl bg-emerald-50 p-3 text-emerald-900"><span><CheckCircle2 className="me-2 inline" size={16}/>{ar?"المكتب جاهز لمواعيد اليوم":"Today’s deadlines are under control"}</span><b>09:42</b></div></div></div></div>; }

function Segment({ icon: Icon, locale, title, points }: { icon: typeof Users; locale: Locale; title: Copy; points: string[] }) { return <article className="segment-card"><Icon/><h3>{t(title,locale)}</h3><ul>{points.map(point=><li key={point}><CheckCircle2/>{point}</li>)}</ul></article>; }
