"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, BadgeCheck, Banknote, BookOpenText, Check, CheckCircle2, CircleMinus, Clock3, ExternalLink, File, FileSearch, Flag, FolderOpen, Lightbulb, Link2, MessageSquareText, NotebookPen, ReceiptText, RotateCcw, Search, ShieldCheck, StickyNote, Target, Trophy, Unlink, X } from "lucide-react";
import { detectiveCases } from "@/data/detective/cases";
import { buildDetectiveTrainingEntries, calculateDetectiveScore, calculateEvidenceAccuracy, nextDetectiveHint, resolveInvestigation } from "@/lib/detective/engine";
import { loadDetectiveProgress, recordDetectiveResult, saveDetectiveDraft } from "@/lib/storage/detective";
import type { DetectiveCase, DetectiveEvidence, DetectivePanel, Locale } from "@/types";

const money = (value?: number) => value === undefined ? "" : `${value.toLocaleString("en-US")} EGP`;
const panelLabels: Record<DetectivePanel, [string, string]> = { brief: ["ملخص القضية", "Case brief"], documents: ["المستندات", "Documents"], bank: ["كشف البنك", "Bank statement"], entries: ["القيود", "Book entries"], parties: ["العملاء / الموردون", "Customers / Suppliers"], evidence: ["الأدلة", "Evidence"], notes: ["ملاحظاتي", "My notes"], conclusion: ["استنتاجي", "Conclusion"] };
const typeLabels: Record<DetectiveEvidence["type"], [string, string]> = { "bank-transaction": ["حركة بنكية", "Bank transaction"], "journal-entry": ["قيد يومية", "Journal entry"], invoice: ["فاتورة", "Invoice"], receipt: ["إيصال", "Receipt"], "customer-message": ["رسالة عميل", "Customer message"], "supplier-message": ["رسالة مورد", "Supplier message"], "cash-movement": ["حركة نقدية", "Cash movement"], "account-balance": ["رصيد حساب", "Account balance"], document: ["مستند", "Document"], "excel-row": ["صف Excel", "Excel row"], "internal-note": ["ملاحظة داخلية", "Internal note"], "asset-register": ["سجل أصول", "Asset register"], "ledger-movement": ["حركة أستاذ", "Ledger movement"] };
const skillLabels: Record<string, [string, string]> = { "bank-reconciliation": ["المطابقة البنكية", "Bank Reconciliation"], "customer-accounts": ["حسابات العملاء", "Customer Accounts"], "journal-logic": ["منطق القيود", "Journal Logic"], "account-classification": ["تصنيف الحسابات", "Account Classification"], "financial-statement-impact": ["أثر القوائم المالية", "Financial Statement Impact"], "error-detection": ["اكتشاف الأخطاء", "Error Detection"], "supplier-accounts": ["حسابات الموردين", "Supplier Accounts"], "ledger-analysis": ["تحليل الأستاذ", "Ledger Analysis"] };

export function DetectiveWorkspace({ caseDefinition, locale }: { caseDefinition: DetectiveCase; locale: Locale }) {
  const ar = locale === "ar";
  const [activePanel, setActivePanel] = useState<DetectivePanel>("brief"), [opened, setOpened] = useState<string[]>([]), [important, setImportant] = useState<string[]>([]), [excluded, setExcluded] = useState<string[]>([]), [selectedEvidence, setSelectedEvidence] = useState<string[]>([]), [links, setLinks] = useState<[string, string][]>([]), [linkStart, setLinkStart] = useState<string>(), [notes, setNotes] = useState<string[]>([]), [customNote, setCustomNote] = useState(""), [conclusion, setConclusion] = useState(""), [hintsUsed, setHintsUsed] = useState(0), [attempts, setAttempts] = useState(0), [feedback, setFeedback] = useState<{ ok: boolean; text: string }>(), [result, setResult] = useState<{ score: number; accuracy: number; elapsed: number; relevant: number }>(), [hydrated, setHydrated] = useState(false);
  const startedAt = useRef(0);
  const evidence = caseDefinition.evidence.filter((item) => item.panel === activePanel);
  const explained = useMemo(() => selectedEvidence.reduce((sum, id) => sum + (caseDefinition.evidence.find((item) => item.id === id)?.amount || 0), 0), [caseDefinition, selectedEvidence]);

  useEffect(() => { const saved = loadDetectiveProgress().records[caseDefinition.id]; setOpened(saved?.openedEvidence || []); setImportant(saved?.importantEvidence || []); setExcluded(saved?.excludedEvidence || []); setLinks(saved?.evidenceLinks || []); setNotes(saved?.notes || []); setHintsUsed(saved?.hintsUsed || 0); startedAt.current = Date.now(); setHydrated(true); }, [caseDefinition.id]);
  useEffect(() => { if (hydrated) saveDetectiveDraft(caseDefinition.id, { openedEvidence: opened, importantEvidence: important, excludedEvidence: excluded, evidenceLinks: links, notes, hintsUsed }); }, [caseDefinition.id, opened, important, excluded, links, notes, hintsUsed, hydrated]);
  const toggle = (id: string, setter: React.Dispatch<React.SetStateAction<string[]>>) => setter((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const openEvidence = (id: string) => setOpened((current) => current.includes(id) ? current : [...current, id]);
  const connect = (id: string) => { if (!linkStart) return setLinkStart(id); if (linkStart === id) return setLinkStart(undefined); const pair: [string, string] = [linkStart, id]; setLinks((current) => current.some(([a, b]) => (a === pair[0] && b === pair[1]) || (a === pair[1] && b === pair[0])) ? current : [...current, pair]); setLinkStart(undefined); };
  const addNote = (text: string) => { const clean = text.trim(); if (clean && !notes.includes(clean)) setNotes((current) => [...current, clean]); setCustomNote(""); };
  const useHint = () => { if (hintsUsed < 3) setHintsUsed((value) => value + 1); };
  const confirm = () => {
    if (!conclusion || !selectedEvidence.length) return;
    const nextAttempts = attempts + 1, resolution = resolveInvestigation(caseDefinition, selectedEvidence, conclusion); setAttempts(nextAttempts);
    if (!resolution.solved) {
      const selected = caseDefinition.conclusions.find((item) => item.id === conclusion);
      setFeedback({ ok: false, text: resolution.conclusionCorrect ? (ar ? "الاستنتاج قريب، لكن راجع الأدلة التي اخترتها واربطها بالحركة." : "The conclusion is close, but review the selected evidence and connect it to the movement.") : (ar ? selected?.feedbackAr || "راجع الأدلة المرتبطة بالحركة." : selected?.feedbackEn || "Review the evidence linked to the movement.") });
      if (hintsUsed === 0) setHintsUsed(1); return;
    }
    const elapsed = Math.max(1, Math.round((Date.now() - (startedAt.current || Date.now())) / 1000));
    const score = calculateDetectiveScore({ caseDefinition, selectedEvidence, openedEvidence: opened, conclusionId: conclusion, hintsUsed, attempts: nextAttempts, elapsedSeconds: elapsed });
    const accuracy = calculateEvidenceAccuracy(caseDefinition, selectedEvidence), relevant = caseDefinition.correctEvidence.filter((id) => selectedEvidence.includes(id)).length;
    recordDetectiveResult({ caseId: caseDefinition.id, score, accuracy, relevantEvidenceFound: relevant, hintsUsed, attempts: nextAttempts, elapsedSeconds: elapsed, completedAt: new Date().toISOString() }, caseDefinition.skills);
    setFeedback({ ok: true, text: ar ? "تم تفسير القضية بالكامل." : "The case is fully explained." }); setResult({ score, accuracy, elapsed, relevant });
  };
  if (result) return <DetectiveResult caseDefinition={caseDefinition} locale={locale} result={result} hintsUsed={hintsUsed}/>;

  return <div className="detective-workspace"><div className="detective-workspace-shell">
    <header className="detective-workspace-head"><Link href={`/${locale}/academy/detective`}>{ar ? <ArrowRight/> : <ArrowLeft/>}{ar ? "كل تدريبات التحقيق" : "All investigation training"}</Link><div><span>CASE #{caseDefinition.caseNumber}</span><h1>{ar ? caseDefinition.titleAr : caseDefinition.titleEn}</h1></div><div className="detective-session"><span><Clock3/> {caseDefinition.estimatedMinutes} {ar ? "دقائق" : "min"}</span><b>{opened.length}/{caseDefinition.evidence.length} {ar ? "مفتوح" : "opened"}</b></div></header>
    <div className="detective-sandbox"><ShieldCheck/><span><b>{ar ? "Training Sandbox" : "Training Sandbox"}</b>{ar ? "كل ملاحظاتك وتصحيحاتك معزولة عن بيانات الشركة الحقيقية." : "All notes and corrections stay isolated from real company data."}</span></div>
    <div className="detective-tabs" role="tablist" aria-label={ar ? "أقسام ملف القضية" : "Case file sections"}>{caseDefinition.panels.map((panel) => <button role="tab" aria-selected={activePanel === panel} className={activePanel === panel ? "active" : ""} onClick={() => setActivePanel(panel)} key={panel}>{panelIcon(panel)}<span>{panelLabels[panel][ar ? 0 : 1]}</span>{panel !== "brief" && panel !== "notes" && panel !== "conclusion" && <small>{caseDefinition.evidence.filter((item) => item.panel === panel).length}</small>}</button>)}</div>
    <main className="detective-panel">
      {activePanel === "brief" && <CaseBrief caseDefinition={caseDefinition} locale={locale} onStart={() => setActivePanel(caseDefinition.panels[1])}/>}
      {activePanel === "notes" && <Notebook caseDefinition={caseDefinition} locale={locale} notes={notes} customNote={customNote} setCustomNote={setCustomNote} addNote={addNote} removeNote={(index) => setNotes((current) => current.filter((_, itemIndex) => itemIndex !== index))} links={links} opened={opened}/>}
      {activePanel === "conclusion" && <Conclusion caseDefinition={caseDefinition} locale={locale} selectedEvidence={selectedEvidence} setSelectedEvidence={setSelectedEvidence} conclusion={conclusion} setConclusion={setConclusion} hintsUsed={hintsUsed} useHint={useHint} feedback={feedback} confirm={confirm} explained={explained}/>}
      {!(["brief", "notes", "conclusion"] as DetectivePanel[]).includes(activePanel) && <section><div className="detective-panel-title"><div><span>{panelLabels[activePanel][ar ? 0 : 1]}</span><h2>{ar ? "افتح الدليل وافحص التفاصيل" : "Open evidence and inspect the details"}</h2></div><small>{ar ? "ليس كل ما في الملف مهمًا." : "Not everything in the file matters."}</small></div><div className="evidence-grid">{evidence.map((item) => <EvidenceCard key={item.id} evidence={item} locale={locale} opened={opened.includes(item.id)} important={important.includes(item.id)} excluded={excluded.includes(item.id)} linking={linkStart === item.id} linked={links.some(([a, b]) => a === item.id || b === item.id)} onOpen={() => openEvidence(item.id)} onImportant={() => toggle(item.id, setImportant)} onExclude={() => toggle(item.id, setExcluded)} onLink={() => connect(item.id)}/>)}</div>{!evidence.length && <div className="detective-empty"><FolderOpen/><p>{ar ? "لا توجد أدلة في هذا القسم لهذه القضية." : "This case has no evidence in this section."}</p></div>}</section>}
    </main>
  </div></div>;
}

function CaseBrief({ caseDefinition, locale, onStart }: { caseDefinition: DetectiveCase; locale: Locale; onStart: () => void }) { const ar = locale === "ar"; return <section className="case-brief"><span><Target/>CASE BRIEF</span><h2>{ar ? caseDefinition.titleAr : caseDefinition.titleEn}</h2><p>{ar ? caseDefinition.briefAr : caseDefinition.briefEn}</p><div className="case-brief-task"><Search/><div><small>{ar ? "مهمتك" : "YOUR ASSIGNMENT"}</small><b>{ar ? caseDefinition.questionAr : caseDefinition.questionEn}</b></div></div><div className="case-brief-facts"><div><small>{ar ? "نوع القضية" : "Case type"}</small><b>{ar ? caseDefinition.caseTypeAr : caseDefinition.caseTypeEn}</b></div><div><small>{ar ? "الأدلة" : "Evidence"}</small><b>{caseDefinition.evidence.length}</b></div><div><small>{ar ? "المهارات" : "Skills"}</small><b>{caseDefinition.skills.length}</b></div></div><button className="detective-primary" onClick={onStart}><FolderOpen/>{ar ? "ابدأ فحص الملف" : "Start examining the file"}{ar ? <ArrowLeft/> : <ArrowRight/>}</button></section>; }

function EvidenceCard({ evidence, locale, opened, important, excluded, linking, linked, onOpen, onImportant, onExclude, onLink }: { evidence: DetectiveEvidence; locale: Locale; opened: boolean; important: boolean; excluded: boolean; linking: boolean; linked: boolean; onOpen: () => void; onImportant: () => void; onExclude: () => void; onLink: () => void }) { const ar = locale === "ar"; return <article className={`evidence-card ${opened ? "opened" : ""} ${excluded ? "excluded" : ""}`}><button className="evidence-open" onClick={onOpen}><div className="evidence-type"><span>{evidenceIcon(evidence.type)}</span><b>{typeLabels[evidence.type][ar ? 0 : 1]}</b>{important && <Flag className="important"/>}</div><small>{evidence.date}</small><h3>{ar ? evidence.titleAr : evidence.titleEn}</h3>{evidence.amount !== undefined && <strong>{money(evidence.amount)}</strong>}<div className="evidence-ref"><span>{evidence.reference || (ar ? "بدون مرجع" : "No reference")}</span><ExternalLink/></div></button>{opened && <div className="evidence-details"><p>{ar ? evidence.contentAr : evidence.contentEn}</p>{evidence.relatedEntity && <span>{ar ? "طرف مرتبط" : "Related entity"}: <b>{evidence.relatedEntity}</b></span>}<div className="evidence-actions"><button className={important ? "active" : ""} onClick={onImportant}><Flag/>{ar ? "مهم" : "Important"}</button><button className={excluded ? "active danger" : ""} onClick={onExclude}><CircleMinus/>{ar ? "استبعاد" : "Exclude"}</button><button className={linking || linked ? "active" : ""} onClick={onLink}><Link2/>{linking ? (ar ? "اختر دليلًا آخر" : "Choose another") : linked ? (ar ? "مرتبط" : "Linked") : (ar ? "ربط" : "Link")}</button></div></div>}</article>; }

function Notebook({ caseDefinition, locale, notes, customNote, setCustomNote, addNote, removeNote, links, opened }: { caseDefinition: DetectiveCase; locale: Locale; notes: string[]; customNote: string; setCustomNote: (value: string) => void; addNote: (value: string) => void; removeNote: (index: number) => void; links: [string, string][]; opened: string[] }) { const ar = locale === "ar", presets = ar ? caseDefinition.notePresetsAr : caseDefinition.notePresetsEn, timeline = caseDefinition.evidence.filter((item) => opened.includes(item.id)).sort((a, b) => a.date.localeCompare(b.date)); return <section><div className="detective-panel-title"><div><span>{ar ? "دفتر المحاسب" : "Accounting notebook"}</span><h2>{ar ? "دوّن ما لاحظته أثناء التحقيق" : "Capture what you notice during the investigation"}</h2></div><small>{links.length} {ar ? "روابط بين الأدلة" : "evidence links"}</small></div><div className="notebook-layout"><div className="note-composer"><h3>{ar ? "ملاحظات جاهزة" : "Quick notes"}</h3>{presets.map((preset) => <button key={preset} onClick={() => addNote(preset)}><StickyNote/>{preset}</button>)}<label><span>{ar ? "أو اكتب ملاحظة قصيرة" : "Or write a short note"}</span><textarea maxLength={180} value={customNote} onChange={(event) => setCustomNote(event.target.value)} placeholder={ar ? "مثال: مرجع التحويل يطابق رسالة العميل..." : "Example: The transfer reference matches the customer message..."}/></label><button className="detective-primary" disabled={!customNote.trim()} onClick={() => addNote(customNote)}><NotebookPen/>{ar ? "أضف الملاحظة" : "Add note"}</button></div><div className="note-stack">{notes.length ? notes.map((note, index) => <article key={`${note}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><p>{note}</p><button aria-label={ar ? "حذف الملاحظة" : "Delete note"} onClick={() => removeNote(index)}><X/></button></article>) : <div className="detective-empty"><NotebookPen/><p>{ar ? "دفترك فارغ حتى الآن." : "Your notebook is empty."}</p></div>}</div></div><div className="detective-timeline"><div><span>{ar ? "تسلسل التحقيق" : "Investigation timeline"}</span><h3>{ar ? "الأدلة التي فتحتها حسب التاريخ" : "Opened evidence by date"}</h3></div>{timeline.length ? timeline.map((item) => <article key={item.id}><time>{item.date}</time><i/><span><b>{ar ? item.titleAr : item.titleEn}</b><small>{typeLabels[item.type][ar ? 0 : 1]}{item.reference ? ` · ${item.reference}` : ""}</small></span></article>) : <p>{ar ? "افتح دليلًا أولًا ليظهر في الخط الزمني." : "Open evidence to build your timeline."}</p>}</div></section>; }

function Conclusion({ caseDefinition, locale, selectedEvidence, setSelectedEvidence, conclusion, setConclusion, hintsUsed, useHint, feedback, confirm, explained }: { caseDefinition: DetectiveCase; locale: Locale; selectedEvidence: string[]; setSelectedEvidence: React.Dispatch<React.SetStateAction<string[]>>; conclusion: string; setConclusion: (value: string) => void; hintsUsed: number; useHint: () => void; feedback?: { ok: boolean; text: string }; confirm: () => void; explained: number }) { const ar = locale === "ar", hint = hintsUsed > 0 ? nextDetectiveHint(caseDefinition, hintsUsed - 1) : undefined; return <section className="conclusion-panel"><div className="detective-panel-title"><div><span>{ar ? "استنتاجي" : "My conclusion"}</span><h2>{ar ? "ما سبب المشكلة؟" : "What caused the problem?"}</h2></div><small>{ar ? "لن نعرض الحل إذا أخطأت." : "A wrong attempt will not reveal the solution."}</small></div><div className="conclusion-grid"><div><h3>{ar ? "1. الأدلة التي تفسر القضية" : "1. Evidence that explains the case"}</h3><div className="conclusion-evidence">{caseDefinition.evidence.map((item) => <label className={selectedEvidence.includes(item.id) ? "selected" : ""} key={item.id}><input type="checkbox" checked={selectedEvidence.includes(item.id)} onChange={() => setSelectedEvidence((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])}/><span>{selectedEvidence.includes(item.id) ? <Check/> : null}</span><b>{ar ? item.titleAr : item.titleEn}</b>{item.amount !== undefined && <small>{money(item.amount)}</small>}</label>)}</div>{caseDefinition.caseNumber === "D001" && <div className="explained-difference"><span>{ar ? "الفرق المفسر" : "Explained difference"}</span><b>{money(explained)}</b><small>/ 7,500 EGP</small></div>}</div><div><h3>{ar ? "2. اختر الاستنتاج" : "2. Choose a conclusion"}</h3><div className="conclusion-options">{caseDefinition.conclusions.map((item) => <button className={conclusion === item.id ? "selected" : ""} onClick={() => setConclusion(item.id)} key={item.id}><span>{conclusion === item.id && <Check/>}</span><b>{ar ? item.titleAr : item.titleEn}</b></button>)}</div>{hint && <div className="detective-hint"><Lightbulb/><div><b>{ar ? `مساعدة ${hintsUsed}` : `Hint ${hintsUsed}`}</b><p>{ar ? hint.textAr : hint.textEn}</p></div></div>}<div className="conclusion-actions"><button className="detective-primary" disabled={!conclusion || !selectedEvidence.length} onClick={confirm}><BadgeCheck/>{ar ? "تأكيد الاستنتاج" : "Confirm conclusion"}</button><button className="detective-secondary" disabled={hintsUsed >= 3} onClick={useHint}><Lightbulb/>{ar ? "مساعدة" : "Hint"} ({3 - hintsUsed})</button></div>{feedback && <div className={`detective-feedback ${feedback.ok ? "success" : "error"}`}>{feedback.ok ? <CheckCircle2/> : <Search/>}<p>{feedback.text}</p></div>}</div></div></section>; }

function DetectiveResult({ caseDefinition, locale, result, hintsUsed }: { caseDefinition: DetectiveCase; locale: Locale; result: { score: number; accuracy: number; elapsed: number; relevant: number }; hintsUsed: number }) { const ar = locale === "ar", entries = buildDetectiveTrainingEntries(caseDefinition), next = detectiveCases[(detectiveCases.findIndex((item) => item.id === caseDefinition.id) + 1) % detectiveCases.length]; return <div className="detective-result-page"><div className="detective-result-shell"><section className="detective-result-hero"><div className="detective-result-icon"><Trophy/></div><span>CASE SOLVED</span><h1>{ar ? "تم حل القضية ✅" : "Case solved ✅"}</h1><p>{ar ? caseDefinition.titleAr : caseDefinition.titleEn}</p><div className="detective-result-metrics"><ResultMetric label={ar ? "Detective Score" : "Detective Score"} value={`${result.score}/1000`}/><ResultMetric label={ar ? "الدقة" : "Accuracy"} value={`${result.accuracy}%`}/><ResultMetric label={ar ? "الأدلة الصحيحة" : "Relevant evidence"} value={`${result.relevant}/${caseDefinition.correctEvidence.length}`}/><ResultMetric label={ar ? "المساعدات" : "Hints used"} value={String(hintsUsed)}/><ResultMetric label={ar ? "الوقت" : "Time"} value={`${Math.floor(result.elapsed / 60)}m ${result.elapsed % 60}s`}/></div></section>
      <section className="detective-result-section"><span><FileSearch/>{ar ? "ماذا حدث فعلًا؟" : "What actually happened?"}</span><p>{ar ? caseDefinition.explanationAr : caseDefinition.explanationEn}</p>{caseDefinition.educationalNoteAr && <div className="detective-education-note"><BookOpenText/><p>{ar ? caseDefinition.educationalNoteAr : caseDefinition.educationalNoteEn}</p></div>}</section>
      <section className="detective-result-section"><span><ShieldCheck/>{ar ? "المعالجة المحاسبية" : "Accounting treatment"}</span><div className="training-warning"><ShieldCheck/><b>{ar ? "عرض تدريبي فقط — لم يتم تعديل أي قيد أو بنك أو عميل حقيقي." : "Training display only — no real journal, bank, or customer data was changed."}</b></div>{entries.map((entry) => <div className="detective-journal" key={entry.id}><header><b>{ar ? entry.titleAr : entry.titleEn}</b><small>{ar ? entry.narrationAr : entry.narrationEn}</small></header>{entry.lines.map((line, index) => <div key={`${entry.id}-${index}`}><span>{line.debit ? (ar ? "مدين" : "Debit") : (ar ? "دائن" : "Credit")}</span><b>{ar ? line.accountAr : line.accountEn}</b><strong>{money(line.debit || line.credit)}</strong></div>)}</div>)}</section>
      <section className="detective-result-section"><span><Target/>{ar ? "الأثر المالي" : "Financial impact"}</span><div className="detective-impact-grid">{caseDefinition.financialImpact.map((item) => <article key={item.labelEn}><i className={item.direction}>{item.direction === "up" ? <ArrowUp/> : item.direction === "down" ? <ArrowDown/> : <Unlink/>}</i><b>{ar ? item.labelAr : item.labelEn}</b><small>{item.before !== undefined ? `${ar ? "قبل" : "Before"}: ${typeof item.before === "number" ? money(item.before) : item.before}` : ""}</small><strong>{item.after !== undefined ? `${ar ? "بعد" : "After"}: ${typeof item.after === "number" ? money(item.after) : item.after}` : (ar ? "لا تغيير" : "No change")}</strong></article>)}</div></section>
      <section className="detective-result-section"><span><CheckCircle2/>{ar ? "ما الذي كان يجب على المحاسب فحصه؟" : "What should the accountant have checked?"}</span><ol>{(ar ? caseDefinition.checksAr : caseDefinition.checksEn).map((item) => <li key={item}>{item}</li>)}</ol><div className="detective-skills">{caseDefinition.skills.map((skill) => <b key={skill}>{skillLabels[skill][ar ? 0 : 1]}</b>)}</div></section>
      <div className="detective-result-actions"><Link className="detective-primary" href={`/${locale}/academy/detective/${next.slug}`}>{ar ? "القضية التالية" : "Next case"}{ar ? <ArrowLeft/> : <ArrowRight/>}</Link><button className="detective-secondary" onClick={() => window.location.reload()}><RotateCcw/>{ar ? "إعادة القضية" : "Replay case"}</button>{caseDefinition.relatedMissionSlug && <Link className="detective-secondary" href={`/${locale}/missions/${caseDefinition.relatedMissionSlug}`}><Target/>{ar ? "تدرب أكثر على المهارة" : "Practice this skill"}</Link>}<Link className="detective-secondary" href={`/${locale}/academy/detective`}><FolderOpen/>{ar ? "كل القضايا" : "All cases"}</Link><Link className="detective-secondary" href={`/${locale}/academy`}><BookOpenText/>{ar ? "العودة للأكاديمية" : "Back to Academy"}</Link></div>
    </div></div>; }

function ResultMetric({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div>; }
function panelIcon(panel: DetectivePanel) { return panel === "brief" ? <FileSearch/> : panel === "bank" ? <Banknote/> : panel === "entries" ? <ReceiptText/> : panel === "notes" ? <NotebookPen/> : panel === "conclusion" ? <Target/> : panel === "parties" ? <MessageSquareText/> : <File/>; }
function evidenceIcon(type: DetectiveEvidence["type"]) { return type === "bank-transaction" ? <Banknote/> : type === "journal-entry" ? <ReceiptText/> : type.includes("message") ? <MessageSquareText/> : type === "invoice" || type === "receipt" ? <File/> : <BookOpenText/>; }
