import { defaultAccounts } from "@/data/accounts";
import { getPostingAccounts } from "@/lib/accounting/accounts";
import { validateJournalEntry, type JournalValidationResult } from "@/lib/accounting/validation";
import type { ArenaTaskLine, ChartAccount, GeneratedJournalEntry } from "@/types";

export const ARENA_ACCOUNT_SOURCE = "finora-default-chart-v1";

export interface ArenaAccountCard extends ChartAccount {
  descriptionAr: string;
  descriptionEn: string;
  source: typeof ARENA_ACCOUNT_SOURCE;
}

const descriptions: Record<string, [string, string]> = {
  cash: ["فلوس الشركة الموجودة في الخزينة", "Company money held in the cash box"],
  bank: ["فلوس الشركة داخل الحساب البنكي", "Company money held in bank accounts"],
  receivables: ["فلوس لينا عند العملاء", "Money customers owe the company"],
  payables: ["فلوس علينا للموردين", "Money the company owes suppliers"],
  inventory: ["بضاعة وخامات تملكها الشركة", "Goods and materials owned by the company"],
  equipment: ["معدات تستخدمها الشركة لأكثر من فترة", "Equipment used across multiple periods"],
  capital: ["استثمار صاحب الشركة", "The owner's investment in the company"],
  "service-revenue": ["دخل ناتج عن تقديم خدمات", "Income earned from providing services"],
  sales: ["دخل ناتج عن بيع البضاعة", "Income earned from selling goods"],
  rent: ["تكلفة استخدام مكان النشاط", "Cost of using the business premises"],
  salaries: ["تكلفة عمل فريق الشركة", "Cost of the company's workforce"],
  "input-vat": ["ضريبة مدخلات قابلة للتسوية", "Input tax available for settlement"],
  "output-vat": ["ضريبة مخرجات مستحقة", "Output tax due"],
};

const genericDescription = (account: ChartAccount): [string, string] => ({
  asset: ["قيمة أو حق تملكه الشركة", "Value or a right owned by the company"],
  liability: ["التزام على الشركة تجاه طرف آخر", "An obligation the company owes another party"],
  equity: ["حق المالك في الشركة", "The owner's interest in the company"],
  revenue: ["دخل ناتج عن نشاط الشركة", "Income generated by the business"],
  expense: ["تكلفة استهلكها النشاط", "A cost consumed by the business"],
}[account.type] as [string, string]);

export function createTrainingAccountSnapshot(accounts: ChartAccount[] = defaultAccounts): ArenaAccountCard[] {
  return getPostingAccounts(accounts).map((account) => {
    const [descriptionAr, descriptionEn] = descriptions[account.id] ?? genericDescription(account);
    return { ...account, descriptionAr, descriptionEn, source: ARENA_ACCOUNT_SOURCE };
  });
}

export function getArenaAccountByCode(code: string, accounts: ChartAccount[] = defaultAccounts) {
  return createTrainingAccountSnapshot(accounts).find((account) => account.code === code);
}

export function validateArenaJournal(lines: ArenaTaskLine[], accounts: ChartAccount[] = defaultAccounts): JournalValidationResult {
  const entry: GeneratedJournalEntry = {
    id: "training-arena-validation", entryNumber: "ARENA-DRAFT", date: "2026-09-03", transactionType: "training-arena",
    titleAr: "قيد تدريبي", titleEn: "Training entry", narrationAr: "تنفيذ مهمة داخل Arena", narrationEn: "Arena training task",
    currency: "EGP", lines: lines.map((line, index) => { const account = accounts.find((item) => item.code === line.accountCode); return { id: `arena-line-${index}`, accountCode: line.accountCode, accountNameAr: account?.nameAr ?? "", accountNameEn: account?.nameEn ?? "", debit: line.side === "debit" ? line.amount : 0, credit: line.side === "credit" ? line.amount : 0 }; }),
    totalDebit: 0, totalCredit: 0, isBalanced: false, explanationAr: [], explanationEn: [], assumptionsAr: [], assumptionsEn: [], warningsAr: [], warningsEn: [], accountingRuleAr: "تدريب معزول", accountingRuleEn: "Isolated training", financialStatementImpact: { assets: 0, liabilities: 0, equity: 0, revenue: 0, expenses: 0, profit: 0 }, workflowStatus: "draft", source: "manual",
  };
  return validateJournalEntry(entry, accounts);
}
