import type { Achievement, ArenaAttempt, ArenaDifficulty, ArenaProfile, ArenaSkillId, CareerRank, CompanyHealth, JournalLine, LeaderboardEntry, MistakeChain, PerformanceReview, ProfessionalScoreConfig, SkillConfidence, SkillRating } from "@/types/arena";

export const ARENA_SCORE_CONFIG: ProfessionalScoreConfig = { accuracy: .45, difficulty: .20, consistency: .15, errorDetection: .10, efficiency: .10 };
export const difficultyWeight: Record<ArenaDifficulty, number> = { beginner: .55, intermediate: .78, advanced: 1 };
export const normalSide = (category: string): "debit" | "credit" => ["asset", "expense", "cost-of-sales"].includes(category) ? "debit" : "credit";
export const movementSide = (category: string, movement: "increase" | "decrease") => movement === "increase" ? normalSide(category) : normalSide(category) === "debit" ? "credit" : "debit";
export const classifyAccount = (accountId: string) => ({ cash:"asset", bank:"asset", customers:"asset", inventory:"asset", equipment:"asset", suppliers:"liability", loans:"liability", capital:"equity", revenue:"revenue", rent:"expense", salaries:"expense", utilities:"expense", "cost-of-sales":"cost-of-sales" } as Record<string,string>)[accountId];
export const validateJournal = (lines: JournalLine[]) => { const debit = lines.reduce((s,l)=>s+l.debit,0), credit=lines.reduce((s,l)=>s+l.credit,0); return { debit, credit, difference: Math.round(Math.abs(debit-credit)*100)/100, balanced: lines.length >= 2 && Math.abs(debit-credit) < .01 && lines.every(l=>l.debit>=0&&l.credit>=0&&!(l.debit&&l.credit)) }; };
export const postToLedger = (lines: JournalLine[]) => Object.values(lines.reduce<Record<string,{accountId:string;debit:number;credit:number}>>((map,line)=>{ const row=map[line.accountId]??{accountId:line.accountId,debit:0,credit:0}; row.debit+=line.debit;row.credit+=line.credit;map[line.accountId]=row;return map;},{})).map(row=>({...row,balance:Math.abs(row.debit-row.credit),side:row.debit>=row.credit?"debit" as const:"credit" as const}));
export const buildTrialBalance = (ledgers: ReturnType<typeof postToLedger>) => ({ debit:ledgers.filter(l=>l.side==="debit").reduce((s,l)=>s+l.balance,0), credit:ledgers.filter(l=>l.side==="credit").reduce((s,l)=>s+l.balance,0) });
export const buildStatements = (balances: Record<string,number>) => { const revenue=balances.revenue??0, expenses=(balances.rent??0)+(balances.salaries??0)+(balances.utilities??0)+(balances["cost-of-sales"]??0); return { revenue, expenses, profit:revenue-expenses, assets:(balances.cash??0)+(balances.bank??0)+(balances.customers??0)+(balances.equipment??0), liabilities:(balances.suppliers??0)+(balances.loans??0), equity:(balances.capital??0)+revenue-expenses }; };

const rankedBestAttempts = (attempts: ArenaAttempt[]) => Object.values(attempts.filter(a=>a.ranked).reduce<Record<string,ArenaAttempt>>((best,a)=>{ if(!best[a.caseId]||best[a.caseId].score<a.score) best[a.caseId]=a; return best; },{}));
export function calculateProfessionalScore(attempts: ArenaAttempt[], config=ARENA_SCORE_CONFIG) { const unique=rankedBestAttempts(attempts); if(!unique.length)return 0; const accuracy=unique.reduce((s,a)=>s+a.accuracy,0)/unique.length/100; const difficulty=unique.reduce((s,a)=>s+difficultyWeight[a.difficulty],0)/unique.length; const consistency=Math.max(0,1-Math.sqrt(unique.reduce((s,a)=>s+(a.accuracy-accuracy*100)**2,0)/unique.length)/50); const detection=unique.filter(a=>a.skills.includes("error-detection")||a.skills.includes("recovery")).reduce((s,a)=>s+a.accuracy,0)/Math.max(1,unique.filter(a=>a.skills.includes("error-detection")||a.skills.includes("recovery")).length)/100; const efficiency=unique.reduce((s,a)=>s+Math.max(.35,1-a.hintsUsed*.16),0)/unique.length; return Math.round(1000*(accuracy*config.accuracy+difficulty*config.difficulty+consistency*config.consistency+detection*config.errorDetection+efficiency*config.efficiency)); }
export const calculateAccuracy = (attempts:ArenaAttempt[]) => { const unique=rankedBestAttempts(attempts); return unique.length?Math.round(unique.reduce((s,a)=>s+a.accuracy,0)/unique.length):0; };
export const confidenceFor = (rating:Pick<SkillRating,"attempts"|"uniqueCases"|"bestAccuracy"|"maxDifficulty">):SkillConfidence => rating.uniqueCases>=5&&rating.attempts>=5&&rating.bestAccuracy>=85&&rating.maxDifficulty!=="beginner"?"verified":rating.uniqueCases>=4&&rating.bestAccuracy>=80?"high":rating.uniqueCases>=2?"medium":"low";
export function calculateSkillRating(skill:ArenaSkillId,attempts:ArenaAttempt[]):SkillRating { const relevant=rankedBestAttempts(attempts).filter(a=>a.skills.includes(skill)), weights={beginner:1,intermediate:1.18,advanced:1.35}; const score=relevant.length?Math.min(100,Math.round(relevant.reduce((s,a)=>s+a.accuracy*weights[a.difficulty],0)/relevant.length)):0; const maxDifficulty:ArenaDifficulty=relevant.some(a=>a.difficulty==="advanced")?"advanced":relevant.some(a=>a.difficulty==="intermediate")?"intermediate":"beginner"; const partial={attempts:attempts.filter(a=>a.skills.includes(skill)).length,uniqueCases:relevant.length,bestAccuracy:relevant.length?Math.max(...relevant.map(a=>a.accuracy)):0,maxDifficulty}; return {id:skill,score,...partial,confidence:confidenceFor(partial)}; }
export const verifySkill = (rating:SkillRating) => rating.confidence==="verified";
export const CAREER_RANKS:CareerRank[]=[
 {id:"intern",titleAr:"متدرب محاسبة",titleEn:"Accounting Intern",requirements:{}},
 {id:"accounting-trainee",titleAr:"متدرب مهني",titleEn:"Accounting Trainee",requirements:{uniqueCases:5,accuracy:65}},
 {id:"junior-ready",titleAr:"جاهز للعمل كمبتدئ",titleEn:"Junior Ready",requirements:{uniqueCases:20,accuracy:80,skills:{"journal-entries":75,"chart-of-accounts":75,"debit-credit":75}}},
 {id:"junior-accountant",titleAr:"محاسب مبتدئ",titleEn:"Junior Accountant",requirements:{uniqueCases:50,accuracy:85,bossIds:["banking","customers","suppliers","month-close"]}},
 {id:"accountant",titleAr:"محاسب",titleEn:"Accountant",requirements:{score:700,workShifts:20}},
 {id:"advanced-accountant",titleAr:"محاسب متقدم",titleEn:"Advanced Accountant",requirements:{score:790,uniqueCases:80}},
 {id:"senior-challenge",titleAr:"تحدي المحاسب الأول",titleEn:"Senior Challenge",requirements:{score:860,uniqueCases:110}},
 {id:"chief-accountant-candidate",titleAr:"مرشح رئيس حسابات",titleEn:"Chief Accountant Candidate",requirements:{score:920,uniqueCases:150}},
];
const meets=(rank:CareerRank,p:ArenaProfile)=>{const r=rank.requirements;return (!r.score||p.professionalScore>=r.score)&&(!r.uniqueCases||p.uniqueCases>=r.uniqueCases)&&(!r.accuracy||p.accuracy>=r.accuracy)&&(!r.workShifts||p.workShifts>=r.workShifts)&&(!r.bossIds||r.bossIds.every(id=>p.bossChallenges.includes(id)))&&(!r.skills||Object.entries(r.skills).every(([id,n])=>p.skills[id as ArenaSkillId].score>=(n??0)));};
export const resolveCareerRank=(profile:ArenaProfile)=>CAREER_RANKS.filter(r=>meets(r,profile)).at(-1)?.id??"intern";
export const updateCfoTrust=(value:number,event:"correct"|"critical-correct"|"critical-mistake"|"self-correction")=>Math.max(0,Math.min(100,value+({correct:2,"critical-correct":4,"critical-mistake":-5,"self-correction":2}[event])));
export function updateCompanyHealth(health:CompanyHealth, effects:Partial<Record<keyof CompanyHealth,number>>) { return Object.fromEntries(Object.entries(health).map(([k,v])=>[k,Math.max(0,Math.min(100,v+(effects[k as keyof CompanyHealth]??0))) ])) as unknown as CompanyHealth; }
export const recoveryScore=(detected:boolean,fixed:boolean,hints:number,understood:boolean)=>Math.max(0,(detected?30:0)+(fixed?35:0)+(understood?35:0)-hints*8);
export const sortLeaderboard=(entries:LeaderboardEntry[])=>[...entries].sort((a,b)=>b.professionalScore-a.professionalScore||b.accuracy-a.accuracy||b.uniqueCases-a.uniqueCases);
export const dailyCaseIndex=(date:string,count:number)=>{let h=0;for(const c of date)h=(h*31+c.charCodeAt(0))>>>0;return h%count;};
export function deriveAchievements(attempts:ArenaAttempt[],existing:Achievement[]=[]){const earned=[...existing],add=(id:string,titleAr:string,titleEn:string)=>{if(!earned.some(x=>x.id===id))earned.push({id,titleAr,titleEn,earnedAt:new Date().toISOString()})};if(attempts.some(a=>a.skills.includes("journal-entries")&&a.accuracy===100))add("first-balanced-entry","أول قيد متوازن","First Balanced Entry");if(new Set(attempts.filter(a=>a.skills.includes("chart-of-accounts")).map(a=>a.caseId)).size>=1)add("chart-builder","باني دليل الحسابات","Chart Builder");if(attempts.some(a=>a.skills.includes("error-detection")&&a.accuracy>=90&&a.hintsUsed===0))add("no-hint-solver","حل بدون تلميح","No-Hint Solver");if(attempts.some(a=>a.skills.includes("banking")&&a.difficulty!=="beginner"&&a.accuracy>=85))add("bank-reconciliation","أول تسوية بنكية","First Bank Reconciliation");return earned;}
export function createPerformanceReview(profile:ArenaProfile):PerformanceReview{const ordered=Object.values(profile.skills).sort((a,b)=>b.score-a.score);return{generatedAt:new Date().toISOString(),overall:profile.accuracy,strong:ordered.slice(0,2).map(x=>x.id),needsWork:ordered.slice(-2).reverse().map(x=>x.id),commonMistakeAr:"معالجة التحصيل كإيراد جديد",commonMistakeEn:"Collections treated as new revenue",recommendedMissionId:"collection-or-revenue"};}
export const createMistakeChain=(triggerCaseId:string):MistakeChain=>({id:`chain-${triggerCaseId}`,triggerCaseId,delayedByTasks:3,cfoMessageAr:"ليه العميل لسه مديون رغم إنه دفع؟ وليه الربح اتغير؟",cfoMessageEn:"Why does the customer still owe us after paying, and why did profit change?",affectedHealth:["receivables","profitIntegrity","accountingAccuracy"],resolved:false});
